var h;h||=typeof Module != 'undefined' ? Module : {};var ba=Object.assign({},h),ca=[],da="./this.program",k="",ea;"undefined"!=typeof document&&document.currentScript&&(k=document.currentScript.src);k=k.startsWith("blob:")?"":k.substr(0,k.replace(/[?#].*/,"").lastIndexOf("/")+1);ea=a=>fetch(a,{credentials:"same-origin"}).then(b=>b.ok?b.arrayBuffer():Promise.reject(Error(b.status+" : "+b.url)));var fa=h.print||console.log.bind(console),l=h.printErr||console.error.bind(console);
Object.assign(h,ba);ba=null;h.arguments&&(ca=h.arguments);h.thisProgram&&(da=h.thisProgram);var ha=h.wasmBinary,ia,p=!1,ja,q,t,ka,la,u,v,w,x,ma=[],na=[],oa=[],pa=[];function qa(){var a=h.preRun.shift();ma.unshift(a)}var y=0,ra=null,sa=null;function ta(a){h.onAbort?.(a);a="Aborted("+a+")";l(a);p=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ua=a=>a.startsWith("data:application/octet-stream;base64,"),va;
function wa(a){if(a==va&&ha)return new Uint8Array(ha);throw"both async and sync fetching of the wasm failed";}function xa(a){return ha?Promise.resolve().then(()=>wa(a)):ea(a).then(b=>new Uint8Array(b),()=>wa(a))}function ya(a,b,c){return xa(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{l(`failed to asynchronously prepare wasm: ${d}`);ta(d)})}
function za(a,b){var c=va;ha||"function"!=typeof WebAssembly.instantiateStreaming||ua(c)||"function"!=typeof fetch?ya(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){l(`wasm streaming compile failed: ${e}`);l("falling back to ArrayBuffer instantiation");return ya(c,a,b)}))}
var Da={7787837:()=>"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?!0:!1,7787984:()=>"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?!0:!1,7788218:a=>{"undefined"===typeof h.SDL2&&(h.SDL2={});var b=h.SDL2;a?b.capture={}:b.audio={};b.fe||("undefined"!==typeof AudioContext?b.fe=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.fe=new webkitAudioContext),b.fe&&
Aa(b.fe));return void 0===b.fe?-1:0},7788711:()=>h.SDL2.fe.sampleRate,7788779:(a,b,c,d)=>{function e(){}function f(m){void 0!==g.capture.qe&&(clearTimeout(g.capture.qe),g.capture.qe=void 0);g.capture.ye=g.fe.createMediaStreamSource(m);g.capture.he=g.fe.createScriptProcessor(b,a,1);g.capture.he.onaudioprocess=function(n){void 0!==g&&void 0!==g.capture&&(n.outputBuffer.getChannelData(0).fill(0),g.capture.Be=n.inputBuffer,Ba(c,[d]))};g.capture.ye.connect(g.capture.he);g.capture.he.connect(g.fe.destination);
g.capture.stream=m}var g=h.SDL2;g.capture.ze=g.fe.createBuffer(a,b,g.fe.sampleRate);g.capture.ze.getChannelData(0).fill(0);g.capture.qe=setTimeout(function(){g.capture.Be=g.capture.ze;Ba(c,[d])},b/g.fe.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(f).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,video:!1},f,e)},7790431:(a,b,c,d)=>{var e=h.SDL2;e.audio.he=
e.fe.createScriptProcessor(b,0,a);e.audio.he.onaudioprocess=function(f){void 0!==e&&void 0!==e.audio&&(e.audio.He=f.outputBuffer,Ba(c,[d]))};e.audio.he.connect(e.fe.destination)},7790841:(a,b)=>{for(var c=h.SDL2,d=c.capture.Be.numberOfChannels,e=0;e<d;++e){var f=c.capture.Be.getChannelData(e);if(f.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";if(1==d)for(var g=0;g<b;++g)Ca(a+4*g,f[g]);else for(g=0;g<b;++g)Ca(a+4*(g*d+e),
f[g])}},7791446:(a,b)=>{for(var c=h.SDL2,d=c.audio.He.numberOfChannels,e=0;e<d;++e){var f=c.audio.He.getChannelData(e);if(f.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";for(var g=0;g<b;++g)f[g]=w[a+(g*d+e<<2)>>2]}},7791926:a=>{var b=h.SDL2;if(a){void 0!==b.capture.qe&&clearTimeout(b.capture.qe);if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c]);
b.capture.stream=void 0}void 0!==b.capture.he&&(b.capture.he.onaudioprocess=function(){},b.capture.he.disconnect(),b.capture.he=void 0);void 0!==b.capture.ye&&(b.capture.ye.disconnect(),b.capture.ye=void 0);void 0!==b.capture.ze&&(b.capture.ze=void 0);b.capture=void 0}else void 0!=b.audio.he&&(b.audio.he.disconnect(),b.audio.he=void 0),b.audio=void 0;void 0!==b.fe&&void 0===b.audio&&void 0===b.capture&&(b.fe.close(),b.fe=void 0)},7793098:(a,b,c)=>{h.SDL2||(h.SDL2={});var d=h.SDL2;d.Pe!==h.canvas&&
(d.le=h.createContext(h.canvas,!1,!0),d.Pe=h.canvas);if(d.w!==a||d.h!==b||d.bf!==d.le)d.image=d.le.createImageData(a,b),d.w=a,d.h=b,d.bf=d.le;a=d.image.data;b=c>>2;var e=0;if("undefined"!==typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var f=u[b];a[e]=f&255;a[e+1]=f>>8&255;a[e+2]=f>>16&255;a[e+3]=255;b++;e+=4}else if(d.Se!==a&&(d.Re=new Int32Array(a.buffer),d.Te=new Uint8Array(a.buffer),d.Se=a),a=d.Re,c=a.length,a.set(u.subarray(b,b+c)),a=d.Te,b=3,e=b+4*c,0==c%8)for(;b<
e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=255,b=b+4|0;d.le.putImageData(d.image,0,0)},7794567:(a,b,c,d,e)=>{var f=document.createElement("canvas");f.width=a;f.height=b;var g=f.getContext("2d");a=g.createImageData(a,b);b=a.data;e>>=2;var m=0,n;if("undefined"!==typeof CanvasPixelArray&&b instanceof CanvasPixelArray)for(n=b.length;m<n;){var r=u[e];b[m]=r&255;b[m+1]=r>>8&255;b[m+2]=r>>
16&255;b[m+3]=r>>24&255;e++;m+=4}else b=new Int32Array(b.buffer),n=b.length,b.set(u.subarray(e,e+n));g.putImageData(a,0,0);c=0===c&&0===d?"url("+f.toDataURL()+"), auto":"url("+f.toDataURL()+") "+c+" "+d+", auto";d=z(c.length+1);B(c,d,c.length+1);return d},7795556:a=>{h.canvas&&(h.canvas.style.cursor=a?C(t,a):"")},7795639:()=>{h.canvas&&(h.canvas.style.cursor="none")},7795708:()=>window.innerWidth,7795738:()=>window.innerHeight};
function Ea(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}var Fa=a=>{for(;0<a.length;)a.shift()(h)},Ga=h.noExitRuntime||!0;
function Ca(a,b){var c="float";c.endsWith("*")&&(c="*");switch(c){case "i1":q[a]=b;break;case "i8":q[a]=b;break;case "i16":ka[a>>1]=b;break;case "i32":u[a>>2]=b;break;case "i64":ta("to do setValue(i64) use WASM_BIGINT");case "float":w[a>>2]=b;break;case "double":x[a>>3]=b;break;case "*":v[a>>2]=b;break;default:ta(`invalid type for setValue: ${c}`)}}
var Ha="undefined"!=typeof TextDecoder?new TextDecoder:void 0,C=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ha)return Ha.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},Ra=(a,
b)=>{Ia=a;Ja=b;if(Ka)if(La||=!0,0==a)D=function(){var d=Math.max(0,Ma+b-Na())|0;setTimeout(Oa,d)};else if(1==a)D=function(){Pa(Oa)};else if(2==a){if("undefined"==typeof Qa)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Qa=d=>{c.push(d);postMessage("setimmediate","*")}}else Qa=setImmediate;D=function(){Qa(Oa)}}},Na;Na=()=>performance.now();
var Sa=a=>{ja=a;Ga||(h.onExit?.(a),p=!0);throw new Ea(a);},Ta=a=>{ja=a;Sa(a)},Ua=a=>{if(!(a instanceof Ea||"unwind"==a))throw a;},Va=()=>{if(!Ga)try{var a=ja;ja=a;Sa(a)}catch(b){Ua(b)}},bb=(a,b,c,d,e)=>{function f(){return g<Wa?(Va(),!1):!0}Ka=a;Xa=d;var g=Wa;La=!1;Oa=function(){if(!p)if(0<Ya.length){var m=Ya.shift();m.lf(m.gf);if(Za){var n=Za,r=0==n%1?n-1:Math.floor(n);Za=m.jf?r:(8*n+(r+.5))/9}h.setStatus&&(m=h.statusMessage||"Please wait...",n=Za,r=$a.kf,n?n<r?h.setStatus("{message} ({expected - remaining}/{expected})"):
h.setStatus(m):h.setStatus(""));f()&&setTimeout(Oa,0)}else if(f())if(ab=ab+1|0,1==Ia&&1<Ja&&0!=ab%Ja)D();else{0==Ia&&(Ma=Na());if(!(p||h.preMainLoop&&!1===h.preMainLoop())){if(!p)try{a(),Va()}catch(A){Ua(A)}h.postMainLoop?.()}f()&&("object"==typeof SDL&&SDL.audio?.qf?.(),D())}};e||(b&&0<b?Ra(0,1E3/b):Ra(1,1),D());if(c)throw"unwind";},La=!1,D=null,Wa=0,Ka=null,Xa=0,Ia=0,Ja=0,ab=0,Ya=[],$a={},Ma,Oa,Za,cb=!1,db=!1,eb=[];
function fb(){function a(){db=document.pointerLockElement===h.canvas||document.mozPointerLockElement===h.canvas||document.webkitPointerLockElement===h.canvas||document.msPointerLockElement===h.canvas}if(!gb){gb=!0;var b=h.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),
b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",c=>{!db&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}var hb=!1,ib=void 0,E=void 0;
function jb(){if(!cb)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var kb=0;function Pa(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===kb)kb=b+1E3/60;else for(;b+2>=kb;)kb+=1E3/60;setTimeout(a,Math.max(kb-b,0))}}var lb=[];function mb(){var a=h.canvas;lb.forEach(b=>b(a.width,a.height))}
function nb(a,b,c){b&&c?(a.ff=b,a.af=c):(b=a.ff,c=a.af);var d=b,e=c;h.forcedAspectRatio&&0<h.forcedAspectRatio&&(d/e<h.forcedAspectRatio?d=Math.round(e*h.forcedAspectRatio):e=Math.round(d/h.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}E?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var Qa,gb,F=12288,ob=!1,pb=0,qb=0,rb=0,G={alpha:!1,depth:!1,stencil:!1,antialias:!1},sb={},tb,I,ub=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,f)=>b.drawArraysInstancedANGLE(c,d,e,f),a.drawElementsInstanced=(c,d,e,f,g)=>b.drawElementsInstancedANGLE(c,d,e,f,g))},vb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),
a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},wb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},xb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},yb=1,zb=[],J=[],Ab=[],K=[],L=[],M=[],Bb=[],N=[],O=[],Cb={},Db=4,Eb=0,Fb=a=>{for(var b=yb++,c=a.length;c<b;c++)a[c]=null;return b},Gb=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=I[c](),g=f&&Fb(d);f?(f.name=g,d[g]=f):P||=1282;u[b+4*e>>2]=g}},Ib=(a,b)=>{a.ue||(a.ue=a.getContext,a.getContext=function(d,e){e=a.ue(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?Hb(c,b):0},Hb=(a,b)=>{var c=
Fb(N),d={handle:c,attributes:b,version:b.Ke,ne:a};a.canvas&&(a.canvas.pe=d);N[c]=d;("undefined"==typeof b.Ve||b.Ve)&&Jb(d);return c},Lb=a=>{Kb=N[a];h.le=I=Kb?.ne},Jb=a=>{a||=Kb;if(!a.cf){a.cf=!0;var b=a.ne;b.pf=b.getExtension("WEBGL_multi_draw");b.Xe=b.getExtension("EXT_polygon_offset_clamp");b.We=b.getExtension("EXT_clip_control");b.ef=b.getExtension("WEBGL_polygon_mode");ub(b);vb(b);wb(b);b.me=b.getExtension("EXT_disjoint_timer_query");xb(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||
b.getExtension(c)})}},Mb={},P,Kb,Nb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},B=(a,b,c)=>{var d=t;if(!(0<c))return 0;var e=b;c=b+c-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var m=a.charCodeAt(++f);g=65536+((g&1023)<<10)|m&1023}if(127>=g){if(b>=c)break;d[b++]=g}else{if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6}else{if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12}else{if(b+3>=c)break;d[b++]=
240|g>>18;d[b++]=128|g>>12&63}d[b++]=128|g>>6&63}d[b++]=128|g&63}}d[b]=0;return b-e},Q=a=>{var b=Nb(a)+1,c=z(b);c&&B(a,c,b);return c},Ob=[],Pb=(a,b)=>{Ob.length=0;for(var c;c=t[a++];){var d=105!=c;d&=112!=c;b+=d&&b%8?4:0;Ob.push(112==c?v[b>>2]:105==c?u[b>>2]:x[b>>3]);b+=d?8:4}return Ob},Qb=0,R=[];
function Rb(a,b,c){function d(f,g){if(f.length!=g.length)return!1;for(var m in f)if(f[m]!=g[m])return!1;return!0}for(var e of R)if(e.De==a&&d(e.Fe,c))return;R.push({De:a,Me:b,Fe:c});R.sort((f,g)=>f.Me<g.Me)}function Sb(a){R=R.filter(b=>b.De!=a)}function Tb(){return navigator.userActivation?navigator.userActivation.isActive:Qb&&Ub.se}function Vb(){if(Tb()){var a=R;R=[];for(var b of a)b.De(...b.Fe)}}var S=[];function Wb(a){var b=S[a];b.target.removeEventListener(b.ge,b.Ie,b.ie);S.splice(a,1)}
function T(a){if(!a.target)return-4;if(a.je)a.Ie=function(c){++Qb;Ub=a;Vb();a.ke(c);Vb();--Qb},a.target.addEventListener(a.ge,a.Ie,a.ie),S.push(a);else for(var b=0;b<S.length;++b)S[b].target==a.target&&S[b].ge==a.ge&&Wb(b--);return 0}function Xb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}function Yb(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}
var Zb={},Ub,$b,ac,bc,cc,dc,ec,fc,gc,hc,ic,jc,kc,lc={},mc=[0,document,window],U=a=>{a=2<a?a?C(t,a):"":a;return mc[a]||document.querySelector(a)},oc=a=>{var b=Nb(a)+1,c=nc(b);B(a,c,b);return c},rc=a=>{var b=pc(),c=nc(8),d=c+4;a=oc(a.id);if(a=U(a))u[c>>2]=a.width,u[d>>2]=a.height;c=[u[c>>2],u[d>>2]];qc(b);return c},sc=(a,b,c)=>{a=U(a);if(!a)return-4;a.width=b;a.height=c;return 0},tc=(a,b,c)=>{if(a.hf){var d=pc();a=oc(a.id);sc(a,b,c);qc(d)}else a.width=b,a.height=c},uc=[],vc,V=a=>{var b=uc[a];b||(a>=
uc.length&&(uc.length=a+1),uc[a]=b=vc.get(a));return b},wc=a=>{function b(){document.fullscreenElement||document.webkitFullscreenElement||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",b),tc(a,d,e),a.style.width=f,a.style.height=g,a.style.backgroundColor=m,n||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=n,a.style.paddingLeft=r,a.style.paddingRight=A,a.style.paddingTop=aa,a.style.paddingBottom=H,a.style.marginLeft=
Fd,a.style.marginRight=Gd,a.style.marginTop=Hd,a.style.marginBottom=Id,document.body.style.margin=Jd,document.documentElement.style.overflow=Kd,document.body.scroll=Ld,a.style.oe=Md,a.pe&&a.pe.ne.viewport(0,0,d,e),lc.te&&V(lc.te)(37,0,lc.Ge))}var c=rc(a),d=c[0],e=c[1],f=a.style.width,g=a.style.height,m=a.style.backgroundColor,n=document.body.style.backgroundColor,r=a.style.paddingLeft,A=a.style.paddingRight,aa=a.style.paddingTop,H=a.style.paddingBottom,Fd=a.style.marginLeft,Gd=a.style.marginRight,
Hd=a.style.marginTop,Id=a.style.marginBottom,Jd=document.body.style.margin,Kd=document.documentElement.style.overflow,Ld=document.body.scroll,Md=a.style.oe;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",b)},xc=(a,b,c)=>{a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"},yc=a=>0>mc.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},zc=(a,b)=>{if(0!=b.Ce||0!=b.Ae){wc(a);var c=b.df?innerWidth:screen.width,
d=b.df?innerHeight:screen.height,e=yc(a),f=e.width;e=e.height;var g=rc(a),m=g[0];g=g[1];3==b.Ce?(xc(a,(d-e)/2,(c-f)/2),c=f,d=e):2==b.Ce&&(c*g<m*d?(f=g*c/m,xc(a,(d-f)/2,0),d=f):(f=m*d/g,xc(a,0,(c-f)/2),c=f));a.style.backgroundColor||(a.style.backgroundColor="black");document.body.style.backgroundColor||(document.body.style.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.Ye&&(a.style.oe="optimizeSpeed",a.style.oe="-moz-crisp-edges",a.style.oe="-o-crisp-edges",a.style.oe="-webkit-optimize-contrast",
a.style.oe="optimize-contrast",a.style.oe="crisp-edges",a.style.oe="pixelated");f=2==b.Ae?devicePixelRatio:1;0!=b.Ae&&(c=c*f|0,d=d*f|0,tc(a,c,d),a.pe&&a.pe.ne.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);else return Yb()?-3:-1;lc=b;b.te&&V(b.te)(37,0,b.Ge);return 0},Ac=a=>{if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?-3:-1;return 0},Bc=(a,b)=>
{x[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)x[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)x[a+8*c+528>>3]="object"==typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)q[a+c+1040]="object"==typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];q[a+1104]=b.connected;u[a+1108>>2]=b.index;u[a+8>>2]=b.axes.length;u[a+12>>2]=b.buttons.length;B(b.id,a+1112,64);B(b.mapping,a+1176,64)},Cc=(a,b)=>{I.attachShader(J[a],M[b])},Dc=(a,b)=>{I.bindBuffer(a,zb[b])},
Ec=a=>I.blendEquation(a),Fc=(a,b)=>I.blendFunc(a,b),Gc=(a,b,c,d)=>{I.bufferData(a,c?t.subarray(c,c+b):b,d)},Hc=a=>I.clear(a),Ic=(a,b,c,d)=>I.clearColor(a,b,c,d),Jc=a=>{I.compileShader(M[a])},Kc=()=>{var a=Fb(J),b=I.createProgram();b.name=a;b.xe=b.ve=b.we=0;b.Ee=1;J[a]=b;return a},Lc=a=>{var b=Fb(M);M[b]=I.createShader(a);return b},Mc=a=>{if(a){var b=J[a];b?(I.deleteProgram(b),b.name=0,J[a]=null):P||=1281}},Nc=a=>{I.depthMask(!!a)},Oc=a=>I.disable(a),Pc=[],Qc=(a,b,c,d)=>{I.drawElements(a,b,c,d)},Rc=
a=>I.enable(a),Sc=a=>{I.enableVertexAttribArray(a)},Tc=(a,b)=>{Gb(a,b,"createBuffer",zb)},Uc=(a,b,c,d,e,f,g,m)=>{b=J[b];if(a=I[a](b,c))d=m&&B(a.name,m,d),e&&(u[e>>2]=d),f&&(u[f>>2]=a.size),g&&(u[g>>2]=a.type)},Vc=(a,b)=>I.getAttribLocation(J[a],b?C(t,b):""),Wc=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&(P||=1280);return;case 36345:d=0;break;case 34466:var e=I.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=I.getParameter(a),typeof e){case "number":d=
e;break;case "boolean":d=e?1:0;break;case "string":P||=1280;return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:P||=1280;return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:u[b+4*a>>2]=e[a];break;case 2:w[b+4*a>>2]=e[a];break;case 4:q[b+a]=e[a]?1:0}return}try{d=e.name|0}catch(f){P||=1280;l(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${f})`);
return}}break;default:P||=1280;l(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${e} of type ${typeof e}!`);return}switch(c){case 1:c=d;v[b>>2]=c;v[b+4>>2]=(c-v[b>>2])/4294967296;break;case 0:u[b>>2]=d;break;case 2:w[b>>2]=d;break;case 4:q[b]=d?1:0}}else P||=1281},Xc=(a,b,c,d)=>{a=I.getProgramInfoLog(J[a]);null===a&&(a="(unknown error)");b=0<b&&d?B(a,d,b):0;c&&(u[c>>2]=b)},Yc=(a,b,c)=>{if(c)if(a>=yb)P||=1281;else if(a=J[a],35716==b)a=I.getProgramInfoLog(a),null===
a&&(a="(unknown error)"),u[c>>2]=a.length+1;else if(35719==b){if(!a.xe){var d=I.getProgramParameter(a,35718);for(b=0;b<d;++b)a.xe=Math.max(a.xe,I.getActiveUniform(a,b).name.length+1)}u[c>>2]=a.xe}else if(35722==b){if(!a.ve)for(d=I.getProgramParameter(a,35721),b=0;b<d;++b)a.ve=Math.max(a.ve,I.getActiveAttrib(a,b).name.length+1);u[c>>2]=a.ve}else if(35381==b){if(!a.we)for(d=I.getProgramParameter(a,35382),b=0;b<d;++b)a.we=Math.max(a.we,I.getActiveUniformBlockName(a,b).length+1);u[c>>2]=a.we}else u[c>>
2]=I.getProgramParameter(a,b);else P||=1281},Zc=(a,b,c)=>{if(c){a=I.me.getQueryObjectEXT(O[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;v[c>>2]=d;v[c+4>>2]=(d-v[c>>2])/4294967296}else P||=1281},$c=(a,b,c)=>{if(c){a=I.me.getQueryObjectEXT(O[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;u[c>>2]=d}else P||=1281};function ad(){var a=xb(I);return a=a.concat(a.map(b=>"GL_"+b))}
var bd=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),cd=a=>{var b=a.re,c=a.Oe,d;if(!b){a.re=b={};a.Ne={};var e=I.getProgramParameter(a,35718);for(d=0;d<e;++d){var f=I.getActiveUniform(a,d);var g=f.name;f=f.size;var m=bd(g);m=0<m?g.slice(0,m):g;var n=a.Ee;a.Ee+=f;c[m]=[f,n];for(g=0;g<f;++g)b[n]=g,a.Ne[n++]=m}}},dd=(a,b)=>{b=b?C(t,b):"";if(a=J[a]){cd(a);var c=a.re,d=0,e=b,f=bd(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.Oe[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||I.getUniformLocation(a,b)))return d}else P||=
1281;return-1},W=a=>{var b=I.Qe;if(b){var c=b.re[a];"number"==typeof c&&(b.re[a]=c=I.getUniformLocation(b,b.Ne[a]+(0<c?`[${c}]`:"")));return c}P||=1282},ed=(a,b,c,d)=>{if(c)if(a=J[a],cd(a),a=I.getUniform(a,W(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:u[c>>2]=a;break;case 2:w[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:u[c+4*b>>2]=a[b];break;case 2:w[c+4*b>>2]=a[b]}else P||=1281},fd=(a,b,c,d)=>{if(c)if(a=I.getVertexAttrib(a,b),34975==b)u[c>>2]=a&&a.name;else if("number"==
typeof a||"boolean"==typeof a)switch(d){case 0:u[c>>2]=a;break;case 2:w[c>>2]=a;break;case 5:u[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:u[c+4*b>>2]=a[b];break;case 2:w[c+4*b>>2]=a[b];break;case 5:u[c+4*b>>2]=Math.fround(a[b])}else P||=1281},gd=a=>{a=J[a];I.linkProgram(a);a.re=0;a.Oe={}},hd=(a,b,c,d,e)=>{a-=5120;a=1==a?t:4==a?u:6==a?w:5==a||28922==a?v:la;b=d*((Eb||c)*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+Db-1&-Db);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),
e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},jd=(a,b,c,d)=>{for(var e="",f=0;f<b;++f){var g=(g=v[c+4*f>>2])?C(t,g,d?v[d+4*f>>2]:void 0):"";e+=g}I.shaderSource(M[a],e)},kd=(a,b)=>{I.uniform1f(W(a),b)},X=[],ld=[],md=(a,b,c,d)=>{I.uniform3f(W(a),b,c,d)},nd=(a,b,c,d)=>{if(18>=b){var e=X[16*b],f=w;d>>=2;b*=16;for(var g=0;g<b;g+=16){var m=d+g;e[g]=f[m];e[g+1]=f[m+1];e[g+2]=f[m+2];e[g+3]=f[m+3];e[g+4]=f[m+4];e[g+5]=f[m+5];e[g+6]=f[m+6];e[g+7]=f[m+7];e[g+8]=f[m+8];e[g+9]=f[m+9];e[g+10]=f[m+10];e[g+11]=f[m+
11];e[g+12]=f[m+12];e[g+13]=f[m+13];e[g+14]=f[m+14];e[g+15]=f[m+15]}}else e=w.subarray(d>>2,d+64*b>>2);I.uniformMatrix4fv(W(a),!!c,e)},od=a=>{a=J[a];I.useProgram(a);I.Qe=a},pd=(a,b,c,d,e,f)=>{I.vertexAttribPointer(a,b,c,!!d,e,f)},qd=(a,b,c,d)=>I.viewport(a,b,c,d),rd=(a,b)=>{if(!Yb())return-1;a=U(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?Tb()?zc(a,b):b.Ue?(Rb(zc,1,[a,b]),1):-2:-3:-4},sd=()=>{try{if(navigator.getGamepads)return($b=navigator.getGamepads())?0:-1}catch(a){navigator.getGamepads=
null}return-1},td=(a,b)=>{var c={target:U(2),ge:"beforeunload",je:b,ke:(d=event)=>{var e=V(b)(28,0,a);e&&=e?C(t,e):"";if(e)return d.preventDefault(),d.returnValue=e},ie:!0};return T(c)},ud=(a,b,c,d,e,f)=>{ac||=z(256);a={target:U(a),ge:f,je:d,ke:(g=event)=>{var m=g.target.id?g.target.id:"",n=ac;B(Xb(g.target),n+0,128);B(m,n+128,128);V(d)(e,n,b)&&g.preventDefault()},ie:c};return T(a)},vd=(a,b,c,d,e)=>{cc||=z(276);return T({target:a,ge:e,je:d,ke:(f=event)=>{var g=cc,m=document.fullscreenElement||document.mozFullScreenElement||
document.webkitFullscreenElement||document.msFullscreenElement,n=!!m;q[g]=n;q[g+1]=Yb();var r=n?m:bc,A=r?.id||"";B(Xb(r),g+2,128);B(A,g+130,128);u[g+260>>2]=r?r.clientWidth:0;u[g+264>>2]=r?r.clientHeight:0;u[g+268>>2]=screen.width;u[g+272>>2]=screen.height;n&&(bc=m);V(d)(19,g,b)&&f.preventDefault()},ie:c})},wd=(a,b,c,d,e)=>{dc||=z(1240);b={target:U(2),se:!0,ge:e,je:c,ke:(f=event)=>{var g=dc;Bc(g,f.gamepad);V(c)(d,g,a)&&f.preventDefault()},ie:b};return T(b)},xd=(a,b,c,d,e,f)=>{ec||=z(160);a={target:U(a),
ge:f,je:d,ke:g=>{var m=ec;x[m>>3]=g.timeStamp;var n=m>>2;u[n+2]=g.location;q[m+12]=g.ctrlKey;q[m+13]=g.shiftKey;q[m+14]=g.altKey;q[m+15]=g.metaKey;q[m+16]=g.repeat;u[n+5]=g.charCode;u[n+6]=g.keyCode;u[n+7]=g.which;B(g.key||"",m+32,32);B(g.code||"",m+64,32);B(g.char||"",m+96,32);B(g.locale||"",m+128,32);V(d)(e,m,b)&&g.preventDefault()},ie:c};return T(a)},yd=(a,b,c)=>{x[a>>3]=b.timeStamp;var d=a>>2;u[d+2]=b.screenX;u[d+3]=b.screenY;u[d+4]=b.clientX;u[d+5]=b.clientY;q[a+24]=b.ctrlKey;q[a+25]=b.shiftKey;
q[a+26]=b.altKey;q[a+27]=b.metaKey;ka[2*d+14]=b.button;ka[2*d+15]=b.buttons;u[d+8]=b.movementX;u[d+9]=b.movementY;a=yc(c);u[d+10]=b.clientX-(a.left|0);u[d+11]=b.clientY-(a.top|0)},zd=(a,b,c,d,e,f)=>{fc||=z(64);a=U(a);return T({target:a,se:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,ge:f,je:d,ke:(g=event)=>{yd(fc,g,a);V(d)(e,fc,b)&&g.preventDefault()},ie:c})},Ad=(a,b,c,d,e)=>{gc||=z(257);return T({target:a,ge:e,je:d,ke:(f=event)=>{var g=gc,m=document.pointerLockElement||document.ue||document.$e||
document.Ze;q[g]=!!m;var n=m?.id||"";B(Xb(m),g+1,128);B(n,g+129,128);V(d)(20,g,b)&&f.preventDefault()},ie:c})},Bd=(a,b,c,d)=>{hc||=z(36);a=U(a);return T({target:a,ge:"resize",je:d,ke:(e=event)=>{if(e.target==a){var f=document.body;if(f){var g=hc;u[g>>2]=0;u[g+4>>2]=f.clientWidth;u[g+8>>2]=f.clientHeight;u[g+12>>2]=innerWidth;u[g+16>>2]=innerHeight;u[g+20>>2]=outerWidth;u[g+24>>2]=outerHeight;u[g+28>>2]=pageXOffset|0;u[g+32>>2]=pageYOffset|0;V(d)(10,g,b)&&e.preventDefault()}}},ie:c})},Cd=(a,b,c,d,
e,f)=>{ic||=z(1552);a=U(a);return T({target:a,se:"touchstart"==f||"touchend"==f,ge:f,je:d,ke:g=>{var m={},n=g.touches;for(var r of n)r.Je=r.Le=0,m[r.identifier]=r;for(var A of g.changedTouches)A.Je=1,m[A.identifier]=A;for(var aa of g.targetTouches)m[aa.identifier].Le=1;n=ic;x[n>>3]=g.timeStamp;q[n+12]=g.ctrlKey;q[n+13]=g.shiftKey;q[n+14]=g.altKey;q[n+15]=g.metaKey;r=n+16;A=yc(a);aa=0;for(let H of Object.values(m))if(m=r>>2,u[m]=H.identifier,u[m+1]=H.screenX,u[m+2]=H.screenY,u[m+3]=H.clientX,u[m+4]=
H.clientY,u[m+5]=H.pageX,u[m+6]=H.pageY,q[r+28]=H.Je,q[r+29]=H.Le,u[m+8]=H.clientX-(A.left|0),u[m+9]=H.clientY-(A.top|0),r+=48,31<++aa)break;u[n+8>>2]=aa;V(d)(e,n,b)&&g.preventDefault()},ie:c})},Dd=(a,b,c)=>{var d=mc[1];jc||=z(8);return T({target:d,ge:"visibilitychange",je:c,ke:(e=event)=>{var f=jc,g=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);q[f]=document.hidden;u[f+4>>2]=g;V(c)(21,f,a)&&e.preventDefault()},ie:b})},Ed=(a,b,c,d)=>{kc||=z(96);return T({target:a,se:!0,
ge:"wheel",je:d,ke:(e=event)=>{var f=kc;yd(f,e,a);x[f+64>>3]=e.deltaX;x[f+72>>3]=e.deltaY;x[f+80>>3]=e.deltaZ;u[f+88>>2]=e.deltaMode;V(d)(9,f,b)&&e.preventDefault()},ie:c})},Nd={},Pd=()=>{if(!Od){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in Nd)void 0===Nd[b]?delete a[b]:a[b]=Nd[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);
Od=c}return Od},Od,Qd=[null,[],[]],Rd=(a,b,c)=>{a.addEventListener(b,c,{once:!0})},Aa=a=>{var b;b||=[document,document.getElementById("canvas")];["keydown","mousedown","touchstart"].forEach(c=>{b.forEach(d=>{d&&Rd(d,c,()=>{"suspended"===a.state&&a.resume()})})})},Ba=(a,b=[])=>{if("vi".includes("j")){var c="vi".replace(/p/g,"i");(0,h["dynCall_"+c])(a,...b)}else V(a)(...b)};
h.requestFullscreen=function(a,b){function c(){cb=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=jb,ib&&d.requestPointerLock(),cb=!0,E?("undefined"!=typeof SDL&&(u[SDL.screen>>2]=v[SDL.screen>>2]|8388608),nb(h.canvas),mb()):nb(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),E?("undefined"!=typeof SDL&&(u[SDL.screen>>2]=v[SDL.screen>>
2]&-8388609),nb(h.canvas),mb()):nb(d));h.onFullScreen?.(cb);h.onFullscreen?.(cb)}ib=a;E=b;"undefined"==typeof ib&&(ib=!0);"undefined"==typeof E&&(E=!1);var d=h.canvas;hb||(hb=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=e.requestFullscreen||
e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()};h.requestAnimationFrame=Pa;h.setCanvasSize=function(a,b,c){nb(h.canvas,a,b);c||mb()};h.pauseMainLoop=function(){D=null;Wa++};h.resumeMainLoop=function(){Wa++;var a=Ia,b=Ja,c=Ka;Ka=null;bb(c,0,!1,Xa,!0);Ra(a,b);D()};
h.getUserMedia=function(a){let b;(b=window).getUserMedia||(b.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)};h.createContext=function(a,b,c,d){if(b&&h.le&&a==h.canvas)return h.le;var e;if(b){var f={antialias:!1,alpha:!1,Ke:1};if(d)for(var g in d)f[g]=d[g];if("undefined"!=typeof Mb&&(e=Ib(a,f)))var m=N[e].ne}else m=a.getContext("2d");if(!m)return null;c&&(h.le=m,b&&Lb(e),eb.forEach(n=>n()),fb());return m};for(var Y=0;32>Y;++Y)Pc.push(Array(Y));var Sd=new Float32Array(288);
for(Y=0;288>=Y;++Y)X[Y]=Sd.subarray(0,Y);var Td=new Int32Array(288);for(Y=0;288>=Y;++Y)ld[Y]=Td.subarray(0,Y);
var Ud={X:function(){return 0},Ya:function(){return 0},Za:function(){},_a:()=>1,ab:(a,b,c)=>t.copyWithin(a,b,b+c),Fa:a=>{if(12448==a)return F=12288,1;F=12300;return 0},Ja:(a,b,c,d,e)=>{if(62E3!=a)F=12296,c=0;else{if(b)for(;;){a=u[b>>2];if(12321==a)G.alpha=0<u[b+4>>2];else if(12325==a)G.depth=0<u[b+4>>2];else if(12326==a)G.stencil=0<u[b+4>>2];else if(12337==a)a=u[b+4>>2],G.antialias=0<a;else if(12338==a)a=u[b+4>>2],G.antialias=1==a;else if(12544==a)G.mf=12547!=u[b+4>>2];else if(12344==a)break;b+=8}c&&
d||e?(e&&(u[e>>2]=1),c&&0<d&&(v[c>>2]=62002),F=12288,c=1):(F=12300,c=0)}return c},wa:(a,b,c,d)=>{if(62E3!=a)return F=12296,0;for(a=1;;){b=u[d>>2];if(12440==b)a=u[d+4>>2];else if(12344==b)break;else return F=12292,0;d+=8}if(2!=a)return F=12293,0;G.Ke=a-1;G.nf=0;tb=Ib(h.canvas,G);if(0!=tb)return F=12288,Lb(tb),eb.forEach(e=>e()),Lb(null),62004;F=12297;return 0},ya:(a,b)=>{if(62E3!=a)return F=12296,0;if(62002!=b)return F=12293,0;F=12288;return 62006},xa:(a,b)=>{if(62E3!=a)return F=12296,0;if(62004!=
b)return F=12294,0;a=tb;Kb===N[a]&&(Kb=null);if("object"==typeof Zb)for(var c=N[a].ne.canvas,d=0;d<S.length;++d)S[d].target!=c||Wb(d--);N[a]&&N[a].ne.canvas&&(N[a].ne.canvas.pe=void 0);N[a]=null;F=12288;pb==b&&(pb=0);return 1},za:(a,b)=>{if(62E3!=a)return F=12296,0;if(62006!=b)return F=12301,1;qb==b&&(qb=0);rb==b&&(rb=0);F=12288;return 1},Ka:(a,b,c,d)=>{if(62E3!=a)return F=12296,0;if(62002!=b)return F=12293,0;if(!d)return F=12300,0;F=12288;switch(c){case 12320:return u[d>>2]=G.alpha?32:24,1;case 12321:return u[d>>
2]=G.alpha?8:0,1;case 12322:return u[d>>2]=8,1;case 12323:return u[d>>2]=8,1;case 12324:return u[d>>2]=8,1;case 12325:return u[d>>2]=G.depth?24:0,1;case 12326:return u[d>>2]=G.stencil?8:0,1;case 12327:return u[d>>2]=12344,1;case 12328:return u[d>>2]=62002,1;case 12329:return u[d>>2]=0,1;case 12330:return u[d>>2]=4096,1;case 12331:return u[d>>2]=16777216,1;case 12332:return u[d>>2]=4096,1;case 12333:return u[d>>2]=0,1;case 12334:return u[d>>2]=0,1;case 12335:return u[d>>2]=12344,1;case 12337:return u[d>>
2]=G.antialias?4:0,1;case 12338:return u[d>>2]=G.antialias?1:0,1;case 12339:return u[d>>2]=4,1;case 12340:return u[d>>2]=12344,1;case 12341:case 12342:case 12343:return u[d>>2]=-1,1;case 12345:case 12346:return u[d>>2]=0,1;case 12347:return u[d>>2]=0,1;case 12348:return u[d>>2]=1;case 12349:case 12350:return u[d>>2]=0,1;case 12351:return u[d>>2]=12430,1;case 12352:return u[d>>2]=4,1;case 12354:return u[d>>2]=0,1;default:return F=12292,0}},Q:a=>{F=12288;return 0!=a&&1!=a?0:62E3},va:()=>F,Ha:(a,b,c)=>
{if(62E3!=a)return F=12296,0;b&&(u[b>>2]=1);c&&(u[c>>2]=4);ob=!0;F=12288;return 1},Aa:(a,b,c,d)=>{if(62E3!=a)return F=12296,0;if(0!=d&&62004!=d)return F=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return F=12301,0;Lb(d?tb:null);pb=d;rb=b;qb=c;F=12288;return 1},ua:(a,b)=>{if(62E3!=a)return F=12296,0;F=12288;if(sb[b])return sb[b];switch(b){case 12371:a=Q("Emscripten");break;case 12372:a=Q("1.4 Emscripten EGL");break;case 12373:a=Q("");break;case 12429:a=Q("OpenGL_ES");break;default:return F=12300,0}return sb[b]=
a},Ba:()=>{if(ob)if(h.le)if(h.le.isContextLost())F=12302;else return F=12288,1;else F=12290;else F=12289;return 0},Ca:(a,b)=>{if(62E3!=a)return F=12296,0;0==b?Ra(0,0):Ra(1,b);F=12288;return 1},Ia:a=>{if(62E3!=a)return F=12296,0;rb=qb=pb=0;ob=!1;F=12288;return 1},Ea:()=>{F=12288;return 1},Da:()=>{F=12288;return 1},Ma:(a,b,c)=>{b=Pb(b,c);return Da[a](...b)},e:(a,b,c)=>{b=Pb(b,c);return Da[a](...b)},Na:(a,b,c)=>{b=Pb(b,c);return Da[a](...b)},$a:()=>Date.now(),na:()=>{if(!Yb())return-1;Sb(zc);var a=mc[1];
if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},sa:()=>{Sb(Ac);if(document.exitPointerLock)document.exitPointerLock();else return-1;return 0},j:()=>devicePixelRatio,f:(a,b,c)=>{a=U(a);if(!a)return-4;a=yc(a);x[b>>3]=a.width;x[c>>3]=a.height;return 0},T:(a,b)=>{if(0>a||a>=$b.length)return-5;if(!$b[a])return-7;Bc(b,$b[a]);return 0},u:Na,La:()=>$b.length,ta:(a,b)=>{u[a>>2]=screen.width;
u[b>>2]=screen.height},Qd:a=>I.activeTexture(a),Pd:Cc,ja:(a,b)=>{I.me.beginQueryEXT(a,O[b])},Od:(a,b,c)=>{I.bindAttribLocation(J[a],b,c?C(t,c):"")},Nd:Dc,Md:(a,b)=>{I.bindFramebuffer(a,Ab[b])},Ld:(a,b)=>{I.bindRenderbuffer(a,K[b])},Kd:(a,b)=>{I.bindTexture(a,L[b])},ba:a=>{I.bindVertexArray(Bb[a])},Jd:(a,b,c,d)=>I.blendColor(a,b,c,d),Id:Ec,Hd:(a,b)=>I.blendEquationSeparate(a,b),Gd:Fc,Fd:(a,b,c,d)=>I.blendFuncSeparate(a,b,c,d),Ed:Gc,Dd:(a,b,c,d)=>{I.bufferSubData(a,b,t.subarray(d,d+c))},Bd:a=>I.checkFramebufferStatus(a),
Ad:Hc,zd:Ic,yd:a=>I.clearDepth(a),xd:a=>I.clearStencil(a),cb:(a,b)=>{I.We.clipControlEXT(a,b)},wd:(a,b,c,d)=>{I.colorMask(!!a,!!b,!!c,!!d)},vd:Jc,ud:(a,b,c,d,e,f,g,m)=>{I.compressedTexImage2D(a,b,c,d,e,f,t.subarray(m,m+g))},td:(a,b,c,d,e,f,g,m,n)=>{I.compressedTexSubImage2D(a,b,c,d,e,f,g,t.subarray(n,n+m))},sd:(a,b,c,d,e,f,g,m)=>I.copyTexImage2D(a,b,c,d,e,f,g,m),rd:(a,b,c,d,e,f,g,m)=>I.copyTexSubImage2D(a,b,c,d,e,f,g,m),qd:Kc,pd:Lc,od:a=>I.cullFace(a),nd:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>
2],e=zb[d];e&&(I.deleteBuffer(e),e.name=0,zb[d]=null)}},md:(a,b)=>{for(var c=0;c<a;++c){var d=u[b+4*c>>2],e=Ab[d];e&&(I.deleteFramebuffer(e),e.name=0,Ab[d]=null)}},ld:Mc,la:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=O[d];e&&(I.me.deleteQueryEXT(e),O[d]=null)}},kd:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=K[d];e&&(I.deleteRenderbuffer(e),e.name=0,K[d]=null)}},jd:a=>{if(a){var b=M[a];b?(I.deleteShader(b),M[a]=null):P||=1281}},id:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=L[d];e&&
(I.deleteTexture(e),e.name=0,L[d]=null)}},aa:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2];I.deleteVertexArray(Bb[d]);Bb[d]=null}},gd:a=>I.depthFunc(a),fd:Nc,ed:(a,b)=>I.depthRange(a,b),dd:(a,b)=>{I.detachShader(J[a],M[b])},cd:Oc,bd:a=>{I.disableVertexAttribArray(a)},ad:(a,b,c)=>{I.drawArrays(a,b,c)},Td:(a,b,c,d)=>{I.drawArraysInstanced(a,b,c,d)},Ud:(a,b)=>{for(var c=Pc[a],d=0;d<a;d++)c[d]=u[b+4*d>>2];I.drawBuffers(c)},$c:Qc,Sd:(a,b,c,d,e)=>{I.drawElementsInstanced(a,b,c,d,e)},_c:Rc,Zc:Sc,ia:a=>
{I.me.endQueryEXT(a)},Yc:()=>I.finish(),Xc:()=>I.flush(),Wc:(a,b,c,d)=>{I.framebufferRenderbuffer(a,b,c,K[d])},Vc:(a,b,c,d,e)=>{I.framebufferTexture2D(a,b,c,L[d],e)},Uc:a=>I.frontFace(a),Tc,Rc:(a,b)=>{Gb(a,b,"createFramebuffer",Ab)},ma:(a,b)=>{for(var c=0;c<a;c++){var d=I.me.createQueryEXT();if(!d){for(P||=1282;c<a;)u[b+4*c++>>2]=0;break}var e=Fb(O);d.name=e;O[e]=d;u[b+4*c>>2]=e}},Qc:(a,b)=>{Gb(a,b,"createRenderbuffer",K)},Pc:(a,b)=>{Gb(a,b,"createTexture",L)},Wd:(a,b)=>{Gb(a,b,"createVertexArray",
Bb)},Sc:a=>I.generateMipmap(a),Oc:(a,b,c,d,e,f,g)=>{Uc("getActiveAttrib",a,b,c,d,e,f,g)},Nc:(a,b,c,d,e,f,g)=>{Uc("getActiveUniform",a,b,c,d,e,f,g)},Mc:(a,b,c,d)=>{a=I.getAttachedShaders(J[a]);var e=a.length;e>b&&(e=b);u[c>>2]=e;for(b=0;b<e;++b)u[d+4*b>>2]=M.indexOf(a[b])},Lc:Vc,Kc:(a,b)=>Wc(a,b,4),Jc:(a,b,c)=>{c?u[c>>2]=I.getBufferParameter(a,b):P||=1281},Ic:()=>{var a=I.getError()||P;P=0;return a},Hc:(a,b)=>Wc(a,b,2),Gc:(a,b,c,d)=>{a=I.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||
a instanceof WebGLTexture)a=a.name|0;u[d>>2]=a},Fc:(a,b)=>Wc(a,b,0),Cc:Xc,Dc:Yc,da:Zc,fa:$c,ca:Zc,ea:$c,ga:(a,b,c)=>{c?u[c>>2]=I.me.getQueryEXT(a,b):P||=1281},Bc:(a,b,c)=>{c?u[c>>2]=I.getRenderbufferParameter(a,b):P||=1281},zc:(a,b,c,d)=>{a=I.getShaderInfoLog(M[a]);null===a&&(a="(unknown error)");b=0<b&&d?B(a,d,b):0;c&&(u[c>>2]=b)},yc:(a,b,c,d)=>{a=I.getShaderPrecisionFormat(a,b);u[c>>2]=a.rangeMin;u[c+4>>2]=a.rangeMax;u[d>>2]=a.precision},xc:(a,b,c,d)=>{if(a=I.getShaderSource(M[a]))b=0<b&&d?B(a,
d,b):0,c&&(u[c>>2]=b)},Ac:(a,b,c)=>{c?35716==b?(a=I.getShaderInfoLog(M[a]),null===a&&(a="(unknown error)"),u[c>>2]=a?a.length+1:0):35720==b?(a=I.getShaderSource(M[a]),u[c>>2]=a?a.length+1:0):u[c>>2]=I.getShaderParameter(M[a],b):P||=1281},wc:a=>{var b=Cb[a];if(!b){switch(a){case 7939:b=Q(ad().join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=I.getParameter(a))||(P||=1280);b=b?Q(b):0;break;case 7938:b=Q(`OpenGL ES 2.0 (${I.getParameter(7938)})`);break;case 35724:b=I.getParameter(35724);
var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=Q(b);break;default:P||=1280}Cb[a]=b}return b},vc:(a,b,c)=>{c?w[c>>2]=I.getTexParameter(a,b):P||=1281},uc:(a,b,c)=>{c?u[c>>2]=I.getTexParameter(a,b):P||=1281},qc:dd,sc:(a,b,c)=>{ed(a,b,c,2)},rc:(a,b,c)=>{ed(a,b,c,0)},nc:(a,b,c)=>{c?u[c>>2]=I.getVertexAttribOffset(a,b):P||=1281},pc:(a,b,c)=>{fd(a,b,c,2)},oc:(a,b,c)=>{fd(a,b,c,5)},mc:(a,b)=>I.hint(a,b),lc:a=>(a=
zb[a])?I.isBuffer(a):0,kc:a=>I.isEnabled(a),jc:a=>(a=Ab[a])?I.isFramebuffer(a):0,ic:a=>(a=J[a])?I.isProgram(a):0,ka:a=>(a=O[a])?I.me.isQueryEXT(a):0,hc:a=>(a=K[a])?I.isRenderbuffer(a):0,gc:a=>(a=M[a])?I.isShader(a):0,fc:a=>(a=L[a])?I.isTexture(a):0,Vd:a=>(a=Bb[a])?I.isVertexArray(a):0,ec:a=>I.lineWidth(a),dc:gd,cc:(a,b)=>{3317==a?Db=b:3314==a&&(Eb=b);I.pixelStorei(a,b)},bb:(a,b)=>{I.ef.polygonModeWEBGL(a,b)},bc:(a,b)=>I.polygonOffset(a,b),db:(a,b,c)=>{I.Xe.polygonOffsetClampEXT(a,b,c)},ha:(a,b)=>
{I.me.queryCounterEXT(O[a],b)},ac:(a,b,c,d,e,f,g)=>{(g=hd(f,e,c,d,g))?I.readPixels(a,b,c,d,e,f,g):P||=1280},$b:()=>{},_b:(a,b,c,d)=>I.renderbufferStorage(a,b,c,d),Zb:(a,b)=>{I.sampleCoverage(a,!!b)},Yb:(a,b,c,d)=>I.scissor(a,b,c,d),Xb:()=>{P||=1280},Wb:jd,Vb:(a,b,c)=>I.stencilFunc(a,b,c),Ub:(a,b,c,d)=>I.stencilFuncSeparate(a,b,c,d),Tb:a=>I.stencilMask(a),Sb:(a,b)=>I.stencilMaskSeparate(a,b),Rb:(a,b,c)=>I.stencilOp(a,b,c),Pb:(a,b,c,d)=>I.stencilOpSeparate(a,b,c,d),Ob:(a,b,c,d,e,f,g,m,n)=>{n=n?hd(m,
g,d,e,n):null;I.texImage2D(a,b,c,d,e,f,g,m,n)},Nb:(a,b,c)=>I.texParameterf(a,b,c),Mb:(a,b,c)=>{I.texParameterf(a,b,w[c>>2])},Lb:(a,b,c)=>I.texParameteri(a,b,c),Kb:(a,b,c)=>{I.texParameteri(a,b,u[c>>2])},Jb:(a,b,c,d,e,f,g,m,n)=>{n=n?hd(m,g,e,f,n):null;I.texSubImage2D(a,b,c,d,e,f,g,m,n)},Ib:kd,Hb:(a,b,c)=>{if(288>=b)for(var d=X[b],e=0;e<b;++e)d[e]=w[c+4*e>>2];else d=w.subarray(c>>2,c+4*b>>2);I.uniform1fv(W(a),d)},Gb:(a,b)=>{I.uniform1i(W(a),b)},Fb:(a,b,c)=>{if(288>=b)for(var d=ld[b],e=0;e<b;++e)d[e]=
u[c+4*e>>2];else d=u.subarray(c>>2,c+4*b>>2);I.uniform1iv(W(a),d)},Eb:(a,b,c)=>{I.uniform2f(W(a),b,c)},Db:(a,b,c)=>{if(144>=b){b*=2;for(var d=X[b],e=0;e<b;e+=2)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2]}else d=w.subarray(c>>2,c+8*b>>2);I.uniform2fv(W(a),d)},Cb:(a,b,c)=>{I.uniform2i(W(a),b,c)},Bb:(a,b,c)=>{if(144>=b){b*=2;for(var d=ld[b],e=0;e<b;e+=2)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2]}else d=u.subarray(c>>2,c+8*b>>2);I.uniform2iv(W(a),d)},Ab:md,zb:(a,b,c)=>{if(96>=b){b*=3;for(var d=X[b],e=0;e<b;e+=
3)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2]}else d=w.subarray(c>>2,c+12*b>>2);I.uniform3fv(W(a),d)},yb:(a,b,c,d)=>{I.uniform3i(W(a),b,c,d)},xb:(a,b,c)=>{if(96>=b){b*=3;for(var d=ld[b],e=0;e<b;e+=3)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2]}else d=u.subarray(c>>2,c+12*b>>2);I.uniform3iv(W(a),d)},wb:(a,b,c,d,e)=>{I.uniform4f(W(a),b,c,d,e)},vb:(a,b,c)=>{if(72>=b){var d=X[4*b],e=w;c>>=2;b*=4;for(var f=0;f<b;f+=4){var g=c+f;d[f]=e[g];d[f+1]=e[g+1];d[f+2]=e[g+2];
d[f+3]=e[g+3]}}else d=w.subarray(c>>2,c+16*b>>2);I.uniform4fv(W(a),d)},ub:(a,b,c,d,e)=>{I.uniform4i(W(a),b,c,d,e)},tb:(a,b,c)=>{if(72>=b){b*=4;for(var d=ld[b],e=0;e<b;e+=4)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2],d[e+3]=u[c+(4*e+12)>>2]}else d=u.subarray(c>>2,c+16*b>>2);I.uniform4iv(W(a),d)},sb:(a,b,c,d)=>{if(72>=b){b*=4;for(var e=X[b],f=0;f<b;f+=4)e[f]=w[d+4*f>>2],e[f+1]=w[d+(4*f+4)>>2],e[f+2]=w[d+(4*f+8)>>2],e[f+3]=w[d+(4*f+12)>>2]}else e=w.subarray(d>>2,d+16*b>>2);I.uniformMatrix2fv(W(a),
!!c,e)},rb:(a,b,c,d)=>{if(32>=b){b*=9;for(var e=X[b],f=0;f<b;f+=9)e[f]=w[d+4*f>>2],e[f+1]=w[d+(4*f+4)>>2],e[f+2]=w[d+(4*f+8)>>2],e[f+3]=w[d+(4*f+12)>>2],e[f+4]=w[d+(4*f+16)>>2],e[f+5]=w[d+(4*f+20)>>2],e[f+6]=w[d+(4*f+24)>>2],e[f+7]=w[d+(4*f+28)>>2],e[f+8]=w[d+(4*f+32)>>2]}else e=w.subarray(d>>2,d+36*b>>2);I.uniformMatrix3fv(W(a),!!c,e)},qb:nd,pb:od,ob:a=>{I.validateProgram(J[a])},nb:(a,b)=>I.vertexAttrib1f(a,b),mb:(a,b)=>{I.vertexAttrib1f(a,w[b>>2])},lb:(a,b,c)=>I.vertexAttrib2f(a,b,c),kb:(a,b)=>
{I.vertexAttrib2f(a,w[b>>2],w[b+4>>2])},jb:(a,b,c,d)=>I.vertexAttrib3f(a,b,c,d),ib:(a,b)=>{I.vertexAttrib3f(a,w[b>>2],w[b+4>>2],w[b+8>>2])},hb:(a,b,c,d,e)=>I.vertexAttrib4f(a,b,c,d,e),gb:(a,b)=>{I.vertexAttrib4f(a,w[b>>2],w[b+4>>2],w[b+8>>2],w[b+12>>2])},Rd:(a,b)=>{I.vertexAttribDivisor(a,b)},fb:pd,eb:qd,n:()=>0,oa:(a,b,c)=>rd(a,{Ce:u[c>>2],Ae:u[c+4>>2],Ye:u[c+8>>2],Ue:b,te:u[c+12>>2],Ge:u[c+16>>2]}),O:(a,b)=>{a=U(a);return a?a.requestPointerLock?Tb()?Ac(a):b?(Rb(Ac,2,[a]),1):-2:-1:-4},Ua:()=>{ta("OOM")},
U:sd,y:(a,b,c)=>"undefined"==typeof onbeforeunload?-1:1!==c?-5:td(a,b),J:(a,b,c,d)=>ud(a,b,c,d,12,"blur"),i:sc,l:(a,b,c)=>{a=U(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},K:(a,b,c,d)=>ud(a,b,c,d,13,"focus"),A:(a,b,c,d)=>{if(!Yb())return-1;a=U(a);if(!a)return-4;vd(a,b,c,d,"webkitfullscreenchange");return vd(a,b,c,d,"fullscreenchange")},S:(a,b,c)=>sd()?-1:wd(a,b,c,26,"gamepadconnected"),R:(a,b,c)=>sd()?-1:wd(a,b,c,27,"gamepaddisconnected"),D:(a,b,c,d)=>xd(a,b,c,d,2,"keydown"),
B:(a,b,c,d)=>xd(a,b,c,d,1,"keypress"),C:(a,b,c,d)=>xd(a,b,c,d,3,"keyup"),Oa:(a,b,c)=>{a=V(a);bb(a,b,c)},q:(a,b,c,d)=>zd(a,b,c,d,5,"mousedown"),N:(a,b,c,d)=>zd(a,b,c,d,33,"mouseenter"),M:(a,b,c,d)=>zd(a,b,c,d,34,"mouseleave"),r:(a,b,c,d)=>zd(a,b,c,d,8,"mousemove"),p:(a,b,c,d)=>zd(a,b,c,d,6,"mouseup"),E:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.ue||document.body.$e||document.body.Ze))return-1;a=U(a);if(!a)return-4;Ad(a,b,c,d,"mozpointerlockchange");
Ad(a,b,c,d,"webkitpointerlockchange");Ad(a,b,c,d,"mspointerlockchange");return Ad(a,b,c,d,"pointerlockchange")},s:(a,b,c,d)=>Bd(a,b,c,d),F:(a,b,c,d)=>Cd(a,b,c,d,25,"touchcancel"),H:(a,b,c,d)=>Cd(a,b,c,d,23,"touchend"),G:(a,b,c,d)=>Cd(a,b,c,d,24,"touchmove"),I:(a,b,c,d)=>Cd(a,b,c,d,22,"touchstart"),z:(a,b,c)=>Dd(a,b,c),L:(a,b,c,d)=>(a=U(a))?"undefined"!=typeof a.onwheel?Ed(a,b,c,d):-1:-4,pa:a=>document.title=a?C(t,a):"",m:()=>{throw"Please compile your program with async support in order to use asynchronous operations like emscripten_sleep";
},Va:(a,b)=>{var c=0;Pd().forEach((d,e)=>{var f=b+c;e=v[a+4*e>>2]=f;for(f=0;f<d.length;++f)q[e++]=d.charCodeAt(f);q[e]=0;c+=d.length+1});return 0},Wa:(a,b)=>{var c=Pd();v[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);v[b>>2]=d;return 0},V:()=>52,Xa:()=>52,Ta:function(){return 70},W:(a,b,c,d)=>{for(var e=0,f=0;f<c;f++){var g=v[b>>2],m=v[b+4>>2];b+=8;for(var n=0;n<m;n++){var r=t[g+n],A=Qd[a];0===r||10===r?((1===a?fa:l)(C(A,0)),A.length=0):A.push(r)}e+=m}v[d>>2]=e;return 0},Z:Cc,a:Dc,Ra:Ec,Sa:Fc,
b:Gc,Qb:Hc,Qa:Ic,_:Jc,Cd:Kc,x:Lc,qa:Mc,k:Nc,Y:Oc,Ga:Qc,v:Rc,o:Sc,c:Tc,w:Vc,ra:Xc,P:Yc,g:dd,hd:gd,$:jd,h:kd,Pa:md,d:nd,Ec:od,t:pd,tc:qd},Z=function(){function a(c){Z=c.exports;ia=Z.Xd;c=ia.buffer;h.HEAP8=q=new Int8Array(c);h.HEAP16=ka=new Int16Array(c);h.HEAPU8=t=new Uint8Array(c);h.HEAPU16=la=new Uint16Array(c);h.HEAP32=u=new Int32Array(c);h.HEAPU32=v=new Uint32Array(c);h.HEAPF32=w=new Float32Array(c);h.HEAPF64=x=new Float64Array(c);vc=Z.$d;na.unshift(Z.Yd);y--;h.monitorRunDependencies?.(y);0==y&&
(null!==ra&&(clearInterval(ra),ra=null),sa&&(c=sa,sa=null,c()));return Z}var b={a:Ud};y++;h.monitorRunDependencies?.(y);if(h.instantiateWasm)try{return h.instantiateWasm(b,a)}catch(c){return l(`Module.instantiateWasm callback failed with error: ${c}`),!1}va||=ua("index.wasm")?"index.wasm":h.locateFile?h.locateFile("index.wasm",k):k+"index.wasm";za(b,function(c){a(c.instance)});return{}}(),z=a=>(z=Z.Zd)(a),Vd=h._main=(a,b)=>(Vd=h._main=Z._d)(a,b),qc=a=>(qc=Z.ae)(a),nc=a=>(nc=Z.be)(a),pc=()=>(pc=Z.ce)();
h.dynCall_jiji=(a,b,c,d,e)=>(h.dynCall_jiji=Z.de)(a,b,c,d,e);h.dynCall_ji=(a,b)=>(h.dynCall_ji=Z.ee)(a,b);var Wd;sa=function Xd(){Wd||Yd();Wd||(sa=Xd)};function Zd(a=[]){var b=Vd;a.unshift(da);var c=a.length,d=nc(4*(c+1)),e=d;a.forEach(g=>{v[e>>2]=oc(g);e+=4});v[e>>2]=0;try{var f=b(c,d);Ta(f)}catch(g){Ua(g)}}
function Yd(){var a=ca;function b(){if(!Wd&&(Wd=!0,h.calledRun=!0,!p)){Fa(na);Fa(oa);h.onRuntimeInitialized?.();$d&&Zd(a);if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var c=h.postRun.shift();pa.unshift(c)}Fa(pa)}}if(!(0<y)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)qa();Fa(ma);0<y||(h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),1);b()},1)):b())}}
if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();var $d=!0;h.noInitialRun&&($d=!1);Yd();
