var h;h||=typeof Module != 'undefined' ? Module : {};var aa=[],ca="./this.program",da="",ea;"undefined"!=typeof document&&document.currentScript&&(da=document.currentScript.src);da=da.startsWith("blob:")?"":da.slice(0,da.replace(/[?#].*/,"").lastIndexOf("/")+1);ea=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};
var fa=console.log.bind(console),ha=console.error.bind(console),ia,ja,ka=!1,ma,k,m,p,na,q,r,u,oa,w,pa=0,qa=null;function ra(){pa++;h.monitorRunDependencies?.(pa)}function sa(){pa--;h.monitorRunDependencies?.(pa);if(0==pa&&qa){var a=qa;qa=null;a()}}function ta(a){h.onAbort?.(a);a="Aborted("+a+")";ha(a);ka=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ua;
async function va(a){if(!ia)try{var b=await ea(a);return new Uint8Array(b)}catch{}if(a==ua&&ia)a=new Uint8Array(ia);else throw"both async and sync fetching of the wasm failed";return a}async function wa(a,b){try{var c=await va(a);return await WebAssembly.instantiate(c,b)}catch(d){ha(`failed to asynchronously prepare wasm: ${d}`),ta(d)}}
async function xa(a){var b=ua;if(!ia&&"function"==typeof WebAssembly.instantiateStreaming)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){ha(`wasm streaming compile failed: ${d}`),ha("falling back to ArrayBuffer instantiation")}return wa(b,a)}class ya{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var za=a=>{for(;0<a.length;)a.shift()(h)},Aa=[],Ba=[],Ca=()=>{var a=h.preRun.shift();Ba.push(a)},Da=!0;function Ea(a,b){var c="float";c.endsWith("*")&&(c="*");switch(c){case "i1":k[a]=b;break;case "i8":k[a]=b;break;case "i16":p[a>>1]=b;break;case "i32":q[a>>2]=b;break;case "i64":oa[a>>3]=BigInt(b);break;case "float":u[a>>2]=b;break;case "double":w[a>>3]=b;break;case "*":r[a>>2]=b;break;default:ta(`invalid type for setValue: ${c}`)}}
var Fa="undefined"!=typeof TextDecoder?new TextDecoder:void 0,x=(a,b=0,c=NaN)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Fa)return Fa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var f=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|f:(e&7)<<18|g<<12|f<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
Ha=(a,b)=>a?x(m,a,b):"",Ia=a=>{if(!(a instanceof ya||"unwind"==a))throw a;},Ja=a=>{ma=a;Da||(h.onExit?.(a),ka=!0);throw new ya(a);},Ka=a=>{ma=a;Ja(a)},La=()=>{if(!Da)try{var a=ma;ma=a;Ja(a)}catch(b){Ia(b)}},Ma=!1,Na=!1,Oa=[];
function Pa(){function a(){var c=h.canvas;Na=document.pointerLockElement===c||document.mozPointerLockElement===c||document.webkitPointerLockElement===c||document.msPointerLockElement===c}if(!Qa){Qa=!0;var b=h.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),b.exitPointerLock=
b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",c=>{!Na&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}var Ra=!1,Sa=void 0,Ta=void 0;
function Ua(){if(!Ma)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var Va=[];function Wa(){var a=h.canvas;Va.forEach(b=>b(a.width,a.height))}
function Xa(a,b,c){b&&c?(a.Af=b,a.sf=c):(b=a.Af,c=a.sf);var d=b,e=c;0<h.forcedAspectRatio&&(d/e<h.forcedAspectRatio?d=Math.round(e*h.forcedAspectRatio):e=Math.round(d/h.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/d,screen.height/e);d=Math.round(d*g);e=Math.round(e*g)}Ta?(a.width!=d&&(a.width=
d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var Qa,y=12288,Ya=!1,Za=0,$a=0,ab=0,z={alpha:!1,depth:!1,stencil:!1,antialias:!1},bb={},cb,B,db=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,g)=>b.drawArraysInstancedANGLE(c,d,e,g),a.drawElementsInstanced=(c,d,e,g,f)=>b.drawElementsInstancedANGLE(c,d,e,g,f))},eb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),
a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},fb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},gb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},hb=1,ib=[],F=[],jb=[],kb=[],lb=[],H=[],mb=[],I=[],nb=[],ob={},pb=4,qb=0,rb=a=>{for(var b=hb++,c=a.length;c<b;c++)a[c]=null;return b},sb=(a,b,c,d)=>{for(var e=0;e<a;e++){var g=B[c](),f=g&&rb(d);g?(g.name=f,d[f]=g):J||=1282;q[b+4*e>>2]=f}},ub=(a,b)=>{a.ne||(a.ne=a.getContext,a.getContext=function(d,e){e=a.ne(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?tb(c,b):0},tb=(a,b)=>{var c=
rb(I),d={handle:c,attributes:b,version:b.af,re:a};a.canvas&&(a.canvas.ve=d);I[c]=d;("undefined"==typeof b.nf||b.nf)&&vb(d);return c},xb=a=>{wb=I[a];h.ctx=B=wb?.re},vb=a=>{a||=wb;if(!a.uf){a.uf=!0;var b=a.re;b.Mf=b.getExtension("WEBGL_multi_draw");b.qf=b.getExtension("EXT_polygon_offset_clamp");b.pf=b.getExtension("EXT_clip_control");b.zf=b.getExtension("WEBGL_polygon_mode");db(b);eb(b);fb(b);b.qe=b.getExtension("EXT_disjoint_timer_query");gb(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||
b.getExtension(c)})}},yb={},J,wb,zb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},K=(a,b,c)=>{var d=m;if(!(0<c))return 0;var e=b;c=b+c-1;for(var g=0;g<a.length;++g){var f=a.charCodeAt(g);if(55296<=f&&57343>=f){var l=a.charCodeAt(++g);f=65536+((f&1023)<<10)|l&1023}if(127>=f){if(b>=c)break;d[b++]=f}else{if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6}else{if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12}else{if(b+3>=c)break;d[b++]=
240|f>>18;d[b++]=128|f>>12&63}d[b++]=128|f>>6&63}d[b++]=128|f&63}}d[b]=0;return b-e},Ab=a=>{var b=zb(a)+1,c=L(b);c&&K(a,c,b);return c},Sb=(a,b,c,d,e)=>{function g(){return f<Bb?(La(),!1):!0}Cb=a;Db=d;var f=Bb;Eb=!1;Fb=function(){if(!ka)if(0<Gb.length){var l=Gb.shift();l.If(l.Bf);if(Ib){var n=Ib,v=0==n%1?n-1:Math.floor(n);Ib=l.Ef?v:(8*n+(v+.5))/9}h.setStatus&&(l=h.statusMessage||"Please wait...",n=Ib??0,v=Jb.Hf??0,n?n<v?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(l):h.setStatus(""));
g()&&setTimeout(Fb,0)}else if(g())if(Kb=Kb+1|0,1==Lb&&1<Mb&&0!=Kb%Mb)Nb();else{0==Lb&&(Ob=performance.now());a:if(!ka){for(l of Pb)if(!1===l())break a;if(!ka)try{a(),La()}catch(E){Ia(E)}for(n of Qb)n()}g()&&Nb()}};e||(0<b?Rb(0,1E3/b):Rb(1,1),Nb());if(c)throw"unwind";},Eb=!1,Nb=null,Bb=0,Cb=null,Db=0,Lb=0,Mb=0,Kb=0,Gb=[],Pb=[],Qb=[],Tb=0;
function Ub(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Tb)Tb=b+1E3/60;else for(;b+2>=Tb;)Tb+=1E3/60;setTimeout(a,Math.max(Tb-b,0))}}
var Jb={},Fb,Ib,Ob,Vb,Rb=(a,b)=>{Lb=a;Mb=b;if(Cb)if(Eb||=!0,0==a)Nb=function(){setTimeout(Fb,Math.max(0,Ob+b-performance.now())|0)};else if(1==a)Nb=function(){Ub(Fb)};else if(2==a){if("undefined"==typeof Vb)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Vb=d=>{c.push(d);postMessage("setimmediate","*")}}else Vb=setImmediate;Nb=function(){Vb(Fb)}}},Wb=[],Xb=(a,b)=>{Wb.length=
0;for(var c;c=m[a++];){var d=105!=c;d&=112!=c;b+=d&&b%8?4:0;Wb.push(112==c?r[b>>2]:106==c?oa[b>>3]:105==c?q[b>>2]:w[b>>3]);b+=d?8:4}return Wb};function Yb(a){var b=M.le[a];b.target.removeEventListener(b.ie,b.Ze,b.je);M.le.splice(a,1)}function Zb(a,b,c){function d(g,f){if(g.length!=f.length)return!1;for(var l in g)if(g[l]!=f[l])return!1;return!0}for(var e of M.se)if(e.Re==a&&d(e.Xe,c))return;M.se.push({Re:a,cf:b,Xe:c});M.se.sort((g,f)=>g.cf<f.cf)}function $b(a){M.se=M.se.filter(b=>b.Re!=a)}
function ac(){return navigator.userActivation?navigator.userActivation.isActive:M.Me&&M.gf.xe}function bc(){if(ac()){var a=M.se;M.se=[];for(var b of a)b.Re(...b.Xe)}}function N(a){if(!a.target)return-4;if(a.ke)a.Ze=function(c){++M.Me;M.gf=a;bc();a.me(c);bc();--M.Me},a.target.addEventListener(a.ie,a.Ze,a.je),M.le.push(a);else for(var b=0;b<M.le.length;++b)M.le[b].target==a.target&&M.le[b].ie==a.ie&&Yb(b--);return 0}
function cc(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var M={Cf:0,Le:0,Ne:0,Ge:0,We:0,Te:0,Je:0,Gf:0,Nf:0,Ff:0,Ke:0,Pe:0,Ve:0,Se:0,Kf(a,b,c){k.set(k.subarray(b,b+c),a)},Of(){for(;M.le.length;)Yb(M.le.length-1);M.se=[]},Me:0,se:[],le:[],xf:(a,b)=>{for(var c=0;c<M.le.length;++c)M.le[c].target!=a||b&&b!=M.le[c].ie||Yb(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},dc=[0,document,window],O=a=>{a=2<a?a?x(m,a):"":a;return dc[a]||document.querySelector(a)},fc=a=>{var b=zb(a)+1,c=ec(b);K(a,c,b);return c},ic=a=>
{var b=gc(),c=ec(8),d=c+4;a=fc(a.id);if(a=O(a))q[c>>2]=a.width,q[d>>2]=a.height;c=[q[c>>2],q[d>>2]];hc(b);return c},jc=(a,b,c)=>{a=O(a);if(!a)return-4;a.width=b;a.height=c;return 0},kc=(a,b,c)=>{if(a.Df){var d=gc();a=fc(a.id);jc(a,b,c);hc(d)}else a.width=b,a.height=c},lc={},mc=[],nc,P=a=>{var b=mc[a];b||(mc[a]=b=nc.get(a));return b},oc=a=>{function b(){document.fullscreenElement||document.webkitFullscreenElement||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",
b),kc(a,d,e),a.style.width=g,a.style.height=f,a.style.backgroundColor=l,n||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=n,a.style.paddingLeft=v,a.style.paddingRight=E,a.style.paddingTop=C,a.style.paddingBottom=G,a.style.marginLeft=T,a.style.marginRight=ba,a.style.marginTop=U,a.style.marginBottom=Q,document.body.style.margin=X,document.documentElement.style.overflow=la,document.body.scroll=t,a.style.te=V,a.ve&&a.ve.re.viewport(0,0,d,e),lc.ye&&P(lc.ye)(37,0,lc.Ye))}
var c=ic(a),d=c[0],e=c[1],g=a.style.width,f=a.style.height,l=a.style.backgroundColor,n=document.body.style.backgroundColor,v=a.style.paddingLeft,E=a.style.paddingRight,C=a.style.paddingTop,G=a.style.paddingBottom,T=a.style.marginLeft,ba=a.style.marginRight,U=a.style.marginTop,Q=a.style.marginBottom,X=document.body.style.margin,la=document.documentElement.style.overflow,t=document.body.scroll,V=a.style.te;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",
b)},pc=(a,b,c)=>{a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"},qc=a=>0>dc.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},rc=(a,b)=>{if(0!=b.Qe||0!=b.He){oc(a);var c=b.yf?innerWidth:screen.width,d=b.yf?innerHeight:screen.height,e=qc(a),g=e.width;e=e.height;var f=ic(a),l=f[0];f=f[1];3==b.Qe?(pc(a,(d-e)/2,(c-g)/2),c=g,d=e):2==b.Qe&&(c*f<l*d?(g=f*c/l,pc(a,(d-g)/2,0),d=g):(g=l*d/f,pc(a,0,(c-g)/2),c=g));var n;(n=a.style).backgroundColor||(n.backgroundColor=
"black");let v;(v=document.body.style).backgroundColor||(v.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.rf&&(a.style.te="optimizeSpeed",a.style.te="-moz-crisp-edges",a.style.te="-o-crisp-edges",a.style.te="-webkit-optimize-contrast",a.style.te="optimize-contrast",a.style.te="crisp-edges",a.style.te="pixelated");n=2==b.He?devicePixelRatio:1;0!=b.He&&(c=c*n|0,d=d*n|0,kc(a,c,d),a.ve&&a.ve.re.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);
else return M.fullscreenEnabled()?-3:-1;lc=b;b.ye&&P(b.ye)(37,0,b.Ye);return 0},sc=a=>{if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?-3:-1;return 0},tc=(a,b)=>{w[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)w[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)w[a+8*c+528>>3]="object"==typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)k[a+c+1040]="object"==typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];
k[a+1104]=b.connected;q[a+1108>>2]=b.index;q[a+8>>2]=b.axes.length;q[a+12>>2]=b.buttons.length;K(b.id,a+1112,64);K(b.mapping,a+1176,64)},uc=(a,b)=>{B.attachShader(F[a],H[b])},vc=(a,b)=>{B.bindBuffer(a,ib[b])},wc=a=>B.blendEquation(a),xc=(a,b)=>B.blendFunc(a,b),yc=(a,b,c,d)=>{B.bufferData(a,c?m.subarray(c,c+b):b,d)},zc=a=>B.clear(a),Ac=(a,b,c,d)=>B.clearColor(a,b,c,d),Bc=a=>{B.compileShader(H[a])},Cc=()=>{var a=rb(F),b=B.createProgram();b.name=a;b.Fe=b.De=b.Ee=0;b.Ue=1;F[a]=b;return a},Dc=a=>{var b=
rb(H);H[b]=B.createShader(a);return b},Ec=a=>{if(a){var b=F[a];b?(B.deleteProgram(b),b.name=0,F[a]=null):J||=1281}},Fc=a=>{B.depthMask(!!a)},Gc=a=>B.disable(a),Hc=[],Ic=(a,b,c,d)=>{B.drawElements(a,b,c,d)},Jc=a=>B.enable(a),Kc=a=>{B.enableVertexAttribArray(a)},Lc=(a,b)=>{sb(a,b,"createBuffer",ib)},Mc=(a,b,c,d,e,g,f,l)=>{b=F[b];if(a=B[a](b,c))d=l&&K(a.name,l,d),e&&(q[e>>2]=d),g&&(q[g>>2]=a.size),f&&(q[f>>2]=a.type)},Nc=(a,b)=>B.getAttribLocation(F[a],b?x(m,b):""),S=(a,b)=>{r[a>>2]=b;r[a+4>>2]=(b-r[a>>
2])/4294967296},Oc=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&(J||=1280);return;case 36345:d=0;break;case 34466:var e=B.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=B.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":J||=1280;return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:J||=1280;return}else{if(e instanceof
Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:q[b+4*a>>2]=e[a];break;case 2:u[b+4*a>>2]=e[a];break;case 4:k[b+a]=e[a]?1:0}return}try{d=e.name|0}catch(g){J||=1280;ha(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${g})`);return}}break;default:J||=1280;ha(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${e} of type ${typeof e}!`);return}switch(c){case 1:S(b,
d);break;case 0:q[b>>2]=d;break;case 2:u[b>>2]=d;break;case 4:k[b]=d?1:0}}else J||=1281},Pc=(a,b,c,d)=>{a=B.getProgramInfoLog(F[a]);null===a&&(a="(unknown error)");b=0<b&&d?K(a,d,b):0;c&&(q[c>>2]=b)},Qc=(a,b,c)=>{if(c)if(a>=hb)J||=1281;else if(a=F[a],35716==b)a=B.getProgramInfoLog(a),null===a&&(a="(unknown error)"),q[c>>2]=a.length+1;else if(35719==b){if(!a.Fe){var d=B.getProgramParameter(a,35718);for(b=0;b<d;++b)a.Fe=Math.max(a.Fe,B.getActiveUniform(a,b).name.length+1)}q[c>>2]=a.Fe}else if(35722==
b){if(!a.De)for(d=B.getProgramParameter(a,35721),b=0;b<d;++b)a.De=Math.max(a.De,B.getActiveAttrib(a,b).name.length+1);q[c>>2]=a.De}else if(35381==b){if(!a.Ee)for(d=B.getProgramParameter(a,35382),b=0;b<d;++b)a.Ee=Math.max(a.Ee,B.getActiveUniformBlockName(a,b).length+1);q[c>>2]=a.Ee}else q[c>>2]=B.getProgramParameter(a,b);else J||=1281},Rc=(a,b,c)=>{if(c){a=B.qe.getQueryObjectEXT(nb[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;S(c,d)}else J||=1281},Sc=(a,b,c)=>{if(c){a=B.qe.getQueryObjectEXT(nb[a],b);
var d;"boolean"==typeof a?d=a?1:0:d=a;q[c>>2]=d}else J||=1281},Tc=()=>{var a=gb(B);return a=a.concat(a.map(b=>"GL_"+b))},Uc=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Vc=a=>{var b=a.we,c=a.ef,d;if(!b){a.we=b={};a.df={};var e=B.getProgramParameter(a,35718);for(d=0;d<e;++d){var g=B.getActiveUniform(a,d);var f=g.name;g=g.size;var l=Uc(f);l=0<l?f.slice(0,l):f;var n=a.Ue;a.Ue+=g;c[l]=[g,n];for(f=0;f<g;++f)b[n]=f,a.df[n++]=l}}},Wc=(a,b)=>{b=b?x(m,b):"";if(a=F[a]){Vc(a);var c=a.we,d=0,e=b,g=Uc(b);0<g&&(d=parseInt(b.slice(g+
1))>>>0,e=b.slice(0,g));if((e=a.ef[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||B.getUniformLocation(a,b)))return d}else J||=1281;return-1},W=a=>{var b=B.hf;if(b){var c=b.we[a];"number"==typeof c&&(b.we[a]=c=B.getUniformLocation(b,b.df[a]+(0<c?`[${c}]`:"")));return c}J||=1282},Xc=(a,b,c,d)=>{if(c)if(a=F[a],Vc(a),a=B.getUniform(a,W(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:q[c>>2]=a;break;case 2:u[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:q[c+4*b>>2]=a[b];break;case 2:u[c+4*b>>2]=
a[b]}else J||=1281},Yc=(a,b,c,d)=>{if(c)if(a=B.getVertexAttrib(a,b),34975==b)q[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:q[c>>2]=a;break;case 2:u[c>>2]=a;break;case 5:q[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:q[c+4*b>>2]=a[b];break;case 2:u[c+4*b>>2]=a[b];break;case 5:q[c+4*b>>2]=Math.fround(a[b])}else J||=1281},Zc=a=>{a=F[a];B.linkProgram(a);a.we=0;a.ef={}},$c=(a,b,c,d,e)=>{a-=5120;a=1==a?m:4==a?q:6==a?u:5==a||28922==a?r:na;b=d*((qb||
c)*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+pb-1&-pb);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},ad=(a,b,c,d)=>{for(var e="",g=0;g<b;++g)e+=Ha(r[c+4*g>>2],d?r[d+4*g>>2]:void 0);B.shaderSource(H[a],e)},bd=(a,b)=>{B.uniform1f(W(a),b)},cd=[],dd=[],ed=(a,b,c,d)=>{B.uniform3f(W(a),b,c,d)},fd=(a,b,c,d)=>{if(18>=b){var e=cd[16*b],g=u;d>>=2;b*=16;for(var f=0;f<b;f+=16){var l=d+f;e[f]=g[l];e[f+1]=g[l+1];e[f+2]=g[l+2];e[f+3]=g[l+
3];e[f+4]=g[l+4];e[f+5]=g[l+5];e[f+6]=g[l+6];e[f+7]=g[l+7];e[f+8]=g[l+8];e[f+9]=g[l+9];e[f+10]=g[l+10];e[f+11]=g[l+11];e[f+12]=g[l+12];e[f+13]=g[l+13];e[f+14]=g[l+14];e[f+15]=g[l+15]}}else e=u.subarray(d>>2,d+64*b>>2);B.uniformMatrix4fv(W(a),!!c,e)},gd=a=>{a=F[a];B.useProgram(a);B.hf=a},hd=(a,b,c,d,e,g)=>{B.vertexAttribPointer(a,b,c,!!d,e,g)},jd=(a,b,c,d)=>B.viewport(a,b,c,d),kd=(a,b)=>{if(!M.fullscreenEnabled())return-1;a=O(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?ac()?rc(a,b):
b.mf?(Zb(rc,1,[a,b]),1):-2:-3:-4},ld=()=>{try{if(navigator.getGamepads)return(M.Ce=navigator.getGamepads())?0:-1}catch(a){navigator.getGamepads=null}return-1},md=(a,b)=>{var c={target:O(2),ie:"beforeunload",ke:b,me:(d=event)=>{var e=P(b)(28,0,a);e&&=e?x(m,e):"";if(e)return d.preventDefault(),d.returnValue=e},je:!0};return N(c)},nd=(a,b,c,d,e,g)=>{M.Je||(M.Je=L(256));a={target:O(a),ie:g,ke:d,me:(f=event)=>{var l=f.target.id?f.target.id:"",n=M.Je;K(cc(f.target),n+0,128);K(l,n+128,128);P(d)(e,n,b)&&
f.preventDefault()},je:c};return N(a)},od=(a,b,c,d,e)=>{M.Ke||(M.Ke=L(276));return N({target:a,ie:e,ke:d,me:(g=event)=>{var f=M.Ke,l=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,n=!!l;k[f]=n;k[f+1]=M.fullscreenEnabled();var v=n?l:M.wf,E=v?.id||"";K(cc(v),f+2,128);K(E,f+130,128);q[f+260>>2]=v?v.clientWidth:0;q[f+264>>2]=v?v.clientHeight:0;q[f+268>>2]=screen.width;q[f+272>>2]=screen.height;n&&(M.wf=l);P(d)(19,f,b)&&g.preventDefault()},
je:c})},pd=(a,b,c,d,e)=>{M.Le||(M.Le=L(1240));b={target:O(2),xe:!0,ie:e,ke:c,me:(g=event)=>{var f=M.Le;tc(f,g.gamepad);P(c)(d,f,a)&&g.preventDefault()},je:b};return N(b)},qd=(a,b,c,d,e,g)=>{M.Ne||(M.Ne=L(160));a={target:O(a),ie:g,ke:d,me:f=>{var l=M.Ne;w[l>>3]=f.timeStamp;var n=l>>2;q[n+2]=f.location;k[l+12]=f.ctrlKey;k[l+13]=f.shiftKey;k[l+14]=f.altKey;k[l+15]=f.metaKey;k[l+16]=f.repeat;q[n+5]=f.charCode;q[n+6]=f.keyCode;q[n+7]=f.which;K(f.key||"",l+32,32);K(f.code||"",l+64,32);K(f.char||"",l+96,
32);K(f.locale||"",l+128,32);P(d)(e,l,b)&&f.preventDefault()},je:c};return N(a)},rd=(a,b,c)=>{w[a>>3]=b.timeStamp;var d=a>>2;q[d+2]=b.screenX;q[d+3]=b.screenY;q[d+4]=b.clientX;q[d+5]=b.clientY;k[a+24]=b.ctrlKey;k[a+25]=b.shiftKey;k[a+26]=b.altKey;k[a+27]=b.metaKey;p[2*d+14]=b.button;p[2*d+15]=b.buttons;q[d+8]=b.movementX;q[d+9]=b.movementY;a=qc(c);q[d+10]=b.clientX-(a.left|0);q[d+11]=b.clientY-(a.top|0)},sd=(a,b,c,d,e,g)=>{M.Ge||(M.Ge=L(64));a=O(a);return N({target:a,xe:"mousemove"!=g&&"mouseenter"!=
g&&"mouseleave"!=g,ie:g,ke:d,me:(f=event)=>{rd(M.Ge,f,a);P(d)(e,M.Ge,b)&&f.preventDefault()},je:c})},td=(a,b,c,d,e)=>{M.Pe||(M.Pe=L(257));return N({target:a,ie:e,ke:d,me:(g=event)=>{var f=M.Pe,l=document.pointerLockElement||document.ne||document.vf||document.Be;k[f]=!!l;var n=l?.id||"";K(cc(l),f+1,128);K(n,f+129,128);P(d)(20,f,b)&&g.preventDefault()},je:c})},ud=(a,b,c,d)=>{M.Te||(M.Te=L(36));a=O(a);return N({target:a,ie:"resize",ke:d,me:(e=event)=>{if(e.target==a){var g=document.body;if(g){var f=
M.Te;q[f>>2]=0;q[f+4>>2]=g.clientWidth;q[f+8>>2]=g.clientHeight;q[f+12>>2]=innerWidth;q[f+16>>2]=innerHeight;q[f+20>>2]=outerWidth;q[f+24>>2]=outerHeight;q[f+28>>2]=pageXOffset|0;q[f+32>>2]=pageYOffset|0;P(d)(10,f,b)&&e.preventDefault()}}},je:c})},vd=(a,b,c,d,e,g)=>{M.Se||(M.Se=L(1552));a=O(a);return N({target:a,xe:"touchstart"==g||"touchend"==g,ie:g,ke:d,me:f=>{var l={},n=f.touches;for(var v of n)v.$e=v.bf=0,l[v.identifier]=v;for(var E of f.changedTouches)E.$e=1,l[E.identifier]=E;for(var C of f.targetTouches)l[C.identifier].bf=
1;n=M.Se;w[n>>3]=f.timeStamp;k[n+12]=f.ctrlKey;k[n+13]=f.shiftKey;k[n+14]=f.altKey;k[n+15]=f.metaKey;v=n+16;E=qc(a);C=0;for(let G of Object.values(l))if(l=v>>2,q[l]=G.identifier,q[l+1]=G.screenX,q[l+2]=G.screenY,q[l+3]=G.clientX,q[l+4]=G.clientY,q[l+5]=G.pageX,q[l+6]=G.pageY,k[v+28]=G.$e,k[v+29]=G.bf,q[l+8]=G.clientX-(E.left|0),q[l+9]=G.clientY-(E.top|0),v+=48,31<++C)break;q[n+8>>2]=C;P(d)(e,n,b)&&f.preventDefault()},je:c})},wd=(a,b,c)=>{var d=dc[1];M.Ve||(M.Ve=L(8));return N({target:d,ie:"visibilitychange",
ke:c,me:(e=event)=>{var g=M.Ve,f=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);k[g]=document.hidden;q[g+4>>2]=f;P(c)(21,g,a)&&e.preventDefault()},je:b})},xd=(a,b,c,d)=>{M.We||(M.We=L(96));return N({target:a,xe:!0,ie:"wheel",ke:d,me:(e=event)=>{var g=M.We;rd(g,e,a);w[g+64>>3]=e.deltaX;w[g+72>>3]=e.deltaY;w[g+80>>3]=e.deltaZ;q[g+88>>2]=e.deltaMode;P(d)(9,g,b)&&e.preventDefault()},je:c})};function yd(a){var b=Y,c=b.Be.pop()||b.ne.length;b.ne[c]=a;return c}
class zd{ne=[void 0];Be=[];get(a){return this.ne[a]}has(a){return void 0!==this.ne[a]}}var Y,Ad;
function Bd(a,b,c,d,e){function g(){var D=0,R=0;t.response&&X&&0===r[a+12>>2]&&(R=t.response.byteLength);0<R&&(D=L(R),m.set(new Uint8Array(t.response),D));r[a+12>>2]=D;S(a+16,R);S(a+24,0);(D=t.response?t.response.byteLength:0)&&S(a+32,D);p[a+40>>1]=t.readyState;p[a+42>>1]=t.status;t.statusText&&K(t.statusText,a+44,64)}var f=r[a+8>>2];if(f){var l=f?x(m,f):"",n=a+108,v=Ha(n+0);v||="GET";var E=r[n+56>>2],C=r[n+68>>2],G=r[n+72>>2];f=r[n+76>>2];var T=r[n+80>>2],ba=r[n+84>>2],U=r[n+88>>2],Q=r[n+52>>2],
X=!!(Q&1),la=!!(Q&2);Q=!!(Q&64);C=C?C?x(m,C):"":void 0;G=G?G?x(m,G):"":void 0;var t=new XMLHttpRequest;t.withCredentials=!!m[n+60];t.open(v,l,!Q,C,G);Q||(t.timeout=E);t.ne=l;t.responseType="arraybuffer";T&&(l=T?x(m,T):"",t.overrideMimeType(l));if(f)for(;;){n=r[f>>2];if(!n)break;l=r[f+4>>2];if(!l)break;f+=8;n=n?x(m,n):"";l=l?x(m,l):"";t.setRequestHeader(n,l)}var V=yd(t);r[a>>2]=V;f=ba&&U?m.slice(ba,ba+U):null;t.onload=D=>{Y.has(V)&&(g(),200<=t.status&&300>t.status?b?.(a,t,D):c?.(a,t,D))};t.onerror=
D=>{Y.has(V)&&(g(),c?.(a,t,D))};t.ontimeout=D=>{Y.has(V)&&c?.(a,t,D)};t.onprogress=D=>{if(Y.has(V)){var R=X&&la&&t.response?t.response.byteLength:0,A=0;0<R&&X&&la&&(A=L(R),m.set(new Uint8Array(t.response),A));r[a+12>>2]=A;S(a+16,R);S(a+24,D.loaded-R);S(a+32,D.total);p[a+40>>1]=t.readyState;3<=t.readyState&&0===t.status&&0<D.loaded&&(t.status=200);p[a+42>>1]=t.status;t.statusText&&K(t.statusText,a+44,64);d?.(a,t,D);A&&Cd(A)}};t.onreadystatechange=D=>{Y.has(V)&&(p[a+40>>1]=t.readyState,2<=t.readyState&&
(p[a+42>>1]=t.status),e?.(a,t,D))};try{t.send(f)}catch(D){c?.(a,t,D)}}else c(a,0,"no url specified!")}function Dd(a,b,c,d){var e=Ad;if(e){var g=r[a+108+64>>2];g||=r[a+8>>2];var f=g?x(m,g):"";try{var l=e.transaction(["FILES"],"readwrite").objectStore("FILES").put(b,f);l.onsuccess=()=>{p[a+40>>1]=4;p[a+42>>1]=200;K("OK",a+44,64);c(a,0,f)};l.onerror=n=>{p[a+40>>1]=4;p[a+42>>1]=413;K("Payload Too Large",a+44,64);d(a,0,n)}}catch(n){d(a,0,n)}}else d(a,0,"IndexedDB not available!")}
function Ed(a,b,c){var d=Ad;if(d){var e=r[a+108+64>>2];e||=r[a+8>>2];e=e?x(m,e):"";try{var g=d.transaction(["FILES"],"readonly").objectStore("FILES").get(e);g.onsuccess=f=>{if(f.target.result){f=f.target.result;var l=f.byteLength||f.length,n=L(l);m.set(new Uint8Array(f),n);r[a+12>>2]=n;S(a+16,l);S(a+24,0);S(a+32,l);p[a+40>>1]=4;p[a+42>>1]=200;K("OK",a+44,64);b(a,0,f)}else p[a+40>>1]=4,p[a+42>>1]=404,K("Not Found",a+44,64),c(a,0,"no data")};g.onerror=f=>{p[a+40>>1]=4;p[a+42>>1]=404;K("Not Found",a+
44,64);c(a,0,f)}}catch(f){c(a,0,f)}}else c(a,0,"IndexedDB not available!")}function Fd(a,b,c){var d=Ad;if(d){var e=r[a+108+64>>2];e||=r[a+8>>2];e=e?x(m,e):"";try{var g=d.transaction(["FILES"],"readwrite").objectStore("FILES").delete(e);g.onsuccess=f=>{f=f.target.result;r[a+12>>2]=0;S(a+16,0);S(a+24,0);S(a+32,0);p[a+40>>1]=4;p[a+42>>1]=200;K("OK",a+44,64);b(a,0,f)};g.onerror=f=>{p[a+40>>1]=4;p[a+42>>1]=404;K("Not Found",a+44,64);c(a,0,f)}}catch(f){c(a,0,f)}}else c(a,0,"IndexedDB not available!")}
var Gd={},Id=()=>{if(!Hd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in Gd)void 0===Gd[b]?delete a[b]:a[b]=Gd[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Hd=c}return Hd},Hd,Jd=[null,[],[]],Kd=(a,b,c)=>{a.addEventListener(b,c,{once:!0})},Ld=a=>{var b;b||=[document,document.getElementById("canvas")];["keydown","mousedown",
"touchstart"].forEach(c=>{b.forEach(d=>{d&&Kd(d,c,()=>{"suspended"===a.state&&a.resume()})})})},Md=(a,b=[])=>{P(a)(...b)};
h.requestFullscreen=function(a,b){function c(){Ma=!1;var g=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===g?(d.exitFullscreen=Ua,Sa&&d.requestPointerLock(),Ma=!0,Ta?("undefined"!=typeof SDL&&(q[SDL.screen>>2]=r[SDL.screen>>2]|8388608),Xa(h.canvas),Wa()):Xa(d)):(g.parentNode.insertBefore(d,g),g.parentNode.removeChild(g),Ta?("undefined"!=typeof SDL&&(q[SDL.screen>>2]=
r[SDL.screen>>2]&-8388609),Xa(h.canvas),Wa()):Xa(d));h.onFullScreen?.(Ma);h.onFullscreen?.(Ma)}Sa=a;Ta=b;"undefined"==typeof Sa&&(Sa=!0);"undefined"==typeof Ta&&(Ta=!1);var d=h.canvas;Ra||(Ra=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=
e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()};h.setCanvasSize=function(a,b,c){Xa(h.canvas,a,b);c||Wa()};h.getUserMedia=function(a){let b;(b=window).getUserMedia||(b.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)};
h.createContext=function(a,b,c,d){if(b&&h.ctx&&a==h.canvas)return h.ctx;var e;if(b){var g={antialias:!1,alpha:!1,af:1};if(d)for(var f in d)g[f]=d[f];if("undefined"!=typeof yb&&(e=ub(a,g)))var l=I[e].re}else l=a.getContext("2d");if(!l)return null;c&&(h.ctx=l,b&&xb(e),Oa.forEach(n=>n()),Pa());return l};h.requestAnimationFrame=Ub;h.pauseMainLoop=function(){Nb=null;Bb++};h.resumeMainLoop=function(){Bb++;var a=Lb,b=Mb,c=Cb;Cb=null;Sb(c,0,!1,Db,!0);Rb(a,b);Nb()};h.preMainLoop&&Pb.push(h.preMainLoop);
h.postMainLoop&&Qb.push(h.postMainLoop);for(let a=0;32>a;++a)Hc.push(Array(a));for(var Nd=new Float32Array(288),Od=0;288>=Od;++Od)cd[Od]=Nd.subarray(0,Od);var Pd=new Int32Array(288);for(Od=0;288>=Od;++Od)dd[Od]=Pd.subarray(0,Od);Y=new zd;ra();
(function(a,b){try{var c=indexedDB.open("emscripten_filesystem",1)}catch(d){b(d);return}c.onupgradeneeded=d=>{d=d.target.result;d.objectStoreNames.contains("FILES")&&d.deleteObjectStore("FILES");d.createObjectStore("FILES")};c.onsuccess=d=>a(d.target.result);c.onerror=b})(a=>{Ad=a;sa()},()=>{Ad=!1;sa()});h.noExitRuntime&&(Da=h.noExitRuntime);h.print&&(fa=h.print);h.printErr&&(ha=h.printErr);h.wasmBinary&&(ia=h.wasmBinary);h.arguments&&(aa=h.arguments);h.thisProgram&&(ca=h.thisProgram);
var Qd={6314682:()=>{1==confirm("Would you like to play Unreleased Game?")&&window.location.assign("https://fishyhotel.com/fishtankdungeons")},6314817:()=>{1==confirm("Would you like to play Fishtank Dungeons?")&&window.location.assign("https://fishyhotel.com/fishtankdungeons")},6314954:()=>{1==confirm("Would you like to play Femboy.wiki?")&&window.location.assign("https://femboy.wiki")},6315065:()=>{1==confirm("Would you like to play Fishtank Arena?")&&window.location.assign("https://fishtankdungeons.itch.io/arena")},
6315198:()=>"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?!0:!1,6315345:()=>"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?!0:!1,6315579:a=>{"undefined"===typeof h.SDL2&&(h.SDL2={});var b=h.SDL2;a?b.capture={}:b.audio={};b.he||("undefined"!==typeof AudioContext?b.he=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.he=new webkitAudioContext),b.he&&"undefined"===
typeof navigator.userActivation&&Ld(b.he));return void 0===b.he?-1:0},6316131:()=>h.SDL2.he.sampleRate,6316199:(a,b,c,d)=>{function e(){}function g(l){void 0!==f.capture.pe&&(clearInterval(f.capture.pe),f.capture.pe=void 0,f.capture.ue=void 0);f.capture.Oe=f.he.createMediaStreamSource(l);f.capture.oe=f.he.createScriptProcessor(b,a,1);f.capture.oe.onaudioprocess=function(n){void 0!==f&&void 0!==f.capture&&(n.outputBuffer.getChannelData(0).fill(0),f.capture.Ie=n.inputBuffer,Md(c,[d]))};f.capture.Oe.connect(f.capture.oe);
f.capture.oe.connect(f.he.destination);f.capture.stream=l}var f=h.SDL2;f.capture.ue=f.he.createBuffer(a,b,f.he.sampleRate);f.capture.ue.getChannelData(0).fill(0);f.capture.pe=setInterval(function(){f.capture.Ie=f.capture.ue;Md(c,[d])},b/f.he.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(g).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,video:!1},g,e)},
6317892:(a,b,c,d)=>{var e=h.SDL2;e.audio.oe=e.he.createScriptProcessor(b,0,a);e.audio.oe.onaudioprocess=function(g){void 0!==e&&void 0!==e.audio&&(void 0!==e.audio.pe&&(clearInterval(e.audio.pe),e.audio.pe=void 0,e.audio.ue=void 0),e.audio.Ae=g.outputBuffer,Md(c,[d]))};e.audio.oe.connect(e.he.destination);"suspended"===e.he.state&&(e.audio.ue=e.he.createBuffer(a,b,e.he.sampleRate),e.audio.ue.getChannelData(0).fill(0),e.audio.pe=setInterval(function(){"undefined"!==typeof navigator.userActivation&&
navigator.userActivation.hasBeenActive&&e.he.resume();e.audio.Ae=e.audio.ue;Md(c,[d]);e.audio.Ae=void 0},b/e.he.sampleRate*1E3))},6319067:(a,b)=>{for(var c=h.SDL2,d=c.capture.Ie.numberOfChannels,e=0;e<d;++e){var g=c.capture.Ie.getChannelData(e);if(g.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+g.length+" samples vs expected "+b+" samples!";if(1==d)for(var f=0;f<b;++f)Ea(a+4*f,g[f]);else for(f=0;f<b;++f)Ea(a+4*(f*d+e),g[f])}},6319672:(a,b)=>{var c=h.SDL2;a>>>=2;for(var d=
c.audio.Ae.numberOfChannels,e=0;e<d;++e){var g=c.audio.Ae.getChannelData(e);if(g.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+g.length+" samples vs expected "+b+" samples!";for(var f=0;f<b;++f)g[f]=u[a+(f*d+e)]}},6320161:a=>{var b=h.SDL2;if(a){void 0!==b.capture.pe&&clearInterval(b.capture.pe);if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c])}void 0!==b.capture.oe&&(b.capture.oe.onaudioprocess=
function(){},b.capture.oe.disconnect());void 0!==b.capture.Oe&&b.capture.Oe.disconnect();b.capture=void 0}else void 0!=b.audio.oe&&b.audio.oe.disconnect(),void 0!==b.audio.pe&&clearInterval(b.audio.pe),b.audio=void 0;void 0!==b.he&&void 0===b.audio&&void 0===b.capture&&(b.he.close(),b.he=void 0)},6321167:(a,b,c)=>{h.SDL2||(h.SDL2={});var d=h.SDL2;d.ff!==h.canvas&&(d.ze=h.createContext(h.canvas,!1,!0),d.ff=h.canvas);if(d.w!==a||d.h!==b||d.tf!==d.ze)d.image=d.ze.createImageData(a,b),d.w=a,d.h=b,d.tf=
d.ze;a=d.image.data;b=c/4;var e=0;if("undefined"!==typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var g=q[b];a[e]=g&255;a[e+1]=g>>8&255;a[e+2]=g>>16&255;a[e+3]=255;b++;e+=4}else if(d.kf!==a&&(d.jf=new Int32Array(a.buffer),d.lf=new Uint8Array(a.buffer),d.kf=a),a=d.jf,c=a.length,a.set(q.subarray(b,b+c)),a=d.lf,b=3,e=b+4*c,0==c%8)for(;b<e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|
0;else for(;b<e;)a[b]=255,b=b+4|0;d.ze.putImageData(d.image,0,0)},6322635:(a,b,c,d,e)=>{var g=document.createElement("canvas");g.width=a;g.height=b;var f=g.getContext("2d");a=f.createImageData(a,b);b=a.data;e/=4;var l=0,n;if("undefined"!==typeof CanvasPixelArray&&b instanceof CanvasPixelArray)for(n=b.length;l<n;){var v=q[e];b[l]=v&255;b[l+1]=v>>8&255;b[l+2]=v>>16&255;b[l+3]=v>>24&255;e++;l+=4}else b=new Int32Array(b.buffer),n=b.length,b.set(q.subarray(e,e+n));f.putImageData(a,0,0);c=0===c&&0===d?
"url("+g.toDataURL()+"), auto":"url("+g.toDataURL()+") "+c+" "+d+", auto";d=L(c.length+1);K(c,d,c.length+1);return d},6323623:a=>{h.canvas&&(h.canvas.style.cursor=a?x(m,a):"")},6323706:()=>{h.canvas&&(h.canvas.style.cursor="none")},6323775:()=>window.innerWidth,6323805:()=>window.innerHeight},Rd={Z:function(){return 0},_a:function(){return 0},$a:function(){},Va:()=>{},Da:a=>{if(12448==a)return y=12288,1;y=12300;return 0},Ga:(a,b,c,d,e)=>{if(62E3!=a)y=12296,c=0;else{if(b)for(;;){a=q[b>>2];if(12321==
a)z.alpha=0<q[b+4>>2];else if(12325==a)z.depth=0<q[b+4>>2];else if(12326==a)z.stencil=0<q[b+4>>2];else if(12337==a)a=q[b+4>>2],z.antialias=0<a;else if(12338==a)a=q[b+4>>2],z.antialias=1==a;else if(12544==a)z.Jf=12547!=q[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(q[e>>2]=1),c&&0<d&&(r[c>>2]=62002),y=12288,c=1):(y=12300,c=0)}return c},ua:(a,b,c,d)=>{if(62E3!=a)return y=12296,0;for(a=1;;){b=q[d>>2];if(12440==b)a=q[d+4>>2];else if(12344==b)break;else return y=12292,0;d+=8}if(2!=a)return y=12293,
0;z.af=a-1;z.Lf=0;cb=ub(h.canvas,z);if(0!=cb)return y=12288,xb(cb),Oa.forEach(e=>e()),xb(null),62004;y=12297;return 0},wa:(a,b)=>{if(62E3!=a)return y=12296,0;if(62002!=b)return y=12293,0;y=12288;return 62006},va:(a,b)=>{if(62E3!=a)return y=12296,0;if(62004!=b)return y=12294,0;a=cb;wb===I[a]&&(wb=null);"object"==typeof M&&M.xf(I[a].re.canvas);I[a]?.re.canvas&&(I[a].re.canvas.ve=void 0);I[a]=null;y=12288;Za==b&&(Za=0);return 1},xa:(a,b)=>{if(62E3!=a)return y=12296,0;if(62006!=b)return y=12301,1;$a==
b&&($a=0);ab==b&&(ab=0);y=12288;return 1},Ha:(a,b,c,d)=>{if(62E3!=a)return y=12296,0;if(62002!=b)return y=12293,0;if(!d)return y=12300,0;y=12288;switch(c){case 12320:return q[d>>2]=z.alpha?32:24,1;case 12321:return q[d>>2]=z.alpha?8:0,1;case 12322:return q[d>>2]=8,1;case 12323:return q[d>>2]=8,1;case 12324:return q[d>>2]=8,1;case 12325:return q[d>>2]=z.depth?24:0,1;case 12326:return q[d>>2]=z.stencil?8:0,1;case 12327:return q[d>>2]=12344,1;case 12328:return q[d>>2]=62002,1;case 12329:return q[d>>
2]=0,1;case 12330:return q[d>>2]=4096,1;case 12331:return q[d>>2]=16777216,1;case 12332:return q[d>>2]=4096,1;case 12333:return q[d>>2]=0,1;case 12334:return q[d>>2]=0,1;case 12335:return q[d>>2]=12344,1;case 12337:return q[d>>2]=z.antialias?4:0,1;case 12338:return q[d>>2]=z.antialias?1:0,1;case 12339:return q[d>>2]=4,1;case 12340:return q[d>>2]=12344,1;case 12341:case 12342:case 12343:return q[d>>2]=-1,1;case 12345:case 12346:return q[d>>2]=0,1;case 12347:return q[d>>2]=0,1;case 12348:return q[d>>
2]=1;case 12349:case 12350:return q[d>>2]=0,1;case 12351:return q[d>>2]=12430,1;case 12352:return q[d>>2]=4,1;case 12354:return q[d>>2]=0,1;default:return y=12292,0}},Q:a=>{y=12288;return 0!=a&&1!=a?0:62E3},ta:()=>y,Ea:(a,b,c)=>{if(62E3!=a)return y=12296,0;b&&(q[b>>2]=1);c&&(q[c>>2]=4);Ya=!0;y=12288;return 1},ya:(a,b,c,d)=>{if(62E3!=a)return y=12296,0;if(0!=d&&62004!=d)return y=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return y=12301,0;xb(d?cb:null);Za=d;ab=b;$a=c;y=12288;return 1},sa:(a,b)=>{if(62E3!=
a)return y=12296,0;y=12288;if(bb[b])return bb[b];switch(b){case 12371:a=Ab("Emscripten");break;case 12372:a=Ab("1.4 Emscripten EGL");break;case 12373:a=Ab("");break;case 12429:a=Ab("OpenGL_ES");break;default:return y=12300,0}return bb[b]=a},za:()=>{if(Ya)if(B)if(B.isContextLost())y=12302;else return y=12288,1;else y=12290;else y=12289;return 0},Aa:(a,b)=>{if(62E3!=a)return y=12296,0;0==b?Rb(0,0):Rb(1,b);y=12288;return 1},Fa:a=>{if(62E3!=a)return y=12296,0;ab=$a=Za=0;Ya=!1;y=12288;return 1},Ca:()=>
{y=12288;return 1},Ba:()=>{y=12288;return 1},k:(a,b,c)=>{b=Xb(b,c);return Qd[a](...b)},e:(a,b,c)=>{b=Xb(b,c);return Qd[a](...b)},Ka:(a,b,c)=>{b=Xb(b,c);return Qd[a](...b)},_:()=>Date.now(),la:()=>{if(!M.fullscreenEnabled())return-1;$b(rc);var a=dc[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},qa:()=>{$b(sc);if(document.exitPointerLock)document.exitPointerLock();else return-1;
return 0},La:function(a){if(Y.has(a)){var b=Y.get(a),c=Y;c.ne[a]=void 0;c.Be.push(a);0<b.readyState&&4>b.readyState&&b.abort()}},j:()=>devicePixelRatio,f:(a,b,c)=>{a=O(a);if(!a)return-4;a=qc(a);w[b>>3]=a.width;w[c>>3]=a.height;return 0},T:(a,b)=>{if(0>a||a>=M.Ce.length)return-5;if(!M.Ce[a])return-7;tc(b,M.Ce[a]);return 0},V:()=>performance.now(),Ja:()=>M.Ce.length,ra:(a,b)=>{q[a>>2]=screen.width;q[b>>2]=screen.height},Pd:a=>B.activeTexture(a),Od:uc,ha:(a,b)=>{B.qe.beginQueryEXT(a,nb[b])},Nd:(a,b,
c)=>{B.bindAttribLocation(F[a],b,c?x(m,c):"")},Md:vc,Ld:(a,b)=>{B.bindFramebuffer(a,jb[b])},Kd:(a,b)=>{B.bindRenderbuffer(a,kb[b])},Jd:(a,b)=>{B.bindTexture(a,lb[b])},Xd:a=>{B.bindVertexArray(mb[a])},Id:(a,b,c,d)=>B.blendColor(a,b,c,d),Hd:wc,Gd:(a,b)=>B.blendEquationSeparate(a,b),Ed:xc,Dd:(a,b,c,d)=>B.blendFuncSeparate(a,b,c,d),Cd:yc,Bd:(a,b,c,d)=>{B.bufferSubData(a,b,m.subarray(d,d+c))},Ad:a=>B.checkFramebufferStatus(a),zd:zc,yd:Ac,xd:a=>B.clearDepth(a),wd:a=>B.clearStencil(a),bb:(a,b)=>{B.pf.clipControlEXT(a,
b)},vd:(a,b,c,d)=>{B.colorMask(!!a,!!b,!!c,!!d)},ud:Bc,td:(a,b,c,d,e,g,f,l)=>{B.compressedTexImage2D(a,b,c,d,e,g,m.subarray(l,l+f))},sd:(a,b,c,d,e,g,f,l,n)=>{B.compressedTexSubImage2D(a,b,c,d,e,g,f,m.subarray(n,n+l))},rd:(a,b,c,d,e,g,f,l)=>B.copyTexImage2D(a,b,c,d,e,g,f,l),qd:(a,b,c,d,e,g,f,l)=>B.copyTexSubImage2D(a,b,c,d,e,g,f,l),pd:Cc,od:Dc,nd:a=>B.cullFace(a),md:(a,b)=>{for(var c=0;c<a;c++){var d=q[b+4*c>>2],e=ib[d];e&&(B.deleteBuffer(e),e.name=0,ib[d]=null)}},ld:(a,b)=>{for(var c=0;c<a;++c){var d=
q[b+4*c>>2],e=jb[d];e&&(B.deleteFramebuffer(e),e.name=0,jb[d]=null)}},jd:Ec,ja:(a,b)=>{for(var c=0;c<a;c++){var d=q[b+4*c>>2],e=nb[d];e&&(B.qe.deleteQueryEXT(e),nb[d]=null)}},id:(a,b)=>{for(var c=0;c<a;c++){var d=q[b+4*c>>2],e=kb[d];e&&(B.deleteRenderbuffer(e),e.name=0,kb[d]=null)}},hd:a=>{if(a){var b=H[a];b?(B.deleteShader(b),H[a]=null):J||=1281}},gd:(a,b)=>{for(var c=0;c<a;c++){var d=q[b+4*c>>2],e=lb[d];e&&(B.deleteTexture(e),e.name=0,lb[d]=null)}},Wd:(a,b)=>{for(var c=0;c<a;c++){var d=q[b+4*c>>
2];B.deleteVertexArray(mb[d]);mb[d]=null}},fd:a=>B.depthFunc(a),ed:Fc,dd:(a,b)=>B.depthRange(a,b),cd:(a,b)=>{B.detachShader(F[a],H[b])},bd:Gc,ad:a=>{B.disableVertexAttribArray(a)},$c:(a,b,c)=>{B.drawArrays(a,b,c)},Sd:(a,b,c,d)=>{B.drawArraysInstanced(a,b,c,d)},Td:(a,b)=>{for(var c=Hc[a],d=0;d<a;d++)c[d]=q[b+4*d>>2];B.drawBuffers(c)},_c:Ic,Rd:(a,b,c,d,e)=>{B.drawElementsInstanced(a,b,c,d,e)},Zc:Jc,Yc:Kc,ga:a=>{B.qe.endQueryEXT(a)},Xc:()=>B.finish(),Wc:()=>B.flush(),Vc:(a,b,c,d)=>{B.framebufferRenderbuffer(a,
b,c,kb[d])},Uc:(a,b,c,d,e)=>{B.framebufferTexture2D(a,b,c,lb[d],e)},Tc:a=>B.frontFace(a),Sc:Lc,Qc:(a,b)=>{sb(a,b,"createFramebuffer",jb)},ka:(a,b)=>{for(var c=0;c<a;c++){var d=B.qe.createQueryEXT();if(!d){for(J||=1282;c<a;)q[b+4*c++>>2]=0;break}var e=rb(nb);d.name=e;nb[e]=d;q[b+4*c>>2]=e}},Pc:(a,b)=>{sb(a,b,"createRenderbuffer",kb)},Oc:(a,b)=>{sb(a,b,"createTexture",lb)},Vd:(a,b)=>{sb(a,b,"createVertexArray",mb)},Rc:a=>B.generateMipmap(a),Nc:(a,b,c,d,e,g,f)=>Mc("getActiveAttrib",a,b,c,d,e,g,f),Mc:(a,
b,c,d,e,g,f)=>Mc("getActiveUniform",a,b,c,d,e,g,f),Lc:(a,b,c,d)=>{a=B.getAttachedShaders(F[a]);var e=a.length;e>b&&(e=b);q[c>>2]=e;for(b=0;b<e;++b)q[d+4*b>>2]=H.indexOf(a[b])},Kc:Nc,Jc:(a,b)=>Oc(a,b,4),Ic:(a,b,c)=>{c?q[c>>2]=B.getBufferParameter(a,b):J||=1281},Gc:()=>{var a=B.getError()||J;J=0;return a},Fc:(a,b)=>Oc(a,b,2),Ec:(a,b,c,d)=>{a=B.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;q[d>>2]=a},Dc:(a,b)=>Oc(a,b,0),Bc:Pc,Cc:Qc,Zd:Rc,
da:Sc,Yd:Rc,ca:Sc,ea:(a,b,c)=>{c?q[c>>2]=B.qe.getQueryEXT(a,b):J||=1281},Ac:(a,b,c)=>{c?q[c>>2]=B.getRenderbufferParameter(a,b):J||=1281},yc:(a,b,c,d)=>{a=B.getShaderInfoLog(H[a]);null===a&&(a="(unknown error)");b=0<b&&d?K(a,d,b):0;c&&(q[c>>2]=b)},xc:(a,b,c,d)=>{a=B.getShaderPrecisionFormat(a,b);q[c>>2]=a.rangeMin;q[c+4>>2]=a.rangeMax;q[d>>2]=a.precision},vc:(a,b,c,d)=>{if(a=B.getShaderSource(H[a]))b=0<b&&d?K(a,d,b):0,c&&(q[c>>2]=b)},zc:(a,b,c)=>{c?35716==b?(a=B.getShaderInfoLog(H[a]),null===a&&(a=
"(unknown error)"),q[c>>2]=a?a.length+1:0):35720==b?(a=B.getShaderSource(H[a]),q[c>>2]=a?a.length+1:0):q[c>>2]=B.getShaderParameter(H[a],b):J||=1281},uc:a=>{var b=ob[a];if(!b){switch(a){case 7939:b=Ab(Tc().join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=B.getParameter(a))||(J||=1280);b=b?Ab(b):0;break;case 7938:b=Ab(`OpenGL ES 2.0 (${B.getParameter(7938)})`);break;case 35724:b=B.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&
(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=Ab(b);break;default:J||=1280}ob[a]=b}return b},tc:(a,b,c)=>{c?u[c>>2]=B.getTexParameter(a,b):J||=1281},sc:(a,b,c)=>{c?q[c>>2]=B.getTexParameter(a,b):J||=1281},pc:Wc,rc:(a,b,c)=>{Xc(a,b,c,2)},qc:(a,b,c)=>{Xc(a,b,c,0)},mc:(a,b,c)=>{c?q[c>>2]=B.getVertexAttribOffset(a,b):J||=1281},oc:(a,b,c)=>{Yc(a,b,c,2)},nc:(a,b,c)=>{Yc(a,b,c,5)},lc:(a,b)=>B.hint(a,b),kc:a=>(a=ib[a])?B.isBuffer(a):0,jc:a=>B.isEnabled(a),ic:a=>(a=jb[a])?B.isFramebuffer(a):0,hc:a=>
(a=F[a])?B.isProgram(a):0,ia:a=>(a=nb[a])?B.qe.isQueryEXT(a):0,gc:a=>(a=kb[a])?B.isRenderbuffer(a):0,fc:a=>(a=H[a])?B.isShader(a):0,ec:a=>(a=lb[a])?B.isTexture(a):0,Ud:a=>(a=mb[a])?B.isVertexArray(a):0,dc:a=>B.lineWidth(a),cc:Zc,bc:(a,b)=>{3317==a?pb=b:3314==a&&(qb=b);B.pixelStorei(a,b)},ab:(a,b)=>{B.zf.polygonModeWEBGL(a,b)},ac:(a,b)=>B.polygonOffset(a,b),cb:(a,b,c)=>{B.qf.polygonOffsetClampEXT(a,b,c)},fa:(a,b)=>{B.qe.queryCounterEXT(nb[a],b)},$b:(a,b,c,d,e,g,f)=>{(f=$c(g,e,c,d,f))?B.readPixels(a,
b,c,d,e,g,f):J||=1280},_b:()=>{},Zb:(a,b,c,d)=>B.renderbufferStorage(a,b,c,d),Yb:(a,b)=>{B.sampleCoverage(a,!!b)},Xb:(a,b,c,d)=>B.scissor(a,b,c,d),Wb:()=>{J||=1280},Vb:ad,Ub:(a,b,c)=>B.stencilFunc(a,b,c),Tb:(a,b,c,d)=>B.stencilFuncSeparate(a,b,c,d),Sb:a=>B.stencilMask(a),Rb:(a,b)=>B.stencilMaskSeparate(a,b),Qb:(a,b,c)=>B.stencilOp(a,b,c),Pb:(a,b,c,d)=>B.stencilOpSeparate(a,b,c,d),Ob:(a,b,c,d,e,g,f,l,n)=>{n=n?$c(l,f,d,e,n):null;B.texImage2D(a,b,c,d,e,g,f,l,n)},Nb:(a,b,c)=>B.texParameterf(a,b,c),Mb:(a,
b,c)=>{B.texParameterf(a,b,u[c>>2])},Lb:(a,b,c)=>B.texParameteri(a,b,c),Kb:(a,b,c)=>{B.texParameteri(a,b,q[c>>2])},Ib:(a,b,c,d,e,g,f,l,n)=>{n=n?$c(l,f,e,g,n):null;B.texSubImage2D(a,b,c,d,e,g,f,l,n)},Hb:bd,Gb:(a,b,c)=>{if(288>=b)for(var d=cd[b],e=0;e<b;++e)d[e]=u[c+4*e>>2];else d=u.subarray(c>>2,c+4*b>>2);B.uniform1fv(W(a),d)},Fb:(a,b)=>{B.uniform1i(W(a),b)},Eb:(a,b,c)=>{if(288>=b)for(var d=dd[b],e=0;e<b;++e)d[e]=q[c+4*e>>2];else d=q.subarray(c>>2,c+4*b>>2);B.uniform1iv(W(a),d)},Db:(a,b,c)=>{B.uniform2f(W(a),
b,c)},Cb:(a,b,c)=>{if(144>=b){b*=2;for(var d=cd[b],e=0;e<b;e+=2)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2]}else d=u.subarray(c>>2,c+8*b>>2);B.uniform2fv(W(a),d)},Bb:(a,b,c)=>{B.uniform2i(W(a),b,c)},Ab:(a,b,c)=>{if(144>=b){b*=2;for(var d=dd[b],e=0;e<b;e+=2)d[e]=q[c+4*e>>2],d[e+1]=q[c+(4*e+4)>>2]}else d=q.subarray(c>>2,c+8*b>>2);B.uniform2iv(W(a),d)},zb:ed,yb:(a,b,c)=>{if(96>=b){b*=3;for(var d=cd[b],e=0;e<b;e+=3)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2]}else d=u.subarray(c>>2,c+12*
b>>2);B.uniform3fv(W(a),d)},xb:(a,b,c,d)=>{B.uniform3i(W(a),b,c,d)},wb:(a,b,c)=>{if(96>=b){b*=3;for(var d=dd[b],e=0;e<b;e+=3)d[e]=q[c+4*e>>2],d[e+1]=q[c+(4*e+4)>>2],d[e+2]=q[c+(4*e+8)>>2]}else d=q.subarray(c>>2,c+12*b>>2);B.uniform3iv(W(a),d)},vb:(a,b,c,d,e)=>{B.uniform4f(W(a),b,c,d,e)},ub:(a,b,c)=>{if(72>=b){var d=cd[4*b],e=u;c>>=2;b*=4;for(var g=0;g<b;g+=4){var f=c+g;d[g]=e[f];d[g+1]=e[f+1];d[g+2]=e[f+2];d[g+3]=e[f+3]}}else d=u.subarray(c>>2,c+16*b>>2);B.uniform4fv(W(a),d)},tb:(a,b,c,d,e)=>{B.uniform4i(W(a),
b,c,d,e)},sb:(a,b,c)=>{if(72>=b){b*=4;for(var d=dd[b],e=0;e<b;e+=4)d[e]=q[c+4*e>>2],d[e+1]=q[c+(4*e+4)>>2],d[e+2]=q[c+(4*e+8)>>2],d[e+3]=q[c+(4*e+12)>>2]}else d=q.subarray(c>>2,c+16*b>>2);B.uniform4iv(W(a),d)},rb:(a,b,c,d)=>{if(72>=b){b*=4;for(var e=cd[b],g=0;g<b;g+=4)e[g]=u[d+4*g>>2],e[g+1]=u[d+(4*g+4)>>2],e[g+2]=u[d+(4*g+8)>>2],e[g+3]=u[d+(4*g+12)>>2]}else e=u.subarray(d>>2,d+16*b>>2);B.uniformMatrix2fv(W(a),!!c,e)},qb:(a,b,c,d)=>{if(32>=b){b*=9;for(var e=cd[b],g=0;g<b;g+=9)e[g]=u[d+4*g>>2],e[g+
1]=u[d+(4*g+4)>>2],e[g+2]=u[d+(4*g+8)>>2],e[g+3]=u[d+(4*g+12)>>2],e[g+4]=u[d+(4*g+16)>>2],e[g+5]=u[d+(4*g+20)>>2],e[g+6]=u[d+(4*g+24)>>2],e[g+7]=u[d+(4*g+28)>>2],e[g+8]=u[d+(4*g+32)>>2]}else e=u.subarray(d>>2,d+36*b>>2);B.uniformMatrix3fv(W(a),!!c,e)},pb:fd,ob:gd,nb:a=>{B.validateProgram(F[a])},mb:(a,b)=>B.vertexAttrib1f(a,b),lb:(a,b)=>{B.vertexAttrib1f(a,u[b>>2])},kb:(a,b,c)=>B.vertexAttrib2f(a,b,c),jb:(a,b)=>{B.vertexAttrib2f(a,u[b>>2],u[b+4>>2])},ib:(a,b,c,d)=>B.vertexAttrib3f(a,b,c,d),hb:(a,b)=>
{B.vertexAttrib3f(a,u[b>>2],u[b+4>>2],u[b+8>>2])},gb:(a,b,c,d,e)=>B.vertexAttrib4f(a,b,c,d,e),fb:(a,b)=>{B.vertexAttrib4f(a,u[b>>2],u[b+4>>2],u[b+8>>2],u[b+12>>2])},Qd:(a,b)=>{B.vertexAttribDivisor(a,b)},eb:hd,db:jd,o:()=>0,Na:()=>!0,ma:(a,b,c)=>kd(a,{Qe:q[c>>2],He:q[c+4>>2],rf:q[c+8>>2],mf:b,ye:q[c+12>>2],Ye:q[c+16>>2]}),O:(a,b)=>{a=O(a);return a?a.requestPointerLock?ac()?sc(a):b?(Zb(sc,2,[a]),1):-2:-1:-4},Ua:()=>{ta("OOM")},U:ld,y:(a,b,c)=>"undefined"==typeof onbeforeunload?-1:1!==c?-5:md(a,b),
J:(a,b,c,d)=>nd(a,b,c,d,12,"blur"),i:jc,m:(a,b,c)=>{a=O(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},K:(a,b,c,d)=>nd(a,b,c,d,13,"focus"),A:(a,b,c,d)=>{if(!M.fullscreenEnabled())return-1;a=O(a);if(!a)return-4;od(a,b,c,d,"webkitfullscreenchange");return od(a,b,c,d,"fullscreenchange")},S:(a,b,c)=>ld()?-1:pd(a,b,c,26,"gamepadconnected"),R:(a,b,c)=>ld()?-1:pd(a,b,c,27,"gamepaddisconnected"),D:(a,b,c,d)=>qd(a,b,c,d,2,"keydown"),B:(a,b,c,d)=>qd(a,b,c,d,1,"keypress"),C:(a,b,c,d)=>
qd(a,b,c,d,3,"keyup"),Oa:(a,b,c)=>{a=P(a);Sb(a,b,c)},r:(a,b,c,d)=>sd(a,b,c,d,5,"mousedown"),N:(a,b,c,d)=>sd(a,b,c,d,33,"mouseenter"),M:(a,b,c,d)=>sd(a,b,c,d,34,"mouseleave"),s:(a,b,c,d)=>sd(a,b,c,d,8,"mousemove"),q:(a,b,c,d)=>sd(a,b,c,d,6,"mouseup"),E:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.ne||document.body.vf||document.body.Be))return-1;a=O(a);if(!a)return-4;td(a,b,c,d,"mozpointerlockchange");td(a,b,c,d,"webkitpointerlockchange");td(a,b,c,d,"mspointerlockchange");
return td(a,b,c,d,"pointerlockchange")},t:(a,b,c,d)=>ud(a,b,c,d),F:(a,b,c,d)=>vd(a,b,c,d,25,"touchcancel"),H:(a,b,c,d)=>vd(a,b,c,d,23,"touchend"),G:(a,b,c,d)=>vd(a,b,c,d,24,"touchmove"),I:(a,b,c,d)=>vd(a,b,c,d,22,"touchstart"),z:(a,b,c)=>wd(a,b,c),L:(a,b,c,d)=>(a=O(a))?"undefined"!=typeof a.onwheel?xd(a,b,c,d):-1:-4,na:a=>document.title=a?x(m,a):"",n:()=>{throw"Please compile your program with async support in order to use asynchronous operations like emscripten_sleep";},Ma:function(a,b,c,d,e){function g(A){if(G)A();
else if(!ka)try{A(),La()}catch(Hb){Ia(Hb)}}var f=a+108,l=r[f+36>>2],n=r[f+40>>2],v=r[f+44>>2],E=r[f+48>>2],C=r[f+52>>2],G=!!(C&64),T=A=>{g(()=>{l?P(l)(A):b?.(A)})},ba=A=>{g(()=>{v?P(v)(A):d?.(A)})},U=A=>{g(()=>{n?P(n)(A):c?.(A)})},Q=A=>{g(()=>{E?P(E)(A):e?.(A)})},X=A=>{Bd(A,T,U,ba,Q)},la=(A,Hb)=>{Dd(A,Hb.response,Ga=>{g(()=>{l?P(l)(Ga):b?.(Ga)})},Ga=>{g(()=>{l?P(l)(Ga):b?.(Ga)})})},t=A=>{Bd(A,la,U,ba,Q)},V=Ha(f+0),D=!!(C&16),R=!!(C&4);C=!!(C&32);if("EM_IDB_STORE"===V)X=r[f+84>>2],Dd(a,m.slice(X,X+
r[f+88>>2]),T,U);else if("EM_IDB_DELETE"===V)Fd(a,T,U);else if(D){if(C)return 0;Bd(a,R?la:T,U,ba,Q)}else Ed(a,T,C?U:R?t:X);return a},Xa:(a,b)=>{var c=0,d=0,e;for(e of Id()){var g=b+c;r[a+d>>2]=g;c+=K(e,g,Infinity)+1;d+=4}return 0},Ya:(a,b)=>{var c=Id();r[a>>2]=c.length;a=0;for(var d of c)a+=zb(d)+1;r[b>>2]=a;return 0},W:()=>52,Za:()=>52,Wa:function(){return 70},Y:(a,b,c,d)=>{for(var e=0,g=0;g<c;g++){var f=r[b>>2],l=r[b+4>>2];b+=8;for(var n=0;n<l;n++){var v=a,E=m[f+n],C=Jd[v];0===E||10===E?((1===v?
fa:ha)(x(C)),C.length=0):C.push(E)}e+=l}r[d>>2]=e;return 0},$:uc,a:vc,Sa:wc,Ta:xc,b:yc,Jb:zc,Ra:Ac,aa:Bc,Fd:Cc,x:Dc,oa:Ec,l:Fc,X:Gc,Ia:Ic,v:Jc,p:Kc,c:Lc,w:Nc,pa:Pc,P:Qc,g:Wc,kd:Zc,ba:ad,h:bd,Qa:ed,d:fd,Hc:gd,u:hd,wc:jd,Pa:function(){var a=new Uint32Array(1);crypto.getRandomValues(a);return a[0]}},Z;
(async function(){function a(c){Z=c.exports;ja=Z._d;c=ja.buffer;k=new Int8Array(c);p=new Int16Array(c);m=new Uint8Array(c);na=new Uint16Array(c);q=new Int32Array(c);r=new Uint32Array(c);u=new Float32Array(c);w=new Float64Array(c);oa=new BigInt64Array(c);new BigUint64Array(c);nc=Z.de;sa();return Z}ra();var b={a:Rd};if(h.instantiateWasm)return new Promise(c=>{h.instantiateWasm(b,(d,e)=>{c(a(d,e))})});ua??=h.locateFile?h.locateFile("index.wasm",da):da+"index.wasm";return a((await xa(b)).instance)})();
var L=a=>(L=Z.ae)(a),Cd=a=>(Cd=Z.be)(a),Sd=h._main=(a,b)=>(Sd=h._main=Z.ce)(a,b),hc=a=>(hc=Z.ee)(a),ec=a=>(ec=Z.fe)(a),gc=()=>(gc=Z.ge)();function Td(a=[]){var b=Sd;a.unshift(ca);var c=a.length,d=ec(4*(c+1)),e=d;a.forEach(f=>{r[e>>2]=fc(f);e+=4});r[e>>2]=0;try{var g=b(c,d);Ka(g)}catch(f){Ia(f)}}
function Ud(a=aa){function b(){h.calledRun=!0;if(!ka){Z.$d();h.onRuntimeInitialized?.();h.noInitialRun||Td(a);if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var c=h.postRun.shift();Aa.push(c)}za(Aa)}}if(0<pa)qa=Ud;else{if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Ca();za(Ba);0<pa?qa=Ud:h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),1);b()},1)):b()}}
if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.shift()();Ud();
