var h;h||=typeof Module != 'undefined' ? Module : {};var aa=[],ba="./this.program",ca="undefined"!=typeof document?document.currentScript?.src:void 0,ea="",ia;try{ea=(new URL(".",ca)).href}catch{}ia=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};var ja=console.log.bind(console),la=console.error.bind(console),ma,na=!1,oa,pa,k,n,p,qa,q,r,u,x,ra;
function sa(a){h.onAbort?.(a);a="Aborted("+a+")";la(a);na=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ta;async function ua(a){if(!ma)try{var b=await ia(a);return new Uint8Array(b)}catch{}if(a==ta&&ma)a=new Uint8Array(ma);else throw"both async and sync fetching of the wasm failed";return a}async function va(a,b){try{var c=await ua(a);return await WebAssembly.instantiate(c,b)}catch(d){la(`failed to asynchronously prepare wasm: ${d}`),sa(d)}}
async function wa(a){var b=ta;if(!ma)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){la(`wasm streaming compile failed: ${d}`),la("falling back to ArrayBuffer instantiation")}return va(b,a)}class xa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var ya=a=>{for(;0<a.length;)a.shift()(h)},za=[],Aa=[],Ba=()=>{var a=h.preRun.shift();Aa.push(a)},Ca=0,Ea=null,Fa=()=>{Ca--;h.monitorRunDependencies?.(Ca);if(0==Ca&&Ea){var a=Ea;Ea=null;a()}},Ga=()=>{Ca++;h.monitorRunDependencies?.(Ca)},Ha=!0;
function Ia(a,b){var c="float";c.endsWith("*")&&(c="*");switch(c){case "i1":k[a]=b;break;case "i8":k[a]=b;break;case "i16":p[a>>1]=b;break;case "i32":q[a>>2]=b;break;case "i64":ra[a>>3]=BigInt(b);break;case "float":u[a>>2]=b;break;case "double":x[a>>3]=b;break;case "*":r[a>>2]=b;break;default:sa(`invalid type for setValue: ${c}`)}}
var Ja="undefined"!=typeof TextDecoder?new TextDecoder:void 0,y=(a,b=0,c)=>{var d=b;for(c=d+c;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&Ja)return Ja.decode(a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|g);else{var f=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|f:(e&7)<<18|g<<12|f<<6|a[b++]&63;65536>e?c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},Ka=
(a,b)=>a?y(n,a,b):"",La=a=>{if(!(a instanceof xa||"unwind"==a))throw a;},Ma=a=>{oa=a;Ha||(h.onExit?.(a),na=!0);throw new xa(a);},Na=a=>{oa=a;Ma(a)},Oa=()=>{if(!Ha)try{var a=oa;oa=a;Ma(a)}catch(b){La(b)}};function Pa(){return document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement||document.msFullscreenElement}var Qa=!1,Ra=[];
function Sa(){function a(){Qa=document.pointerLockElement===h.canvas}if(!Ta){Ta=!0;var b=h.canvas;b&&(document.addEventListener("pointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",c=>{!Qa&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function Ua(a,b,c,d){if(b&&h.ctx&&a==h.canvas)return h.ctx;var e;if(b){var g={antialias:!1,alpha:!1,Ze:1};if(d)for(var f in d)g[f]=d[f];if("undefined"!=typeof Va&&(e=Wa(a,g)))var l=z[e].pe}else l=a.getContext("2d");if(!l)return null;c&&(h.ctx=l,b&&Xa(e),Ra.forEach(m=>m()),Sa());return l}
var Ta,A=12288,Ya=!1,Za=0,$a=0,ab=0,C={alpha:!1,depth:!1,stencil:!1,antialias:!1},bb={},cb,F,db=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,g)=>b.drawArraysInstancedANGLE(c,d,e,g),a.drawElementsInstanced=(c,d,e,g,f)=>b.drawElementsInstancedANGLE(c,d,e,g,f))},eb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),
a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},fb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},gb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},hb=1,ib=[],H=[],jb=[],kb=[],lb=[],I=[],mb=[],z=[],J=[],nb={},ob=4,pb=0,qb=a=>{for(var b=hb++,c=a.length;c<b;c++)a[c]=null;return b},rb=(a,b,c,d)=>{for(var e=0;e<a;e++){var g=F[c](),f=g&&qb(d);g?(g.name=f,d[f]=g):K||=1282;q[b+4*e>>2]=f}},Wa=(a,b)=>{a.oe||(a.oe=a.getContext,a.getContext=function(d,e){e=a.oe(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?sb(c,b):0},sb=(a,b)=>{var c=
qb(z),d={handle:c,attributes:b,version:b.Ze,pe:a};a.canvas&&(a.canvas.te=d);z[c]=d;("undefined"==typeof b.lf||b.lf)&&tb(d);return c},Xa=a=>{ub=z[a];h.ctx=F=ub?.pe},tb=a=>{a||=ub;if(!a.rf){a.rf=!0;var b=a.pe;b.Hf=b.getExtension("WEBGL_multi_draw");b.nf=b.getExtension("EXT_polygon_offset_clamp");b.mf=b.getExtension("EXT_clip_control");b.vf=b.getExtension("WEBGL_polygon_mode");db(b);eb(b);fb(b);b.ne=b.getExtension("EXT_disjoint_timer_query");gb(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||
b.getExtension(c)})}},Va={},K,ub,vb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},L=(a,b,c)=>{var d=n;if(!(0<c))return 0;var e=b;c=b+c-1;for(var g=0;g<a.length;++g){var f=a.codePointAt(g);if(127>=f){if(b>=c)break;d[b++]=f}else if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6;d[b++]=128|f&63}else if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12;d[b++]=128|f>>6&63;d[b++]=128|f&63}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|
f>>12&63;d[b++]=128|f>>6&63;d[b++]=128|f&63;g++}}d[b]=0;return b-e},N=a=>{var b=vb(a)+1,c=M(b);c&&L(a,c,b);return c},Mb=(a,b,c,d,e)=>{function g(){return f<wb?(Oa(),!1):!0}xb=a;yb=d;var f=wb;zb=!1;Ab=function(){if(!na)if(0<Bb.length){var l=Bb.shift();l.Df(l.wf);if(Cb){var m=Cb,v=0==m%1?m-1:Math.floor(m);Cb=l.zf?v:(8*m+(v+.5))/9}h.setStatus&&(l=h.statusMessage||"Please wait...",m=Cb??0,v=Db.Cf??0,m?m<v?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(l):h.setStatus(""));g()&&
setTimeout(Ab,0)}else if(g())if(Eb=Eb+1|0,1==Fb&&1<Gb&&0!=Eb%Gb)Hb();else{0==Fb&&(Ib=performance.now());a:if(!na){for(l of Jb)if(!1===l())break a;if(!na)try{a(),Oa()}catch(E){La(E)}for(m of Kb)m()}g()&&Hb()}};e||(0<b?Lb(0,1E3/b):Lb(1,1),Hb());if(c)throw"unwind";},zb=!1,Hb=null,wb=0,xb=null,yb=0,Fb=0,Gb=0,Eb=0,Bb=[],Jb=[],Kb=[],Nb=0;
function Ob(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Nb)Nb=b+1E3/60;else for(;b+2>=Nb;)Nb+=1E3/60;setTimeout(a,Math.max(Nb-b,0))}}
var Db={},Ab,Cb,Ib,Pb,Lb=(a,b)=>{Fb=a;Gb=b;if(xb)if(zb||=!0,0==a)Hb=function(){setTimeout(Ab,Math.max(0,Ib+b-performance.now())|0)};else if(1==a)Hb=function(){Ob(Ab)};else if(2==a){if("undefined"==typeof Pb)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Pb=d=>{c.push(d);postMessage("setimmediate","*")}}else Pb=setImmediate;Hb=function(){Pb(Ab)}}},Qb=[],Rb=(a,b)=>{Qb.length=
0;for(var c;c=n[a++];){var d=105!=c;d&=112!=c;b+=d&&b%8?4:0;Qb.push(112==c?r[b>>2]:106==c?ra[b>>3]:105==c?q[b>>2]:x[b>>3]);b+=d?8:4}return Qb};function Sb(a){var b=O.je[a];b.target.removeEventListener(b.ge,b.We,b.he);O.je.splice(a,1)}function Tb(a,b,c){function d(g,f){if(g.length!=f.length)return!1;for(var l in g)if(g[l]!=f[l])return!1;return!0}for(var e of O.qe)if(e.Oe==a&&d(e.Ue,c))return;O.qe.push({Oe:a,af:b,Ue:c});O.qe.sort((g,f)=>g.af<f.af)}function Ub(a){O.qe=O.qe.filter(b=>b.Oe!=a)}
function Vb(){return navigator.userActivation?navigator.userActivation.isActive:O.Je&&O.ef.ve}function Wb(){if(Vb()){var a=O.qe;O.qe=[];for(var b of a)b.Oe(...b.Ue)}}function P(a){if(!a.target)return-4;if(a.ie)a.We=function(c){++O.Je;O.ef=a;Wb();a.ke(c);Wb();--O.Je},a.target.addEventListener(a.ge,a.We,a.he),O.je.push(a);else for(var b=0;b<O.je.length;++b)O.je[b].target==a.target&&O.je[b].ge==a.ge&&Sb(b--);return 0}
function Xb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var O={xf:0,Ie:0,Ke:0,De:0,Te:0,Qe:0,Ge:0,Bf:0,If:0,Af:0,He:0,Me:0,Se:0,Pe:0,Ff(a,b,c){k.set(k.subarray(b,b+c),a)},Jf(){for(;O.je.length;)Sb(O.je.length-1);O.qe=[]},Je:0,qe:[],je:[],tf:(a,b)=>{for(var c=0;c<O.je.length;++c)O.je[c].target!=a||b&&b!=O.je[c].ge||Sb(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},Yb=[0,document,window],Q=a=>{a=2<a?a?y(n,a):"":a;return Yb[a]||document.querySelector(a)},$b=a=>{var b=vb(a)+1,c=Zb(b);L(a,c,b);return c},cc=a=>
{var b=ac(),c=Zb(8),d=c+4;a=$b(a.id);if(a=Q(a))q[c>>2]=a.width,q[d>>2]=a.height;c=[q[c>>2],q[d>>2]];bc(b);return c},dc=(a,b,c)=>{a=Q(a);if(!a)return-4;a.width=b;a.height=c;return 0},ec=(a,b,c)=>{if(a.yf){var d=ac();a=$b(a.id);dc(a,b,c);bc(d)}else a.width=b,a.height=c},fc={},gc=[],hc,T=a=>{var b=gc[a];b||(gc[a]=b=hc.get(a));return b},ic=a=>{function b(){Pa()||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",b),ec(a,d,e),a.style.width=g,a.style.height=
f,a.style.backgroundColor=l,m||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=m,a.style.paddingLeft=v,a.style.paddingRight=E,a.style.paddingTop=D,a.style.paddingBottom=G,a.style.marginLeft=R,a.style.marginRight=Y,a.style.marginTop=S,a.style.marginBottom=Z,document.body.style.margin=U,document.documentElement.style.overflow=ka,document.body.scroll=da,a.style.re=t,a.te&&a.te.pe.viewport(0,0,d,e),fc.we&&T(fc.we)(37,0,fc.Ve))}var c=cc(a),d=c[0],e=c[1],g=a.style.width,
f=a.style.height,l=a.style.backgroundColor,m=document.body.style.backgroundColor,v=a.style.paddingLeft,E=a.style.paddingRight,D=a.style.paddingTop,G=a.style.paddingBottom,R=a.style.marginLeft,Y=a.style.marginRight,S=a.style.marginTop,Z=a.style.marginBottom,U=document.body.style.margin,ka=document.documentElement.style.overflow,da=document.body.scroll,t=a.style.re;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",b)},jc=(a,b,c)=>{a.style.paddingLeft=
a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"},kc=a=>0>Yb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},lc=(a,b)=>{if(0!=b.Ne||0!=b.Ee){ic(a);var c=b.uf?innerWidth:screen.width,d=b.uf?innerHeight:screen.height,e=kc(a),g=e.width;e=e.height;var f=cc(a),l=f[0];f=f[1];3==b.Ne?(jc(a,(d-e)/2,(c-g)/2),c=g,d=e):2==b.Ne&&(c*f<l*d?(g=f*c/l,jc(a,(d-g)/2,0),d=g):(g=l*d/f,jc(a,0,(c-g)/2),c=g));var m;(m=a.style).backgroundColor||(m.backgroundColor="black");let v;(v=document.body.style).backgroundColor||
(v.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.pf&&(a.style.re="optimizeSpeed",a.style.re="-moz-crisp-edges",a.style.re="-o-crisp-edges",a.style.re="-webkit-optimize-contrast",a.style.re="optimize-contrast",a.style.re="crisp-edges",a.style.re="pixelated");m=2==b.Ee?devicePixelRatio:1;0!=b.Ee&&(c=c*m|0,d=d*m|0,ec(a,c,d),a.te&&a.te.pe.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);
else return O.fullscreenEnabled()?-3:-1;fc=b;b.we&&T(b.we)(37,0,b.Ve);return 0},mc=a=>{if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?-3:-1;return 0},nc=(a,b)=>{x[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)x[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)x[a+8*c+528>>3]="object"==typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)k[a+c+1040]="object"==typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];
k[a+1104]=b.connected;q[a+1108>>2]=b.index;q[a+8>>2]=b.axes.length;q[a+12>>2]=b.buttons.length;L(b.id,a+1112,64);L(b.mapping,a+1176,64)},oc=(a,b)=>{F.attachShader(H[a],I[b])},pc=(a,b)=>{F.bindBuffer(a,ib[b])},qc=a=>F.blendEquation(a),rc=(a,b)=>F.blendFunc(a,b),sc=(a,b,c,d)=>{F.bufferData(a,c?n.subarray(c,c+b):b,d)},tc=a=>F.clear(a),uc=(a,b,c,d)=>F.clearColor(a,b,c,d),vc=a=>{F.compileShader(I[a])},wc=()=>{var a=qb(H),b=F.createProgram();b.name=a;b.Ce=b.Ae=b.Be=0;b.Re=1;H[a]=b;return a},xc=a=>{var b=
qb(I);I[b]=F.createShader(a);return b},yc=a=>{F.depthMask(!!a)},zc=a=>F.disable(a),Ac=[],Bc=(a,b,c,d)=>{F.drawElements(a,b,c,d)},Cc=a=>F.enable(a),Dc=a=>{F.enableVertexAttribArray(a)},Ec=(a,b)=>{rb(a,b,"createBuffer",ib)},Fc=(a,b,c,d,e,g,f,l)=>{b=H[b];if(a=F[a](b,c))d=l&&L(a.name,l,d),e&&(q[e>>2]=d),g&&(q[g>>2]=a.size),f&&(q[f>>2]=a.type)},Gc=(a,b)=>F.getAttribLocation(H[a],b?y(n,b):""),V=(a,b)=>{r[a>>2]=b;r[a+4>>2]=(b-r[a>>2])/4294967296},Hc=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;
break;case 36344:0!=c&&1!=c&&(K||=1280);return;case 36345:d=0;break;case 34466:var e=F.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=F.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":K||=1280;return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:K||=1280;return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof
Array){for(a=0;a<e.length;++a)switch(c){case 0:q[b+4*a>>2]=e[a];break;case 2:u[b+4*a>>2]=e[a];break;case 4:k[b+a]=e[a]?1:0}return}try{d=e.name|0}catch(g){K||=1280;la(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${g})`);return}}break;default:K||=1280;la(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${e} of type ${typeof e}!`);return}switch(c){case 1:V(b,d);break;case 0:q[b>>2]=d;break;case 2:u[b>>2]=d;break;case 4:k[b]=
d?1:0}}else K||=1281},Ic=(a,b,c)=>{if(c){a=F.ne.getQueryObjectEXT(J[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;V(c,d)}else K||=1281},Jc=(a,b,c)=>{if(c){a=F.ne.getQueryObjectEXT(J[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;q[c>>2]=d}else K||=1281},Kc=()=>{var a=gb(F);return a=a.concat(a.map(b=>"GL_"+b))},Lc=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Mc=a=>{var b=a.ue,c=a.cf,d;if(!b){a.ue=b={};a.bf={};var e=F.getProgramParameter(a,35718);for(d=0;d<e;++d){var g=F.getActiveUniform(a,d);var f=g.name;g=
g.size;var l=Lc(f);l=0<l?f.slice(0,l):f;var m=a.Re;a.Re+=g;c[l]=[g,m];for(f=0;f<g;++f)b[m]=f,a.bf[m++]=l}}},Nc=(a,b)=>{b=b?y(n,b):"";if(a=H[a]){Mc(a);var c=a.ue,d=0,e=b,g=Lc(b);0<g&&(d=parseInt(b.slice(g+1))>>>0,e=b.slice(0,g));if((e=a.cf[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||F.getUniformLocation(a,b)))return d}else K||=1281;return-1},W=a=>{var b=F.ff;if(b){var c=b.ue[a];"number"==typeof c&&(b.ue[a]=c=F.getUniformLocation(b,b.bf[a]+(0<c?`[${c}]`:"")));return c}K||=1282},Oc=(a,b,c,d)=>{if(c)if(a=H[a],Mc(a),
a=F.getUniform(a,W(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:q[c>>2]=a;break;case 2:u[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:q[c+4*b>>2]=a[b];break;case 2:u[c+4*b>>2]=a[b]}else K||=1281},Pc=(a,b,c,d)=>{if(c)if(a=F.getVertexAttrib(a,b),34975==b)q[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:q[c>>2]=a;break;case 2:u[c>>2]=a;break;case 5:q[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:q[c+4*b>>2]=a[b];break;case 2:u[c+
4*b>>2]=a[b];break;case 5:q[c+4*b>>2]=Math.fround(a[b])}else K||=1281},Qc=a=>{a=H[a];F.linkProgram(a);a.ue=0;a.cf={}},Rc=(a,b,c,d,e)=>{a-=5120;a=1==a?n:4==a?q:6==a?u:5==a||28922==a?r:qa;b=d*((pb||c)*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+ob-1&-ob);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},Sc=(a,b,c,d)=>{for(var e="",g=0;g<b;++g)e+=Ka(r[c+4*g>>2],d?r[d+4*g>>2]:void 0);F.shaderSource(I[a],e)},Tc=(a,b)=>{F.uniform1f(W(a),
b)},Uc=[],Vc=[],Wc=(a,b,c,d)=>{F.uniform3f(W(a),b,c,d)},Xc=(a,b,c,d)=>{if(18>=b){var e=Uc[16*b],g=u;d>>=2;b*=16;for(var f=0;f<b;f+=16){var l=d+f;e[f]=g[l];e[f+1]=g[l+1];e[f+2]=g[l+2];e[f+3]=g[l+3];e[f+4]=g[l+4];e[f+5]=g[l+5];e[f+6]=g[l+6];e[f+7]=g[l+7];e[f+8]=g[l+8];e[f+9]=g[l+9];e[f+10]=g[l+10];e[f+11]=g[l+11];e[f+12]=g[l+12];e[f+13]=g[l+13];e[f+14]=g[l+14];e[f+15]=g[l+15]}}else e=u.subarray(d>>2,d+64*b>>2);F.uniformMatrix4fv(W(a),!!c,e)},Yc=a=>{a=H[a];F.useProgram(a);F.ff=a},Zc=(a,b,c,d,e,g)=>{F.vertexAttribPointer(a,
b,c,!!d,e,g)},$c=(a,b,c,d)=>F.viewport(a,b,c,d),ad=(a,b)=>{if(!O.fullscreenEnabled())return-1;a=Q(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?Vb()?lc(a,b):b.kf?(Tb(lc,1,[a,b]),1):-2:-3:-4},bd=()=>{try{if(navigator.getGamepads)return(O.ze=navigator.getGamepads())?0:-1}catch(a){navigator.getGamepads=null}return-1},cd=(a,b)=>{var c={target:Q(2),ge:"beforeunload",ie:b,ke:(d=event)=>{var e=T(b)(28,0,a);e&&=e?y(n,e):"";if(e)return d.preventDefault(),d.returnValue=e},he:!0};return P(c)},dd=
(a,b,c,d,e,g)=>{O.Ge||(O.Ge=M(256));a={target:Q(a),ge:g,ie:d,ke:(f=event)=>{var l=f.target.id?f.target.id:"",m=O.Ge;L(Xb(f.target),m+0,128);L(l,m+128,128);T(d)(e,m,b)&&f.preventDefault()},he:c};return P(a)},ed=(a,b,c,d,e)=>{O.He||(O.He=M(276));return P({target:a,ge:e,ie:d,ke:(g=event)=>{var f=O.He,l=Pa(),m=!!l;k[f]=m;k[f+1]=O.fullscreenEnabled();var v=m?l:O.sf,E=v?.id||"";L(Xb(v),f+2,128);L(E,f+130,128);q[f+260>>2]=v?v.clientWidth:0;q[f+264>>2]=v?v.clientHeight:0;q[f+268>>2]=screen.width;q[f+272>>
2]=screen.height;m&&(O.sf=l);T(d)(19,f,b)&&g.preventDefault()},he:c})},fd=(a,b,c,d,e)=>{O.Ie||(O.Ie=M(1240));b={target:Q(2),ve:!0,ge:e,ie:c,ke:(g=event)=>{var f=O.Ie;nc(f,g.gamepad);T(c)(d,f,a)&&g.preventDefault()},he:b};return P(b)},gd=(a,b,c,d,e,g)=>{O.Ke||(O.Ke=M(160));a={target:Q(a),ge:g,ie:d,ke:f=>{var l=O.Ke;x[l>>3]=f.timeStamp;var m=l>>2;q[m+2]=f.location;k[l+12]=f.ctrlKey;k[l+13]=f.shiftKey;k[l+14]=f.altKey;k[l+15]=f.metaKey;k[l+16]=f.repeat;q[m+5]=f.charCode;q[m+6]=f.keyCode;q[m+7]=f.which;
L(f.key||"",l+32,32);L(f.code||"",l+64,32);L(f.char||"",l+96,32);L(f.locale||"",l+128,32);T(d)(e,l,b)&&f.preventDefault()},he:c};return P(a)},hd=(a,b,c)=>{x[a>>3]=b.timeStamp;var d=a>>2;q[d+2]=b.screenX;q[d+3]=b.screenY;q[d+4]=b.clientX;q[d+5]=b.clientY;k[a+24]=b.ctrlKey;k[a+25]=b.shiftKey;k[a+26]=b.altKey;k[a+27]=b.metaKey;p[2*d+14]=b.button;p[2*d+15]=b.buttons;q[d+8]=b.movementX;q[d+9]=b.movementY;a=kc(c);q[d+10]=b.clientX-(a.left|0);q[d+11]=b.clientY-(a.top|0)},jd=(a,b,c,d,e,g)=>{O.De||(O.De=M(64));
a=Q(a);return P({target:a,ve:"mousemove"!=g&&"mouseenter"!=g&&"mouseleave"!=g,ge:g,ie:d,ke:(f=event)=>{hd(O.De,f,a);T(d)(e,O.De,b)&&f.preventDefault()},he:c})},kd=(a,b,c,d)=>{O.Me||(O.Me=M(257));return P({target:a,ge:"pointerlockchange",ie:d,ke:(e=event)=>{var g=O.Me,f=document.pointerLockElement;k[g]=!!f;var l=f?.id||"";L(Xb(f),g+1,128);L(l,g+129,128);T(d)(20,g,b)&&e.preventDefault()},he:c})},ld=(a,b,c,d)=>{O.Qe||(O.Qe=M(36));a=Q(a);return P({target:a,ge:"resize",ie:d,ke:(e=event)=>{if(e.target==
a){var g=document.body;if(g){var f=O.Qe;q[f>>2]=0;q[f+4>>2]=g.clientWidth;q[f+8>>2]=g.clientHeight;q[f+12>>2]=innerWidth;q[f+16>>2]=innerHeight;q[f+20>>2]=outerWidth;q[f+24>>2]=outerHeight;q[f+28>>2]=pageXOffset|0;q[f+32>>2]=pageYOffset|0;T(d)(10,f,b)&&e.preventDefault()}}},he:c})},md=(a,b,c,d,e,g)=>{O.Pe||(O.Pe=M(1552));a=Q(a);return P({target:a,ve:"touchstart"==g||"touchend"==g,ge:g,ie:d,ke:f=>{var l={},m=f.touches;for(var v of m)v.Ye=v.$e=0,l[v.identifier]=v;for(var E of f.changedTouches)E.Ye=
1,l[E.identifier]=E;for(var D of f.targetTouches)l[D.identifier].$e=1;m=O.Pe;x[m>>3]=f.timeStamp;k[m+12]=f.ctrlKey;k[m+13]=f.shiftKey;k[m+14]=f.altKey;k[m+15]=f.metaKey;v=m+16;E=kc(a);D=0;for(let G of Object.values(l))if(l=v>>2,q[l]=G.identifier,q[l+1]=G.screenX,q[l+2]=G.screenY,q[l+3]=G.clientX,q[l+4]=G.clientY,q[l+5]=G.pageX,q[l+6]=G.pageY,k[v+28]=G.Ye,k[v+29]=G.$e,q[l+8]=G.clientX-(E.left|0),q[l+9]=G.clientY-(E.top|0),v+=48,31<++D)break;q[m+8>>2]=D;T(d)(e,m,b)&&f.preventDefault()},he:c})},nd=(a,
b,c)=>{var d=Yb[1];O.Se||(O.Se=M(8));return P({target:d,ge:"visibilitychange",ie:c,ke:(e=event)=>{var g=O.Se,f=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);k[g]=document.hidden;q[g+4>>2]=f;T(c)(21,g,a)&&e.preventDefault()},he:b})},od=(a,b,c,d)=>{O.Te||(O.Te=M(96));return P({target:a,ve:!0,ge:"wheel",ie:d,ke:(e=event)=>{var g=O.Te;hd(g,e,a);x[g+64>>3]=e.deltaX;x[g+72>>3]=e.deltaY;x[g+80>>3]=e.deltaZ;q[g+88>>2]=e.deltaMode;T(d)(9,g,b)&&e.preventDefault()},he:c})};
function pd(a){var b=X,c=b.Xe.pop()||b.oe.length;b.oe[c]=a;return c}class qd{oe=[void 0];Xe=[];get(a){return this.oe[a]}has(a){return void 0!==this.oe[a]}}async function rd(){return new Promise((a,b)=>{try{var c=indexedDB.open("emscripten_filesystem",1)}catch(d){return b(d)}c.onupgradeneeded=d=>{d=d.target.result;d.objectStoreNames.contains("FILES")&&d.deleteObjectStore("FILES");d.createObjectStore("FILES")};c.onsuccess=d=>a(d.target.result);c.onerror=b})}var X,sd;
function td(a,b,c,d,e){function g(){var B=0,w=0;t.response&&U&&0===r[a+12>>2]&&(w=t.response.byteLength);0<w&&(B=M(w),n.set(new Uint8Array(t.response),B));r[a+12>>2]=B;V(a+16,w);V(a+24,0);(B=t.response?t.response.byteLength:0)&&V(a+32,B);p[a+40>>1]=t.readyState;p[a+42>>1]=t.status;t.statusText&&L(t.statusText,a+44,64);da&&(B=N(t.responseURL),r[a+200>>2]=B)}var f=r[a+8>>2];if(f){var l=f?y(n,f):"",m=a+108,v=Ka(m+0);v||="GET";var E=r[m+56>>2],D=r[m+68>>2],G=r[m+72>>2];f=r[m+76>>2];var R=r[m+80>>2],Y=
r[m+84>>2],S=r[m+88>>2],Z=r[m+52>>2],U=!!(Z&1),ka=!!(Z&2),da=!!(Z&64);D=D?D?y(n,D):"":void 0;G=G?G?y(n,G):"":void 0;var t=new XMLHttpRequest;t.withCredentials=!!n[m+60];t.open(v,l,!da,D,G);da||(t.timeout=E);t.oe=l;t.responseType="arraybuffer";R&&(l=R?y(n,R):"",t.overrideMimeType(l));if(f)for(;;){m=r[f>>2];if(!m)break;l=r[f+4>>2];if(!l)break;f+=8;m=m?y(n,m):"";l=l?y(n,l):"";t.setRequestHeader(m,l)}var fa=pd(t);r[a>>2]=fa;f=Y&&S?n.slice(Y,Y+S):null;t.onload=B=>{X.has(fa)&&(g(),200<=t.status&&300>t.status?
b(a,t,B):c(a,B))};t.onerror=B=>{X.has(fa)&&(g(),c(a,B))};t.ontimeout=B=>{X.has(fa)&&c(a,B)};t.onprogress=B=>{if(X.has(fa)){var w=U&&ka&&t.response?t.response.byteLength:0,ha=0;0<w&&U&&ka&&(ha=M(w),n.set(new Uint8Array(t.response),ha));r[a+12>>2]=ha;V(a+16,w);V(a+24,B.loaded-w);V(a+32,B.total);p[a+40>>1]=t.readyState;w=t.status;3<=t.readyState&&0===t.status&&0<B.loaded&&(w=200);p[a+42>>1]=w;t.statusText&&L(t.statusText,a+44,64);d(a,B);ud(ha)}};t.onreadystatechange=B=>{if(X.has(fa)){p[a+40>>1]=t.readyState;
2<=t.readyState&&(p[a+42>>1]=t.status);if(!da&&2===t.readyState&&0<t.responseURL.length){var w=N(t.responseURL);r[a+200>>2]=w}e(a,B)}};try{t.send(f)}catch(B){c(a,B)}}else c(a,"no url specified!")}
function vd(a,b,c,d){var e=sd;if(e){var g=r[a+108+64>>2];g||=r[a+8>>2];var f=g?y(n,g):"";try{var l=e.transaction(["FILES"],"readwrite").objectStore("FILES").put(b,f);l.onsuccess=()=>{p[a+40>>1]=4;p[a+42>>1]=200;L("OK",a+44,64);c(a,0,f)};l.onerror=m=>{p[a+40>>1]=4;p[a+42>>1]=413;L("Payload Too Large",a+44,64);d(a,0,m)}}catch(m){d(a,0,m)}}else d(a,0,"IndexedDB not available!")}
function wd(a,b,c){var d=sd;if(d){var e=r[a+108+64>>2];e||=r[a+8>>2];e=e?y(n,e):"";try{var g=d.transaction(["FILES"],"readonly").objectStore("FILES").get(e);g.onsuccess=f=>{if(f.target.result){f=f.target.result;var l=f.byteLength||f.length,m=M(l);n.set(new Uint8Array(f),m);r[a+12>>2]=m;V(a+16,l);V(a+24,0);V(a+32,l);p[a+40>>1]=4;p[a+42>>1]=200;L("OK",a+44,64);b(a,0,f)}else p[a+40>>1]=4,p[a+42>>1]=404,L("Not Found",a+44,64),c(a,0,"no data")};g.onerror=f=>{p[a+40>>1]=4;p[a+42>>1]=404;L("Not Found",a+
44,64);c(a,0,f)}}catch(f){c(a,0,f)}}else c(a,0,"IndexedDB not available!")}function xd(a,b,c){var d=sd;if(d){var e=r[a+108+64>>2];e||=r[a+8>>2];e=e?y(n,e):"";try{var g=d.transaction(["FILES"],"readwrite").objectStore("FILES").delete(e);g.onsuccess=f=>{f=f.target.result;r[a+12>>2]=0;V(a+16,0);V(a+24,0);V(a+32,0);p[a+40>>1]=4;p[a+42>>1]=200;L("OK",a+44,64);b(a,0,f)};g.onerror=f=>{p[a+40>>1]=4;p[a+42>>1]=404;L("Not Found",a+44,64);c(a,0,f)}}catch(f){c(a,0,f)}}else c(a,0,"IndexedDB not available!")}
var yd={},Ad=()=>{if(!zd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.language||"C").replace("-","_")+".UTF-8",_:ba||"./this.program"},b;for(b in yd)void 0===yd[b]?delete a[b]:a[b]=yd[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);zd=c}return zd},zd,Bd=[null,[],[]],Cd=a=>{var b;b||=[document,document.getElementById("canvas")];["keydown","mousedown","touchstart"].forEach(c=>{b.forEach(d=>{d?.addEventListener(c,()=>{"suspended"===
a.state&&a.resume()},{once:!0})})})},Dd=(a,b=[])=>{T(a)(...b)};h.requestAnimationFrame=Ob;h.pauseMainLoop=function(){Hb=null;wb++};h.resumeMainLoop=function(){wb++;var a=Fb,b=Gb,c=xb;xb=null;Mb(c,0,!1,yb,!0);Lb(a,b);Hb()};h.preMainLoop&&Jb.push(h.preMainLoop);h.postMainLoop&&Kb.push(h.postMainLoop);for(let a=0;32>a;++a)Ac.push(Array(a));for(var Ed=new Float32Array(288),Fd=0;288>=Fd;++Fd)Uc[Fd]=Ed.subarray(0,Fd);var Gd=new Int32Array(288);for(Fd=0;288>=Fd;++Fd)Vc[Fd]=Gd.subarray(0,Fd);
(async function(){X=new qd;Ga();try{sd=await rd()}catch(a){sd=!1}finally{Fa()}})();h.noExitRuntime&&(Ha=h.noExitRuntime);h.print&&(ja=h.print);h.printErr&&(la=h.printErr);h.wasmBinary&&(ma=h.wasmBinary);h.arguments&&(aa=h.arguments);h.thisProgram&&(ba=h.thisProgram);if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.shift()();h.createContext=Ua;
var Hd={8001338:()=>{alert("The FishyHotel server is currently down for maintinance.")},8001407:()=>{1==confirm("Would you like to play Hypergolia?")&&window.open("https://silentrooms.itch.io/hypergolia").focus()},8001531:()=>{1==confirm("Would you like to play Fishtank Dungeons?")&&window.open("https://fishyhotel.com/fishtankdungeons").focus()},8001663:()=>{1==confirm("Would you like to play BloodGames Coin Pusher?")&&window.open("https://fishyhotel.com/blood").focus()},8001789:()=>{1==confirm("Would you like to play Fishtank Arena?")&&
window.open("https://fishtankdungeons.itch.io/arena").focus()},8001917:()=>"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?!0:!1,8002064:()=>"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?!0:!1,8002298:a=>{"undefined"===typeof h.SDL2&&(h.SDL2={});var b=h.SDL2;a?b.capture={}:b.audio={};b.fe||("undefined"!==typeof AudioContext?b.fe=new AudioContext:"undefined"!==typeof webkitAudioContext&&
(b.fe=new webkitAudioContext),b.fe&&"undefined"===typeof navigator.userActivation&&Cd(b.fe));return void 0===b.fe?-1:0},8002850:()=>h.SDL2.fe.sampleRate,8002918:(a,b,c,d)=>{function e(){}function g(l){void 0!==f.capture.me&&(clearInterval(f.capture.me),f.capture.me=void 0,f.capture.se=void 0);f.capture.Le=f.fe.createMediaStreamSource(l);f.capture.le=f.fe.createScriptProcessor(b,a,1);f.capture.le.onaudioprocess=function(m){void 0!==f&&void 0!==f.capture&&(m.outputBuffer.getChannelData(0).fill(0),f.capture.Fe=
m.inputBuffer,Dd(c,[d]))};f.capture.Le.connect(f.capture.le);f.capture.le.connect(f.fe.destination);f.capture.stream=l}var f=h.SDL2;f.capture.se=f.fe.createBuffer(a,b,f.fe.sampleRate);f.capture.se.getChannelData(0).fill(0);f.capture.me=setInterval(function(){f.capture.Fe=f.capture.se;Dd(c,[d])},b/f.fe.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(g).catch(e):void 0!==navigator.webkitGetUserMedia&&
navigator.webkitGetUserMedia({audio:!0,video:!1},g,e)},8004611:(a,b,c,d)=>{var e=h.SDL2;e.audio.le=e.fe.createScriptProcessor(b,0,a);e.audio.le.onaudioprocess=function(g){void 0!==e&&void 0!==e.audio&&(void 0!==e.audio.me&&(clearInterval(e.audio.me),e.audio.me=void 0,e.audio.se=void 0),e.audio.ye=g.outputBuffer,Dd(c,[d]))};e.audio.le.connect(e.fe.destination);"suspended"===e.fe.state&&(e.audio.se=e.fe.createBuffer(a,b,e.fe.sampleRate),e.audio.se.getChannelData(0).fill(0),e.audio.me=setInterval(function(){"undefined"!==
typeof navigator.userActivation&&navigator.userActivation.hasBeenActive&&e.fe.resume();e.audio.ye=e.audio.se;Dd(c,[d]);e.audio.ye=void 0},b/e.fe.sampleRate*1E3))},8005786:(a,b)=>{for(var c=h.SDL2,d=c.capture.Fe.numberOfChannels,e=0;e<d;++e){var g=c.capture.Fe.getChannelData(e);if(g.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+g.length+" samples vs expected "+b+" samples!";if(1==d)for(var f=0;f<b;++f)Ia(a+4*f,g[f]);else for(f=0;f<b;++f)Ia(a+4*(f*d+e),g[f])}},8006391:(a,
b)=>{var c=h.SDL2;a>>>=2;for(var d=c.audio.ye.numberOfChannels,e=0;e<d;++e){var g=c.audio.ye.getChannelData(e);if(g.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+g.length+" samples vs expected "+b+" samples!";for(var f=0;f<b;++f)g[f]=u[a+(f*d+e)]}},8006880:a=>{var b=h.SDL2;if(a){void 0!==b.capture.me&&clearInterval(b.capture.me);if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c])}void 0!==b.capture.le&&
(b.capture.le.onaudioprocess=function(){},b.capture.le.disconnect());void 0!==b.capture.Le&&b.capture.Le.disconnect();b.capture=void 0}else void 0!=b.audio.le&&b.audio.le.disconnect(),void 0!==b.audio.me&&clearInterval(b.audio.me),b.audio=void 0;void 0!==b.fe&&void 0===b.audio&&void 0===b.capture&&(b.fe.close(),b.fe=void 0)},8007886:(a,b,c)=>{h.SDL2||(h.SDL2={});var d=h.SDL2;d.df!==h.canvas&&(d.xe=Ua(h.canvas,!1,!0),d.df=h.canvas);if(d.w!==a||d.h!==b||d.qf!==d.xe)d.image=d.xe.createImageData(a,b),
d.w=a,d.h=b,d.qf=d.xe;a=d.image.data;b=c/4;var e=0;if("undefined"!==typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var g=q[b];a[e]=g&255;a[e+1]=g>>8&255;a[e+2]=g>>16&255;a[e+3]=255;b++;e+=4}else if(d.hf!==a&&(d.gf=new Int32Array(a.buffer),d.jf=new Uint8Array(a.buffer),d.hf=a),a=d.gf,c=a.length,a.set(q.subarray(b,b+c)),a=d.jf,b=3,e=b+4*c,0==c%8)for(;b<e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|
0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=255,b=b+4|0;d.xe.putImageData(d.image,0,0)},8009352:(a,b,c,d,e)=>{var g=document.createElement("canvas");g.width=a;g.height=b;var f=g.getContext("2d");a=f.createImageData(a,b);b=a.data;e/=4;var l=0,m;if("undefined"!==typeof CanvasPixelArray&&b instanceof CanvasPixelArray)for(m=b.length;l<m;){var v=q[e];b[l]=v&255;b[l+1]=v>>8&255;b[l+2]=v>>16&255;b[l+3]=v>>24&255;e++;l+=4}else b=new Int32Array(b.buffer),m=b.length,b.set(q.subarray(e,e+m));f.putImageData(a,0,0);
c=0===c&&0===d?"url("+g.toDataURL()+"), auto":"url("+g.toDataURL()+") "+c+" "+d+", auto";d=M(c.length+1);L(c,d,c.length+1);return d},8010340:a=>{h.canvas&&(h.canvas.style.cursor=a?y(n,a):"")},8010423:()=>{h.canvas&&(h.canvas.style.cursor="none")},8010492:()=>window.innerWidth,8010522:()=>window.innerHeight},Id,M,ud,bc,Zb,ac,Jd={aa:function(){return 0},_a:function(){return 0},$a:function(){},Ua:()=>{},Ga:a=>{if(12448==a)return A=12288,1;A=12300;return 0},Ka:(a,b,c,d,e)=>{if(62E3!=a)A=12296,c=0;else{if(b)for(;;){a=
q[b>>2];if(12321==a)C.alpha=0<q[b+4>>2];else if(12325==a)C.depth=0<q[b+4>>2];else if(12326==a)C.stencil=0<q[b+4>>2];else if(12337==a)a=q[b+4>>2],C.antialias=0<a;else if(12338==a)a=q[b+4>>2],C.antialias=1==a;else if(12544==a)C.Ef=12547!=q[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(q[e>>2]=1),c&&0<d&&(r[c>>2]=62002),A=12288,c=1):(A=12300,c=0)}return c},xa:(a,b,c,d)=>{if(62E3!=a)return A=12296,0;for(a=1;;){b=q[d>>2];if(12440==b)a=q[d+4>>2];else if(12344==b)break;else return A=12292,0;d+=8}if(2!=
a)return A=12293,0;C.Ze=a-1;C.Gf=0;cb=Wa(h.canvas,C);if(0!=cb)return A=12288,Xa(cb),Ra.forEach(e=>e()),Xa(null),62004;A=12297;return 0},za:(a,b)=>{if(62E3!=a)return A=12296,0;if(62002!=b)return A=12293,0;A=12288;return 62006},ya:(a,b)=>{if(62E3!=a)return A=12296,0;if(62004!=b)return A=12294,0;a=cb;ub===z[a]&&(ub=null);"object"==typeof O&&O.tf(z[a].pe.canvas);z[a]?.pe.canvas&&(z[a].pe.canvas.te=void 0);z[a]=null;A=12288;Za==b&&(Za=0);return 1},Aa:(a,b)=>{if(62E3!=a)return A=12296,0;if(62006!=b)return A=
12301,1;$a==b&&($a=0);ab==b&&(ab=0);A=12288;return 1},La:(a,b,c,d)=>{if(62E3!=a)return A=12296,0;if(62002!=b)return A=12293,0;if(!d)return A=12300,0;A=12288;switch(c){case 12320:return q[d>>2]=C.alpha?32:24,1;case 12321:return q[d>>2]=C.alpha?8:0,1;case 12322:return q[d>>2]=8,1;case 12323:return q[d>>2]=8,1;case 12324:return q[d>>2]=8,1;case 12325:return q[d>>2]=C.depth?24:0,1;case 12326:return q[d>>2]=C.stencil?8:0,1;case 12327:return q[d>>2]=12344,1;case 12328:return q[d>>2]=62002,1;case 12329:return q[d>>
2]=0,1;case 12330:return q[d>>2]=4096,1;case 12331:return q[d>>2]=16777216,1;case 12332:return q[d>>2]=4096,1;case 12333:return q[d>>2]=0,1;case 12334:return q[d>>2]=0,1;case 12335:return q[d>>2]=12344,1;case 12337:return q[d>>2]=C.antialias?4:0,1;case 12338:return q[d>>2]=C.antialias?1:0,1;case 12339:return q[d>>2]=4,1;case 12340:return q[d>>2]=12344,1;case 12341:case 12342:case 12343:return q[d>>2]=-1,1;case 12345:case 12346:return q[d>>2]=0,1;case 12347:return q[d>>2]=0,1;case 12348:return q[d>>
2]=1;case 12349:case 12350:return q[d>>2]=0,1;case 12351:return q[d>>2]=12430,1;case 12352:return q[d>>2]=4,1;case 12354:return q[d>>2]=0,1;default:return A=12292,0}},S:a=>{A=12288;return 0!=a&&1!=a?0:62E3},wa:()=>A,Ha:(a,b,c)=>{if(62E3!=a)return A=12296,0;b&&(q[b>>2]=1);c&&(q[c>>2]=4);Ya=!0;A=12288;return 1},Ba:(a,b,c,d)=>{if(62E3!=a)return A=12296,0;if(0!=d&&62004!=d)return A=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return A=12301,0;Xa(d?cb:null);Za=d;ab=b;$a=c;A=12288;return 1},va:(a,b)=>{if(62E3!=
a)return A=12296,0;A=12288;if(bb[b])return bb[b];switch(b){case 12371:a=N("Emscripten");break;case 12372:a=N("1.4 Emscripten EGL");break;case 12373:a=N("");break;case 12429:a=N("OpenGL_ES");break;default:return A=12300,0}return bb[b]=a},Ca:()=>{if(Ya)if(F)if(F.isContextLost())A=12302;else return A=12288,1;else A=12290;else A=12289;return 0},Da:(a,b)=>{if(62E3!=a)return A=12296,0;0==b?Lb(0,0):Lb(1,b);A=12288;return 1},Ja:a=>{if(62E3!=a)return A=12296,0;ab=$a=Za=0;Ya=!1;A=12288;return 1},Fa:()=>{A=
12288;return 1},Ea:()=>{A=12288;return 1},j:(a,b,c)=>{b=Rb(b,c);return Hd[a](...b)},e:(a,b,c)=>{b=Rb(b,c);return Hd[a](...b)},ta:(a,b,c)=>{b=Rb(b,c);return Hd[a](...b)},ba:()=>Date.now(),pa:()=>{if(!O.fullscreenEnabled())return-1;Ub(lc);var a=Yb[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},sa:()=>{Ub(mc);if(!document.exitPointerLock)return-1;document.exitPointerLock();return 0},
Na:function(a){if(X.has(a)){var b=X.get(a),c=X;c.oe[a]=void 0;c.Xe.push(a);0<b.readyState&&4>b.readyState&&b.abort()}},l:()=>devicePixelRatio,f:(a,b,c)=>{a=Q(a);if(!a)return-4;a=kc(a);x[b>>3]=a.width;x[c>>3]=a.height;return 0},V:(a,b)=>{if(0>a||a>=O.ze.length)return-5;if(!O.ze[a])return-7;nc(b,O.ze[a]);return 0},Z:()=>performance.now(),Ma:()=>O.ze.length,ua:(a,b)=>{q[a>>2]=screen.width;q[b>>2]=screen.height},Pd:a=>F.activeTexture(a),Od:oc,ka:(a,b)=>{F.ne.beginQueryEXT(a,J[b])},Md:(a,b,c)=>{F.bindAttribLocation(H[a],
b,c?y(n,c):"")},Ld:pc,Kd:(a,b)=>{F.bindFramebuffer(a,jb[b])},Jd:(a,b)=>{F.bindRenderbuffer(a,kb[b])},Id:(a,b)=>{F.bindTexture(a,lb[b])},Xd:a=>{F.bindVertexArray(mb[a])},Hd:(a,b,c,d)=>F.blendColor(a,b,c,d),Gd:qc,Fd:(a,b)=>F.blendEquationSeparate(a,b),Ed:rc,Dd:(a,b,c,d)=>F.blendFuncSeparate(a,b,c,d),Cd:sc,Bd:(a,b,c,d)=>{F.bufferSubData(a,b,n.subarray(d,d+c))},Ad:a=>F.checkFramebufferStatus(a),zd:tc,yd:uc,xd:a=>F.clearDepth(a),wd:a=>F.clearStencil(a),bb:(a,b)=>{F.mf.clipControlEXT(a,b)},vd:(a,b,c,d)=>
{F.colorMask(!!a,!!b,!!c,!!d)},ud:vc,td:(a,b,c,d,e,g,f,l)=>{F.compressedTexImage2D(a,b,c,d,e,g,n.subarray(l,l+f))},sd:(a,b,c,d,e,g,f,l,m)=>{F.compressedTexSubImage2D(a,b,c,d,e,g,f,n.subarray(m,m+l))},rd:(a,b,c,d,e,g,f,l)=>F.copyTexImage2D(a,b,c,d,e,g,f,l),qd:(a,b,c,d,e,g,f,l)=>F.copyTexSubImage2D(a,b,c,d,e,g,f,l),pd:wc,od:xc,nd:a=>F.cullFace(a),md:(a,b)=>{for(var c=0;c<a;c++){var d=q[b+4*c>>2],e=ib[d];e&&(F.deleteBuffer(e),e.name=0,ib[d]=null)}},ld:(a,b)=>{for(var c=0;c<a;++c){var d=q[b+4*c>>2],e=
jb[d];e&&(F.deleteFramebuffer(e),e.name=0,jb[d]=null)}},kd:a=>{if(a){var b=H[a];b?(F.deleteProgram(b),b.name=0,H[a]=null):K||=1281}},ma:(a,b)=>{for(var c=0;c<a;c++){var d=q[b+4*c>>2],e=J[d];e&&(F.ne.deleteQueryEXT(e),J[d]=null)}},jd:(a,b)=>{for(var c=0;c<a;c++){var d=q[b+4*c>>2],e=kb[d];e&&(F.deleteRenderbuffer(e),e.name=0,kb[d]=null)}},hd:a=>{if(a){var b=I[a];b?(F.deleteShader(b),I[a]=null):K||=1281}},gd:(a,b)=>{for(var c=0;c<a;c++){var d=q[b+4*c>>2],e=lb[d];e&&(F.deleteTexture(e),e.name=0,lb[d]=
null)}},Wd:(a,b)=>{for(var c=0;c<a;c++){var d=q[b+4*c>>2];F.deleteVertexArray(mb[d]);mb[d]=null}},fd:a=>F.depthFunc(a),ed:yc,dd:(a,b)=>F.depthRange(a,b),cd:(a,b)=>{F.detachShader(H[a],I[b])},bd:zc,ad:a=>{F.disableVertexAttribArray(a)},$c:(a,b,c)=>{F.drawArrays(a,b,c)},Sd:(a,b,c,d)=>{F.drawArraysInstanced(a,b,c,d)},Td:(a,b)=>{for(var c=Ac[a],d=0;d<a;d++)c[d]=q[b+4*d>>2];F.drawBuffers(c)},_c:Bc,Rd:(a,b,c,d,e)=>{F.drawElementsInstanced(a,b,c,d,e)},Yc:Cc,Xc:Dc,ja:a=>{F.ne.endQueryEXT(a)},Wc:()=>F.finish(),
Vc:()=>F.flush(),Uc:(a,b,c,d)=>{F.framebufferRenderbuffer(a,b,c,kb[d])},Tc:(a,b,c,d,e)=>{F.framebufferTexture2D(a,b,c,lb[d],e)},Sc:a=>F.frontFace(a),Rc:Ec,Pc:(a,b)=>{rb(a,b,"createFramebuffer",jb)},oa:(a,b)=>{for(var c=0;c<a;c++){var d=F.ne.createQueryEXT();if(!d){for(K||=1282;c<a;)q[b+4*c++>>2]=0;break}var e=qb(J);d.name=e;J[e]=d;q[b+4*c>>2]=e}},Oc:(a,b)=>{rb(a,b,"createRenderbuffer",kb)},Nc:(a,b)=>{rb(a,b,"createTexture",lb)},Vd:(a,b)=>{rb(a,b,"createVertexArray",mb)},Qc:a=>F.generateMipmap(a),
Mc:(a,b,c,d,e,g,f)=>Fc("getActiveAttrib",a,b,c,d,e,g,f),Lc:(a,b,c,d,e,g,f)=>Fc("getActiveUniform",a,b,c,d,e,g,f),Kc:(a,b,c,d)=>{a=F.getAttachedShaders(H[a]);var e=a.length;e>b&&(e=b);q[c>>2]=e;for(b=0;b<e;++b)q[d+4*b>>2]=I.indexOf(a[b])},Jc:Gc,Ic:(a,b)=>Hc(a,b,4),Hc:(a,b,c)=>{c?q[c>>2]=F.getBufferParameter(a,b):K||=1281},Gc:()=>{var a=F.getError()||K;K=0;return a},Fc:(a,b)=>Hc(a,b,2),Ec:(a,b,c,d)=>{a=F.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=
a.name|0;q[d>>2]=a},Dc:(a,b)=>Hc(a,b,0),Bc:(a,b,c,d)=>{a=F.getProgramInfoLog(H[a]);null===a&&(a="(unknown error)");b=0<b&&d?L(a,d,b):0;c&&(q[c>>2]=b)},Cc:(a,b,c)=>{if(c)if(a>=hb)K||=1281;else if(a=H[a],35716==b)a=F.getProgramInfoLog(a),null===a&&(a="(unknown error)"),q[c>>2]=a.length+1;else if(35719==b){if(!a.Ce){var d=F.getProgramParameter(a,35718);for(b=0;b<d;++b)a.Ce=Math.max(a.Ce,F.getActiveUniform(a,b).name.length+1)}q[c>>2]=a.Ce}else if(35722==b){if(!a.Ae)for(d=F.getProgramParameter(a,35721),
b=0;b<d;++b)a.Ae=Math.max(a.Ae,F.getActiveAttrib(a,b).name.length+1);q[c>>2]=a.Ae}else if(35381==b){if(!a.Be)for(d=F.getProgramParameter(a,35382),b=0;b<d;++b)a.Be=Math.max(a.Be,F.getActiveUniformBlockName(a,b).length+1);q[c>>2]=a.Be}else q[c>>2]=F.getProgramParameter(a,b);else K||=1281},ea:Ic,ga:Jc,da:Ic,fa:Jc,ha:(a,b,c)=>{c?q[c>>2]=F.ne.getQueryEXT(a,b):K||=1281},Ac:(a,b,c)=>{c?q[c>>2]=F.getRenderbufferParameter(a,b):K||=1281},yc:(a,b,c,d)=>{a=F.getShaderInfoLog(I[a]);null===a&&(a="(unknown error)");
b=0<b&&d?L(a,d,b):0;c&&(q[c>>2]=b)},xc:(a,b,c,d)=>{a=F.getShaderPrecisionFormat(a,b);q[c>>2]=a.rangeMin;q[c+4>>2]=a.rangeMax;q[d>>2]=a.precision},wc:(a,b,c,d)=>{if(a=F.getShaderSource(I[a]))b=0<b&&d?L(a,d,b):0,c&&(q[c>>2]=b)},zc:(a,b,c)=>{c?35716==b?(a=F.getShaderInfoLog(I[a]),null===a&&(a="(unknown error)"),q[c>>2]=a?a.length+1:0):35720==b?(a=F.getShaderSource(I[a]),q[c>>2]=a?a.length+1:0):q[c>>2]=F.getShaderParameter(I[a],b):K||=1281},vc:a=>{var b=nb[a];if(!b){switch(a){case 7939:b=N(Kc().join(" "));
break;case 7936:case 7937:case 37445:case 37446:(b=F.getParameter(a))||(K||=1280);b=b?N(b):0;break;case 7938:b=N(`OpenGL ES 2.0 (${F.getParameter(7938)})`);break;case 35724:b=F.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=N(b);break;default:K||=1280}nb[a]=b}return b},uc:(a,b,c)=>{c?u[c>>2]=F.getTexParameter(a,b):K||=1281},tc:(a,b,c)=>{c?q[c>>2]=F.getTexParameter(a,b):K||=1281},qc:Nc,
sc:(a,b,c)=>{Oc(a,b,c,2)},rc:(a,b,c)=>{Oc(a,b,c,0)},nc:(a,b,c)=>{c?q[c>>2]=F.getVertexAttribOffset(a,b):K||=1281},pc:(a,b,c)=>{Pc(a,b,c,2)},oc:(a,b,c)=>{Pc(a,b,c,5)},mc:(a,b)=>F.hint(a,b),lc:a=>(a=ib[a])?F.isBuffer(a):0,jc:a=>F.isEnabled(a),ic:a=>(a=jb[a])?F.isFramebuffer(a):0,hc:a=>(a=H[a])?F.isProgram(a):0,la:a=>(a=J[a])?F.ne.isQueryEXT(a):0,gc:a=>(a=kb[a])?F.isRenderbuffer(a):0,fc:a=>(a=I[a])?F.isShader(a):0,ec:a=>(a=lb[a])?F.isTexture(a):0,Ud:a=>(a=mb[a])?F.isVertexArray(a):0,dc:a=>F.lineWidth(a),
cc:Qc,bc:(a,b)=>{3317==a?ob=b:3314==a&&(pb=b);F.pixelStorei(a,b)},ab:(a,b)=>{F.vf.polygonModeWEBGL(a,b)},ac:(a,b)=>F.polygonOffset(a,b),cb:(a,b,c)=>{F.nf.polygonOffsetClampEXT(a,b,c)},ia:(a,b)=>{F.ne.queryCounterEXT(J[a],b)},$b:(a,b,c,d,e,g,f)=>{(f=Rc(g,e,c,d,f))?F.readPixels(a,b,c,d,e,g,f):K||=1280},_b:()=>{},Zb:(a,b,c,d)=>F.renderbufferStorage(a,b,c,d),Yb:(a,b)=>{F.sampleCoverage(a,!!b)},Xb:(a,b,c,d)=>F.scissor(a,b,c,d),Wb:()=>{K||=1280},Vb:Sc,Ub:(a,b,c)=>F.stencilFunc(a,b,c),Tb:(a,b,c,d)=>F.stencilFuncSeparate(a,
b,c,d),Sb:a=>F.stencilMask(a),Rb:(a,b)=>F.stencilMaskSeparate(a,b),Qb:(a,b,c)=>F.stencilOp(a,b,c),Pb:(a,b,c,d)=>F.stencilOpSeparate(a,b,c,d),Ob:(a,b,c,d,e,g,f,l,m)=>{m=m?Rc(l,f,d,e,m):null;F.texImage2D(a,b,c,d,e,g,f,l,m)},Nb:(a,b,c)=>F.texParameterf(a,b,c),Mb:(a,b,c)=>{F.texParameterf(a,b,u[c>>2])},Lb:(a,b,c)=>F.texParameteri(a,b,c),Kb:(a,b,c)=>{F.texParameteri(a,b,q[c>>2])},Jb:(a,b,c,d,e,g,f,l,m)=>{m=m?Rc(l,f,e,g,m):null;F.texSubImage2D(a,b,c,d,e,g,f,l,m)},Ib:Tc,Hb:(a,b,c)=>{if(288>=b)for(var d=
Uc[b],e=0;e<b;++e)d[e]=u[c+4*e>>2];else d=u.subarray(c>>2,c+4*b>>2);F.uniform1fv(W(a),d)},Gb:(a,b)=>{F.uniform1i(W(a),b)},Fb:(a,b,c)=>{if(288>=b)for(var d=Vc[b],e=0;e<b;++e)d[e]=q[c+4*e>>2];else d=q.subarray(c>>2,c+4*b>>2);F.uniform1iv(W(a),d)},Eb:(a,b,c)=>{F.uniform2f(W(a),b,c)},Db:(a,b,c)=>{if(144>=b){b*=2;for(var d=Uc[b],e=0;e<b;e+=2)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2]}else d=u.subarray(c>>2,c+8*b>>2);F.uniform2fv(W(a),d)},Cb:(a,b,c)=>{F.uniform2i(W(a),b,c)},Bb:(a,b,c)=>{if(144>=b){b*=2;for(var d=
Vc[b],e=0;e<b;e+=2)d[e]=q[c+4*e>>2],d[e+1]=q[c+(4*e+4)>>2]}else d=q.subarray(c>>2,c+8*b>>2);F.uniform2iv(W(a),d)},Ab:Wc,zb:(a,b,c)=>{if(96>=b){b*=3;for(var d=Uc[b],e=0;e<b;e+=3)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2]}else d=u.subarray(c>>2,c+12*b>>2);F.uniform3fv(W(a),d)},yb:(a,b,c,d)=>{F.uniform3i(W(a),b,c,d)},xb:(a,b,c)=>{if(96>=b){b*=3;for(var d=Vc[b],e=0;e<b;e+=3)d[e]=q[c+4*e>>2],d[e+1]=q[c+(4*e+4)>>2],d[e+2]=q[c+(4*e+8)>>2]}else d=q.subarray(c>>2,c+12*b>>2);F.uniform3iv(W(a),
d)},wb:(a,b,c,d,e)=>{F.uniform4f(W(a),b,c,d,e)},vb:(a,b,c)=>{if(72>=b){var d=Uc[4*b],e=u;c>>=2;b*=4;for(var g=0;g<b;g+=4){var f=c+g;d[g]=e[f];d[g+1]=e[f+1];d[g+2]=e[f+2];d[g+3]=e[f+3]}}else d=u.subarray(c>>2,c+16*b>>2);F.uniform4fv(W(a),d)},ub:(a,b,c,d,e)=>{F.uniform4i(W(a),b,c,d,e)},tb:(a,b,c)=>{if(72>=b){b*=4;for(var d=Vc[b],e=0;e<b;e+=4)d[e]=q[c+4*e>>2],d[e+1]=q[c+(4*e+4)>>2],d[e+2]=q[c+(4*e+8)>>2],d[e+3]=q[c+(4*e+12)>>2]}else d=q.subarray(c>>2,c+16*b>>2);F.uniform4iv(W(a),d)},sb:(a,b,c,d)=>{if(72>=
b){b*=4;for(var e=Uc[b],g=0;g<b;g+=4)e[g]=u[d+4*g>>2],e[g+1]=u[d+(4*g+4)>>2],e[g+2]=u[d+(4*g+8)>>2],e[g+3]=u[d+(4*g+12)>>2]}else e=u.subarray(d>>2,d+16*b>>2);F.uniformMatrix2fv(W(a),!!c,e)},rb:(a,b,c,d)=>{if(32>=b){b*=9;for(var e=Uc[b],g=0;g<b;g+=9)e[g]=u[d+4*g>>2],e[g+1]=u[d+(4*g+4)>>2],e[g+2]=u[d+(4*g+8)>>2],e[g+3]=u[d+(4*g+12)>>2],e[g+4]=u[d+(4*g+16)>>2],e[g+5]=u[d+(4*g+20)>>2],e[g+6]=u[d+(4*g+24)>>2],e[g+7]=u[d+(4*g+28)>>2],e[g+8]=u[d+(4*g+32)>>2]}else e=u.subarray(d>>2,d+36*b>>2);F.uniformMatrix3fv(W(a),
!!c,e)},qb:Xc,pb:Yc,ob:a=>{F.validateProgram(H[a])},nb:(a,b)=>F.vertexAttrib1f(a,b),mb:(a,b)=>{F.vertexAttrib1f(a,u[b>>2])},lb:(a,b,c)=>F.vertexAttrib2f(a,b,c),kb:(a,b)=>{F.vertexAttrib2f(a,u[b>>2],u[b+4>>2])},jb:(a,b,c,d)=>F.vertexAttrib3f(a,b,c,d),ib:(a,b)=>{F.vertexAttrib3f(a,u[b>>2],u[b+4>>2],u[b+8>>2])},hb:(a,b,c,d,e)=>F.vertexAttrib4f(a,b,c,d,e),gb:(a,b)=>{F.vertexAttrib4f(a,u[b>>2],u[b+4>>2],u[b+8>>2],u[b+12>>2])},Qd:(a,b)=>{F.vertexAttribDivisor(a,b)},fb:Zc,eb:$c,q:()=>0,Pa:()=>!0,qa:(a,b,
c)=>ad(a,{Ne:q[c>>2],Ee:q[c+4>>2],pf:q[c+8>>2],kf:b,we:q[c+12>>2],Ve:q[c+16>>2]}),Q:(a,b)=>{a=Q(a);return a?a.requestPointerLock?Vb()?mc(a):b?(Tb(mc,2,[a]),1):-2:-1:-4},Ta:()=>{sa("OOM")},X:a=>{eval(a?y(n,a):"")},W:bd,y:(a,b,c)=>"undefined"==typeof onbeforeunload?-1:1!==c?-5:cd(a,b),K:(a,b,c,d)=>dd(a,b,c,d,12,"blur"),k:dc,o:(a,b,c)=>{a=Q(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},L:(a,b,c,d)=>dd(a,b,c,d,13,"focus"),A:(a,b,c,d)=>{if(!O.fullscreenEnabled())return-1;a=Q(a);
if(!a)return-4;ed(a,b,c,d,"webkitfullscreenchange");return ed(a,b,c,d,"fullscreenchange")},U:(a,b,c)=>bd()?-1:fd(a,b,c,26,"gamepadconnected"),T:(a,b,c)=>bd()?-1:fd(a,b,c,27,"gamepaddisconnected"),D:(a,b,c,d)=>gd(a,b,c,d,2,"keydown"),B:(a,b,c,d)=>gd(a,b,c,d,1,"keypress"),C:(a,b,c,d)=>gd(a,b,c,d,3,"keyup"),Qa:(a,b,c)=>{a=T(a);Mb(a,b,c)},t:(a,b,c,d)=>jd(a,b,c,d,5,"mousedown"),O:(a,b,c,d)=>jd(a,b,c,d,33,"mouseenter"),N:(a,b,c,d)=>jd(a,b,c,d,34,"mouseleave"),u:(a,b,c,d)=>jd(a,b,c,d,8,"mousemove"),s:(a,
b,c,d)=>jd(a,b,c,d,6,"mouseup"),F:(a,b,c,d)=>document.body?.requestPointerLock?(a=Q(a))?kd(a,b,c,d):-4:-1,v:(a,b,c,d)=>ld(a,b,c,d),G:(a,b,c,d)=>md(a,b,c,d,25,"touchcancel"),I:(a,b,c,d)=>md(a,b,c,d,23,"touchend"),H:(a,b,c,d)=>md(a,b,c,d,24,"touchmove"),J:(a,b,c,d)=>md(a,b,c,d,22,"touchstart"),z:(a,b,c)=>nd(a,b,c),M:(a,b,c,d)=>(a=Q(a))?"undefined"!=typeof a.onwheel?od(a,b,c,d):-1:-4,ra:a=>document.title=a?y(n,a):"",p:()=>{throw"Please compile your program with async support in order to use asynchronous operations like emscripten_sleep";
},Oa:function(a,b,c,d,e){function g(w){if(G)w();else if(!na)try{w(),Oa()}catch(ha){La(ha)}}var f=a+108,l=r[f+36>>2],m=r[f+40>>2],v=r[f+44>>2],E=r[f+48>>2],D=r[f+52>>2],G=!!(D&64),R=w=>{g(()=>{l?T(l)(w):b?.(w)})},Y=w=>{g(()=>{v?T(v)(w):d?.(w)})},S=w=>{g(()=>{m?T(m)(w):c?.(w)})},Z=w=>{g(()=>{E?T(E)(w):e?.(w)})},U=w=>{td(w,R,S,Y,Z)},ka=(w,ha)=>{vd(w,ha.response,Da=>{g(()=>{l?T(l)(Da):b?.(Da)})},Da=>{g(()=>{l?T(l)(Da):b?.(Da)})})},da=w=>{td(w,ka,S,Y,Z)},t=Ka(f+0),fa=!!(D&16),B=!!(D&4);D=!!(D&32);if("EM_IDB_STORE"===
t)U=r[f+84>>2],vd(a,n.slice(U,U+r[f+88>>2]),R,S);else if("EM_IDB_DELETE"===t)xd(a,R,S);else if(fa){if(D)return 0;td(a,B?ka:R,S,Y,Z)}else wd(a,R,D?S:B?da:U);return a},Wa:(a,b)=>{var c=0,d=0,e;for(e of Ad()){var g=b+c;r[a+d>>2]=g;c+=L(e,g,Infinity)+1;d+=4}return 0},Xa:(a,b)=>{var c=Ad();r[a>>2]=c.length;a=0;for(var d of c)a+=vb(d)+1;r[b>>2]=a;return 0},_:()=>52,Za:()=>52,Va:function(){return 70},$:(a,b,c,d)=>{for(var e=0,g=0;g<c;g++){var f=r[b>>2],l=r[b+4>>2];b+=8;for(var m=0;m<l;m++){var v=a,E=n[f+
m],D=Bd[v];0===E||10===E?((1===v?ja:la)(y(D)),D.length=0):D.push(E)}e+=l}r[d>>2]=e;return 0},ca:oc,a:pc,Sa:qc,Ya:rc,b:sc,kc:tc,Ra:uc,E:vc,na:wc,R:xc,g:yc,n:zc,Ia:Bc,m:Cc,r:Dc,c:Ec,x:Gc,h:Nc,Nd:Qc,P:Sc,i:Tc,db:Wc,d:Xc,id:Yc,w:Zc,Zc:$c,Y:function(){var a=new Uint32Array(1);crypto.getRandomValues(a);return a[0]}};function Kd(a=[]){var b=Id;a.unshift(ba);var c=a.length,d=Zb(4*(c+1)),e=d;a.forEach(f=>{r[e>>2]=$b(f);e+=4});r[e>>2]=0;try{var g=b(c,d);Na(g)}catch(f){La(f)}}
function Ld(a=aa){function b(){h.calledRun=!0;if(!na){Md.Zd();h.onRuntimeInitialized?.();h.noInitialRun||Kd(a);if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var c=h.postRun.shift();za.push(c)}ya(za)}}if(0<Ca)Ea=Ld;else{if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Ba();ya(Aa);0<Ca?Ea=Ld:h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),1);b()},1)):b()}}var Md;
(async function(){function a(c){Md=c.exports;pa=Md.Yd;c=pa.buffer;k=new Int8Array(c);p=new Int16Array(c);n=new Uint8Array(c);qa=new Uint16Array(c);q=new Int32Array(c);r=new Uint32Array(c);u=new Float32Array(c);x=new Float64Array(c);ra=new BigInt64Array(c);new BigUint64Array(c);hc=Md.$d;c=Md;h._main=Id=c._d;M=c.ae;ud=c.be;bc=c.ce;Zb=c.de;ac=c.ee;Fa();return Md}Ga();var b={a:Jd};if(h.instantiateWasm)return new Promise(c=>{h.instantiateWasm(b,(d,e)=>{c(a(d,e))})});ta??=h.locateFile?h.locateFile("index.wasm",
ea):ea+"index.wasm";return a((await wa(b)).instance)})();Ld();
