var h;h||=typeof Module != 'undefined' ? Module : {};var aa=Object.assign({},h),ba=[],da="./this.program",ea="",fa;"undefined"!=typeof document&&document.currentScript&&(ea=document.currentScript.src);ea=ea.startsWith("blob:")?"":ea.slice(0,ea.replace(/[?#].*/,"").lastIndexOf("/")+1);fa=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};var ha=h.print||console.log.bind(console),ia=h.printErr||console.error.bind(console);
Object.assign(h,aa);aa=null;h.arguments&&(ba=h.arguments);h.thisProgram&&(da=h.thisProgram);var ja=h.wasmBinary,ka,ma=!1,na,k,m,p,oa,q,r,u,pa,w,qa=0,ra=null;function sa(){qa++;h.monitorRunDependencies?.(qa)}function ta(){qa--;h.monitorRunDependencies?.(qa);if(0==qa&&ra){var a=ra;ra=null;a()}}function ua(a){h.onAbort?.(a);a="Aborted("+a+")";ia(a);ma=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var va;
async function wa(a){if(!ja)try{var b=await fa(a);return new Uint8Array(b)}catch{}if(a==va&&ja)a=new Uint8Array(ja);else throw"both async and sync fetching of the wasm failed";return a}async function xa(a,b){try{var c=await wa(a);return await WebAssembly.instantiate(c,b)}catch(d){ia(`failed to asynchronously prepare wasm: ${d}`),ua(d)}}
async function ya(a){var b=va;if(!ja&&"function"==typeof WebAssembly.instantiateStreaming)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){ia(`wasm streaming compile failed: ${d}`),ia("falling back to ArrayBuffer instantiation")}return xa(b,a)}
var Ca={7792527:()=>"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?!0:!1,7792674:()=>"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?!0:!1,7792908:a=>{"undefined"===typeof h.SDL2&&(h.SDL2={});var b=h.SDL2;a?b.capture={}:b.audio={};b.ke||("undefined"!==typeof AudioContext?b.ke=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.ke=new webkitAudioContext),b.ke&&
"undefined"===typeof navigator.userActivation&&za(b.ke));return void 0===b.ke?-1:0},7793460:()=>h.SDL2.ke.sampleRate,7793528:(a,b,c,d)=>{function e(){}function g(l){void 0!==f.capture.se&&(clearInterval(f.capture.se),f.capture.se=void 0,f.capture.xe=void 0);f.capture.Re=f.ke.createMediaStreamSource(l);f.capture.re=f.ke.createScriptProcessor(b,a,1);f.capture.re.onaudioprocess=function(n){void 0!==f&&void 0!==f.capture&&(n.outputBuffer.getChannelData(0).fill(0),f.capture.Le=n.inputBuffer,Aa(c,[d]))};
f.capture.Re.connect(f.capture.re);f.capture.re.connect(f.ke.destination);f.capture.stream=l}var f=h.SDL2;f.capture.xe=f.ke.createBuffer(a,b,f.ke.sampleRate);f.capture.xe.getChannelData(0).fill(0);f.capture.se=setInterval(function(){f.capture.Le=f.capture.xe;Aa(c,[d])},b/f.ke.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(g).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,
video:!1},g,e)},7795221:(a,b,c,d)=>{var e=h.SDL2;e.audio.re=e.ke.createScriptProcessor(b,0,a);e.audio.re.onaudioprocess=function(g){void 0!==e&&void 0!==e.audio&&(void 0!==e.audio.se&&(clearInterval(e.audio.se),e.audio.se=void 0,e.audio.xe=void 0),e.audio.De=g.outputBuffer,Aa(c,[d]))};e.audio.re.connect(e.ke.destination);"suspended"===e.ke.state&&(e.audio.xe=e.ke.createBuffer(a,b,e.ke.sampleRate),e.audio.xe.getChannelData(0).fill(0),e.audio.se=setInterval(function(){"undefined"!==typeof navigator.userActivation&&
navigator.userActivation.hasBeenActive&&e.ke.resume();e.audio.De=e.audio.xe;Aa(c,[d]);e.audio.De=void 0},b/e.ke.sampleRate*1E3))},7796396:(a,b)=>{for(var c=h.SDL2,d=c.capture.Le.numberOfChannels,e=0;e<d;++e){var g=c.capture.Le.getChannelData(e);if(g.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+g.length+" samples vs expected "+b+" samples!";if(1==d)for(var f=0;f<b;++f)Ba(a+4*f,g[f]);else for(f=0;f<b;++f)Ba(a+4*(f*d+e),g[f])}},7797001:(a,b)=>{var c=h.SDL2;a>>>=2;for(var d=
c.audio.De.numberOfChannels,e=0;e<d;++e){var g=c.audio.De.getChannelData(e);if(g.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+g.length+" samples vs expected "+b+" samples!";for(var f=0;f<b;++f)g[f]=u[a+(f*d+e)]}},7797490:a=>{var b=h.SDL2;if(a){void 0!==b.capture.se&&clearInterval(b.capture.se);if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c])}void 0!==b.capture.re&&(b.capture.re.onaudioprocess=
function(){},b.capture.re.disconnect());void 0!==b.capture.Re&&b.capture.Re.disconnect();b.capture=void 0}else void 0!=b.audio.re&&b.audio.re.disconnect(),void 0!==b.audio.se&&clearInterval(b.audio.se),b.audio=void 0;void 0!==b.ke&&void 0===b.audio&&void 0===b.capture&&(b.ke.close(),b.ke=void 0)},7798496:(a,b,c)=>{h.SDL2||(h.SDL2={});var d=h.SDL2;d.jf!==h.canvas&&(d.Ce=h.createContext(h.canvas,!1,!0),d.jf=h.canvas);if(d.w!==a||d.h!==b||d.wf!==d.Ce)d.image=d.Ce.createImageData(a,b),d.w=a,d.h=b,d.wf=
d.Ce;a=d.image.data;b=c/4;var e=0;if("undefined"!==typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var g=q[b];a[e]=g&255;a[e+1]=g>>8&255;a[e+2]=g>>16&255;a[e+3]=255;b++;e+=4}else if(d.nf!==a&&(d.mf=new Int32Array(a.buffer),d.pf=new Uint8Array(a.buffer),d.nf=a),a=d.mf,c=a.length,a.set(q.subarray(b,b+c)),a=d.pf,b=3,e=b+4*c,0==c%8)for(;b<e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|
0;else for(;b<e;)a[b]=255,b=b+4|0;d.Ce.putImageData(d.image,0,0)},7799964:(a,b,c,d,e)=>{var g=document.createElement("canvas");g.width=a;g.height=b;var f=g.getContext("2d");a=f.createImageData(a,b);b=a.data;e/=4;var l=0,n;if("undefined"!==typeof CanvasPixelArray&&b instanceof CanvasPixelArray)for(n=b.length;l<n;){var v=q[e];b[l]=v&255;b[l+1]=v>>8&255;b[l+2]=v>>16&255;b[l+3]=v>>24&255;e++;l+=4}else b=new Int32Array(b.buffer),n=b.length,b.set(q.subarray(e,e+n));f.putImageData(a,0,0);c=0===c&&0===d?
"url("+g.toDataURL()+"), auto":"url("+g.toDataURL()+") "+c+" "+d+", auto";d=x(c.length+1);y(c,d,c.length+1);return d},7800952:a=>{h.canvas&&(h.canvas.style.cursor=a?z(m,a):"")},7801035:()=>{h.canvas&&(h.canvas.style.cursor="none")},7801104:()=>window.innerWidth,7801134:()=>window.innerHeight};class Da{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Ea=a=>{for(;0<a.length;)a.shift()(h)},Ga=[],Ha=[],Ia=()=>{var a=h.preRun.shift();Ha.unshift(a)},Ja=h.noExitRuntime||!0;function Ba(a,b){var c="float";c.endsWith("*")&&(c="*");switch(c){case "i1":k[a]=b;break;case "i8":k[a]=b;break;case "i16":p[a>>1]=b;break;case "i32":q[a>>2]=b;break;case "i64":pa[a>>3]=BigInt(b);break;case "float":u[a>>2]=b;break;case "double":w[a>>3]=b;break;case "*":r[a>>2]=b;break;default:ua(`invalid type for setValue: ${c}`)}}
var Ka="undefined"!=typeof TextDecoder?new TextDecoder:void 0,z=(a,b=0,c=NaN)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ka)return Ka.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var f=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|f:(e&7)<<18|g<<12|f<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
La=(a,b)=>a?z(m,a,b):"",Ma=a=>{if(!(a instanceof Da||"unwind"==a))throw a;},Na=a=>{na=a;Ja||(h.onExit?.(a),ma=!0);throw new Da(a);},Oa=a=>{na=a;Na(a)},Pa=()=>{if(!Ja)try{var a=na;na=a;Na(a)}catch(b){Ma(b)}},Qa=!1,Ra=!1,Sa=[];
function Ta(){function a(){var c=h.canvas;Ra=document.pointerLockElement===c||document.mozPointerLockElement===c||document.webkitPointerLockElement===c||document.msPointerLockElement===c}if(!Ua){Ua=!0;var b=h.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),b.exitPointerLock=
b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",c=>{!Ra&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}var Va=!1,Wa=void 0,Xa=void 0;
function Ya(){if(!Qa)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var Za=[];function $a(){var a=h.canvas;Za.forEach(b=>b(a.width,a.height))}
function ab(a,b,c){b&&c?(a.Df=b,a.vf=c):(b=a.Df,c=a.vf);var d=b,e=c;0<h.forcedAspectRatio&&(d/e<h.forcedAspectRatio?d=Math.round(e*h.forcedAspectRatio):e=Math.round(d/h.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/d,screen.height/e);d=Math.round(d*g);e=Math.round(e*g)}Xa?(a.width!=d&&(a.width=
d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var Ua,B=12288,bb=!1,cb=0,db=0,eb=0,E={alpha:!1,depth:!1,stencil:!1,antialias:!1},fb={},gb,H,hb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,g)=>b.drawArraysInstancedANGLE(c,d,e,g),a.drawElementsInstanced=(c,d,e,g,f)=>b.drawElementsInstancedANGLE(c,d,e,g,f))},ib=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),
a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},jb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},kb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},lb=1,mb=[],I=[],nb=[],ob=[],pb=[],J=[],qb=[],rb=[],sb=[],tb={},ub=4,vb=0,wb=a=>{for(var b=lb++,c=a.length;c<b;c++)a[c]=null;return b},xb=(a,b,c,d)=>{for(var e=0;e<a;e++){var g=H[c](),f=g&&wb(d);g?(g.name=f,d[f]=g):K||=1282;q[b+4*e>>2]=f}},zb=(a,b)=>{a.qe||(a.qe=a.getContext,a.getContext=function(d,e){e=a.qe(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?yb(c,b):0},yb=(a,b)=>
{var c=wb(rb),d={handle:c,attributes:b,version:b.df,ue:a};a.canvas&&(a.canvas.ye=d);rb[c]=d;("undefined"==typeof b.rf||b.rf)&&Ab(d);return c},Cb=a=>{Bb=rb[a];h.ctx=H=Bb?.ue},Ab=a=>{a||=Bb;if(!a.xf){a.xf=!0;var b=a.ue;b.Pf=b.getExtension("WEBGL_multi_draw");b.tf=b.getExtension("EXT_polygon_offset_clamp");b.sf=b.getExtension("EXT_clip_control");b.Cf=b.getExtension("WEBGL_polygon_mode");hb(b);ib(b);jb(b);b.te=b.getExtension("EXT_disjoint_timer_query");kb(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||
b.getExtension(c)})}},Db={},K,Bb,Eb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},y=(a,b,c)=>{var d=m;if(!(0<c))return 0;var e=b;c=b+c-1;for(var g=0;g<a.length;++g){var f=a.charCodeAt(g);if(55296<=f&&57343>=f){var l=a.charCodeAt(++g);f=65536+((f&1023)<<10)|l&1023}if(127>=f){if(b>=c)break;d[b++]=f}else{if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6}else{if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12}else{if(b+3>=c)break;d[b++]=
240|f>>18;d[b++]=128|f>>12&63}d[b++]=128|f>>6&63}d[b++]=128|f&63}}d[b]=0;return b-e},Fb=a=>{var b=Eb(a)+1,c=x(b);c&&y(a,c,b);return c},Xb=(a,b,c,d,e)=>{function g(){return f<Hb?(Pa(),!1):!0}Ib=a;Jb=d;var f=Hb;Kb=!1;Lb=function(){if(!ma)if(0<Mb.length){var l=Mb.shift();l.Lf(l.Ef);if(Nb){var n=Nb,v=0==n%1?n-1:Math.floor(n);Nb=l.Hf?v:(8*n+(v+.5))/9}h.setStatus&&(l=h.statusMessage||"Please wait...",n=Nb??0,v=Ob.Kf??0,n?n<v?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(l):h.setStatus(""));
g()&&setTimeout(Lb,0)}else if(g())if(Pb=Pb+1|0,1==Qb&&1<Rb&&0!=Pb%Rb)Sb();else{0==Qb&&(Tb=performance.now());a:if(!ma){for(l of Ub)if(!1===l())break a;if(!ma)try{a(),Pa()}catch(D){Ma(D)}for(n of Vb)n()}g()&&Sb()}};e||(0<b?Wb(0,1E3/b):Wb(1,1),Sb());if(c)throw"unwind";},Kb=!1,Sb=null,Hb=0,Ib=null,Jb=0,Qb=0,Rb=0,Pb=0,Mb=[],Ub=[],Vb=[],Yb=0;
function Zb(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Yb)Yb=b+1E3/60;else for(;b+2>=Yb;)Yb+=1E3/60;setTimeout(a,Math.max(Yb-b,0))}}
var Ob={},Lb,Nb,Tb,$b,Wb=(a,b)=>{Qb=a;Rb=b;if(Ib)if(Kb||=!0,0==a)Sb=function(){setTimeout(Lb,Math.max(0,Tb+b-performance.now())|0)};else if(1==a)Sb=function(){Zb(Lb)};else if(2==a){if("undefined"==typeof $b)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);$b=d=>{c.push(d);postMessage("setimmediate","*")}}else $b=setImmediate;Sb=function(){$b(Lb)}}},ac=[],bc=(a,b)=>{ac.length=
0;for(var c;c=m[a++];){var d=105!=c;d&=112!=c;b+=d&&b%8?4:0;ac.push(112==c?r[b>>2]:106==c?pa[b>>3]:105==c?q[b>>2]:w[b>>3]);b+=d?8:4}return ac};function cc(a){var b=L.oe[a];b.target.removeEventListener(b.le,b.bf,b.me);L.oe.splice(a,1)}function dc(a,b,c){function d(g,f){if(g.length!=f.length)return!1;for(var l in g)if(g[l]!=f[l])return!1;return!0}for(var e of L.ve)if(e.Ue==a&&d(e.$e,c))return;L.ve.push({Ue:a,ff:b,$e:c});L.ve.sort((g,f)=>g.ff<f.ff)}function ec(a){L.ve=L.ve.filter(b=>b.Ue!=a)}
function fc(){return navigator.userActivation?navigator.userActivation.isActive:L.Pe&&L.kf.Ae}function gc(){if(fc()){var a=L.ve;L.ve=[];for(var b of a)b.Ue(...b.$e)}}function M(a){if(!a.target)return-4;if(a.ne)a.bf=function(c){++L.Pe;L.kf=a;gc();a.pe(c);gc();--L.Pe},a.target.addEventListener(a.le,a.bf,a.me),L.oe.push(a);else for(var b=0;b<L.oe.length;++b)L.oe[b].target==a.target&&L.oe[b].le==a.le&&cc(b--);return 0}
function hc(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var L={Ff:0,Oe:0,Qe:0,Je:0,Ze:0,We:0,Me:0,Jf:0,Qf:0,If:0,Ne:0,Se:0,Ye:0,Ve:0,Nf(a,b,c){k.set(k.subarray(b,b+c),a)},Rf(){for(;L.oe.length;)cc(L.oe.length-1);L.ve=[]},Pe:0,ve:[],oe:[],Af:(a,b)=>{for(var c=0;c<L.oe.length;++c)L.oe[c].target!=a||b&&b!=L.oe[c].le||cc(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},ic={},jc=[0,document,window],N=a=>{a=2<a?a?z(m,a):"":a;return jc[a]||document.querySelector(a)},lc=a=>{var b=Eb(a)+1,c=kc(b);y(a,c,b);return c},
oc=a=>{var b=mc(),c=kc(8),d=c+4;a=lc(a.id);if(a=N(a))q[c>>2]=a.width,q[d>>2]=a.height;c=[q[c>>2],q[d>>2]];nc(b);return c},pc=(a,b,c)=>{a=N(a);if(!a)return-4;a.width=b;a.height=c;return 0},qc=(a,b,c)=>{if(a.Gf){var d=mc();a=lc(a.id);pc(a,b,c);nc(d)}else a.width=b,a.height=c},rc=[],sc,O=a=>{var b=rc[a];b||(a>=rc.length&&(rc.length=a+1),rc[a]=b=sc.get(a));return b},tc=a=>{function b(){document.fullscreenElement||document.webkitFullscreenElement||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",
b),qc(a,d,e),a.style.width=g,a.style.height=f,a.style.backgroundColor=l,n||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=n,a.style.paddingLeft=v,a.style.paddingRight=D,a.style.paddingTop=G,a.style.paddingBottom=F,a.style.marginLeft=U,a.style.marginRight=ca,a.style.marginTop=V,a.style.marginBottom=R,document.body.style.margin=Y,document.documentElement.style.overflow=la,document.body.scroll=t,a.style.we=W,a.ye&&a.ye.ue.viewport(0,0,d,e),ic.Be&&O(ic.Be)(37,0,ic.af))}
var c=oc(a),d=c[0],e=c[1],g=a.style.width,f=a.style.height,l=a.style.backgroundColor,n=document.body.style.backgroundColor,v=a.style.paddingLeft,D=a.style.paddingRight,G=a.style.paddingTop,F=a.style.paddingBottom,U=a.style.marginLeft,ca=a.style.marginRight,V=a.style.marginTop,R=a.style.marginBottom,Y=document.body.style.margin,la=document.documentElement.style.overflow,t=document.body.scroll,W=a.style.we;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",
b)},uc=(a,b,c)=>{a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"},vc=a=>0>jc.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},wc=(a,b)=>{if(0!=b.Te||0!=b.Ke){tc(a);var c=b.Bf?innerWidth:screen.width,d=b.Bf?innerHeight:screen.height,e=vc(a),g=e.width;e=e.height;var f=oc(a),l=f[0];f=f[1];3==b.Te?(uc(a,(d-e)/2,(c-g)/2),c=g,d=e):2==b.Te&&(c*f<l*d?(g=f*c/l,uc(a,(d-g)/2,0),d=g):(g=l*d/f,uc(a,0,(c-g)/2),c=g));var n;(n=a.style).backgroundColor||(n.backgroundColor=
"black");let v;(v=document.body.style).backgroundColor||(v.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.uf&&(a.style.we="optimizeSpeed",a.style.we="-moz-crisp-edges",a.style.we="-o-crisp-edges",a.style.we="-webkit-optimize-contrast",a.style.we="optimize-contrast",a.style.we="crisp-edges",a.style.we="pixelated");n=2==b.Ke?devicePixelRatio:1;0!=b.Ke&&(c=c*n|0,d=d*n|0,qc(a,c,d),a.ye&&a.ye.ue.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);
else return L.fullscreenEnabled()?-3:-1;ic=b;b.Be&&O(b.Be)(37,0,b.af);return 0},xc=a=>{if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?-3:-1;return 0},yc=(a,b)=>{w[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)w[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)w[a+8*c+528>>3]="object"==typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)k[a+c+1040]="object"==typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];
k[a+1104]=b.connected;q[a+1108>>2]=b.index;q[a+8>>2]=b.axes.length;q[a+12>>2]=b.buttons.length;y(b.id,a+1112,64);y(b.mapping,a+1176,64)},zc=(a,b)=>{H.attachShader(I[a],J[b])},Ac=(a,b)=>{H.bindBuffer(a,mb[b])},Bc=a=>H.blendEquation(a),Cc=(a,b)=>H.blendFunc(a,b),Dc=(a,b,c,d)=>{H.bufferData(a,c?m.subarray(c,c+b):b,d)},Ec=a=>H.clear(a),Fc=(a,b,c,d)=>H.clearColor(a,b,c,d),Gc=a=>{H.compileShader(J[a])},Hc=()=>{var a=wb(I),b=H.createProgram();b.name=a;b.Ie=b.Ge=b.He=0;b.Xe=1;I[a]=b;return a},Ic=a=>{var b=
wb(J);J[b]=H.createShader(a);return b},Jc=a=>{if(a){var b=I[a];b?(H.deleteProgram(b),b.name=0,I[a]=null):K||=1281}},Kc=a=>{H.depthMask(!!a)},Lc=a=>H.disable(a),Mc=[],Nc=(a,b,c,d)=>{H.drawElements(a,b,c,d)},Oc=a=>H.enable(a),Pc=a=>{H.enableVertexAttribArray(a)},Qc=(a,b)=>{xb(a,b,"createBuffer",mb)},Rc=(a,b,c,d,e,g,f,l)=>{b=I[b];if(a=H[a](b,c))d=l&&y(a.name,l,d),e&&(q[e>>2]=d),g&&(q[g>>2]=a.size),f&&(q[f>>2]=a.type)},Sc=(a,b)=>H.getAttribLocation(I[a],b?z(m,b):""),P=(a,b)=>{r[a>>2]=b;r[a+4>>2]=(b-r[a>>
2])/4294967296},Tc=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&(K||=1280);return;case 36345:d=0;break;case 34466:var e=H.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=H.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":K||=1280;return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:K||=1280;return}else{if(e instanceof
Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:q[b+4*a>>2]=e[a];break;case 2:u[b+4*a>>2]=e[a];break;case 4:k[b+a]=e[a]?1:0}return}try{d=e.name|0}catch(g){K||=1280;ia(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${g})`);return}}break;default:K||=1280;ia(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${e} of type ${typeof e}!`);return}switch(c){case 1:P(b,
d);break;case 0:q[b>>2]=d;break;case 2:u[b>>2]=d;break;case 4:k[b]=d?1:0}}else K||=1281},Uc=(a,b,c,d)=>{a=H.getProgramInfoLog(I[a]);null===a&&(a="(unknown error)");b=0<b&&d?y(a,d,b):0;c&&(q[c>>2]=b)},Vc=(a,b,c)=>{if(c)if(a>=lb)K||=1281;else if(a=I[a],35716==b)a=H.getProgramInfoLog(a),null===a&&(a="(unknown error)"),q[c>>2]=a.length+1;else if(35719==b){if(!a.Ie){var d=H.getProgramParameter(a,35718);for(b=0;b<d;++b)a.Ie=Math.max(a.Ie,H.getActiveUniform(a,b).name.length+1)}q[c>>2]=a.Ie}else if(35722==
b){if(!a.Ge)for(d=H.getProgramParameter(a,35721),b=0;b<d;++b)a.Ge=Math.max(a.Ge,H.getActiveAttrib(a,b).name.length+1);q[c>>2]=a.Ge}else if(35381==b){if(!a.He)for(d=H.getProgramParameter(a,35382),b=0;b<d;++b)a.He=Math.max(a.He,H.getActiveUniformBlockName(a,b).length+1);q[c>>2]=a.He}else q[c>>2]=H.getProgramParameter(a,b);else K||=1281},Wc=(a,b,c)=>{if(c){a=H.te.getQueryObjectEXT(sb[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;P(c,d)}else K||=1281},Xc=(a,b,c)=>{if(c){a=H.te.getQueryObjectEXT(sb[a],b);
var d;"boolean"==typeof a?d=a?1:0:d=a;q[c>>2]=d}else K||=1281},Yc=()=>{var a=kb(H);return a=a.concat(a.map(b=>"GL_"+b))},Zc=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),$c=a=>{var b=a.ze,c=a.hf,d;if(!b){a.ze=b={};a.gf={};var e=H.getProgramParameter(a,35718);for(d=0;d<e;++d){var g=H.getActiveUniform(a,d);var f=g.name;g=g.size;var l=Zc(f);l=0<l?f.slice(0,l):f;var n=a.Xe;a.Xe+=g;c[l]=[g,n];for(f=0;f<g;++f)b[n]=f,a.gf[n++]=l}}},ad=(a,b)=>{b=b?z(m,b):"";if(a=I[a]){$c(a);var c=a.ze,d=0,e=b,g=Zc(b);0<g&&(d=parseInt(b.slice(g+
1))>>>0,e=b.slice(0,g));if((e=a.hf[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||H.getUniformLocation(a,b)))return d}else K||=1281;return-1},Q=a=>{var b=H.lf;if(b){var c=b.ze[a];"number"==typeof c&&(b.ze[a]=c=H.getUniformLocation(b,b.gf[a]+(0<c?`[${c}]`:"")));return c}K||=1282},bd=(a,b,c,d)=>{if(c)if(a=I[a],$c(a),a=H.getUniform(a,Q(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:q[c>>2]=a;break;case 2:u[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:q[c+4*b>>2]=a[b];break;case 2:u[c+4*b>>2]=
a[b]}else K||=1281},cd=(a,b,c,d)=>{if(c)if(a=H.getVertexAttrib(a,b),34975==b)q[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:q[c>>2]=a;break;case 2:u[c>>2]=a;break;case 5:q[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:q[c+4*b>>2]=a[b];break;case 2:u[c+4*b>>2]=a[b];break;case 5:q[c+4*b>>2]=Math.fround(a[b])}else K||=1281},dd=a=>{a=I[a];H.linkProgram(a);a.ze=0;a.hf={}},ed=(a,b,c,d,e)=>{a-=5120;a=1==a?m:4==a?q:6==a?u:5==a||28922==a?r:oa;b=d*((vb||
c)*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+ub-1&-ub);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},fd=(a,b,c,d)=>{for(var e="",g=0;g<b;++g)e+=La(r[c+4*g>>2],d?r[d+4*g>>2]:void 0);H.shaderSource(J[a],e)},gd=(a,b)=>{H.uniform1f(Q(a),b)},hd=[],jd=[],kd=(a,b,c,d)=>{H.uniform3f(Q(a),b,c,d)},ld=(a,b,c,d)=>{if(18>=b){var e=hd[16*b],g=u;d>>=2;b*=16;for(var f=0;f<b;f+=16){var l=d+f;e[f]=g[l];e[f+1]=g[l+1];e[f+2]=g[l+2];e[f+3]=g[l+
3];e[f+4]=g[l+4];e[f+5]=g[l+5];e[f+6]=g[l+6];e[f+7]=g[l+7];e[f+8]=g[l+8];e[f+9]=g[l+9];e[f+10]=g[l+10];e[f+11]=g[l+11];e[f+12]=g[l+12];e[f+13]=g[l+13];e[f+14]=g[l+14];e[f+15]=g[l+15]}}else e=u.subarray(d>>2,d+64*b>>2);H.uniformMatrix4fv(Q(a),!!c,e)},md=a=>{a=I[a];H.useProgram(a);H.lf=a},nd=(a,b,c,d,e,g)=>{H.vertexAttribPointer(a,b,c,!!d,e,g)},od=(a,b,c,d)=>H.viewport(a,b,c,d),pd=(a,b)=>{if(!L.fullscreenEnabled())return-1;a=N(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?fc()?wc(a,b):
b.qf?(dc(wc,1,[a,b]),1):-2:-3:-4},qd=()=>{try{if(navigator.getGamepads)return(L.Ee=navigator.getGamepads())?0:-1}catch(a){navigator.getGamepads=null}return-1},rd=(a,b)=>{var c={target:N(2),le:"beforeunload",ne:b,pe:(d=event)=>{var e=O(b)(28,0,a);e&&=e?z(m,e):"";if(e)return d.preventDefault(),d.returnValue=e},me:!0};return M(c)},sd=(a,b,c,d,e,g)=>{L.Me||(L.Me=x(256));a={target:N(a),le:g,ne:d,pe:(f=event)=>{var l=f.target.id?f.target.id:"",n=L.Me;y(hc(f.target),n+0,128);y(l,n+128,128);O(d)(e,n,b)&&
f.preventDefault()},me:c};return M(a)},td=(a,b,c,d,e)=>{L.Ne||(L.Ne=x(276));return M({target:a,le:e,ne:d,pe:(g=event)=>{var f=L.Ne,l=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,n=!!l;k[f]=n;k[f+1]=L.fullscreenEnabled();var v=n?l:L.zf,D=v?.id||"";y(hc(v),f+2,128);y(D,f+130,128);q[f+260>>2]=v?v.clientWidth:0;q[f+264>>2]=v?v.clientHeight:0;q[f+268>>2]=screen.width;q[f+272>>2]=screen.height;n&&(L.zf=l);O(d)(19,f,b)&&g.preventDefault()},
me:c})},ud=(a,b,c,d,e)=>{L.Oe||(L.Oe=x(1240));b={target:N(2),Ae:!0,le:e,ne:c,pe:(g=event)=>{var f=L.Oe;yc(f,g.gamepad);O(c)(d,f,a)&&g.preventDefault()},me:b};return M(b)},vd=(a,b,c,d,e,g)=>{L.Qe||(L.Qe=x(160));a={target:N(a),le:g,ne:d,pe:f=>{var l=L.Qe;w[l>>3]=f.timeStamp;var n=l>>2;q[n+2]=f.location;k[l+12]=f.ctrlKey;k[l+13]=f.shiftKey;k[l+14]=f.altKey;k[l+15]=f.metaKey;k[l+16]=f.repeat;q[n+5]=f.charCode;q[n+6]=f.keyCode;q[n+7]=f.which;y(f.key||"",l+32,32);y(f.code||"",l+64,32);y(f.char||"",l+96,
32);y(f.locale||"",l+128,32);O(d)(e,l,b)&&f.preventDefault()},me:c};return M(a)},wd=(a,b,c)=>{w[a>>3]=b.timeStamp;var d=a>>2;q[d+2]=b.screenX;q[d+3]=b.screenY;q[d+4]=b.clientX;q[d+5]=b.clientY;k[a+24]=b.ctrlKey;k[a+25]=b.shiftKey;k[a+26]=b.altKey;k[a+27]=b.metaKey;p[2*d+14]=b.button;p[2*d+15]=b.buttons;q[d+8]=b.movementX;q[d+9]=b.movementY;a=vc(c);q[d+10]=b.clientX-(a.left|0);q[d+11]=b.clientY-(a.top|0)},xd=(a,b,c,d,e,g)=>{L.Je||(L.Je=x(64));a=N(a);return M({target:a,Ae:"mousemove"!=g&&"mouseenter"!=
g&&"mouseleave"!=g,le:g,ne:d,pe:(f=event)=>{wd(L.Je,f,a);O(d)(e,L.Je,b)&&f.preventDefault()},me:c})},yd=(a,b,c,d,e)=>{L.Se||(L.Se=x(257));return M({target:a,le:e,ne:d,pe:(g=event)=>{var f=L.Se,l=document.pointerLockElement||document.qe||document.yf||document.Fe;k[f]=!!l;var n=l?.id||"";y(hc(l),f+1,128);y(n,f+129,128);O(d)(20,f,b)&&g.preventDefault()},me:c})},zd=(a,b,c,d)=>{L.We||(L.We=x(36));a=N(a);return M({target:a,le:"resize",ne:d,pe:(e=event)=>{if(e.target==a){var g=document.body;if(g){var f=
L.We;q[f>>2]=0;q[f+4>>2]=g.clientWidth;q[f+8>>2]=g.clientHeight;q[f+12>>2]=innerWidth;q[f+16>>2]=innerHeight;q[f+20>>2]=outerWidth;q[f+24>>2]=outerHeight;q[f+28>>2]=pageXOffset|0;q[f+32>>2]=pageYOffset|0;O(d)(10,f,b)&&e.preventDefault()}}},me:c})},Ad=(a,b,c,d,e,g)=>{L.Ve||(L.Ve=x(1552));a=N(a);return M({target:a,Ae:"touchstart"==g||"touchend"==g,le:g,ne:d,pe:f=>{var l={},n=f.touches;for(var v of n)v.cf=v.ef=0,l[v.identifier]=v;for(var D of f.changedTouches)D.cf=1,l[D.identifier]=D;for(var G of f.targetTouches)l[G.identifier].ef=
1;n=L.Ve;w[n>>3]=f.timeStamp;k[n+12]=f.ctrlKey;k[n+13]=f.shiftKey;k[n+14]=f.altKey;k[n+15]=f.metaKey;v=n+16;D=vc(a);G=0;for(let F of Object.values(l))if(l=v>>2,q[l]=F.identifier,q[l+1]=F.screenX,q[l+2]=F.screenY,q[l+3]=F.clientX,q[l+4]=F.clientY,q[l+5]=F.pageX,q[l+6]=F.pageY,k[v+28]=F.cf,k[v+29]=F.ef,q[l+8]=F.clientX-(D.left|0),q[l+9]=F.clientY-(D.top|0),v+=48,31<++G)break;q[n+8>>2]=G;O(d)(e,n,b)&&f.preventDefault()},me:c})},Bd=(a,b,c)=>{var d=jc[1];L.Ye||(L.Ye=x(8));return M({target:d,le:"visibilitychange",
ne:c,pe:(e=event)=>{var g=L.Ye,f=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);k[g]=document.hidden;q[g+4>>2]=f;O(c)(21,g,a)&&e.preventDefault()},me:b})},Cd=(a,b,c,d)=>{L.Ze||(L.Ze=x(96));return M({target:a,Ae:!0,le:"wheel",ne:d,pe:(e=event)=>{var g=L.Ze;wd(g,e,a);w[g+64>>3]=e.deltaX;w[g+72>>3]=e.deltaY;w[g+80>>3]=e.deltaZ;q[g+88>>2]=e.deltaMode;O(d)(9,g,b)&&e.preventDefault()},me:c})};function Dd(a){var b=T,c=b.Fe.pop()||b.qe.length;b.qe[c]=a;return c}
class Ed{qe=[void 0];Fe=[];get(a){return this.qe[a]}has(a){return void 0!==this.qe[a]}}var T,Fd;
function Gd(a,b,c,d,e){function g(){var C=0,S=0;t.response&&Y&&0===r[a+12>>2]&&(S=t.response.byteLength);0<S&&(C=x(S),m.set(new Uint8Array(t.response),C));r[a+12>>2]=C;P(a+16,S);P(a+24,0);(C=t.response?t.response.byteLength:0)&&P(a+32,C);p[a+40>>1]=t.readyState;p[a+42>>1]=t.status;t.statusText&&y(t.statusText,a+44,64)}var f=r[a+8>>2];if(f){var l=f?z(m,f):"",n=a+108,v=La(n+0);v||="GET";var D=r[n+56>>2],G=r[n+68>>2],F=r[n+72>>2];f=r[n+76>>2];var U=r[n+80>>2],ca=r[n+84>>2],V=r[n+88>>2],R=r[n+52>>2],
Y=!!(R&1),la=!!(R&2);R=!!(R&64);G=G?G?z(m,G):"":void 0;F=F?F?z(m,F):"":void 0;var t=new XMLHttpRequest;t.withCredentials=!!m[n+60];t.open(v,l,!R,G,F);R||(t.timeout=D);t.qe=l;t.responseType="arraybuffer";U&&(l=U?z(m,U):"",t.overrideMimeType(l));if(f)for(;;){n=r[f>>2];if(!n)break;l=r[f+4>>2];if(!l)break;f+=8;n=n?z(m,n):"";l=l?z(m,l):"";t.setRequestHeader(n,l)}var W=Dd(t);r[a>>2]=W;f=ca&&V?m.slice(ca,ca+V):null;t.onload=C=>{T.has(W)&&(g(),200<=t.status&&300>t.status?b?.(a,t,C):c?.(a,t,C))};t.onerror=
C=>{T.has(W)&&(g(),c?.(a,t,C))};t.ontimeout=C=>{T.has(W)&&c?.(a,t,C)};t.onprogress=C=>{if(T.has(W)){var S=Y&&la&&t.response?t.response.byteLength:0,A=0;0<S&&Y&&la&&(A=x(S),m.set(new Uint8Array(t.response),A));r[a+12>>2]=A;P(a+16,S);P(a+24,C.loaded-S);P(a+32,C.total);p[a+40>>1]=t.readyState;3<=t.readyState&&0===t.status&&0<C.loaded&&(t.status=200);p[a+42>>1]=t.status;t.statusText&&y(t.statusText,a+44,64);d?.(a,t,C);A&&Hd(A)}};t.onreadystatechange=C=>{T.has(W)&&(p[a+40>>1]=t.readyState,2<=t.readyState&&
(p[a+42>>1]=t.status),e?.(a,t,C))};try{t.send(f)}catch(C){c?.(a,t,C)}}else c(a,0,"no url specified!")}function Id(a,b,c,d){var e=Fd;if(e){var g=r[a+108+64>>2];g||=r[a+8>>2];var f=g?z(m,g):"";try{var l=e.transaction(["FILES"],"readwrite").objectStore("FILES").put(b,f);l.onsuccess=()=>{p[a+40>>1]=4;p[a+42>>1]=200;y("OK",a+44,64);c(a,0,f)};l.onerror=n=>{p[a+40>>1]=4;p[a+42>>1]=413;y("Payload Too Large",a+44,64);d(a,0,n)}}catch(n){d(a,0,n)}}else d(a,0,"IndexedDB not available!")}
function Jd(a,b,c){var d=Fd;if(d){var e=r[a+108+64>>2];e||=r[a+8>>2];e=e?z(m,e):"";try{var g=d.transaction(["FILES"],"readonly").objectStore("FILES").get(e);g.onsuccess=f=>{if(f.target.result){f=f.target.result;var l=f.byteLength||f.length,n=x(l);m.set(new Uint8Array(f),n);r[a+12>>2]=n;P(a+16,l);P(a+24,0);P(a+32,l);p[a+40>>1]=4;p[a+42>>1]=200;y("OK",a+44,64);b(a,0,f)}else p[a+40>>1]=4,p[a+42>>1]=404,y("Not Found",a+44,64),c(a,0,"no data")};g.onerror=f=>{p[a+40>>1]=4;p[a+42>>1]=404;y("Not Found",a+
44,64);c(a,0,f)}}catch(f){c(a,0,f)}}else c(a,0,"IndexedDB not available!")}function Kd(a,b,c){var d=Fd;if(d){var e=r[a+108+64>>2];e||=r[a+8>>2];e=e?z(m,e):"";try{var g=d.transaction(["FILES"],"readwrite").objectStore("FILES").delete(e);g.onsuccess=f=>{f=f.target.result;r[a+12>>2]=0;P(a+16,0);P(a+24,0);P(a+32,0);p[a+40>>1]=4;p[a+42>>1]=200;y("OK",a+44,64);b(a,0,f)};g.onerror=f=>{p[a+40>>1]=4;p[a+42>>1]=404;y("Not Found",a+44,64);c(a,0,f)}}catch(f){c(a,0,f)}}else c(a,0,"IndexedDB not available!")}
var Ld={},Nd=()=>{if(!Md){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in Ld)void 0===Ld[b]?delete a[b]:a[b]=Ld[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Md=c}return Md},Md,Od=[null,[],[]],Pd=(a,b,c)=>{a.addEventListener(b,c,{once:!0})},za=a=>{var b;b||=[document,document.getElementById("canvas")];["keydown","mousedown",
"touchstart"].forEach(c=>{b.forEach(d=>{d&&Pd(d,c,()=>{"suspended"===a.state&&a.resume()})})})},Aa=(a,b=[])=>{O(a)(...b)};
h.requestFullscreen=function(a,b){function c(){Qa=!1;var g=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===g?(d.exitFullscreen=Ya,Wa&&d.requestPointerLock(),Qa=!0,Xa?("undefined"!=typeof SDL&&(q[SDL.screen>>2]=r[SDL.screen>>2]|8388608),ab(h.canvas),$a()):ab(d)):(g.parentNode.insertBefore(d,g),g.parentNode.removeChild(g),Xa?("undefined"!=typeof SDL&&(q[SDL.screen>>2]=
r[SDL.screen>>2]&-8388609),ab(h.canvas),$a()):ab(d));h.onFullScreen?.(Qa);h.onFullscreen?.(Qa)}Wa=a;Xa=b;"undefined"==typeof Wa&&(Wa=!0);"undefined"==typeof Xa&&(Xa=!1);var d=h.canvas;Va||(Va=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=
e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()};h.setCanvasSize=function(a,b,c){ab(h.canvas,a,b);c||$a()};h.getUserMedia=function(a){let b;(b=window).getUserMedia||(b.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)};
h.createContext=function(a,b,c,d){if(b&&h.ctx&&a==h.canvas)return h.ctx;var e;if(b){var g={antialias:!1,alpha:!1,df:1};if(d)for(var f in d)g[f]=d[f];if("undefined"!=typeof Db&&(e=zb(a,g)))var l=rb[e].ue}else l=a.getContext("2d");if(!l)return null;c&&(h.ctx=l,b&&Cb(e),Sa.forEach(n=>n()),Ta());return l};h.requestAnimationFrame=Zb;h.pauseMainLoop=function(){Sb=null;Hb++};h.resumeMainLoop=function(){Hb++;var a=Qb,b=Rb,c=Ib;Ib=null;Xb(c,0,!1,Jb,!0);Wb(a,b);Sb()};h.preMainLoop&&Ub.push(h.preMainLoop);
h.postMainLoop&&Vb.push(h.postMainLoop);for(var X=0;32>X;++X)Mc.push(Array(X));var Qd=new Float32Array(288);for(X=0;288>=X;++X)hd[X]=Qd.subarray(0,X);var Rd=new Int32Array(288);for(X=0;288>=X;++X)jd[X]=Rd.subarray(0,X);T=new Ed;sa();
(function(a,b){try{var c=indexedDB.open("emscripten_filesystem",1)}catch(d){b(d);return}c.onupgradeneeded=d=>{d=d.target.result;d.objectStoreNames.contains("FILES")&&d.deleteObjectStore("FILES");d.createObjectStore("FILES")};c.onsuccess=d=>a(d.target.result);c.onerror=b})(a=>{Fd=a;ta()},()=>{Fd=!1;ta()});
var Sd={X:function(){return 0},$a:()=>{},bb:function(){return 0},Ya:()=>{},Za:()=>{},cb:function(){},_a:()=>{},Ca:a=>{if(12448==a)return B=12288,1;B=12300;return 0},Fa:(a,b,c,d,e)=>{if(62E3!=a)B=12296,c=0;else{if(b)for(;;){a=q[b>>2];if(12321==a)E.alpha=0<q[b+4>>2];else if(12325==a)E.depth=0<q[b+4>>2];else if(12326==a)E.stencil=0<q[b+4>>2];else if(12337==a)a=q[b+4>>2],E.antialias=0<a;else if(12338==a)a=q[b+4>>2],E.antialias=1==a;else if(12544==a)E.Mf=12547!=q[b+4>>2];else if(12344==a)break;b+=8}c&&
d||e?(e&&(q[e>>2]=1),c&&0<d&&(r[c>>2]=62002),B=12288,c=1):(B=12300,c=0)}return c},ta:(a,b,c,d)=>{if(62E3!=a)return B=12296,0;for(a=1;;){b=q[d>>2];if(12440==b)a=q[d+4>>2];else if(12344==b)break;else return B=12292,0;d+=8}if(2!=a)return B=12293,0;E.df=a-1;E.Of=0;gb=zb(h.canvas,E);if(0!=gb)return B=12288,Cb(gb),Sa.forEach(e=>e()),Cb(null),62004;B=12297;return 0},va:(a,b)=>{if(62E3!=a)return B=12296,0;if(62002!=b)return B=12293,0;B=12288;return 62006},ua:(a,b)=>{if(62E3!=a)return B=12296,0;if(62004!=
b)return B=12294,0;a=gb;Bb===rb[a]&&(Bb=null);"object"==typeof L&&L.Af(rb[a].ue.canvas);rb[a]?.ue.canvas&&(rb[a].ue.canvas.ye=void 0);rb[a]=null;B=12288;cb==b&&(cb=0);return 1},wa:(a,b)=>{if(62E3!=a)return B=12296,0;if(62006!=b)return B=12301,1;db==b&&(db=0);eb==b&&(eb=0);B=12288;return 1},Ga:(a,b,c,d)=>{if(62E3!=a)return B=12296,0;if(62002!=b)return B=12293,0;if(!d)return B=12300,0;B=12288;switch(c){case 12320:return q[d>>2]=E.alpha?32:24,1;case 12321:return q[d>>2]=E.alpha?8:0,1;case 12322:return q[d>>
2]=8,1;case 12323:return q[d>>2]=8,1;case 12324:return q[d>>2]=8,1;case 12325:return q[d>>2]=E.depth?24:0,1;case 12326:return q[d>>2]=E.stencil?8:0,1;case 12327:return q[d>>2]=12344,1;case 12328:return q[d>>2]=62002,1;case 12329:return q[d>>2]=0,1;case 12330:return q[d>>2]=4096,1;case 12331:return q[d>>2]=16777216,1;case 12332:return q[d>>2]=4096,1;case 12333:return q[d>>2]=0,1;case 12334:return q[d>>2]=0,1;case 12335:return q[d>>2]=12344,1;case 12337:return q[d>>2]=E.antialias?4:0,1;case 12338:return q[d>>
2]=E.antialias?1:0,1;case 12339:return q[d>>2]=4,1;case 12340:return q[d>>2]=12344,1;case 12341:case 12342:case 12343:return q[d>>2]=-1,1;case 12345:case 12346:return q[d>>2]=0,1;case 12347:return q[d>>2]=0,1;case 12348:return q[d>>2]=1;case 12349:case 12350:return q[d>>2]=0,1;case 12351:return q[d>>2]=12430,1;case 12352:return q[d>>2]=4,1;case 12354:return q[d>>2]=0,1;default:return B=12292,0}},P:a=>{B=12288;return 0!=a&&1!=a?0:62E3},sa:()=>B,Da:(a,b,c)=>{if(62E3!=a)return B=12296,0;b&&(q[b>>2]=
1);c&&(q[c>>2]=4);bb=!0;B=12288;return 1},xa:(a,b,c,d)=>{if(62E3!=a)return B=12296,0;if(0!=d&&62004!=d)return B=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return B=12301,0;Cb(d?gb:null);cb=d;eb=b;db=c;B=12288;return 1},ra:(a,b)=>{if(62E3!=a)return B=12296,0;B=12288;if(fb[b])return fb[b];switch(b){case 12371:a=Fb("Emscripten");break;case 12372:a=Fb("1.4 Emscripten EGL");break;case 12373:a=Fb("");break;case 12429:a=Fb("OpenGL_ES");break;default:return B=12300,0}return fb[b]=a},ya:()=>{if(bb)if(H)if(H.isContextLost())B=
12302;else return B=12288,1;else B=12290;else B=12289;return 0},za:(a,b)=>{if(62E3!=a)return B=12296,0;0==b?Wb(0,0):Wb(1,b);B=12288;return 1},Ea:a=>{if(62E3!=a)return B=12296,0;eb=db=cb=0;bb=!1;B=12288;return 1},Ba:()=>{B=12288;return 1},Aa:()=>{B=12288;return 1},Ja:(a,b,c)=>{b=bc(b,c);return Ca[a](...b)},e:(a,b,c)=>{b=bc(b,c);return Ca[a](...b)},Ka:(a,b,c)=>{b=bc(b,c);return Ca[a](...b)},Y:()=>Date.now(),ka:()=>{if(!L.fullscreenEnabled())return-1;ec(wc);var a=jc[1];if(a.exitFullscreen)a.fullscreenElement&&
a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},pa:()=>{ec(xc);if(document.exitPointerLock)document.exitPointerLock();else return-1;return 0},La:function(a){if(T.has(a)){var b=T.get(a),c=T;c.qe[a]=void 0;c.Fe.push(a);0<b.readyState&&4>b.readyState&&b.abort()}},j:()=>devicePixelRatio,f:(a,b,c)=>{a=N(a);if(!a)return-4;a=vc(a);w[b>>3]=a.width;w[c>>3]=a.height;return 0},S:(a,b)=>{if(0>a||a>=L.Ee.length)return-5;if(!L.Ee[a])return-7;
yc(b,L.Ee[a]);return 0},U:()=>performance.now(),Ia:()=>L.Ee.length,qa:(a,b)=>{q[a>>2]=screen.width;q[b>>2]=screen.height},Sd:a=>H.activeTexture(a),Rd:zc,ga:(a,b)=>{H.te.beginQueryEXT(a,sb[b])},Qd:(a,b,c)=>{H.bindAttribLocation(I[a],b,c?z(m,c):"")},Pd:Ac,Od:(a,b)=>{H.bindFramebuffer(a,nb[b])},Nd:(a,b)=>{H.bindRenderbuffer(a,ob[b])},Md:(a,b)=>{H.bindTexture(a,pb[b])},_d:a=>{H.bindVertexArray(qb[a])},Ld:(a,b,c,d)=>H.blendColor(a,b,c,d),Kd:Bc,Jd:(a,b)=>H.blendEquationSeparate(a,b),Hd:Cc,Gd:(a,b,c,d)=>
H.blendFuncSeparate(a,b,c,d),Fd:Dc,Ed:(a,b,c,d)=>{H.bufferSubData(a,b,m.subarray(d,d+c))},Dd:a=>H.checkFramebufferStatus(a),Cd:Ec,Bd:Fc,Ad:a=>H.clearDepth(a),zd:a=>H.clearStencil(a),eb:(a,b)=>{H.sf.clipControlEXT(a,b)},yd:(a,b,c,d)=>{H.colorMask(!!a,!!b,!!c,!!d)},xd:Gc,wd:(a,b,c,d,e,g,f,l)=>{H.compressedTexImage2D(a,b,c,d,e,g,m.subarray(l,l+f))},vd:(a,b,c,d,e,g,f,l,n)=>{H.compressedTexSubImage2D(a,b,c,d,e,g,f,m.subarray(n,n+l))},ud:(a,b,c,d,e,g,f,l)=>H.copyTexImage2D(a,b,c,d,e,g,f,l),td:(a,b,c,d,
e,g,f,l)=>H.copyTexSubImage2D(a,b,c,d,e,g,f,l),sd:Hc,rd:Ic,qd:a=>H.cullFace(a),pd:(a,b)=>{for(var c=0;c<a;c++){var d=q[b+4*c>>2],e=mb[d];e&&(H.deleteBuffer(e),e.name=0,mb[d]=null)}},od:(a,b)=>{for(var c=0;c<a;++c){var d=q[b+4*c>>2],e=nb[d];e&&(H.deleteFramebuffer(e),e.name=0,nb[d]=null)}},md:Jc,ia:(a,b)=>{for(var c=0;c<a;c++){var d=q[b+4*c>>2],e=sb[d];e&&(H.te.deleteQueryEXT(e),sb[d]=null)}},ld:(a,b)=>{for(var c=0;c<a;c++){var d=q[b+4*c>>2],e=ob[d];e&&(H.deleteRenderbuffer(e),e.name=0,ob[d]=null)}},
kd:a=>{if(a){var b=J[a];b?(H.deleteShader(b),J[a]=null):K||=1281}},jd:(a,b)=>{for(var c=0;c<a;c++){var d=q[b+4*c>>2],e=pb[d];e&&(H.deleteTexture(e),e.name=0,pb[d]=null)}},Zd:(a,b)=>{for(var c=0;c<a;c++){var d=q[b+4*c>>2];H.deleteVertexArray(qb[d]);qb[d]=null}},id:a=>H.depthFunc(a),hd:Kc,gd:(a,b)=>H.depthRange(a,b),fd:(a,b)=>{H.detachShader(I[a],J[b])},ed:Lc,dd:a=>{H.disableVertexAttribArray(a)},cd:(a,b,c)=>{H.drawArrays(a,b,c)},Vd:(a,b,c,d)=>{H.drawArraysInstanced(a,b,c,d)},Wd:(a,b)=>{for(var c=Mc[a],
d=0;d<a;d++)c[d]=q[b+4*d>>2];H.drawBuffers(c)},bd:Nc,Ud:(a,b,c,d,e)=>{H.drawElementsInstanced(a,b,c,d,e)},ad:Oc,$c:Pc,fa:a=>{H.te.endQueryEXT(a)},_c:()=>H.finish(),Zc:()=>H.flush(),Yc:(a,b,c,d)=>{H.framebufferRenderbuffer(a,b,c,ob[d])},Xc:(a,b,c,d,e)=>{H.framebufferTexture2D(a,b,c,pb[d],e)},Wc:a=>H.frontFace(a),Vc:Qc,Tc:(a,b)=>{xb(a,b,"createFramebuffer",nb)},ja:(a,b)=>{for(var c=0;c<a;c++){var d=H.te.createQueryEXT();if(!d){for(K||=1282;c<a;)q[b+4*c++>>2]=0;break}var e=wb(sb);d.name=e;sb[e]=d;q[b+
4*c>>2]=e}},Sc:(a,b)=>{xb(a,b,"createRenderbuffer",ob)},Rc:(a,b)=>{xb(a,b,"createTexture",pb)},Yd:(a,b)=>{xb(a,b,"createVertexArray",qb)},Uc:a=>H.generateMipmap(a),Qc:(a,b,c,d,e,g,f)=>Rc("getActiveAttrib",a,b,c,d,e,g,f),Pc:(a,b,c,d,e,g,f)=>Rc("getActiveUniform",a,b,c,d,e,g,f),Oc:(a,b,c,d)=>{a=H.getAttachedShaders(I[a]);var e=a.length;e>b&&(e=b);q[c>>2]=e;for(b=0;b<e;++b)q[d+4*b>>2]=J.indexOf(a[b])},Nc:Sc,Mc:(a,b)=>Tc(a,b,4),Lc:(a,b,c)=>{c?q[c>>2]=H.getBufferParameter(a,b):K||=1281},Jc:()=>{var a=
H.getError()||K;K=0;return a},Ic:(a,b)=>Tc(a,b,2),Hc:(a,b,c,d)=>{a=H.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;q[d>>2]=a},Gc:(a,b)=>Tc(a,b,0),Ec:Uc,Fc:Vc,ae:Wc,ca:Xc,$d:Wc,ba:Xc,da:(a,b,c)=>{c?q[c>>2]=H.te.getQueryEXT(a,b):K||=1281},Dc:(a,b,c)=>{c?q[c>>2]=H.getRenderbufferParameter(a,b):K||=1281},Bc:(a,b,c,d)=>{a=H.getShaderInfoLog(J[a]);null===a&&(a="(unknown error)");b=0<b&&d?y(a,d,b):0;c&&(q[c>>2]=b)},Ac:(a,b,c,d)=>{a=H.getShaderPrecisionFormat(a,
b);q[c>>2]=a.rangeMin;q[c+4>>2]=a.rangeMax;q[d>>2]=a.precision},yc:(a,b,c,d)=>{if(a=H.getShaderSource(J[a]))b=0<b&&d?y(a,d,b):0,c&&(q[c>>2]=b)},Cc:(a,b,c)=>{c?35716==b?(a=H.getShaderInfoLog(J[a]),null===a&&(a="(unknown error)"),q[c>>2]=a?a.length+1:0):35720==b?(a=H.getShaderSource(J[a]),q[c>>2]=a?a.length+1:0):q[c>>2]=H.getShaderParameter(J[a],b):K||=1281},xc:a=>{var b=tb[a];if(!b){switch(a){case 7939:b=Fb(Yc().join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=H.getParameter(a))||(K||=
1280);b=b?Fb(b):0;break;case 7938:b=Fb(`OpenGL ES 2.0 (${H.getParameter(7938)})`);break;case 35724:b=H.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=Fb(b);break;default:K||=1280}tb[a]=b}return b},wc:(a,b,c)=>{c?u[c>>2]=H.getTexParameter(a,b):K||=1281},vc:(a,b,c)=>{c?q[c>>2]=H.getTexParameter(a,b):K||=1281},sc:ad,uc:(a,b,c)=>{bd(a,b,c,2)},tc:(a,b,c)=>{bd(a,b,c,0)},pc:(a,b,c)=>{c?q[c>>
2]=H.getVertexAttribOffset(a,b):K||=1281},rc:(a,b,c)=>{cd(a,b,c,2)},qc:(a,b,c)=>{cd(a,b,c,5)},oc:(a,b)=>H.hint(a,b),nc:a=>(a=mb[a])?H.isBuffer(a):0,mc:a=>H.isEnabled(a),lc:a=>(a=nb[a])?H.isFramebuffer(a):0,kc:a=>(a=I[a])?H.isProgram(a):0,ha:a=>(a=sb[a])?H.te.isQueryEXT(a):0,jc:a=>(a=ob[a])?H.isRenderbuffer(a):0,ic:a=>(a=J[a])?H.isShader(a):0,hc:a=>(a=pb[a])?H.isTexture(a):0,Xd:a=>(a=qb[a])?H.isVertexArray(a):0,gc:a=>H.lineWidth(a),fc:dd,ec:(a,b)=>{3317==a?ub=b:3314==a&&(vb=b);H.pixelStorei(a,b)},
db:(a,b)=>{H.Cf.polygonModeWEBGL(a,b)},dc:(a,b)=>H.polygonOffset(a,b),fb:(a,b,c)=>{H.tf.polygonOffsetClampEXT(a,b,c)},ea:(a,b)=>{H.te.queryCounterEXT(sb[a],b)},cc:(a,b,c,d,e,g,f)=>{(f=ed(g,e,c,d,f))?H.readPixels(a,b,c,d,e,g,f):K||=1280},bc:()=>{},ac:(a,b,c,d)=>H.renderbufferStorage(a,b,c,d),$b:(a,b)=>{H.sampleCoverage(a,!!b)},_b:(a,b,c,d)=>H.scissor(a,b,c,d),Zb:()=>{K||=1280},Yb:fd,Xb:(a,b,c)=>H.stencilFunc(a,b,c),Vb:(a,b,c,d)=>H.stencilFuncSeparate(a,b,c,d),Ub:a=>H.stencilMask(a),Tb:(a,b)=>H.stencilMaskSeparate(a,
b),Sb:(a,b,c)=>H.stencilOp(a,b,c),Rb:(a,b,c,d)=>H.stencilOpSeparate(a,b,c,d),Qb:(a,b,c,d,e,g,f,l,n)=>{n=n?ed(l,f,d,e,n):null;H.texImage2D(a,b,c,d,e,g,f,l,n)},Pb:(a,b,c)=>H.texParameterf(a,b,c),Ob:(a,b,c)=>{H.texParameterf(a,b,u[c>>2])},Nb:(a,b,c)=>H.texParameteri(a,b,c),Mb:(a,b,c)=>{H.texParameteri(a,b,q[c>>2])},Lb:(a,b,c,d,e,g,f,l,n)=>{n=n?ed(l,f,e,g,n):null;H.texSubImage2D(a,b,c,d,e,g,f,l,n)},Kb:gd,Jb:(a,b,c)=>{if(288>=b)for(var d=hd[b],e=0;e<b;++e)d[e]=u[c+4*e>>2];else d=u.subarray(c>>2,c+4*b>>
2);H.uniform1fv(Q(a),d)},Ib:(a,b)=>{H.uniform1i(Q(a),b)},Hb:(a,b,c)=>{if(288>=b)for(var d=jd[b],e=0;e<b;++e)d[e]=q[c+4*e>>2];else d=q.subarray(c>>2,c+4*b>>2);H.uniform1iv(Q(a),d)},Gb:(a,b,c)=>{H.uniform2f(Q(a),b,c)},Fb:(a,b,c)=>{if(144>=b){b*=2;for(var d=hd[b],e=0;e<b;e+=2)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2]}else d=u.subarray(c>>2,c+8*b>>2);H.uniform2fv(Q(a),d)},Eb:(a,b,c)=>{H.uniform2i(Q(a),b,c)},Db:(a,b,c)=>{if(144>=b){b*=2;for(var d=jd[b],e=0;e<b;e+=2)d[e]=q[c+4*e>>2],d[e+1]=q[c+(4*e+4)>>2]}else d=
q.subarray(c>>2,c+8*b>>2);H.uniform2iv(Q(a),d)},Cb:kd,Bb:(a,b,c)=>{if(96>=b){b*=3;for(var d=hd[b],e=0;e<b;e+=3)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2]}else d=u.subarray(c>>2,c+12*b>>2);H.uniform3fv(Q(a),d)},Ab:(a,b,c,d)=>{H.uniform3i(Q(a),b,c,d)},zb:(a,b,c)=>{if(96>=b){b*=3;for(var d=jd[b],e=0;e<b;e+=3)d[e]=q[c+4*e>>2],d[e+1]=q[c+(4*e+4)>>2],d[e+2]=q[c+(4*e+8)>>2]}else d=q.subarray(c>>2,c+12*b>>2);H.uniform3iv(Q(a),d)},yb:(a,b,c,d,e)=>{H.uniform4f(Q(a),b,c,d,e)},xb:(a,b,c)=>
{if(72>=b){var d=hd[4*b],e=u;c>>=2;b*=4;for(var g=0;g<b;g+=4){var f=c+g;d[g]=e[f];d[g+1]=e[f+1];d[g+2]=e[f+2];d[g+3]=e[f+3]}}else d=u.subarray(c>>2,c+16*b>>2);H.uniform4fv(Q(a),d)},wb:(a,b,c,d,e)=>{H.uniform4i(Q(a),b,c,d,e)},vb:(a,b,c)=>{if(72>=b){b*=4;for(var d=jd[b],e=0;e<b;e+=4)d[e]=q[c+4*e>>2],d[e+1]=q[c+(4*e+4)>>2],d[e+2]=q[c+(4*e+8)>>2],d[e+3]=q[c+(4*e+12)>>2]}else d=q.subarray(c>>2,c+16*b>>2);H.uniform4iv(Q(a),d)},ub:(a,b,c,d)=>{if(72>=b){b*=4;for(var e=hd[b],g=0;g<b;g+=4)e[g]=u[d+4*g>>2],
e[g+1]=u[d+(4*g+4)>>2],e[g+2]=u[d+(4*g+8)>>2],e[g+3]=u[d+(4*g+12)>>2]}else e=u.subarray(d>>2,d+16*b>>2);H.uniformMatrix2fv(Q(a),!!c,e)},tb:(a,b,c,d)=>{if(32>=b){b*=9;for(var e=hd[b],g=0;g<b;g+=9)e[g]=u[d+4*g>>2],e[g+1]=u[d+(4*g+4)>>2],e[g+2]=u[d+(4*g+8)>>2],e[g+3]=u[d+(4*g+12)>>2],e[g+4]=u[d+(4*g+16)>>2],e[g+5]=u[d+(4*g+20)>>2],e[g+6]=u[d+(4*g+24)>>2],e[g+7]=u[d+(4*g+28)>>2],e[g+8]=u[d+(4*g+32)>>2]}else e=u.subarray(d>>2,d+36*b>>2);H.uniformMatrix3fv(Q(a),!!c,e)},sb:ld,rb:md,qb:a=>{H.validateProgram(I[a])},
pb:(a,b)=>H.vertexAttrib1f(a,b),ob:(a,b)=>{H.vertexAttrib1f(a,u[b>>2])},nb:(a,b,c)=>H.vertexAttrib2f(a,b,c),mb:(a,b)=>{H.vertexAttrib2f(a,u[b>>2],u[b+4>>2])},lb:(a,b,c,d)=>H.vertexAttrib3f(a,b,c,d),kb:(a,b)=>{H.vertexAttrib3f(a,u[b>>2],u[b+4>>2],u[b+8>>2])},jb:(a,b,c,d,e)=>H.vertexAttrib4f(a,b,c,d,e),ib:(a,b)=>{H.vertexAttrib4f(a,u[b>>2],u[b+4>>2],u[b+8>>2],u[b+12>>2])},Td:(a,b)=>{H.vertexAttribDivisor(a,b)},hb:nd,gb:od,n:()=>0,Na:()=>!0,la:(a,b,c)=>pd(a,{Te:q[c>>2],Ke:q[c+4>>2],uf:q[c+8>>2],qf:b,
Be:q[c+12>>2],af:q[c+16>>2]}),N:(a,b)=>{a=N(a);return a?a.requestPointerLock?fc()?xc(a):b?(dc(xc,2,[a]),1):-2:-1:-4},Ta:()=>{ua("OOM")},T:qd,x:(a,b,c)=>"undefined"==typeof onbeforeunload?-1:1!==c?-5:rd(a,b),I:(a,b,c,d)=>sd(a,b,c,d,12,"blur"),i:pc,l:(a,b,c)=>{a=N(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},J:(a,b,c,d)=>sd(a,b,c,d,13,"focus"),z:(a,b,c,d)=>{if(!L.fullscreenEnabled())return-1;a=N(a);if(!a)return-4;td(a,b,c,d,"webkitfullscreenchange");return td(a,b,c,d,"fullscreenchange")},
R:(a,b,c)=>qd()?-1:ud(a,b,c,26,"gamepadconnected"),Q:(a,b,c)=>qd()?-1:ud(a,b,c,27,"gamepaddisconnected"),C:(a,b,c,d)=>vd(a,b,c,d,2,"keydown"),A:(a,b,c,d)=>vd(a,b,c,d,1,"keypress"),B:(a,b,c,d)=>vd(a,b,c,d,3,"keyup"),Oa:(a,b,c)=>{a=O(a);Xb(a,b,c)},q:(a,b,c,d)=>xd(a,b,c,d,5,"mousedown"),M:(a,b,c,d)=>xd(a,b,c,d,33,"mouseenter"),L:(a,b,c,d)=>xd(a,b,c,d,34,"mouseleave"),r:(a,b,c,d)=>xd(a,b,c,d,8,"mousemove"),p:(a,b,c,d)=>xd(a,b,c,d,6,"mouseup"),D:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||
document.body.qe||document.body.yf||document.body.Fe))return-1;a=N(a);if(!a)return-4;yd(a,b,c,d,"mozpointerlockchange");yd(a,b,c,d,"webkitpointerlockchange");yd(a,b,c,d,"mspointerlockchange");return yd(a,b,c,d,"pointerlockchange")},s:(a,b,c,d)=>zd(a,b,c,d),E:(a,b,c,d)=>Ad(a,b,c,d,25,"touchcancel"),G:(a,b,c,d)=>Ad(a,b,c,d,23,"touchend"),F:(a,b,c,d)=>Ad(a,b,c,d,24,"touchmove"),H:(a,b,c,d)=>Ad(a,b,c,d,22,"touchstart"),y:(a,b,c)=>Bd(a,b,c),K:(a,b,c,d)=>(a=N(a))?"undefined"!=typeof a.onwheel?Cd(a,b,c,
d):-1:-4,ma:a=>document.title=a?z(m,a):"",m:()=>{throw"Please compile your program with async support in order to use asynchronous operations like emscripten_sleep";},Ma:function(a,b,c,d,e){function g(A){if(F)A();else if(!ma)try{A(),Pa()}catch(Gb){Ma(Gb)}}var f=a+108,l=r[f+36>>2],n=r[f+40>>2],v=r[f+44>>2],D=r[f+48>>2],G=r[f+52>>2],F=!!(G&64),U=A=>{g(()=>{l?O(l)(A):b?.(A)})},ca=A=>{g(()=>{v?O(v)(A):d?.(A)})},V=A=>{g(()=>{n?O(n)(A):c?.(A)})},R=A=>{g(()=>{D?O(D)(A):e?.(A)})},Y=A=>{Gd(A,U,V,ca,R)},la=
(A,Gb)=>{Id(A,Gb.response,Fa=>{g(()=>{l?O(l)(Fa):b?.(Fa)})},Fa=>{g(()=>{l?O(l)(Fa):b?.(Fa)})})},t=A=>{Gd(A,la,V,ca,R)},W=La(f+0),C=!!(G&16),S=!!(G&4);G=!!(G&32);if("EM_IDB_STORE"===W)Y=r[f+84>>2],Id(a,m.slice(Y,Y+r[f+88>>2]),U,V);else if("EM_IDB_DELETE"===W)Kd(a,U,V);else if(C){if(G)return 0;Gd(a,S?la:U,V,ca,R)}else Jd(a,U,G?V:S?t:Y);return a},Wa:(a,b)=>{var c=0;Nd().forEach((d,e)=>{var g=b+c;e=r[a+4*e>>2]=g;for(g=0;g<d.length;++g)k[e++]=d.charCodeAt(g);k[e]=0;c+=d.length+1});return 0},Xa:(a,b)=>
{var c=Nd();r[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);r[b>>2]=d;return 0},V:()=>52,ab:()=>52,Va:function(){return 70},W:(a,b,c,d)=>{for(var e=0,g=0;g<c;g++){var f=r[b>>2],l=r[b+4>>2];b+=8;for(var n=0;n<l;n++){var v=m[f+n],D=Od[a];0===v||10===v?((1===a?ha:ia)(z(D)),D.length=0):D.push(v)}e+=l}r[d>>2]=e;return 0},_:zc,a:Ac,Sa:Bc,Ua:Cc,b:Dc,Wb:Ec,Ra:Fc,$:Gc,Id:Hc,w:Ic,na:Jc,k:Kc,Z:Lc,Ha:Nc,u:Oc,o:Pc,c:Qc,v:Sc,oa:Uc,O:Vc,g:ad,nd:dd,aa:fd,h:gd,Qa:kd,d:ld,Kc:md,t:nd,zc:od,Pa:function(){var a=
new Uint32Array(1);crypto.getRandomValues(a);return a[0]}},Z;
(async function(){function a(c){Z=c.exports;ka=Z.be;c=ka.buffer;h.HEAP8=k=new Int8Array(c);h.HEAP16=p=new Int16Array(c);h.HEAPU8=m=new Uint8Array(c);h.HEAPU16=oa=new Uint16Array(c);h.HEAP32=q=new Int32Array(c);h.HEAPU32=r=new Uint32Array(c);h.HEAPF32=u=new Float32Array(c);h.HEAPF64=w=new Float64Array(c);h.HEAP64=pa=new BigInt64Array(c);h.HEAPU64=new BigUint64Array(c);sc=Z.ge;ta();return Z}sa();var b={a:Sd};if(h.instantiateWasm)return new Promise(c=>{h.instantiateWasm(b,(d,e)=>{a(d,e);c(d.exports)})});
va??=h.locateFile?h.locateFile("index.wasm",ea):ea+"index.wasm";return a((await ya(b)).instance)})();var x=a=>(x=Z.de)(a),Hd=a=>(Hd=Z.ee)(a),Td=h._main=(a,b)=>(Td=h._main=Z.fe)(a,b),nc=a=>(nc=Z.he)(a),kc=a=>(kc=Z.ie)(a),mc=()=>(mc=Z.je)();function Ud(a=[]){var b=Td;a.unshift(da);var c=a.length,d=kc(4*(c+1)),e=d;a.forEach(f=>{r[e>>2]=lc(f);e+=4});r[e>>2]=0;try{var g=b(c,d);Oa(g)}catch(f){Ma(f)}}
function Vd(a=ba){function b(){h.calledRun=!0;if(!ma){Z.ce();h.onRuntimeInitialized?.();h.noInitialRun||Ud(a);if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var c=h.postRun.shift();Ga.unshift(c)}Ea(Ga)}}if(0<qa)ra=Vd;else{if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Ia();Ea(Ha);0<qa?ra=Vd:h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),1);b()},1)):b()}}
if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();Vd();
