var h;h||=typeof Module != 'undefined' ? Module : {};var aa=[],ba="./this.program",k="",ca;"undefined"!=typeof document&&document.currentScript&&(k=document.currentScript.src);k=k.startsWith("blob:")?"":k.slice(0,k.replace(/[?#].*/,"").lastIndexOf("/")+1);ca=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};
var da=console.log.bind(console),m=console.error.bind(console),ea,fa,p=!1,ha,q,r,ia,ja,u,v,w,ka,x,y=0,la=null;function ma(a){h.onAbort?.(a);a="Aborted("+a+")";m(a);p=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var na;async function oa(a){if(!ea)try{var b=await ca(a);return new Uint8Array(b)}catch{}if(a==na&&ea)a=new Uint8Array(ea);else throw"both async and sync fetching of the wasm failed";return a}
async function pa(a,b){try{var c=await oa(a);return await WebAssembly.instantiate(c,b)}catch(d){m(`failed to asynchronously prepare wasm: ${d}`),ma(d)}}async function qa(a){var b=na;if(!ea&&"function"==typeof WebAssembly.instantiateStreaming)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){m(`wasm streaming compile failed: ${d}`),m("falling back to ArrayBuffer instantiation")}return pa(b,a)}
class ra{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var sa=a=>{for(;0<a.length;)a.shift()(h)},ta=[],ua=[],va=()=>{var a=h.preRun.shift();ua.push(a)},wa=!0;
function xa(a,b){var c="float";c.endsWith("*")&&(c="*");switch(c){case "i1":q[a]=b;break;case "i8":q[a]=b;break;case "i16":ia[a>>1]=b;break;case "i32":u[a>>2]=b;break;case "i64":ka[a>>3]=BigInt(b);break;case "float":w[a>>2]=b;break;case "double":x[a>>3]=b;break;case "*":v[a>>2]=b;break;default:ma(`invalid type for setValue: ${c}`)}}
var ya="undefined"!=typeof TextDecoder?new TextDecoder:void 0,z=(a,b=0,c=NaN)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&ya)return ya.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var f=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|f:(e&7)<<18|g<<12|f<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
za=a=>{if(!(a instanceof ra||"unwind"==a))throw a;},Aa=a=>{ha=a;wa||(h.onExit?.(a),p=!0);throw new ra(a);},Ba=a=>{ha=a;Aa(a)},Ca=()=>{if(!wa)try{var a=ha;ha=a;Aa(a)}catch(b){za(b)}},Da=!1,Ea=!1,Fa=[];
function Ga(){function a(){var c=h.canvas;Ea=document.pointerLockElement===c||document.mozPointerLockElement===c||document.webkitPointerLockElement===c||document.msPointerLockElement===c}if(!Ha){Ha=!0;var b=h.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),b.exitPointerLock=
b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",c=>{!Ea&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}var Ia=!1,Ja=void 0,A=void 0;
function Ka(){if(!Da)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var La=[];function Ma(){var a=h.canvas;La.forEach(b=>b(a.width,a.height))}
function Na(a,b,c){b&&c?(a.sf=b,a.kf=c):(b=a.sf,c=a.kf);var d=b,e=c;0<h.forcedAspectRatio&&(d/e<h.forcedAspectRatio?d=Math.round(e*h.forcedAspectRatio):e=Math.round(d/h.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/d,screen.height/e);d=Math.round(d*g);e=Math.round(e*g)}A?(a.width!=d&&(a.width=
d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var Ha,C=12288,Oa=!1,Pa=0,Qa=0,Ra=0,D={alpha:!1,depth:!1,stencil:!1,antialias:!1},Sa={},Ta,E,Ua=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,g)=>b.drawArraysInstancedANGLE(c,d,e,g),a.drawElementsInstanced=(c,d,e,g,f)=>b.drawElementsInstancedANGLE(c,d,e,g,f))},Va=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),
a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},Wa=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},Xa=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},Ya=1,Za=[],F=[],$a=[],G=[],H=[],J=[],ab=[],K=[],M=[],bb={},cb=4,db=0,eb=a=>{for(var b=Ya++,c=a.length;c<b;c++)a[c]=null;return b},fb=(a,b,c,d)=>{for(var e=0;e<a;e++){var g=E[c](),f=g&&eb(d);g?(g.name=f,d[f]=g):N||=1282;u[b+4*e>>2]=f}},hb=(a,b)=>{a.oe||(a.oe=a.getContext,a.getContext=function(d,e){e=a.oe(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?gb(c,b):0},gb=(a,b)=>{var c=
eb(K),d={handle:c,attributes:b,version:b.Se,ie:a};a.canvas&&(a.canvas.me=d);K[c]=d;("undefined"==typeof b.ff||b.ff)&&ib(d);return c},kb=a=>{jb=K[a];h.ctx=E=jb?.ie},ib=a=>{a||=jb;if(!a.mf){a.mf=!0;var b=a.ie;b.Ef=b.getExtension("WEBGL_multi_draw");b.hf=b.getExtension("EXT_polygon_offset_clamp");b.gf=b.getExtension("EXT_clip_control");b.rf=b.getExtension("WEBGL_polygon_mode");Ua(b);Va(b);Wa(b);b.he=b.getExtension("EXT_disjoint_timer_query");Xa(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||
b.getExtension(c)})}},lb={},N,jb,mb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},O=(a,b,c)=>{var d=r;if(!(0<c))return 0;var e=b;c=b+c-1;for(var g=0;g<a.length;++g){var f=a.charCodeAt(g);if(55296<=f&&57343>=f){var l=a.charCodeAt(++g);f=65536+((f&1023)<<10)|l&1023}if(127>=f){if(b>=c)break;d[b++]=f}else{if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6}else{if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12}else{if(b+3>=c)break;d[b++]=
240|f>>18;d[b++]=128|f>>12&63}d[b++]=128|f>>6&63}d[b++]=128|f&63}}d[b]=0;return b-e},Q=a=>{var b=mb(a)+1,c=P(b);c&&O(a,c,b);return c},Cb=(a,b,c,d,e)=>{function g(){return f<nb?(Ca(),!1):!0}ob=a;pb=d;var f=nb;qb=!1;rb=function(){if(!p)if(0<sb.length){var l=sb.shift();l.Af(l.tf);if(tb){var n=tb,t=0==n%1?n-1:Math.floor(n);tb=l.wf?t:(8*n+(t+.5))/9}h.setStatus&&(l=h.statusMessage||"Please wait...",n=tb??0,t=ub.zf??0,n?n<t?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(l):h.setStatus(""));
g()&&setTimeout(rb,0)}else if(g())if(vb=vb+1|0,1==wb&&1<xb&&0!=vb%xb)R();else{0==wb&&(yb=performance.now());a:if(!p){for(l of zb)if(!1===l())break a;if(!p)try{a(),Ca()}catch(B){za(B)}for(n of Ab)n()}g()&&R()}};e||(0<b?Bb(0,1E3/b):Bb(1,1),R());if(c)throw"unwind";},qb=!1,R=null,nb=0,ob=null,pb=0,wb=0,xb=0,vb=0,sb=[],zb=[],Ab=[],Db=0;
function Eb(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Db)Db=b+1E3/60;else for(;b+2>=Db;)Db+=1E3/60;setTimeout(a,Math.max(Db-b,0))}}
var ub={},rb,tb,yb,Fb,Bb=(a,b)=>{wb=a;xb=b;if(ob)if(qb||=!0,0==a)R=function(){setTimeout(rb,Math.max(0,yb+b-performance.now())|0)};else if(1==a)R=function(){Eb(rb)};else if(2==a){if("undefined"==typeof Fb)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Fb=d=>{c.push(d);postMessage("setimmediate","*")}}else Fb=setImmediate;R=function(){Fb(rb)}}},Gb=[],Hb=(a,b)=>{Gb.length=0;
for(var c;c=r[a++];){var d=105!=c;d&=112!=c;b+=d&&b%8?4:0;Gb.push(112==c?v[b>>2]:106==c?ka[b>>3]:105==c?u[b>>2]:x[b>>3]);b+=d?8:4}return Gb};function Ib(a){var b=S.de[a];b.target.removeEventListener(b.ae,b.Qe,b.be);S.de.splice(a,1)}function Jb(a,b,c){function d(g,f){if(g.length!=f.length)return!1;for(var l in g)if(g[l]!=f[l])return!1;return!0}for(var e of S.je)if(e.Ie==a&&d(e.Oe,c))return;S.je.push({Ie:a,Ue:b,Oe:c});S.je.sort((g,f)=>g.Ue<f.Ue)}function Kb(a){S.je=S.je.filter(b=>b.Ie!=a)}
function Lb(){return navigator.userActivation?navigator.userActivation.isActive:S.De&&S.$e.pe}function Mb(){if(Lb()){var a=S.je;S.je=[];for(var b of a)b.Ie(...b.Oe)}}function T(a){if(!a.target)return-4;if(a.ce)a.Qe=function(c){++S.De;S.$e=a;Mb();a.ee(c);Mb();--S.De},a.target.addEventListener(a.ae,a.Qe,a.be),S.de.push(a);else for(var b=0;b<S.de.length;++b)S.de[b].target==a.target&&S.de[b].ae==a.ae&&Ib(b--);return 0}
function Nb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var S={uf:0,Ce:0,Ee:0,xe:0,Ne:0,Ke:0,Ae:0,yf:0,Ff:0,xf:0,Be:0,Ge:0,Me:0,Je:0,Cf(a,b,c){q.set(q.subarray(b,b+c),a)},Gf(){for(;S.de.length;)Ib(S.de.length-1);S.je=[]},De:0,je:[],de:[],pf:(a,b)=>{for(var c=0;c<S.de.length;++c)S.de[c].target!=a||b&&b!=S.de[c].ae||Ib(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},Ob=[0,document,window],U=a=>{a=2<a?a?z(r,a):"":a;return Ob[a]||document.querySelector(a)},Qb=a=>{var b=mb(a)+1,c=Pb(b);O(a,c,b);return c},Tb=a=>
{var b=Rb(),c=Pb(8),d=c+4;a=Qb(a.id);if(a=U(a))u[c>>2]=a.width,u[d>>2]=a.height;c=[u[c>>2],u[d>>2]];Sb(b);return c},Ub=(a,b,c)=>{a=U(a);if(!a)return-4;a.width=b;a.height=c;return 0},Vb=(a,b,c)=>{if(a.vf){var d=Rb();a=Qb(a.id);Ub(a,b,c);Sb(d)}else a.width=b,a.height=c},Wb={},Xb=[],Yb,V=a=>{var b=Xb[a];b||(Xb[a]=b=Yb.get(a));return b},Zb=a=>{function b(){document.fullscreenElement||document.webkitFullscreenElement||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",
b),Vb(a,d,e),a.style.width=g,a.style.height=f,a.style.backgroundColor=l,n||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=n,a.style.paddingLeft=t,a.style.paddingRight=B,a.style.paddingTop=L,a.style.paddingBottom=I,a.style.marginLeft=bd,a.style.marginRight=cd,a.style.marginTop=dd,a.style.marginBottom=ed,document.body.style.margin=fd,document.documentElement.style.overflow=gd,document.body.scroll=hd,a.style.ke=jd,a.me&&a.me.ie.viewport(0,0,d,e),Wb.qe&&V(Wb.qe)(37,
0,Wb.Pe))}var c=Tb(a),d=c[0],e=c[1],g=a.style.width,f=a.style.height,l=a.style.backgroundColor,n=document.body.style.backgroundColor,t=a.style.paddingLeft,B=a.style.paddingRight,L=a.style.paddingTop,I=a.style.paddingBottom,bd=a.style.marginLeft,cd=a.style.marginRight,dd=a.style.marginTop,ed=a.style.marginBottom,fd=document.body.style.margin,gd=document.documentElement.style.overflow,hd=document.body.scroll,jd=a.style.ke;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",
b)},$b=(a,b,c)=>{a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"},ac=a=>0>Ob.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},bc=(a,b)=>{if(0!=b.He||0!=b.ye){Zb(a);var c=b.qf?innerWidth:screen.width,d=b.qf?innerHeight:screen.height,e=ac(a),g=e.width;e=e.height;var f=Tb(a),l=f[0];f=f[1];3==b.He?($b(a,(d-e)/2,(c-g)/2),c=g,d=e):2==b.He&&(c*f<l*d?(g=f*c/l,$b(a,(d-g)/2,0),d=g):(g=l*d/f,$b(a,0,(c-g)/2),c=g));var n;(n=a.style).backgroundColor||(n.backgroundColor=
"black");let t;(t=document.body.style).backgroundColor||(t.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.jf&&(a.style.ke="optimizeSpeed",a.style.ke="-moz-crisp-edges",a.style.ke="-o-crisp-edges",a.style.ke="-webkit-optimize-contrast",a.style.ke="optimize-contrast",a.style.ke="crisp-edges",a.style.ke="pixelated");n=2==b.ye?devicePixelRatio:1;0!=b.ye&&(c=c*n|0,d=d*n|0,Vb(a,c,d),a.me&&a.me.ie.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);
else return S.fullscreenEnabled()?-3:-1;Wb=b;b.qe&&V(b.qe)(37,0,b.Pe);return 0},cc=a=>{if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?-3:-1;return 0},dc=(a,b)=>{x[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)x[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)x[a+8*c+528>>3]="object"==typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)q[a+c+1040]="object"==typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];
q[a+1104]=b.connected;u[a+1108>>2]=b.index;u[a+8>>2]=b.axes.length;u[a+12>>2]=b.buttons.length;O(b.id,a+1112,64);O(b.mapping,a+1176,64)},ec=(a,b)=>{E.attachShader(F[a],J[b])},fc=(a,b)=>{E.bindBuffer(a,Za[b])},gc=(a,b)=>E.blendFunc(a,b),hc=(a,b,c,d)=>{E.bufferData(a,c?r.subarray(c,c+b):b,d)},ic=a=>E.clear(a),jc=(a,b,c,d)=>E.clearColor(a,b,c,d),kc=a=>{E.compileShader(J[a])},lc=()=>{var a=eb(F),b=E.createProgram();b.name=a;b.we=b.ue=b.ve=0;b.Le=1;F[a]=b;return a},mc=a=>{var b=eb(J);J[b]=E.createShader(a);
return b},nc=a=>E.disable(a),oc=[],pc=(a,b,c,d)=>{E.drawElements(a,b,c,d)},qc=a=>E.enable(a),rc=a=>{E.enableVertexAttribArray(a)},sc=(a,b)=>{fb(a,b,"createBuffer",Za)},tc=(a,b,c,d,e,g,f,l)=>{b=F[b];if(a=E[a](b,c))d=l&&O(a.name,l,d),e&&(u[e>>2]=d),g&&(u[g>>2]=a.size),f&&(u[f>>2]=a.type)},uc=(a,b)=>E.getAttribLocation(F[a],b?z(r,b):""),vc=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&(N||=1280);return;case 36345:d=0;break;case 34466:var e=E.getParameter(34467);d=
e?e.length:0}if(void 0===d)switch(e=E.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":N||=1280;return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:N||=1280;return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:u[b+4*a>>2]=e[a];break;case 2:w[b+4*a>>2]=e[a];break;
case 4:q[b+a]=e[a]?1:0}return}try{d=e.name|0}catch(g){N||=1280;m(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${g})`);return}}break;default:N||=1280;m(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${e} of type ${typeof e}!`);return}switch(c){case 1:c=d;v[b>>2]=c;v[b+4>>2]=(c-v[b>>2])/4294967296;break;case 0:u[b>>2]=d;break;case 2:w[b>>2]=d;break;case 4:q[b]=d?1:0}}else N||=1281},wc=(a,b,c)=>{if(c){a=E.he.getQueryObjectEXT(M[a],
b);var d;"boolean"==typeof a?d=a?1:0:d=a;v[c>>2]=d;v[c+4>>2]=(d-v[c>>2])/4294967296}else N||=1281},xc=(a,b,c)=>{if(c){a=E.he.getQueryObjectEXT(M[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;u[c>>2]=d}else N||=1281},yc=()=>{var a=Xa(E);return a=a.concat(a.map(b=>"GL_"+b))},zc=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Ac=a=>{var b=a.ne,c=a.We,d;if(!b){a.ne=b={};a.Ve={};var e=E.getProgramParameter(a,35718);for(d=0;d<e;++d){var g=E.getActiveUniform(a,d);var f=g.name;g=g.size;var l=zc(f);l=0<l?f.slice(0,
l):f;var n=a.Le;a.Le+=g;c[l]=[g,n];for(f=0;f<g;++f)b[n]=f,a.Ve[n++]=l}}},Bc=(a,b)=>{b=b?z(r,b):"";if(a=F[a]){Ac(a);var c=a.ne,d=0,e=b,g=zc(b);0<g&&(d=parseInt(b.slice(g+1))>>>0,e=b.slice(0,g));if((e=a.We[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||E.getUniformLocation(a,b)))return d}else N||=1281;return-1},W=a=>{var b=E.af;if(b){var c=b.ne[a];"number"==typeof c&&(b.ne[a]=c=E.getUniformLocation(b,b.Ve[a]+(0<c?`[${c}]`:"")));return c}N||=1282},Cc=(a,b,c,d)=>{if(c)if(a=F[a],Ac(a),a=E.getUniform(a,W(b)),"number"==
typeof a||"boolean"==typeof a)switch(d){case 0:u[c>>2]=a;break;case 2:w[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:u[c+4*b>>2]=a[b];break;case 2:w[c+4*b>>2]=a[b]}else N||=1281},Dc=(a,b,c,d)=>{if(c)if(a=E.getVertexAttrib(a,b),34975==b)u[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:u[c>>2]=a;break;case 2:w[c>>2]=a;break;case 5:u[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:u[c+4*b>>2]=a[b];break;case 2:w[c+4*b>>2]=a[b];break;case 5:u[c+
4*b>>2]=Math.fround(a[b])}else N||=1281},Ec=a=>{a=F[a];E.linkProgram(a);a.ne=0;a.We={}},Fc=(a,b,c,d,e)=>{a-=5120;a=1==a?r:4==a?u:6==a?w:5==a||28922==a?v:ja;b=d*((db||c)*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+cb-1&-cb);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},Gc=(a,b,c,d)=>{for(var e="",g=0;g<b;++g){var f=(f=v[c+4*g>>2])?z(r,f,d?v[d+4*g>>2]:void 0):"";e+=f}E.shaderSource(J[a],e)},Hc=(a,b)=>{E.uniform1f(W(a),b)},X=[],
Ic=[],Jc=(a,b,c,d)=>{E.uniform3f(W(a),b,c,d)},Kc=(a,b,c,d)=>{if(18>=b){var e=X[16*b],g=w;d>>=2;b*=16;for(var f=0;f<b;f+=16){var l=d+f;e[f]=g[l];e[f+1]=g[l+1];e[f+2]=g[l+2];e[f+3]=g[l+3];e[f+4]=g[l+4];e[f+5]=g[l+5];e[f+6]=g[l+6];e[f+7]=g[l+7];e[f+8]=g[l+8];e[f+9]=g[l+9];e[f+10]=g[l+10];e[f+11]=g[l+11];e[f+12]=g[l+12];e[f+13]=g[l+13];e[f+14]=g[l+14];e[f+15]=g[l+15]}}else e=w.subarray(d>>2,d+64*b>>2);E.uniformMatrix4fv(W(a),!!c,e)},Lc=a=>{a=F[a];E.useProgram(a);E.af=a},Mc=(a,b,c,d,e,g)=>{E.vertexAttribPointer(a,
b,c,!!d,e,g)},Nc=(a,b,c,d)=>E.viewport(a,b,c,d),Oc=(a,b)=>{if(!S.fullscreenEnabled())return-1;a=U(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?Lb()?bc(a,b):b.ef?(Jb(bc,1,[a,b]),1):-2:-3:-4},Pc=()=>{try{if(navigator.getGamepads)return(S.te=navigator.getGamepads())?0:-1}catch(a){navigator.getGamepads=null}return-1},Qc=(a,b)=>{var c={target:U(2),ae:"beforeunload",ce:b,ee:(d=event)=>{var e=V(b)(28,0,a);e&&=e?z(r,e):"";if(e)return d.preventDefault(),d.returnValue=e},be:!0};return T(c)},Rc=
(a,b,c,d,e,g)=>{S.Ae||(S.Ae=P(256));a={target:U(a),ae:g,ce:d,ee:(f=event)=>{var l=f.target.id?f.target.id:"",n=S.Ae;O(Nb(f.target),n+0,128);O(l,n+128,128);V(d)(e,n,b)&&f.preventDefault()},be:c};return T(a)},Sc=(a,b,c,d,e)=>{S.Be||(S.Be=P(276));return T({target:a,ae:e,ce:d,ee:(g=event)=>{var f=S.Be,l=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,n=!!l;q[f]=n;q[f+1]=S.fullscreenEnabled();var t=n?l:S.nf,B=t?.id||"";O(Nb(t),f+
2,128);O(B,f+130,128);u[f+260>>2]=t?t.clientWidth:0;u[f+264>>2]=t?t.clientHeight:0;u[f+268>>2]=screen.width;u[f+272>>2]=screen.height;n&&(S.nf=l);V(d)(19,f,b)&&g.preventDefault()},be:c})},Tc=(a,b,c,d,e)=>{S.Ce||(S.Ce=P(1240));b={target:U(2),pe:!0,ae:e,ce:c,ee:(g=event)=>{var f=S.Ce;dc(f,g.gamepad);V(c)(d,f,a)&&g.preventDefault()},be:b};return T(b)},Uc=(a,b,c,d,e,g)=>{S.Ee||(S.Ee=P(160));a={target:U(a),ae:g,ce:d,ee:f=>{var l=S.Ee;x[l>>3]=f.timeStamp;var n=l>>2;u[n+2]=f.location;q[l+12]=f.ctrlKey;q[l+
13]=f.shiftKey;q[l+14]=f.altKey;q[l+15]=f.metaKey;q[l+16]=f.repeat;u[n+5]=f.charCode;u[n+6]=f.keyCode;u[n+7]=f.which;O(f.key||"",l+32,32);O(f.code||"",l+64,32);O(f.char||"",l+96,32);O(f.locale||"",l+128,32);V(d)(e,l,b)&&f.preventDefault()},be:c};return T(a)},Vc=(a,b,c)=>{x[a>>3]=b.timeStamp;var d=a>>2;u[d+2]=b.screenX;u[d+3]=b.screenY;u[d+4]=b.clientX;u[d+5]=b.clientY;q[a+24]=b.ctrlKey;q[a+25]=b.shiftKey;q[a+26]=b.altKey;q[a+27]=b.metaKey;ia[2*d+14]=b.button;ia[2*d+15]=b.buttons;u[d+8]=b.movementX;
u[d+9]=b.movementY;a=ac(c);u[d+10]=b.clientX-(a.left|0);u[d+11]=b.clientY-(a.top|0)},Wc=(a,b,c,d,e,g)=>{S.xe||(S.xe=P(64));a=U(a);return T({target:a,pe:"mousemove"!=g&&"mouseenter"!=g&&"mouseleave"!=g,ae:g,ce:d,ee:(f=event)=>{Vc(S.xe,f,a);V(d)(e,S.xe,b)&&f.preventDefault()},be:c})},Xc=(a,b,c,d,e)=>{S.Ge||(S.Ge=P(257));return T({target:a,ae:e,ce:d,ee:(g=event)=>{var f=S.Ge,l=document.pointerLockElement||document.oe||document.Ye||document.Xe;q[f]=!!l;var n=l?.id||"";O(Nb(l),f+1,128);O(n,f+129,128);
V(d)(20,f,b)&&g.preventDefault()},be:c})},Yc=(a,b,c,d)=>{S.Ke||(S.Ke=P(36));a=U(a);return T({target:a,ae:"resize",ce:d,ee:(e=event)=>{if(e.target==a){var g=document.body;if(g){var f=S.Ke;u[f>>2]=0;u[f+4>>2]=g.clientWidth;u[f+8>>2]=g.clientHeight;u[f+12>>2]=innerWidth;u[f+16>>2]=innerHeight;u[f+20>>2]=outerWidth;u[f+24>>2]=outerHeight;u[f+28>>2]=pageXOffset|0;u[f+32>>2]=pageYOffset|0;V(d)(10,f,b)&&e.preventDefault()}}},be:c})},Zc=(a,b,c,d,e,g)=>{S.Je||(S.Je=P(1552));a=U(a);return T({target:a,pe:"touchstart"==
g||"touchend"==g,ae:g,ce:d,ee:f=>{var l={},n=f.touches;for(var t of n)t.Re=t.Te=0,l[t.identifier]=t;for(var B of f.changedTouches)B.Re=1,l[B.identifier]=B;for(var L of f.targetTouches)l[L.identifier].Te=1;n=S.Je;x[n>>3]=f.timeStamp;q[n+12]=f.ctrlKey;q[n+13]=f.shiftKey;q[n+14]=f.altKey;q[n+15]=f.metaKey;t=n+16;B=ac(a);L=0;for(let I of Object.values(l))if(l=t>>2,u[l]=I.identifier,u[l+1]=I.screenX,u[l+2]=I.screenY,u[l+3]=I.clientX,u[l+4]=I.clientY,u[l+5]=I.pageX,u[l+6]=I.pageY,q[t+28]=I.Re,q[t+29]=I.Te,
u[l+8]=I.clientX-(B.left|0),u[l+9]=I.clientY-(B.top|0),t+=48,31<++L)break;u[n+8>>2]=L;V(d)(e,n,b)&&f.preventDefault()},be:c})},$c=(a,b,c)=>{var d=Ob[1];S.Me||(S.Me=P(8));return T({target:d,ae:"visibilitychange",ce:c,ee:(e=event)=>{var g=S.Me,f=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);q[g]=document.hidden;u[g+4>>2]=f;V(c)(21,g,a)&&e.preventDefault()},be:b})},ad=(a,b,c,d)=>{S.Ne||(S.Ne=P(96));return T({target:a,pe:!0,ae:"wheel",ce:d,ee:(e=event)=>{var g=S.Ne;Vc(g,
e,a);x[g+64>>3]=e.deltaX;x[g+72>>3]=e.deltaY;x[g+80>>3]=e.deltaZ;u[g+88>>2]=e.deltaMode;V(d)(9,g,b)&&e.preventDefault()},be:c})},kd={},md=()=>{if(!ld){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ba||"./this.program"},b;for(b in kd)void 0===kd[b]?delete a[b]:a[b]=kd[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);ld=c}return ld},ld,nd=[null,[],[]],od=(a,
b,c)=>{a.addEventListener(b,c,{once:!0})},pd=a=>{var b;b||=[document,document.getElementById("canvas")];["keydown","mousedown","touchstart"].forEach(c=>{b.forEach(d=>{d&&od(d,c,()=>{"suspended"===a.state&&a.resume()})})})},qd=(a,b=[])=>{V(a)(...b)};
h.requestFullscreen=function(a,b){function c(){Da=!1;var g=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===g?(d.exitFullscreen=Ka,Ja&&d.requestPointerLock(),Da=!0,A?("undefined"!=typeof SDL&&(u[SDL.screen>>2]=v[SDL.screen>>2]|8388608),Na(h.canvas),Ma()):Na(d)):(g.parentNode.insertBefore(d,g),g.parentNode.removeChild(g),A?("undefined"!=typeof SDL&&(u[SDL.screen>>2]=v[SDL.screen>>
2]&-8388609),Na(h.canvas),Ma()):Na(d));h.onFullScreen?.(Da);h.onFullscreen?.(Da)}Ja=a;A=b;"undefined"==typeof Ja&&(Ja=!0);"undefined"==typeof A&&(A=!1);var d=h.canvas;Ia||(Ia=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=e.requestFullscreen||
e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()};h.setCanvasSize=function(a,b,c){Na(h.canvas,a,b);c||Ma()};h.getUserMedia=function(a){let b;(b=window).getUserMedia||(b.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)};
h.createContext=function(a,b,c,d){if(b&&h.ctx&&a==h.canvas)return h.ctx;var e;if(b){var g={antialias:!1,alpha:!1,Se:1};if(d)for(var f in d)g[f]=d[f];if("undefined"!=typeof lb&&(e=hb(a,g)))var l=K[e].ie}else l=a.getContext("2d");if(!l)return null;c&&(h.ctx=l,b&&kb(e),Fa.forEach(n=>n()),Ga());return l};h.requestAnimationFrame=Eb;h.pauseMainLoop=function(){R=null;nb++};h.resumeMainLoop=function(){nb++;var a=wb,b=xb,c=ob;ob=null;Cb(c,0,!1,pb,!0);Bb(a,b);R()};h.preMainLoop&&zb.push(h.preMainLoop);
h.postMainLoop&&Ab.push(h.postMainLoop);for(let a=0;32>a;++a)oc.push(Array(a));for(var rd=new Float32Array(288),Y=0;288>=Y;++Y)X[Y]=rd.subarray(0,Y);var sd=new Int32Array(288);for(Y=0;288>=Y;++Y)Ic[Y]=sd.subarray(0,Y);h.noExitRuntime&&(wa=h.noExitRuntime);h.print&&(da=h.print);h.printErr&&(m=h.printErr);h.wasmBinary&&(ea=h.wasmBinary);h.arguments&&(aa=h.arguments);h.thisProgram&&(ba=h.thisProgram);
var td={36587469:()=>"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?!0:!1,36587616:()=>"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?!0:!1,36587850:a=>{"undefined"===typeof h.SDL2&&(h.SDL2={});var b=h.SDL2;a?b.capture={}:b.audio={};b.$d||("undefined"!==typeof AudioContext?b.$d=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.$d=new webkitAudioContext),
b.$d&&"undefined"===typeof navigator.userActivation&&pd(b.$d));return void 0===b.$d?-1:0},36588402:()=>h.SDL2.$d.sampleRate,36588470:(a,b,c,d)=>{function e(){}function g(l){void 0!==f.capture.ge&&(clearInterval(f.capture.ge),f.capture.ge=void 0,f.capture.le=void 0);f.capture.Fe=f.$d.createMediaStreamSource(l);f.capture.fe=f.$d.createScriptProcessor(b,a,1);f.capture.fe.onaudioprocess=function(n){void 0!==f&&void 0!==f.capture&&(n.outputBuffer.getChannelData(0).fill(0),f.capture.ze=n.inputBuffer,qd(c,
[d]))};f.capture.Fe.connect(f.capture.fe);f.capture.fe.connect(f.$d.destination);f.capture.stream=l}var f=h.SDL2;f.capture.le=f.$d.createBuffer(a,b,f.$d.sampleRate);f.capture.le.getChannelData(0).fill(0);f.capture.ge=setInterval(function(){f.capture.ze=f.capture.le;qd(c,[d])},b/f.$d.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(g).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,
video:!1},g,e)},36590163:(a,b,c,d)=>{var e=h.SDL2;e.audio.fe=e.$d.createScriptProcessor(b,0,a);e.audio.fe.onaudioprocess=function(g){void 0!==e&&void 0!==e.audio&&(void 0!==e.audio.ge&&(clearInterval(e.audio.ge),e.audio.ge=void 0,e.audio.le=void 0),e.audio.se=g.outputBuffer,qd(c,[d]))};e.audio.fe.connect(e.$d.destination);"suspended"===e.$d.state&&(e.audio.le=e.$d.createBuffer(a,b,e.$d.sampleRate),e.audio.le.getChannelData(0).fill(0),e.audio.ge=setInterval(function(){"undefined"!==typeof navigator.userActivation&&
navigator.userActivation.hasBeenActive&&e.$d.resume();e.audio.se=e.audio.le;qd(c,[d]);e.audio.se=void 0},b/e.$d.sampleRate*1E3))},36591338:(a,b)=>{for(var c=h.SDL2,d=c.capture.ze.numberOfChannels,e=0;e<d;++e){var g=c.capture.ze.getChannelData(e);if(g.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+g.length+" samples vs expected "+b+" samples!";if(1==d)for(var f=0;f<b;++f)xa(a+4*f,g[f]);else for(f=0;f<b;++f)xa(a+4*(f*d+e),g[f])}},36591943:(a,b)=>{var c=h.SDL2;a>>>=2;for(var d=
c.audio.se.numberOfChannels,e=0;e<d;++e){var g=c.audio.se.getChannelData(e);if(g.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+g.length+" samples vs expected "+b+" samples!";for(var f=0;f<b;++f)g[f]=w[a+(f*d+e)]}},36592432:a=>{var b=h.SDL2;if(a){void 0!==b.capture.ge&&clearInterval(b.capture.ge);if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c])}void 0!==b.capture.fe&&(b.capture.fe.onaudioprocess=
function(){},b.capture.fe.disconnect());void 0!==b.capture.Fe&&b.capture.Fe.disconnect();b.capture=void 0}else void 0!=b.audio.fe&&b.audio.fe.disconnect(),void 0!==b.audio.ge&&clearInterval(b.audio.ge),b.audio=void 0;void 0!==b.$d&&void 0===b.audio&&void 0===b.capture&&(b.$d.close(),b.$d=void 0)},36593438:(a,b,c)=>{h.SDL2||(h.SDL2={});var d=h.SDL2;d.Ze!==h.canvas&&(d.re=h.createContext(h.canvas,!1,!0),d.Ze=h.canvas);if(d.w!==a||d.h!==b||d.lf!==d.re)d.image=d.re.createImageData(a,b),d.w=a,d.h=b,d.lf=
d.re;a=d.image.data;b=c/4;var e=0;if("undefined"!==typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var g=u[b];a[e]=g&255;a[e+1]=g>>8&255;a[e+2]=g>>16&255;a[e+3]=255;b++;e+=4}else if(d.cf!==a&&(d.bf=new Int32Array(a.buffer),d.df=new Uint8Array(a.buffer),d.cf=a),a=d.bf,c=a.length,a.set(u.subarray(b,b+c)),a=d.df,b=3,e=b+4*c,0==c%8)for(;b<e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|
0;else for(;b<e;)a[b]=255,b=b+4|0;d.re.putImageData(d.image,0,0)},36594906:(a,b,c,d,e)=>{var g=document.createElement("canvas");g.width=a;g.height=b;var f=g.getContext("2d");a=f.createImageData(a,b);b=a.data;e/=4;var l=0,n;if("undefined"!==typeof CanvasPixelArray&&b instanceof CanvasPixelArray)for(n=b.length;l<n;){var t=u[e];b[l]=t&255;b[l+1]=t>>8&255;b[l+2]=t>>16&255;b[l+3]=t>>24&255;e++;l+=4}else b=new Int32Array(b.buffer),n=b.length,b.set(u.subarray(e,e+n));f.putImageData(a,0,0);c=0===c&&0===d?
"url("+g.toDataURL()+"), auto":"url("+g.toDataURL()+") "+c+" "+d+", auto";d=P(c.length+1);O(c,d,c.length+1);return d},36595894:a=>{h.canvas&&(h.canvas.style.cursor=a?z(r,a):"")},36595977:()=>{h.canvas&&(h.canvas.style.cursor="none")},36596046:()=>window.innerWidth,36596076:()=>window.innerHeight},ud={Y:function(){return 0},Ya:function(){return 0},_a:function(){},Ta:()=>{},Ia:a=>{if(12448==a)return C=12288,1;C=12300;return 0},La:(a,b,c,d,e)=>{if(62E3!=a)C=12296,c=0;else{if(b)for(;;){a=u[b>>2];if(12321==
a)D.alpha=0<u[b+4>>2];else if(12325==a)D.depth=0<u[b+4>>2];else if(12326==a)D.stencil=0<u[b+4>>2];else if(12337==a)a=u[b+4>>2],D.antialias=0<a;else if(12338==a)a=u[b+4>>2],D.antialias=1==a;else if(12544==a)D.Bf=12547!=u[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(u[e>>2]=1),c&&0<d&&(v[c>>2]=62002),C=12288,c=1):(C=12300,c=0)}return c},za:(a,b,c,d)=>{if(62E3!=a)return C=12296,0;for(a=1;;){b=u[d>>2];if(12440==b)a=u[d+4>>2];else if(12344==b)break;else return C=12292,0;d+=8}if(2!=a)return C=12293,
0;D.Se=a-1;D.Df=0;Ta=hb(h.canvas,D);if(0!=Ta)return C=12288,kb(Ta),Fa.forEach(e=>e()),kb(null),62004;C=12297;return 0},Ba:(a,b)=>{if(62E3!=a)return C=12296,0;if(62002!=b)return C=12293,0;C=12288;return 62006},Aa:(a,b)=>{if(62E3!=a)return C=12296,0;if(62004!=b)return C=12294,0;a=Ta;jb===K[a]&&(jb=null);"object"==typeof S&&S.pf(K[a].ie.canvas);K[a]?.ie.canvas&&(K[a].ie.canvas.me=void 0);K[a]=null;C=12288;Pa==b&&(Pa=0);return 1},Ca:(a,b)=>{if(62E3!=a)return C=12296,0;if(62006!=b)return C=12301,1;Qa==
b&&(Qa=0);Ra==b&&(Ra=0);C=12288;return 1},Ma:(a,b,c,d)=>{if(62E3!=a)return C=12296,0;if(62002!=b)return C=12293,0;if(!d)return C=12300,0;C=12288;switch(c){case 12320:return u[d>>2]=D.alpha?32:24,1;case 12321:return u[d>>2]=D.alpha?8:0,1;case 12322:return u[d>>2]=8,1;case 12323:return u[d>>2]=8,1;case 12324:return u[d>>2]=8,1;case 12325:return u[d>>2]=D.depth?24:0,1;case 12326:return u[d>>2]=D.stencil?8:0,1;case 12327:return u[d>>2]=12344,1;case 12328:return u[d>>2]=62002,1;case 12329:return u[d>>
2]=0,1;case 12330:return u[d>>2]=4096,1;case 12331:return u[d>>2]=16777216,1;case 12332:return u[d>>2]=4096,1;case 12333:return u[d>>2]=0,1;case 12334:return u[d>>2]=0,1;case 12335:return u[d>>2]=12344,1;case 12337:return u[d>>2]=D.antialias?4:0,1;case 12338:return u[d>>2]=D.antialias?1:0,1;case 12339:return u[d>>2]=4,1;case 12340:return u[d>>2]=12344,1;case 12341:case 12342:case 12343:return u[d>>2]=-1,1;case 12345:case 12346:return u[d>>2]=0,1;case 12347:return u[d>>2]=0,1;case 12348:return u[d>>
2]=1;case 12349:case 12350:return u[d>>2]=0,1;case 12351:return u[d>>2]=12430,1;case 12352:return u[d>>2]=4,1;case 12354:return u[d>>2]=0,1;default:return C=12292,0}},Q:a=>{C=12288;return 0!=a&&1!=a?0:62E3},ya:()=>C,Ja:(a,b,c)=>{if(62E3!=a)return C=12296,0;b&&(u[b>>2]=1);c&&(u[c>>2]=4);Oa=!0;C=12288;return 1},Da:(a,b,c,d)=>{if(62E3!=a)return C=12296,0;if(0!=d&&62004!=d)return C=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return C=12301,0;kb(d?Ta:null);Pa=d;Ra=b;Qa=c;C=12288;return 1},xa:(a,b)=>{if(62E3!=
a)return C=12296,0;C=12288;if(Sa[b])return Sa[b];switch(b){case 12371:a=Q("Emscripten");break;case 12372:a=Q("1.4 Emscripten EGL");break;case 12373:a=Q("");break;case 12429:a=Q("OpenGL_ES");break;default:return C=12300,0}return Sa[b]=a},Ea:()=>{if(Oa)if(E)if(E.isContextLost())C=12302;else return C=12288,1;else C=12290;else C=12289;return 0},Fa:(a,b)=>{if(62E3!=a)return C=12296,0;0==b?Bb(0,0):Bb(1,b);C=12288;return 1},Ka:a=>{if(62E3!=a)return C=12296,0;Ra=Qa=Pa=0;Oa=!1;C=12288;return 1},Ha:()=>{C=
12288;return 1},Ga:()=>{C=12288;return 1},Oa:(a,b,c)=>{b=Hb(b,c);return td[a](...b)},e:(a,b,c)=>{b=Hb(b,c);return td[a](...b)},Pa:(a,b,c)=>{b=Hb(b,c);return td[a](...b)},Z:()=>Date.now(),sa:()=>{if(!S.fullscreenEnabled())return-1;Kb(bc);var a=Ob[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},va:()=>{Kb(cc);if(document.exitPointerLock)document.exitPointerLock();else return-1;return 0},
l:()=>devicePixelRatio,g:(a,b,c)=>{a=U(a);if(!a)return-4;a=ac(a);x[b>>3]=a.width;x[c>>3]=a.height;return 0},T:(a,b)=>{if(0>a||a>=S.te.length)return-5;if(!S.te[a])return-7;dc(b,S.te[a]);return 0},V:()=>performance.now(),Na:()=>S.te.length,wa:(a,b)=>{u[a>>2]=screen.width;u[b>>2]=screen.height},Pd:a=>E.activeTexture(a),Od:ec,oa:(a,b)=>{E.he.beginQueryEXT(a,M[b])},Nd:(a,b,c)=>{E.bindAttribLocation(F[a],b,c?z(r,c):"")},Md:fc,Ld:(a,b)=>{E.bindFramebuffer(a,$a[b])},Kd:(a,b)=>{E.bindRenderbuffer(a,G[b])},
Jd:(a,b)=>{E.bindTexture(a,H[b])},fa:a=>{E.bindVertexArray(ab[a])},Id:(a,b,c,d)=>E.blendColor(a,b,c,d),Gd:a=>E.blendEquation(a),Fd:(a,b)=>E.blendEquationSeparate(a,b),Ed:gc,Dd:(a,b,c,d)=>E.blendFuncSeparate(a,b,c,d),Cd:hc,Bd:(a,b,c,d)=>{E.bufferSubData(a,b,r.subarray(d,d+c))},Ad:a=>E.checkFramebufferStatus(a),zd:ic,yd:jc,xd:a=>E.clearDepth(a),wd:a=>E.clearStencil(a),ab:(a,b)=>{E.gf.clipControlEXT(a,b)},vd:(a,b,c,d)=>{E.colorMask(!!a,!!b,!!c,!!d)},ud:kc,td:(a,b,c,d,e,g,f,l)=>{E.compressedTexImage2D(a,
b,c,d,e,g,r.subarray(l,l+f))},sd:(a,b,c,d,e,g,f,l,n)=>{E.compressedTexSubImage2D(a,b,c,d,e,g,f,r.subarray(n,n+l))},rd:(a,b,c,d,e,g,f,l)=>E.copyTexImage2D(a,b,c,d,e,g,f,l),qd:(a,b,c,d,e,g,f,l)=>E.copyTexSubImage2D(a,b,c,d,e,g,f,l),pd:lc,od:mc,nd:a=>E.cullFace(a),md:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=Za[d];e&&(E.deleteBuffer(e),e.name=0,Za[d]=null)}},ld:(a,b)=>{for(var c=0;c<a;++c){var d=u[b+4*c>>2],e=$a[d];e&&(E.deleteFramebuffer(e),e.name=0,$a[d]=null)}},kd:a=>{if(a){var b=F[a];b?(E.deleteProgram(b),
b.name=0,F[a]=null):N||=1281}},qa:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=M[d];e&&(E.he.deleteQueryEXT(e),M[d]=null)}},jd:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=G[d];e&&(E.deleteRenderbuffer(e),e.name=0,G[d]=null)}},id:a=>{if(a){var b=J[a];b?(E.deleteShader(b),J[a]=null):N||=1281}},hd:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=H[d];e&&(E.deleteTexture(e),e.name=0,H[d]=null)}},ea:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2];E.deleteVertexArray(ab[d]);ab[d]=null}},gd:a=>E.depthFunc(a),
fd:a=>{E.depthMask(!!a)},ed:(a,b)=>E.depthRange(a,b),dd:(a,b)=>{E.detachShader(F[a],J[b])},bd:nc,ad:a=>{E.disableVertexAttribArray(a)},$c:(a,b,c)=>{E.drawArrays(a,b,c)},aa:(a,b,c,d)=>{E.drawArraysInstanced(a,b,c,d)},ba:(a,b)=>{for(var c=oc[a],d=0;d<a;d++)c[d]=u[b+4*d>>2];E.drawBuffers(c)},_c:pc,Rd:(a,b,c,d,e)=>{E.drawElementsInstanced(a,b,c,d,e)},Zc:qc,Yc:rc,na:a=>{E.he.endQueryEXT(a)},Xc:()=>E.finish(),Wc:()=>E.flush(),Vc:(a,b,c,d)=>{E.framebufferRenderbuffer(a,b,c,G[d])},Uc:(a,b,c,d,e)=>{E.framebufferTexture2D(a,
b,c,H[d],e)},Tc:a=>E.frontFace(a),Sc:sc,Qc:(a,b)=>{fb(a,b,"createFramebuffer",$a)},ra:(a,b)=>{for(var c=0;c<a;c++){var d=E.he.createQueryEXT();if(!d){for(N||=1282;c<a;)u[b+4*c++>>2]=0;break}var e=eb(M);d.name=e;M[e]=d;u[b+4*c>>2]=e}},Pc:(a,b)=>{fb(a,b,"createRenderbuffer",G)},Oc:(a,b)=>{fb(a,b,"createTexture",H)},da:(a,b)=>{fb(a,b,"createVertexArray",ab)},Rc:a=>E.generateMipmap(a),Nc:(a,b,c,d,e,g,f)=>tc("getActiveAttrib",a,b,c,d,e,g,f),Mc:(a,b,c,d,e,g,f)=>tc("getActiveUniform",a,b,c,d,e,g,f),Lc:(a,
b,c,d)=>{a=E.getAttachedShaders(F[a]);var e=a.length;e>b&&(e=b);u[c>>2]=e;for(b=0;b<e;++b)u[d+4*b>>2]=J.indexOf(a[b])},Kc:uc,Ic:(a,b)=>vc(a,b,4),Hc:(a,b,c)=>{c?u[c>>2]=E.getBufferParameter(a,b):N||=1281},Gc:()=>{var a=E.getError()||N;N=0;return a},Fc:(a,b)=>vc(a,b,2),Ec:(a,b,c,d)=>{a=E.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;u[d>>2]=a},Dc:(a,b)=>vc(a,b,0),Bc:(a,b,c,d)=>{a=E.getProgramInfoLog(F[a]);null===a&&(a="(unknown error)");
b=0<b&&d?O(a,d,b):0;c&&(u[c>>2]=b)},Cc:(a,b,c)=>{if(c)if(a>=Ya)N||=1281;else if(a=F[a],35716==b)a=E.getProgramInfoLog(a),null===a&&(a="(unknown error)"),u[c>>2]=a.length+1;else if(35719==b){if(!a.we){var d=E.getProgramParameter(a,35718);for(b=0;b<d;++b)a.we=Math.max(a.we,E.getActiveUniform(a,b).name.length+1)}u[c>>2]=a.we}else if(35722==b){if(!a.ue)for(d=E.getProgramParameter(a,35721),b=0;b<d;++b)a.ue=Math.max(a.ue,E.getActiveAttrib(a,b).name.length+1);u[c>>2]=a.ue}else if(35381==b){if(!a.ve)for(d=
E.getProgramParameter(a,35382),b=0;b<d;++b)a.ve=Math.max(a.ve,E.getActiveUniformBlockName(a,b).length+1);u[c>>2]=a.ve}else u[c>>2]=E.getProgramParameter(a,b);else N||=1281},ha:wc,ja:xc,ga:wc,ia:xc,la:(a,b,c)=>{c?u[c>>2]=E.he.getQueryEXT(a,b):N||=1281},Ac:(a,b,c)=>{c?u[c>>2]=E.getRenderbufferParameter(a,b):N||=1281},yc:(a,b,c,d)=>{a=E.getShaderInfoLog(J[a]);null===a&&(a="(unknown error)");b=0<b&&d?O(a,d,b):0;c&&(u[c>>2]=b)},xc:(a,b,c,d)=>{a=E.getShaderPrecisionFormat(a,b);u[c>>2]=a.rangeMin;u[c+4>>
2]=a.rangeMax;u[d>>2]=a.precision},wc:(a,b,c,d)=>{if(a=E.getShaderSource(J[a]))b=0<b&&d?O(a,d,b):0,c&&(u[c>>2]=b)},zc:(a,b,c)=>{c?35716==b?(a=E.getShaderInfoLog(J[a]),null===a&&(a="(unknown error)"),u[c>>2]=a?a.length+1:0):35720==b?(a=E.getShaderSource(J[a]),u[c>>2]=a?a.length+1:0):u[c>>2]=E.getShaderParameter(J[a],b):N||=1281},vc:a=>{var b=bb[a];if(!b){switch(a){case 7939:b=Q(yc().join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=E.getParameter(a))||(N||=1280);b=b?Q(b):0;break;case 7938:b=
Q(`OpenGL ES 2.0 (${E.getParameter(7938)})`);break;case 35724:b=E.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=Q(b);break;default:N||=1280}bb[a]=b}return b},uc:(a,b,c)=>{c?w[c>>2]=E.getTexParameter(a,b):N||=1281},tc:(a,b,c)=>{c?u[c>>2]=E.getTexParameter(a,b):N||=1281},qc:Bc,sc:(a,b,c)=>{Cc(a,b,c,2)},rc:(a,b,c)=>{Cc(a,b,c,0)},mc:(a,b,c)=>{c?u[c>>2]=E.getVertexAttribOffset(a,b):N||=1281},
pc:(a,b,c)=>{Dc(a,b,c,2)},nc:(a,b,c)=>{Dc(a,b,c,5)},lc:(a,b)=>E.hint(a,b),kc:a=>(a=Za[a])?E.isBuffer(a):0,jc:a=>E.isEnabled(a),ic:a=>(a=$a[a])?E.isFramebuffer(a):0,hc:a=>(a=F[a])?E.isProgram(a):0,pa:a=>(a=M[a])?E.he.isQueryEXT(a):0,gc:a=>(a=G[a])?E.isRenderbuffer(a):0,fc:a=>(a=J[a])?E.isShader(a):0,ec:a=>(a=H[a])?E.isTexture(a):0,ca:a=>(a=ab[a])?E.isVertexArray(a):0,dc:a=>E.lineWidth(a),cc:Ec,bc:(a,b)=>{3317==a?cb=b:3314==a&&(db=b);E.pixelStorei(a,b)},$a:(a,b)=>{E.rf.polygonModeWEBGL(a,b)},ac:(a,
b)=>E.polygonOffset(a,b),bb:(a,b,c)=>{E.hf.polygonOffsetClampEXT(a,b,c)},ma:(a,b)=>{E.he.queryCounterEXT(M[a],b)},$b:(a,b,c,d,e,g,f)=>{(f=Fc(g,e,c,d,f))?E.readPixels(a,b,c,d,e,g,f):N||=1280},_b:()=>{},Zb:(a,b,c,d)=>E.renderbufferStorage(a,b,c,d),Yb:(a,b)=>{E.sampleCoverage(a,!!b)},Xb:(a,b,c,d)=>E.scissor(a,b,c,d),Wb:()=>{N||=1280},Vb:Gc,Ub:(a,b,c)=>E.stencilFunc(a,b,c),Tb:(a,b,c,d)=>E.stencilFuncSeparate(a,b,c,d),Sb:a=>E.stencilMask(a),Rb:(a,b)=>E.stencilMaskSeparate(a,b),Qb:(a,b,c)=>E.stencilOp(a,
b,c),Pb:(a,b,c,d)=>E.stencilOpSeparate(a,b,c,d),Ob:(a,b,c,d,e,g,f,l,n)=>{n=n?Fc(l,f,d,e,n):null;E.texImage2D(a,b,c,d,e,g,f,l,n)},Nb:(a,b,c)=>E.texParameterf(a,b,c),Mb:(a,b,c)=>{E.texParameterf(a,b,w[c>>2])},Lb:(a,b,c)=>E.texParameteri(a,b,c),Kb:(a,b,c)=>{E.texParameteri(a,b,u[c>>2])},Jb:(a,b,c,d,e,g,f,l,n)=>{n=n?Fc(l,f,e,g,n):null;E.texSubImage2D(a,b,c,d,e,g,f,l,n)},Ib:Hc,Hb:(a,b,c)=>{if(288>=b)for(var d=X[b],e=0;e<b;++e)d[e]=w[c+4*e>>2];else d=w.subarray(c>>2,c+4*b>>2);E.uniform1fv(W(a),d)},Gb:(a,
b)=>{E.uniform1i(W(a),b)},Fb:(a,b,c)=>{if(288>=b)for(var d=Ic[b],e=0;e<b;++e)d[e]=u[c+4*e>>2];else d=u.subarray(c>>2,c+4*b>>2);E.uniform1iv(W(a),d)},Eb:(a,b,c)=>{E.uniform2f(W(a),b,c)},Db:(a,b,c)=>{if(144>=b){b*=2;for(var d=X[b],e=0;e<b;e+=2)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2]}else d=w.subarray(c>>2,c+8*b>>2);E.uniform2fv(W(a),d)},Cb:(a,b,c)=>{E.uniform2i(W(a),b,c)},Bb:(a,b,c)=>{if(144>=b){b*=2;for(var d=Ic[b],e=0;e<b;e+=2)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2]}else d=u.subarray(c>>2,c+8*b>>
2);E.uniform2iv(W(a),d)},Ab:Jc,zb:(a,b,c)=>{if(96>=b){b*=3;for(var d=X[b],e=0;e<b;e+=3)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2]}else d=w.subarray(c>>2,c+12*b>>2);E.uniform3fv(W(a),d)},yb:(a,b,c,d)=>{E.uniform3i(W(a),b,c,d)},xb:(a,b,c)=>{if(96>=b){b*=3;for(var d=Ic[b],e=0;e<b;e+=3)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2]}else d=u.subarray(c>>2,c+12*b>>2);E.uniform3iv(W(a),d)},wb:(a,b,c,d,e)=>{E.uniform4f(W(a),b,c,d,e)},vb:(a,b,c)=>{if(72>=b){var d=X[4*b],
e=w;c>>=2;b*=4;for(var g=0;g<b;g+=4){var f=c+g;d[g]=e[f];d[g+1]=e[f+1];d[g+2]=e[f+2];d[g+3]=e[f+3]}}else d=w.subarray(c>>2,c+16*b>>2);E.uniform4fv(W(a),d)},ub:(a,b,c,d,e)=>{E.uniform4i(W(a),b,c,d,e)},tb:(a,b,c)=>{if(72>=b){b*=4;for(var d=Ic[b],e=0;e<b;e+=4)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2],d[e+3]=u[c+(4*e+12)>>2]}else d=u.subarray(c>>2,c+16*b>>2);E.uniform4iv(W(a),d)},sb:(a,b,c,d)=>{if(72>=b){b*=4;for(var e=X[b],g=0;g<b;g+=4)e[g]=w[d+4*g>>2],e[g+1]=w[d+(4*g+4)>>2],e[g+
2]=w[d+(4*g+8)>>2],e[g+3]=w[d+(4*g+12)>>2]}else e=w.subarray(d>>2,d+16*b>>2);E.uniformMatrix2fv(W(a),!!c,e)},qb:(a,b,c,d)=>{if(32>=b){b*=9;for(var e=X[b],g=0;g<b;g+=9)e[g]=w[d+4*g>>2],e[g+1]=w[d+(4*g+4)>>2],e[g+2]=w[d+(4*g+8)>>2],e[g+3]=w[d+(4*g+12)>>2],e[g+4]=w[d+(4*g+16)>>2],e[g+5]=w[d+(4*g+20)>>2],e[g+6]=w[d+(4*g+24)>>2],e[g+7]=w[d+(4*g+28)>>2],e[g+8]=w[d+(4*g+32)>>2]}else e=w.subarray(d>>2,d+36*b>>2);E.uniformMatrix3fv(W(a),!!c,e)},pb:Kc,ob:Lc,nb:a=>{E.validateProgram(F[a])},mb:(a,b)=>E.vertexAttrib1f(a,
b),lb:(a,b)=>{E.vertexAttrib1f(a,w[b>>2])},kb:(a,b,c)=>E.vertexAttrib2f(a,b,c),jb:(a,b)=>{E.vertexAttrib2f(a,w[b>>2],w[b+4>>2])},ib:(a,b,c,d)=>E.vertexAttrib3f(a,b,c,d),hb:(a,b)=>{E.vertexAttrib3f(a,w[b>>2],w[b+4>>2],w[b+8>>2])},fb:(a,b,c,d,e)=>E.vertexAttrib4f(a,b,c,d,e),eb:(a,b)=>{E.vertexAttrib4f(a,w[b>>2],w[b+4>>2],w[b+8>>2],w[b+12>>2])},Qd:(a,b)=>{E.vertexAttribDivisor(a,b)},db:Mc,cb:Nc,p:()=>0,ta:(a,b,c)=>Oc(a,{He:u[c>>2],ye:u[c+4>>2],jf:u[c+8>>2],ef:b,qe:u[c+12>>2],Pe:u[c+16>>2]}),N:(a,b)=>
{a=U(a);return a?a.requestPointerLock?Lb()?cc(a):b?(Jb(cc,2,[a]),1):-2:-1:-4},Sa:()=>{ma("OOM")},Ra:a=>{eval(a?z(r,a):"")},U:Pc,w:(a,b,c)=>"undefined"==typeof onbeforeunload?-1:1!==c?-5:Qc(a,b),F:(a,b,c,d)=>Rc(a,b,c,d,12,"blur"),k:Ub,n:(a,b,c)=>{a=U(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},H:(a,b,c,d)=>Rc(a,b,c,d,13,"focus"),y:(a,b,c,d)=>{if(!S.fullscreenEnabled())return-1;a=U(a);if(!a)return-4;Sc(a,b,c,d,"webkitfullscreenchange");return Sc(a,b,c,d,"fullscreenchange")},
S:(a,b,c)=>Pc()?-1:Tc(a,b,c,26,"gamepadconnected"),R:(a,b,c)=>Pc()?-1:Tc(a,b,c,27,"gamepaddisconnected"),B:(a,b,c,d)=>Uc(a,b,c,d,2,"keydown"),z:(a,b,c,d)=>Uc(a,b,c,d,1,"keypress"),A:(a,b,c,d)=>Uc(a,b,c,d,3,"keyup"),Qa:(a,b,c)=>{a=V(a);Cb(a,b,c)},M:(a,b,c,d)=>Wc(a,b,c,d,5,"mousedown"),K:(a,b,c,d)=>Wc(a,b,c,d,33,"mouseenter"),J:(a,b,c,d)=>Wc(a,b,c,d,34,"mouseleave"),s:(a,b,c,d)=>Wc(a,b,c,d,8,"mousemove"),L:(a,b,c,d)=>Wc(a,b,c,d,6,"mouseup"),C:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||
document.body.oe||document.body.Ye||document.body.Xe))return-1;a=U(a);if(!a)return-4;Xc(a,b,c,d,"mozpointerlockchange");Xc(a,b,c,d,"webkitpointerlockchange");Xc(a,b,c,d,"mspointerlockchange");return Xc(a,b,c,d,"pointerlockchange")},t:(a,b,c,d)=>Yc(a,b,c,d),D:(a,b,c,d)=>Zc(a,b,c,d,25,"touchcancel"),q:(a,b,c,d)=>Zc(a,b,c,d,23,"touchend"),r:(a,b,c,d)=>Zc(a,b,c,d,24,"touchmove"),E:(a,b,c,d)=>Zc(a,b,c,d,22,"touchstart"),x:(a,b,c)=>$c(a,b,c),I:(a,b,c,d)=>(a=U(a))?"undefined"!=typeof a.onwheel?ad(a,b,c,
d):-1:-4,ua:a=>document.title=a?z(r,a):"",o:()=>{throw"Please compile your program with async support in order to use asynchronous operations like emscripten_sleep";},Va:(a,b)=>{var c=0,d=0,e;for(e of md()){var g=b+c;v[a+d>>2]=g;c+=O(e,g,Infinity)+1;d+=4}return 0},Wa:(a,b)=>{var c=md();v[a>>2]=c.length;a=0;for(var d of c)a+=mb(d)+1;v[b>>2]=a;return 0},W:()=>52,Xa:()=>52,Ua:function(){return 70},X:(a,b,c,d)=>{for(var e=0,g=0;g<c;g++){var f=v[b>>2],l=v[b+4>>2];b+=8;for(var n=0;n<l;n++){var t=a,B=r[f+
n],L=nd[t];0===B||10===B?((1===t?da:m)(z(L)),L.length=0):L.push(B)}e+=l}v[d>>2]=e;return 0},$:ec,a:fc,gb:gc,b:hc,oc:ic,Za:jc,v:kc,ka:lc,O:mc,_:nc,P:pc,m:qc,i:rc,c:sc,u:uc,h:Bc,Hd:Ec,G:Gc,f:Hc,rb:Jc,d:Kc,cd:Lc,j:Mc,Jc:Nc},Z;
(async function(){function a(c){Z=c.exports;fa=Z.Sd;c=fa.buffer;q=new Int8Array(c);ia=new Int16Array(c);r=new Uint8Array(c);ja=new Uint16Array(c);u=new Int32Array(c);v=new Uint32Array(c);w=new Float32Array(c);x=new Float64Array(c);ka=new BigInt64Array(c);new BigUint64Array(c);Yb=Z.Vd;y--;h.monitorRunDependencies?.(y);0==y&&la&&(c=la,la=null,c());return Z}y++;h.monitorRunDependencies?.(y);var b={a:ud};if(h.instantiateWasm)return new Promise(c=>{h.instantiateWasm(b,(d,e)=>{c(a(d,e))})});na??=h.locateFile?
h.locateFile("game.wasm",k):k+"game.wasm";return a((await qa(b)).instance)})();var vd=h._main=(a,b)=>(vd=h._main=Z.Ud)(a,b),P=a=>(P=Z.Wd)(a),Sb=a=>(Sb=Z.Xd)(a),Pb=a=>(Pb=Z.Yd)(a),Rb=()=>(Rb=Z.Zd)();function wd(a=[]){var b=vd;a.unshift(ba);var c=a.length,d=Pb(4*(c+1)),e=d;a.forEach(f=>{v[e>>2]=Qb(f);e+=4});v[e>>2]=0;try{var g=b(c,d);Ba(g)}catch(f){za(f)}}
function xd(a=aa){function b(){h.calledRun=!0;if(!p){Z.Td();h.onRuntimeInitialized?.();h.noInitialRun||wd(a);if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var c=h.postRun.shift();ta.push(c)}sa(ta)}}if(0<y)la=xd;else{if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)va();sa(ua);0<y?la=xd:h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),1);b()},1)):b()}}
if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.shift()();xd();
