var h;h||=typeof Module != 'undefined' ? Module : {};var aa=[],ba="./this.program",k="",ca;"undefined"!=typeof document&&document.currentScript&&(k=document.currentScript.src);k=k.startsWith("blob:")?"":k.slice(0,k.replace(/[?#].*/,"").lastIndexOf("/")+1);ca=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};
var da=console.log.bind(console),m=console.error.bind(console),ea,fa,p=!1,ha,q,r,ia,ja,u,v,w,ka,x,y=0,la=null;function ma(a){h.onAbort?.(a);a="Aborted("+a+")";m(a);p=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var na;async function oa(a){if(!ea)try{var b=await ca(a);return new Uint8Array(b)}catch{}if(a==na&&ea)a=new Uint8Array(ea);else throw"both async and sync fetching of the wasm failed";return a}
async function pa(a,b){try{var c=await oa(a);return await WebAssembly.instantiate(c,b)}catch(d){m(`failed to asynchronously prepare wasm: ${d}`),ma(d)}}async function qa(a){var b=na;if(!ea&&"function"==typeof WebAssembly.instantiateStreaming)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){m(`wasm streaming compile failed: ${d}`),m("falling back to ArrayBuffer instantiation")}return pa(b,a)}
class ra{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var sa=a=>{for(;0<a.length;)a.shift()(h)},ta=[],ua=[],va=()=>{var a=h.preRun.shift();ua.push(a)},wa=!0;
function xa(a,b){var c="float";c.endsWith("*")&&(c="*");switch(c){case "i1":q[a]=b;break;case "i8":q[a]=b;break;case "i16":ia[a>>1]=b;break;case "i32":u[a>>2]=b;break;case "i64":ka[a>>3]=BigInt(b);break;case "float":w[a>>2]=b;break;case "double":x[a>>3]=b;break;case "*":v[a>>2]=b;break;default:ma(`invalid type for setValue: ${c}`)}}
var ya="undefined"!=typeof TextDecoder?new TextDecoder:void 0,z=(a,b=0,c=NaN)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&ya)return ya.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var f=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|f:(e&7)<<18|g<<12|f<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
za=a=>{if(!(a instanceof ra||"unwind"==a))throw a;},Aa=a=>{ha=a;wa||(h.onExit?.(a),p=!0);throw new ra(a);},Ba=a=>{ha=a;Aa(a)},Ca=()=>{if(!wa)try{var a=ha;ha=a;Aa(a)}catch(b){za(b)}},Da=!1,Ea=!1,Fa=[];
function Ga(){function a(){var c=h.canvas;Ea=document.pointerLockElement===c||document.mozPointerLockElement===c||document.webkitPointerLockElement===c||document.msPointerLockElement===c}if(!Ha){Ha=!0;var b=h.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),b.exitPointerLock=
b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",c=>{!Ea&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}var Ia=!1,Ja=void 0,A=void 0;
function Ka(){if(!Da)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var La=[];function Ma(){var a=h.canvas;La.forEach(b=>b(a.width,a.height))}
function Na(a,b,c){b&&c?(a.uf=b,a.mf=c):(b=a.uf,c=a.mf);var d=b,e=c;0<h.forcedAspectRatio&&(d/e<h.forcedAspectRatio?d=Math.round(e*h.forcedAspectRatio):e=Math.round(d/h.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/d,screen.height/e);d=Math.round(d*g);e=Math.round(e*g)}A?(a.width!=d&&(a.width=
d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var Ha,C=12288,Oa=!1,Pa=0,Qa=0,Ra=0,D={alpha:!1,depth:!1,stencil:!1,antialias:!1},Sa={},Ta,E,Ua=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,g)=>b.drawArraysInstancedANGLE(c,d,e,g),a.drawElementsInstanced=(c,d,e,g,f)=>b.drawElementsInstancedANGLE(c,d,e,g,f))},Va=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),
a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},Wa=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},Xa=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},Ya=1,Za=[],F=[],$a=[],G=[],H=[],J=[],ab=[],K=[],M=[],bb={},cb=4,db=0,eb=a=>{for(var b=Ya++,c=a.length;c<b;c++)a[c]=null;return b},fb=(a,b,c,d)=>{for(var e=0;e<a;e++){var g=E[c](),f=g&&eb(d);g?(g.name=f,d[f]=g):N||=1282;u[b+4*e>>2]=f}},hb=(a,b)=>{a.re||(a.re=a.getContext,a.getContext=function(d,e){e=a.re(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?gb(c,b):0},gb=(a,b)=>{var c=
eb(K),d={handle:c,attributes:b,version:b.Ue,ke:a};a.canvas&&(a.canvas.oe=d);K[c]=d;("undefined"==typeof b.hf||b.hf)&&ib(d);return c},kb=a=>{jb=K[a];h.ctx=E=jb?.ke},ib=a=>{a||=jb;if(!a.pf){a.pf=!0;var b=a.ke;b.Gf=b.getExtension("WEBGL_multi_draw");b.kf=b.getExtension("EXT_polygon_offset_clamp");b.jf=b.getExtension("EXT_clip_control");b.tf=b.getExtension("WEBGL_polygon_mode");Ua(b);Va(b);Wa(b);b.je=b.getExtension("EXT_disjoint_timer_query");Xa(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||
b.getExtension(c)})}},lb={},N,jb,mb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},O=(a,b,c)=>{var d=r;if(!(0<c))return 0;var e=b;c=b+c-1;for(var g=0;g<a.length;++g){var f=a.charCodeAt(g);if(55296<=f&&57343>=f){var l=a.charCodeAt(++g);f=65536+((f&1023)<<10)|l&1023}if(127>=f){if(b>=c)break;d[b++]=f}else{if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6}else{if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12}else{if(b+3>=c)break;d[b++]=
240|f>>18;d[b++]=128|f>>12&63}d[b++]=128|f>>6&63}d[b++]=128|f&63}}d[b]=0;return b-e},Q=a=>{var b=mb(a)+1,c=P(b);c&&O(a,c,b);return c},Cb=(a,b,c,d,e)=>{function g(){return f<nb?(Ca(),!1):!0}ob=a;pb=d;var f=nb;qb=!1;rb=function(){if(!p)if(0<sb.length){var l=sb.shift();l.Cf(l.vf);if(tb){var n=tb,t=0==n%1?n-1:Math.floor(n);tb=l.yf?t:(8*n+(t+.5))/9}h.setStatus&&(l=h.statusMessage||"Please wait...",n=tb??0,t=ub.Bf??0,n?n<t?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(l):h.setStatus(""));
g()&&setTimeout(rb,0)}else if(g())if(vb=vb+1|0,1==wb&&1<xb&&0!=vb%xb)R();else{0==wb&&(yb=performance.now());a:if(!p){for(l of zb)if(!1===l())break a;if(!p)try{a(),Ca()}catch(B){za(B)}for(n of Ab)n()}g()&&R()}};e||(0<b?Bb(0,1E3/b):Bb(1,1),R());if(c)throw"unwind";},qb=!1,R=null,nb=0,ob=null,pb=0,wb=0,xb=0,vb=0,sb=[],zb=[],Ab=[],Db=0;
function Eb(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Db)Db=b+1E3/60;else for(;b+2>=Db;)Db+=1E3/60;setTimeout(a,Math.max(Db-b,0))}}
var ub={},rb,tb,yb,Fb,Bb=(a,b)=>{wb=a;xb=b;if(ob)if(qb||=!0,0==a)R=function(){setTimeout(rb,Math.max(0,yb+b-performance.now())|0)};else if(1==a)R=function(){Eb(rb)};else if(2==a){if("undefined"==typeof Fb)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Fb=d=>{c.push(d);postMessage("setimmediate","*")}}else Fb=setImmediate;R=function(){Fb(rb)}}},Gb=[],Hb=(a,b)=>{Gb.length=0;
for(var c;c=r[a++];){var d=105!=c;d&=112!=c;b+=d&&b%8?4:0;Gb.push(112==c?v[b>>2]:106==c?ka[b>>3]:105==c?u[b>>2]:x[b>>3]);b+=d?8:4}return Gb};function Ib(a){var b=S.fe[a];b.target.removeEventListener(b.ce,b.Se,b.de);S.fe.splice(a,1)}function Jb(a,b,c){function d(g,f){if(g.length!=f.length)return!1;for(var l in g)if(g[l]!=f[l])return!1;return!0}for(var e of S.le)if(e.Ke==a&&d(e.Qe,c))return;S.le.push({Ke:a,We:b,Qe:c});S.le.sort((g,f)=>g.We<f.We)}function Kb(a){S.le=S.le.filter(b=>b.Ke!=a)}
function Lb(){return navigator.userActivation?navigator.userActivation.isActive:S.Fe&&S.af.qe}function Mb(){if(Lb()){var a=S.le;S.le=[];for(var b of a)b.Ke(...b.Qe)}}function T(a){if(!a.target)return-4;if(a.ee)a.Se=function(c){++S.Fe;S.af=a;Mb();a.ge(c);Mb();--S.Fe},a.target.addEventListener(a.ce,a.Se,a.de),S.fe.push(a);else for(var b=0;b<S.fe.length;++b)S.fe[b].target==a.target&&S.fe[b].ce==a.ce&&Ib(b--);return 0}
function Nb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var S={wf:0,Ee:0,Ge:0,ze:0,Pe:0,Me:0,Ce:0,Af:0,Hf:0,zf:0,De:0,Ie:0,Oe:0,Le:0,Ef(a,b,c){q.set(q.subarray(b,b+c),a)},If(){for(;S.fe.length;)Ib(S.fe.length-1);S.le=[]},Fe:0,le:[],fe:[],rf:(a,b)=>{for(var c=0;c<S.fe.length;++c)S.fe[c].target!=a||b&&b!=S.fe[c].ce||Ib(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},Ob=[0,document,window],U=a=>{a=2<a?a?z(r,a):"":a;return Ob[a]||document.querySelector(a)},Qb=a=>{var b=mb(a)+1,c=Pb(b);O(a,c,b);return c},Tb=a=>
{var b=Rb(),c=Pb(8),d=c+4;a=Qb(a.id);if(a=U(a))u[c>>2]=a.width,u[d>>2]=a.height;c=[u[c>>2],u[d>>2]];Sb(b);return c},Ub=(a,b,c)=>{a=U(a);if(!a)return-4;a.width=b;a.height=c;return 0},Vb=(a,b,c)=>{if(a.xf){var d=Rb();a=Qb(a.id);Ub(a,b,c);Sb(d)}else a.width=b,a.height=c},Wb={},Xb=[],Yb,V=a=>{var b=Xb[a];b||(Xb[a]=b=Yb.get(a));return b},Zb=a=>{function b(){document.fullscreenElement||document.webkitFullscreenElement||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",
b),Vb(a,d,e),a.style.width=g,a.style.height=f,a.style.backgroundColor=l,n||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=n,a.style.paddingLeft=t,a.style.paddingRight=B,a.style.paddingTop=L,a.style.paddingBottom=I,a.style.marginLeft=ed,a.style.marginRight=fd,a.style.marginTop=gd,a.style.marginBottom=hd,document.body.style.margin=jd,document.documentElement.style.overflow=kd,document.body.scroll=ld,a.style.me=md,a.oe&&a.oe.ke.viewport(0,0,d,e),Wb.se&&V(Wb.se)(37,
0,Wb.Re))}var c=Tb(a),d=c[0],e=c[1],g=a.style.width,f=a.style.height,l=a.style.backgroundColor,n=document.body.style.backgroundColor,t=a.style.paddingLeft,B=a.style.paddingRight,L=a.style.paddingTop,I=a.style.paddingBottom,ed=a.style.marginLeft,fd=a.style.marginRight,gd=a.style.marginTop,hd=a.style.marginBottom,jd=document.body.style.margin,kd=document.documentElement.style.overflow,ld=document.body.scroll,md=a.style.me;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",
b)},$b=(a,b,c)=>{a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"},ac=a=>0>Ob.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},bc=(a,b)=>{if(0!=b.Je||0!=b.Ae){Zb(a);var c=b.sf?innerWidth:screen.width,d=b.sf?innerHeight:screen.height,e=ac(a),g=e.width;e=e.height;var f=Tb(a),l=f[0];f=f[1];3==b.Je?($b(a,(d-e)/2,(c-g)/2),c=g,d=e):2==b.Je&&(c*f<l*d?(g=f*c/l,$b(a,(d-g)/2,0),d=g):(g=l*d/f,$b(a,0,(c-g)/2),c=g));var n;(n=a.style).backgroundColor||(n.backgroundColor=
"black");let t;(t=document.body.style).backgroundColor||(t.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.lf&&(a.style.me="optimizeSpeed",a.style.me="-moz-crisp-edges",a.style.me="-o-crisp-edges",a.style.me="-webkit-optimize-contrast",a.style.me="optimize-contrast",a.style.me="crisp-edges",a.style.me="pixelated");n=2==b.Ae?devicePixelRatio:1;0!=b.Ae&&(c=c*n|0,d=d*n|0,Vb(a,c,d),a.oe&&a.oe.ke.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);
else return S.fullscreenEnabled()?-3:-1;Wb=b;b.se&&V(b.se)(37,0,b.Re);return 0},cc=a=>{if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?-3:-1;return 0},dc=(a,b)=>{x[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)x[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)x[a+8*c+528>>3]="object"==typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)q[a+c+1040]="object"==typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];
q[a+1104]=b.connected;u[a+1108>>2]=b.index;u[a+8>>2]=b.axes.length;u[a+12>>2]=b.buttons.length;O(b.id,a+1112,64);O(b.mapping,a+1176,64)},ec=(a,b)=>{E.attachShader(F[a],J[b])},fc=(a,b)=>{E.bindBuffer(a,Za[b])},gc=(a,b)=>E.blendFunc(a,b),hc=(a,b,c,d)=>{E.bufferData(a,c?r.subarray(c,c+b):b,d)},ic=a=>E.clear(a),jc=(a,b,c,d)=>E.clearColor(a,b,c,d),kc=a=>{E.compileShader(J[a])},lc=()=>{var a=eb(F),b=E.createProgram();b.name=a;b.ye=b.we=b.xe=0;b.Ne=1;F[a]=b;return a},mc=a=>{var b=eb(J);J[b]=E.createShader(a);
return b},nc=a=>{if(a){var b=F[a];b?(E.deleteProgram(b),b.name=0,F[a]=null):N||=1281}},oc=a=>E.disable(a),pc=[],qc=(a,b,c,d)=>{E.drawElements(a,b,c,d)},rc=a=>E.enable(a),sc=a=>{E.enableVertexAttribArray(a)},tc=(a,b)=>{fb(a,b,"createBuffer",Za)},uc=(a,b,c,d,e,g,f,l)=>{b=F[b];if(a=E[a](b,c))d=l&&O(a.name,l,d),e&&(u[e>>2]=d),g&&(u[g>>2]=a.size),f&&(u[f>>2]=a.type)},vc=(a,b)=>E.getAttribLocation(F[a],b?z(r,b):""),wc=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&(N||=
1280);return;case 36345:d=0;break;case 34466:var e=E.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=E.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":N||=1280;return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:N||=1280;return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:u[b+
4*a>>2]=e[a];break;case 2:w[b+4*a>>2]=e[a];break;case 4:q[b+a]=e[a]?1:0}return}try{d=e.name|0}catch(g){N||=1280;m(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${g})`);return}}break;default:N||=1280;m(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${e} of type ${typeof e}!`);return}switch(c){case 1:c=d;v[b>>2]=c;v[b+4>>2]=(c-v[b>>2])/4294967296;break;case 0:u[b>>2]=d;break;case 2:w[b>>2]=d;break;case 4:q[b]=d?1:
0}}else N||=1281},xc=(a,b,c,d)=>{a=E.getProgramInfoLog(F[a]);null===a&&(a="(unknown error)");b=0<b&&d?O(a,d,b):0;c&&(u[c>>2]=b)},yc=(a,b,c)=>{if(c)if(a>=Ya)N||=1281;else if(a=F[a],35716==b)a=E.getProgramInfoLog(a),null===a&&(a="(unknown error)"),u[c>>2]=a.length+1;else if(35719==b){if(!a.ye){var d=E.getProgramParameter(a,35718);for(b=0;b<d;++b)a.ye=Math.max(a.ye,E.getActiveUniform(a,b).name.length+1)}u[c>>2]=a.ye}else if(35722==b){if(!a.we)for(d=E.getProgramParameter(a,35721),b=0;b<d;++b)a.we=Math.max(a.we,
E.getActiveAttrib(a,b).name.length+1);u[c>>2]=a.we}else if(35381==b){if(!a.xe)for(d=E.getProgramParameter(a,35382),b=0;b<d;++b)a.xe=Math.max(a.xe,E.getActiveUniformBlockName(a,b).length+1);u[c>>2]=a.xe}else u[c>>2]=E.getProgramParameter(a,b);else N||=1281},zc=(a,b,c)=>{if(c){a=E.je.getQueryObjectEXT(M[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;v[c>>2]=d;v[c+4>>2]=(d-v[c>>2])/4294967296}else N||=1281},Ac=(a,b,c)=>{if(c){a=E.je.getQueryObjectEXT(M[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;u[c>>2]=
d}else N||=1281},Bc=()=>{var a=Xa(E);return a=a.concat(a.map(b=>"GL_"+b))},Cc=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Dc=a=>{var b=a.pe,c=a.Ye,d;if(!b){a.pe=b={};a.Xe={};var e=E.getProgramParameter(a,35718);for(d=0;d<e;++d){var g=E.getActiveUniform(a,d);var f=g.name;g=g.size;var l=Cc(f);l=0<l?f.slice(0,l):f;var n=a.Ne;a.Ne+=g;c[l]=[g,n];for(f=0;f<g;++f)b[n]=f,a.Xe[n++]=l}}},Ec=(a,b)=>{b=b?z(r,b):"";if(a=F[a]){Dc(a);var c=a.pe,d=0,e=b,g=Cc(b);0<g&&(d=parseInt(b.slice(g+1))>>>0,e=b.slice(0,g));if((e=
a.Ye[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||E.getUniformLocation(a,b)))return d}else N||=1281;return-1},W=a=>{var b=E.bf;if(b){var c=b.pe[a];"number"==typeof c&&(b.pe[a]=c=E.getUniformLocation(b,b.Xe[a]+(0<c?`[${c}]`:"")));return c}N||=1282},Fc=(a,b,c,d)=>{if(c)if(a=F[a],Dc(a),a=E.getUniform(a,W(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:u[c>>2]=a;break;case 2:w[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:u[c+4*b>>2]=a[b];break;case 2:w[c+4*b>>2]=a[b]}else N||=1281},Gc=(a,b,c,
d)=>{if(c)if(a=E.getVertexAttrib(a,b),34975==b)u[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:u[c>>2]=a;break;case 2:w[c>>2]=a;break;case 5:u[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:u[c+4*b>>2]=a[b];break;case 2:w[c+4*b>>2]=a[b];break;case 5:u[c+4*b>>2]=Math.fround(a[b])}else N||=1281},Hc=a=>{a=F[a];E.linkProgram(a);a.pe=0;a.Ye={}},Ic=(a,b,c,d,e)=>{a-=5120;a=1==a?r:4==a?u:6==a?w:5==a||28922==a?v:ja;b=d*((db||c)*({5:3,6:4,8:2,29502:3,29504:4}[b-
6402]||1)*a.BYTES_PER_ELEMENT+cb-1&-cb);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},Jc=(a,b,c,d)=>{for(var e="",g=0;g<b;++g){var f=(f=v[c+4*g>>2])?z(r,f,d?v[d+4*g>>2]:void 0):"";e+=f}E.shaderSource(J[a],e)},Kc=(a,b)=>{E.uniform1f(W(a),b)},X=[],Lc=[],Mc=(a,b,c,d)=>{E.uniform3f(W(a),b,c,d)},Nc=(a,b,c,d)=>{if(18>=b){var e=X[16*b],g=w;d>>=2;b*=16;for(var f=0;f<b;f+=16){var l=d+f;e[f]=g[l];e[f+1]=g[l+1];e[f+2]=g[l+2];e[f+3]=g[l+3];e[f+4]=g[l+4];e[f+
5]=g[l+5];e[f+6]=g[l+6];e[f+7]=g[l+7];e[f+8]=g[l+8];e[f+9]=g[l+9];e[f+10]=g[l+10];e[f+11]=g[l+11];e[f+12]=g[l+12];e[f+13]=g[l+13];e[f+14]=g[l+14];e[f+15]=g[l+15]}}else e=w.subarray(d>>2,d+64*b>>2);E.uniformMatrix4fv(W(a),!!c,e)},Oc=a=>{a=F[a];E.useProgram(a);E.bf=a},Pc=(a,b,c,d,e,g)=>{E.vertexAttribPointer(a,b,c,!!d,e,g)},Qc=(a,b,c,d)=>E.viewport(a,b,c,d),Rc=(a,b)=>{if(!S.fullscreenEnabled())return-1;a=U(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?Lb()?bc(a,b):b.gf?(Jb(bc,1,[a,b]),
1):-2:-3:-4},Sc=()=>{try{if(navigator.getGamepads)return(S.ve=navigator.getGamepads())?0:-1}catch(a){navigator.getGamepads=null}return-1},Tc=(a,b)=>{var c={target:U(2),ce:"beforeunload",ee:b,ge:(d=event)=>{var e=V(b)(28,0,a);e&&=e?z(r,e):"";if(e)return d.preventDefault(),d.returnValue=e},de:!0};return T(c)},Uc=(a,b,c,d,e,g)=>{S.Ce||(S.Ce=P(256));a={target:U(a),ce:g,ee:d,ge:(f=event)=>{var l=f.target.id?f.target.id:"",n=S.Ce;O(Nb(f.target),n+0,128);O(l,n+128,128);V(d)(e,n,b)&&f.preventDefault()},de:c};
return T(a)},Vc=(a,b,c,d,e)=>{S.De||(S.De=P(276));return T({target:a,ce:e,ee:d,ge:(g=event)=>{var f=S.De,l=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,n=!!l;q[f]=n;q[f+1]=S.fullscreenEnabled();var t=n?l:S.qf,B=t?.id||"";O(Nb(t),f+2,128);O(B,f+130,128);u[f+260>>2]=t?t.clientWidth:0;u[f+264>>2]=t?t.clientHeight:0;u[f+268>>2]=screen.width;u[f+272>>2]=screen.height;n&&(S.qf=l);V(d)(19,f,b)&&g.preventDefault()},de:c})},Wc=(a,
b,c,d,e)=>{S.Ee||(S.Ee=P(1240));b={target:U(2),qe:!0,ce:e,ee:c,ge:(g=event)=>{var f=S.Ee;dc(f,g.gamepad);V(c)(d,f,a)&&g.preventDefault()},de:b};return T(b)},Xc=(a,b,c,d,e,g)=>{S.Ge||(S.Ge=P(160));a={target:U(a),ce:g,ee:d,ge:f=>{var l=S.Ge;x[l>>3]=f.timeStamp;var n=l>>2;u[n+2]=f.location;q[l+12]=f.ctrlKey;q[l+13]=f.shiftKey;q[l+14]=f.altKey;q[l+15]=f.metaKey;q[l+16]=f.repeat;u[n+5]=f.charCode;u[n+6]=f.keyCode;u[n+7]=f.which;O(f.key||"",l+32,32);O(f.code||"",l+64,32);O(f.char||"",l+96,32);O(f.locale||
"",l+128,32);V(d)(e,l,b)&&f.preventDefault()},de:c};return T(a)},Yc=(a,b,c)=>{x[a>>3]=b.timeStamp;var d=a>>2;u[d+2]=b.screenX;u[d+3]=b.screenY;u[d+4]=b.clientX;u[d+5]=b.clientY;q[a+24]=b.ctrlKey;q[a+25]=b.shiftKey;q[a+26]=b.altKey;q[a+27]=b.metaKey;ia[2*d+14]=b.button;ia[2*d+15]=b.buttons;u[d+8]=b.movementX;u[d+9]=b.movementY;a=ac(c);u[d+10]=b.clientX-(a.left|0);u[d+11]=b.clientY-(a.top|0)},Zc=(a,b,c,d,e,g)=>{S.ze||(S.ze=P(64));a=U(a);return T({target:a,qe:"mousemove"!=g&&"mouseenter"!=g&&"mouseleave"!=
g,ce:g,ee:d,ge:(f=event)=>{Yc(S.ze,f,a);V(d)(e,S.ze,b)&&f.preventDefault()},de:c})},$c=(a,b,c,d,e)=>{S.Ie||(S.Ie=P(257));return T({target:a,ce:e,ee:d,ge:(g=event)=>{var f=S.Ie,l=document.pointerLockElement||document.re||document.ff||document.Ze;q[f]=!!l;var n=l?.id||"";O(Nb(l),f+1,128);O(n,f+129,128);V(d)(20,f,b)&&g.preventDefault()},de:c})},ad=(a,b,c,d)=>{S.Me||(S.Me=P(36));a=U(a);return T({target:a,ce:"resize",ee:d,ge:(e=event)=>{if(e.target==a){var g=document.body;if(g){var f=S.Me;u[f>>2]=0;u[f+
4>>2]=g.clientWidth;u[f+8>>2]=g.clientHeight;u[f+12>>2]=innerWidth;u[f+16>>2]=innerHeight;u[f+20>>2]=outerWidth;u[f+24>>2]=outerHeight;u[f+28>>2]=pageXOffset|0;u[f+32>>2]=pageYOffset|0;V(d)(10,f,b)&&e.preventDefault()}}},de:c})},bd=(a,b,c,d,e,g)=>{S.Le||(S.Le=P(1552));a=U(a);return T({target:a,qe:"touchstart"==g||"touchend"==g,ce:g,ee:d,ge:f=>{var l={},n=f.touches;for(var t of n)t.Te=t.Ve=0,l[t.identifier]=t;for(var B of f.changedTouches)B.Te=1,l[B.identifier]=B;for(var L of f.targetTouches)l[L.identifier].Ve=
1;n=S.Le;x[n>>3]=f.timeStamp;q[n+12]=f.ctrlKey;q[n+13]=f.shiftKey;q[n+14]=f.altKey;q[n+15]=f.metaKey;t=n+16;B=ac(a);L=0;for(let I of Object.values(l))if(l=t>>2,u[l]=I.identifier,u[l+1]=I.screenX,u[l+2]=I.screenY,u[l+3]=I.clientX,u[l+4]=I.clientY,u[l+5]=I.pageX,u[l+6]=I.pageY,q[t+28]=I.Te,q[t+29]=I.Ve,u[l+8]=I.clientX-(B.left|0),u[l+9]=I.clientY-(B.top|0),t+=48,31<++L)break;u[n+8>>2]=L;V(d)(e,n,b)&&f.preventDefault()},de:c})},cd=(a,b,c)=>{var d=Ob[1];S.Oe||(S.Oe=P(8));return T({target:d,ce:"visibilitychange",
ee:c,ge:(e=event)=>{var g=S.Oe,f=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);q[g]=document.hidden;u[g+4>>2]=f;V(c)(21,g,a)&&e.preventDefault()},de:b})},dd=(a,b,c,d)=>{S.Pe||(S.Pe=P(96));return T({target:a,qe:!0,ce:"wheel",ee:d,ge:(e=event)=>{var g=S.Pe;Yc(g,e,a);x[g+64>>3]=e.deltaX;x[g+72>>3]=e.deltaY;x[g+80>>3]=e.deltaZ;u[g+88>>2]=e.deltaMode;V(d)(9,g,b)&&e.preventDefault()},de:c})},nd={},pd=()=>{if(!od){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",
HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ba||"./this.program"},b;for(b in nd)void 0===nd[b]?delete a[b]:a[b]=nd[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);od=c}return od},od,qd=[null,[],[]],rd=(a,b,c)=>{a.addEventListener(b,c,{once:!0})},sd=a=>{var b;b||=[document,document.getElementById("canvas")];["keydown","mousedown","touchstart"].forEach(c=>{b.forEach(d=>{d&&rd(d,c,()=>{"suspended"===a.state&&a.resume()})})})},
td=(a,b=[])=>{V(a)(...b)};
h.requestFullscreen=function(a,b){function c(){Da=!1;var g=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===g?(d.exitFullscreen=Ka,Ja&&d.requestPointerLock(),Da=!0,A?("undefined"!=typeof SDL&&(u[SDL.screen>>2]=v[SDL.screen>>2]|8388608),Na(h.canvas),Ma()):Na(d)):(g.parentNode.insertBefore(d,g),g.parentNode.removeChild(g),A?("undefined"!=typeof SDL&&(u[SDL.screen>>2]=v[SDL.screen>>
2]&-8388609),Na(h.canvas),Ma()):Na(d));h.onFullScreen?.(Da);h.onFullscreen?.(Da)}Ja=a;A=b;"undefined"==typeof Ja&&(Ja=!0);"undefined"==typeof A&&(A=!1);var d=h.canvas;Ia||(Ia=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=e.requestFullscreen||
e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()};h.setCanvasSize=function(a,b,c){Na(h.canvas,a,b);c||Ma()};h.getUserMedia=function(a){let b;(b=window).getUserMedia||(b.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)};
h.createContext=function(a,b,c,d){if(b&&h.ctx&&a==h.canvas)return h.ctx;var e;if(b){var g={antialias:!1,alpha:!1,Ue:1};if(d)for(var f in d)g[f]=d[f];if("undefined"!=typeof lb&&(e=hb(a,g)))var l=K[e].ke}else l=a.getContext("2d");if(!l)return null;c&&(h.ctx=l,b&&kb(e),Fa.forEach(n=>n()),Ga());return l};h.requestAnimationFrame=Eb;h.pauseMainLoop=function(){R=null;nb++};h.resumeMainLoop=function(){nb++;var a=wb,b=xb,c=ob;ob=null;Cb(c,0,!1,pb,!0);Bb(a,b);R()};h.preMainLoop&&zb.push(h.preMainLoop);
h.postMainLoop&&Ab.push(h.postMainLoop);for(let a=0;32>a;++a)pc.push(Array(a));for(var ud=new Float32Array(288),Y=0;288>=Y;++Y)X[Y]=ud.subarray(0,Y);var vd=new Int32Array(288);for(Y=0;288>=Y;++Y)Lc[Y]=vd.subarray(0,Y);h.noExitRuntime&&(wa=h.noExitRuntime);h.print&&(da=h.print);h.printErr&&(m=h.printErr);h.wasmBinary&&(ea=h.wasmBinary);h.arguments&&(aa=h.arguments);h.thisProgram&&(ba=h.thisProgram);
var wd={36595869:()=>"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?!0:!1,36596016:()=>"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?!0:!1,36596250:a=>{"undefined"===typeof h.SDL2&&(h.SDL2={});var b=h.SDL2;a?b.capture={}:b.audio={};b.be||("undefined"!==typeof AudioContext?b.be=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.be=new webkitAudioContext),
b.be&&"undefined"===typeof navigator.userActivation&&sd(b.be));return void 0===b.be?-1:0},36596802:()=>h.SDL2.be.sampleRate,36596870:(a,b,c,d)=>{function e(){}function g(l){void 0!==f.capture.ie&&(clearInterval(f.capture.ie),f.capture.ie=void 0,f.capture.ne=void 0);f.capture.He=f.be.createMediaStreamSource(l);f.capture.he=f.be.createScriptProcessor(b,a,1);f.capture.he.onaudioprocess=function(n){void 0!==f&&void 0!==f.capture&&(n.outputBuffer.getChannelData(0).fill(0),f.capture.Be=n.inputBuffer,td(c,
[d]))};f.capture.He.connect(f.capture.he);f.capture.he.connect(f.be.destination);f.capture.stream=l}var f=h.SDL2;f.capture.ne=f.be.createBuffer(a,b,f.be.sampleRate);f.capture.ne.getChannelData(0).fill(0);f.capture.ie=setInterval(function(){f.capture.Be=f.capture.ne;td(c,[d])},b/f.be.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(g).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,
video:!1},g,e)},36598563:(a,b,c,d)=>{var e=h.SDL2;e.audio.he=e.be.createScriptProcessor(b,0,a);e.audio.he.onaudioprocess=function(g){void 0!==e&&void 0!==e.audio&&(void 0!==e.audio.ie&&(clearInterval(e.audio.ie),e.audio.ie=void 0,e.audio.ne=void 0),e.audio.ue=g.outputBuffer,td(c,[d]))};e.audio.he.connect(e.be.destination);"suspended"===e.be.state&&(e.audio.ne=e.be.createBuffer(a,b,e.be.sampleRate),e.audio.ne.getChannelData(0).fill(0),e.audio.ie=setInterval(function(){"undefined"!==typeof navigator.userActivation&&
navigator.userActivation.hasBeenActive&&e.be.resume();e.audio.ue=e.audio.ne;td(c,[d]);e.audio.ue=void 0},b/e.be.sampleRate*1E3))},36599738:(a,b)=>{for(var c=h.SDL2,d=c.capture.Be.numberOfChannels,e=0;e<d;++e){var g=c.capture.Be.getChannelData(e);if(g.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+g.length+" samples vs expected "+b+" samples!";if(1==d)for(var f=0;f<b;++f)xa(a+4*f,g[f]);else for(f=0;f<b;++f)xa(a+4*(f*d+e),g[f])}},36600343:(a,b)=>{var c=h.SDL2;a>>>=2;for(var d=
c.audio.ue.numberOfChannels,e=0;e<d;++e){var g=c.audio.ue.getChannelData(e);if(g.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+g.length+" samples vs expected "+b+" samples!";for(var f=0;f<b;++f)g[f]=w[a+(f*d+e)]}},36600832:a=>{var b=h.SDL2;if(a){void 0!==b.capture.ie&&clearInterval(b.capture.ie);if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c])}void 0!==b.capture.he&&(b.capture.he.onaudioprocess=
function(){},b.capture.he.disconnect());void 0!==b.capture.He&&b.capture.He.disconnect();b.capture=void 0}else void 0!=b.audio.he&&b.audio.he.disconnect(),void 0!==b.audio.ie&&clearInterval(b.audio.ie),b.audio=void 0;void 0!==b.be&&void 0===b.audio&&void 0===b.capture&&(b.be.close(),b.be=void 0)},36601838:(a,b,c)=>{h.SDL2||(h.SDL2={});var d=h.SDL2;d.$e!==h.canvas&&(d.te=h.createContext(h.canvas,!1,!0),d.$e=h.canvas);if(d.w!==a||d.h!==b||d.nf!==d.te)d.image=d.te.createImageData(a,b),d.w=a,d.h=b,d.nf=
d.te;a=d.image.data;b=c/4;var e=0;if("undefined"!==typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var g=u[b];a[e]=g&255;a[e+1]=g>>8&255;a[e+2]=g>>16&255;a[e+3]=255;b++;e+=4}else if(d.df!==a&&(d.cf=new Int32Array(a.buffer),d.ef=new Uint8Array(a.buffer),d.df=a),a=d.cf,c=a.length,a.set(u.subarray(b,b+c)),a=d.ef,b=3,e=b+4*c,0==c%8)for(;b<e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|
0;else for(;b<e;)a[b]=255,b=b+4|0;d.te.putImageData(d.image,0,0)},36603306:(a,b,c,d,e)=>{var g=document.createElement("canvas");g.width=a;g.height=b;var f=g.getContext("2d");a=f.createImageData(a,b);b=a.data;e/=4;var l=0,n;if("undefined"!==typeof CanvasPixelArray&&b instanceof CanvasPixelArray)for(n=b.length;l<n;){var t=u[e];b[l]=t&255;b[l+1]=t>>8&255;b[l+2]=t>>16&255;b[l+3]=t>>24&255;e++;l+=4}else b=new Int32Array(b.buffer),n=b.length,b.set(u.subarray(e,e+n));f.putImageData(a,0,0);c=0===c&&0===d?
"url("+g.toDataURL()+"), auto":"url("+g.toDataURL()+") "+c+" "+d+", auto";d=P(c.length+1);O(c,d,c.length+1);return d},36604294:a=>{h.canvas&&(h.canvas.style.cursor=a?z(r,a):"")},36604377:()=>{h.canvas&&(h.canvas.style.cursor="none")},36604446:()=>window.innerWidth,36604476:()=>window.innerHeight},xd={_:function(){return 0},ab:function(){return 0},bb:function(){},Wa:()=>{},Ja:a=>{if(12448==a)return C=12288,1;C=12300;return 0},Ma:(a,b,c,d,e)=>{if(62E3!=a)C=12296,c=0;else{if(b)for(;;){a=u[b>>2];if(12321==
a)D.alpha=0<u[b+4>>2];else if(12325==a)D.depth=0<u[b+4>>2];else if(12326==a)D.stencil=0<u[b+4>>2];else if(12337==a)a=u[b+4>>2],D.antialias=0<a;else if(12338==a)a=u[b+4>>2],D.antialias=1==a;else if(12544==a)D.Df=12547!=u[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(u[e>>2]=1),c&&0<d&&(v[c>>2]=62002),C=12288,c=1):(C=12300,c=0)}return c},Aa:(a,b,c,d)=>{if(62E3!=a)return C=12296,0;for(a=1;;){b=u[d>>2];if(12440==b)a=u[d+4>>2];else if(12344==b)break;else return C=12292,0;d+=8}if(2!=a)return C=12293,
0;D.Ue=a-1;D.Ff=0;Ta=hb(h.canvas,D);if(0!=Ta)return C=12288,kb(Ta),Fa.forEach(e=>e()),kb(null),62004;C=12297;return 0},Ca:(a,b)=>{if(62E3!=a)return C=12296,0;if(62002!=b)return C=12293,0;C=12288;return 62006},Ba:(a,b)=>{if(62E3!=a)return C=12296,0;if(62004!=b)return C=12294,0;a=Ta;jb===K[a]&&(jb=null);"object"==typeof S&&S.rf(K[a].ke.canvas);K[a]?.ke.canvas&&(K[a].ke.canvas.oe=void 0);K[a]=null;C=12288;Pa==b&&(Pa=0);return 1},Da:(a,b)=>{if(62E3!=a)return C=12296,0;if(62006!=b)return C=12301,1;Qa==
b&&(Qa=0);Ra==b&&(Ra=0);C=12288;return 1},Na:(a,b,c,d)=>{if(62E3!=a)return C=12296,0;if(62002!=b)return C=12293,0;if(!d)return C=12300,0;C=12288;switch(c){case 12320:return u[d>>2]=D.alpha?32:24,1;case 12321:return u[d>>2]=D.alpha?8:0,1;case 12322:return u[d>>2]=8,1;case 12323:return u[d>>2]=8,1;case 12324:return u[d>>2]=8,1;case 12325:return u[d>>2]=D.depth?24:0,1;case 12326:return u[d>>2]=D.stencil?8:0,1;case 12327:return u[d>>2]=12344,1;case 12328:return u[d>>2]=62002,1;case 12329:return u[d>>
2]=0,1;case 12330:return u[d>>2]=4096,1;case 12331:return u[d>>2]=16777216,1;case 12332:return u[d>>2]=4096,1;case 12333:return u[d>>2]=0,1;case 12334:return u[d>>2]=0,1;case 12335:return u[d>>2]=12344,1;case 12337:return u[d>>2]=D.antialias?4:0,1;case 12338:return u[d>>2]=D.antialias?1:0,1;case 12339:return u[d>>2]=4,1;case 12340:return u[d>>2]=12344,1;case 12341:case 12342:case 12343:return u[d>>2]=-1,1;case 12345:case 12346:return u[d>>2]=0,1;case 12347:return u[d>>2]=0,1;case 12348:return u[d>>
2]=1;case 12349:case 12350:return u[d>>2]=0,1;case 12351:return u[d>>2]=12430,1;case 12352:return u[d>>2]=4,1;case 12354:return u[d>>2]=0,1;default:return C=12292,0}},S:a=>{C=12288;return 0!=a&&1!=a?0:62E3},za:()=>C,Ka:(a,b,c)=>{if(62E3!=a)return C=12296,0;b&&(u[b>>2]=1);c&&(u[c>>2]=4);Oa=!0;C=12288;return 1},Ea:(a,b,c,d)=>{if(62E3!=a)return C=12296,0;if(0!=d&&62004!=d)return C=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return C=12301,0;kb(d?Ta:null);Pa=d;Ra=b;Qa=c;C=12288;return 1},ya:(a,b)=>{if(62E3!=
a)return C=12296,0;C=12288;if(Sa[b])return Sa[b];switch(b){case 12371:a=Q("Emscripten");break;case 12372:a=Q("1.4 Emscripten EGL");break;case 12373:a=Q("");break;case 12429:a=Q("OpenGL_ES");break;default:return C=12300,0}return Sa[b]=a},Fa:()=>{if(Oa)if(E)if(E.isContextLost())C=12302;else return C=12288,1;else C=12290;else C=12289;return 0},Ga:(a,b)=>{if(62E3!=a)return C=12296,0;0==b?Bb(0,0):Bb(1,b);C=12288;return 1},La:a=>{if(62E3!=a)return C=12296,0;Ra=Qa=Pa=0;Oa=!1;C=12288;return 1},Ia:()=>{C=
12288;return 1},Ha:()=>{C=12288;return 1},Pa:(a,b,c)=>{b=Hb(b,c);return wd[a](...b)},e:(a,b,c)=>{b=Hb(b,c);return wd[a](...b)},Qa:(a,b,c)=>{b=Hb(b,c);return wd[a](...b)},$:()=>Date.now(),ra:()=>{if(!S.fullscreenEnabled())return-1;Kb(bc);var a=Ob[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},wa:()=>{Kb(cc);if(document.exitPointerLock)document.exitPointerLock();else return-1;return 0},
m:()=>devicePixelRatio,h:(a,b,c)=>{a=U(a);if(!a)return-4;a=ac(a);x[b>>3]=a.width;x[c>>3]=a.height;return 0},V:(a,b)=>{if(0>a||a>=S.ve.length)return-5;if(!S.ve[a])return-7;dc(b,S.ve[a]);return 0},X:()=>performance.now(),Oa:()=>S.ve.length,xa:(a,b)=>{u[a>>2]=screen.width;u[b>>2]=screen.height},Pd:a=>E.activeTexture(a),Od:ec,na:(a,b)=>{E.je.beginQueryEXT(a,M[b])},Nd:(a,b,c)=>{E.bindAttribLocation(F[a],b,c?z(r,c):"")},Md:fc,Ld:(a,b)=>{E.bindFramebuffer(a,$a[b])},Kd:(a,b)=>{E.bindRenderbuffer(a,G[b])},
Jd:(a,b)=>{E.bindTexture(a,H[b])},fa:a=>{E.bindVertexArray(ab[a])},Id:(a,b,c,d)=>E.blendColor(a,b,c,d),Hd:a=>E.blendEquation(a),Gd:(a,b)=>E.blendEquationSeparate(a,b),Fd:gc,Ed:(a,b,c,d)=>E.blendFuncSeparate(a,b,c,d),Dd:hc,Cd:(a,b,c,d)=>{E.bufferSubData(a,b,r.subarray(d,d+c))},Bd:a=>E.checkFramebufferStatus(a),Ad:ic,zd:jc,yd:a=>E.clearDepth(a),xd:a=>E.clearStencil(a),db:(a,b)=>{E.jf.clipControlEXT(a,b)},wd:(a,b,c,d)=>{E.colorMask(!!a,!!b,!!c,!!d)},vd:kc,ud:(a,b,c,d,e,g,f,l)=>{E.compressedTexImage2D(a,
b,c,d,e,g,r.subarray(l,l+f))},td:(a,b,c,d,e,g,f,l,n)=>{E.compressedTexSubImage2D(a,b,c,d,e,g,f,r.subarray(n,n+l))},sd:(a,b,c,d,e,g,f,l)=>E.copyTexImage2D(a,b,c,d,e,g,f,l),rd:(a,b,c,d,e,g,f,l)=>E.copyTexSubImage2D(a,b,c,d,e,g,f,l),qd:lc,pd:mc,od:a=>E.cullFace(a),nd:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=Za[d];e&&(E.deleteBuffer(e),e.name=0,Za[d]=null)}},md:(a,b)=>{for(var c=0;c<a;++c){var d=u[b+4*c>>2],e=$a[d];e&&(E.deleteFramebuffer(e),e.name=0,$a[d]=null)}},ld:nc,pa:(a,b)=>{for(var c=0;c<
a;c++){var d=u[b+4*c>>2],e=M[d];e&&(E.je.deleteQueryEXT(e),M[d]=null)}},kd:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=G[d];e&&(E.deleteRenderbuffer(e),e.name=0,G[d]=null)}},jd:a=>{if(a){var b=J[a];b?(E.deleteShader(b),J[a]=null):N||=1281}},id:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=H[d];e&&(E.deleteTexture(e),e.name=0,H[d]=null)}},ea:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2];E.deleteVertexArray(ab[d]);ab[d]=null}},hd:a=>E.depthFunc(a),gd:a=>{E.depthMask(!!a)},fd:(a,b)=>E.depthRange(a,
b),ed:(a,b)=>{E.detachShader(F[a],J[b])},dd:oc,cd:a=>{E.disableVertexAttribArray(a)},bd:(a,b,c)=>{E.drawArrays(a,b,c)},Sd:(a,b,c,d)=>{E.drawArraysInstanced(a,b,c,d)},Td:(a,b)=>{for(var c=pc[a],d=0;d<a;d++)c[d]=u[b+4*d>>2];E.drawBuffers(c)},ad:qc,Rd:(a,b,c,d,e)=>{E.drawElementsInstanced(a,b,c,d,e)},$c:rc,_c:sc,ma:a=>{E.je.endQueryEXT(a)},Zc:()=>E.finish(),Yc:()=>E.flush(),Xc:(a,b,c,d)=>{E.framebufferRenderbuffer(a,b,c,G[d])},Wc:(a,b,c,d,e)=>{E.framebufferTexture2D(a,b,c,H[d],e)},Vc:a=>E.frontFace(a),
Uc:tc,Sc:(a,b)=>{fb(a,b,"createFramebuffer",$a)},qa:(a,b)=>{for(var c=0;c<a;c++){var d=E.je.createQueryEXT();if(!d){for(N||=1282;c<a;)u[b+4*c++>>2]=0;break}var e=eb(M);d.name=e;M[e]=d;u[b+4*c>>2]=e}},Rc:(a,b)=>{fb(a,b,"createRenderbuffer",G)},Qc:(a,b)=>{fb(a,b,"createTexture",H)},da:(a,b)=>{fb(a,b,"createVertexArray",ab)},Tc:a=>E.generateMipmap(a),Pc:(a,b,c,d,e,g,f)=>uc("getActiveAttrib",a,b,c,d,e,g,f),Oc:(a,b,c,d,e,g,f)=>uc("getActiveUniform",a,b,c,d,e,g,f),Nc:(a,b,c,d)=>{a=E.getAttachedShaders(F[a]);
var e=a.length;e>b&&(e=b);u[c>>2]=e;for(b=0;b<e;++b)u[d+4*b>>2]=J.indexOf(a[b])},Mc:vc,Lc:(a,b)=>wc(a,b,4),Kc:(a,b,c)=>{c?u[c>>2]=E.getBufferParameter(a,b):N||=1281},Jc:()=>{var a=E.getError()||N;N=0;return a},Ic:(a,b)=>wc(a,b,2),Hc:(a,b,c,d)=>{a=E.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;u[d>>2]=a},Gc:(a,b)=>wc(a,b,0),Dc:xc,Fc:yc,ha:zc,ja:Ac,ga:zc,ia:Ac,ka:(a,b,c)=>{c?u[c>>2]=E.je.getQueryEXT(a,b):N||=1281},Cc:(a,b,c)=>{c?u[c>>
2]=E.getRenderbufferParameter(a,b):N||=1281},Ac:(a,b,c,d)=>{a=E.getShaderInfoLog(J[a]);null===a&&(a="(unknown error)");b=0<b&&d?O(a,d,b):0;c&&(u[c>>2]=b)},zc:(a,b,c,d)=>{a=E.getShaderPrecisionFormat(a,b);u[c>>2]=a.rangeMin;u[c+4>>2]=a.rangeMax;u[d>>2]=a.precision},yc:(a,b,c,d)=>{if(a=E.getShaderSource(J[a]))b=0<b&&d?O(a,d,b):0,c&&(u[c>>2]=b)},Bc:(a,b,c)=>{c?35716==b?(a=E.getShaderInfoLog(J[a]),null===a&&(a="(unknown error)"),u[c>>2]=a?a.length+1:0):35720==b?(a=E.getShaderSource(J[a]),u[c>>2]=a?a.length+
1:0):u[c>>2]=E.getShaderParameter(J[a],b):N||=1281},xc:a=>{var b=bb[a];if(!b){switch(a){case 7939:b=Q(Bc().join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=E.getParameter(a))||(N||=1280);b=b?Q(b):0;break;case 7938:b=Q(`OpenGL ES 2.0 (${E.getParameter(7938)})`);break;case 35724:b=E.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=Q(b);break;default:N||=1280}bb[a]=b}return b},
wc:(a,b,c)=>{c?w[c>>2]=E.getTexParameter(a,b):N||=1281},vc:(a,b,c)=>{c?u[c>>2]=E.getTexParameter(a,b):N||=1281},sc:Ec,uc:(a,b,c)=>{Fc(a,b,c,2)},tc:(a,b,c)=>{Fc(a,b,c,0)},pc:(a,b,c)=>{c?u[c>>2]=E.getVertexAttribOffset(a,b):N||=1281},rc:(a,b,c)=>{Gc(a,b,c,2)},qc:(a,b,c)=>{Gc(a,b,c,5)},oc:(a,b)=>E.hint(a,b),nc:a=>(a=Za[a])?E.isBuffer(a):0,mc:a=>E.isEnabled(a),lc:a=>(a=$a[a])?E.isFramebuffer(a):0,kc:a=>(a=F[a])?E.isProgram(a):0,oa:a=>(a=M[a])?E.je.isQueryEXT(a):0,ic:a=>(a=G[a])?E.isRenderbuffer(a):0,
hc:a=>(a=J[a])?E.isShader(a):0,gc:a=>(a=H[a])?E.isTexture(a):0,Ud:a=>(a=ab[a])?E.isVertexArray(a):0,fc:a=>E.lineWidth(a),ec:Hc,dc:(a,b)=>{3317==a?cb=b:3314==a&&(db=b);E.pixelStorei(a,b)},cb:(a,b)=>{E.tf.polygonModeWEBGL(a,b)},cc:(a,b)=>E.polygonOffset(a,b),eb:(a,b,c)=>{E.kf.polygonOffsetClampEXT(a,b,c)},la:(a,b)=>{E.je.queryCounterEXT(M[a],b)},bc:(a,b,c,d,e,g,f)=>{(f=Ic(g,e,c,d,f))?E.readPixels(a,b,c,d,e,g,f):N||=1280},ac:()=>{},$b:(a,b,c,d)=>E.renderbufferStorage(a,b,c,d),_b:(a,b)=>{E.sampleCoverage(a,
!!b)},Zb:(a,b,c,d)=>E.scissor(a,b,c,d),Yb:()=>{N||=1280},Xb:Jc,Wb:(a,b,c)=>E.stencilFunc(a,b,c),Vb:(a,b,c,d)=>E.stencilFuncSeparate(a,b,c,d),Ub:a=>E.stencilMask(a),Tb:(a,b)=>E.stencilMaskSeparate(a,b),Sb:(a,b,c)=>E.stencilOp(a,b,c),Rb:(a,b,c,d)=>E.stencilOpSeparate(a,b,c,d),Pb:(a,b,c,d,e,g,f,l,n)=>{n=n?Ic(l,f,d,e,n):null;E.texImage2D(a,b,c,d,e,g,f,l,n)},Ob:(a,b,c)=>E.texParameterf(a,b,c),Nb:(a,b,c)=>{E.texParameterf(a,b,w[c>>2])},Mb:(a,b,c)=>E.texParameteri(a,b,c),Lb:(a,b,c)=>{E.texParameteri(a,b,
u[c>>2])},Kb:(a,b,c,d,e,g,f,l,n)=>{n=n?Ic(l,f,e,g,n):null;E.texSubImage2D(a,b,c,d,e,g,f,l,n)},Jb:Kc,Ib:(a,b,c)=>{if(288>=b)for(var d=X[b],e=0;e<b;++e)d[e]=w[c+4*e>>2];else d=w.subarray(c>>2,c+4*b>>2);E.uniform1fv(W(a),d)},Hb:(a,b)=>{E.uniform1i(W(a),b)},Gb:(a,b,c)=>{if(288>=b)for(var d=Lc[b],e=0;e<b;++e)d[e]=u[c+4*e>>2];else d=u.subarray(c>>2,c+4*b>>2);E.uniform1iv(W(a),d)},Fb:(a,b,c)=>{E.uniform2f(W(a),b,c)},Eb:(a,b,c)=>{if(144>=b){b*=2;for(var d=X[b],e=0;e<b;e+=2)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*
e+4)>>2]}else d=w.subarray(c>>2,c+8*b>>2);E.uniform2fv(W(a),d)},Db:(a,b,c)=>{E.uniform2i(W(a),b,c)},Cb:(a,b,c)=>{if(144>=b){b*=2;for(var d=Lc[b],e=0;e<b;e+=2)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2]}else d=u.subarray(c>>2,c+8*b>>2);E.uniform2iv(W(a),d)},Bb:Mc,Ab:(a,b,c)=>{if(96>=b){b*=3;for(var d=X[b],e=0;e<b;e+=3)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2]}else d=w.subarray(c>>2,c+12*b>>2);E.uniform3fv(W(a),d)},zb:(a,b,c,d)=>{E.uniform3i(W(a),b,c,d)},yb:(a,b,c)=>{if(96>=b){b*=3;
for(var d=Lc[b],e=0;e<b;e+=3)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2]}else d=u.subarray(c>>2,c+12*b>>2);E.uniform3iv(W(a),d)},xb:(a,b,c,d,e)=>{E.uniform4f(W(a),b,c,d,e)},wb:(a,b,c)=>{if(72>=b){var d=X[4*b],e=w;c>>=2;b*=4;for(var g=0;g<b;g+=4){var f=c+g;d[g]=e[f];d[g+1]=e[f+1];d[g+2]=e[f+2];d[g+3]=e[f+3]}}else d=w.subarray(c>>2,c+16*b>>2);E.uniform4fv(W(a),d)},vb:(a,b,c,d,e)=>{E.uniform4i(W(a),b,c,d,e)},ub:(a,b,c)=>{if(72>=b){b*=4;for(var d=Lc[b],e=0;e<b;e+=4)d[e]=u[c+4*e>>2],
d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2],d[e+3]=u[c+(4*e+12)>>2]}else d=u.subarray(c>>2,c+16*b>>2);E.uniform4iv(W(a),d)},tb:(a,b,c,d)=>{if(72>=b){b*=4;for(var e=X[b],g=0;g<b;g+=4)e[g]=w[d+4*g>>2],e[g+1]=w[d+(4*g+4)>>2],e[g+2]=w[d+(4*g+8)>>2],e[g+3]=w[d+(4*g+12)>>2]}else e=w.subarray(d>>2,d+16*b>>2);E.uniformMatrix2fv(W(a),!!c,e)},sb:(a,b,c,d)=>{if(32>=b){b*=9;for(var e=X[b],g=0;g<b;g+=9)e[g]=w[d+4*g>>2],e[g+1]=w[d+(4*g+4)>>2],e[g+2]=w[d+(4*g+8)>>2],e[g+3]=w[d+(4*g+12)>>2],e[g+4]=w[d+(4*g+16)>>
2],e[g+5]=w[d+(4*g+20)>>2],e[g+6]=w[d+(4*g+24)>>2],e[g+7]=w[d+(4*g+28)>>2],e[g+8]=w[d+(4*g+32)>>2]}else e=w.subarray(d>>2,d+36*b>>2);E.uniformMatrix3fv(W(a),!!c,e)},rb:Nc,qb:Oc,pb:a=>{E.validateProgram(F[a])},ob:(a,b)=>E.vertexAttrib1f(a,b),nb:(a,b)=>{E.vertexAttrib1f(a,w[b>>2])},mb:(a,b,c)=>E.vertexAttrib2f(a,b,c),lb:(a,b)=>{E.vertexAttrib2f(a,w[b>>2],w[b+4>>2])},kb:(a,b,c,d)=>E.vertexAttrib3f(a,b,c,d),jb:(a,b)=>{E.vertexAttrib3f(a,w[b>>2],w[b+4>>2],w[b+8>>2])},ib:(a,b,c,d,e)=>E.vertexAttrib4f(a,
b,c,d,e),hb:(a,b)=>{E.vertexAttrib4f(a,w[b>>2],w[b+4>>2],w[b+8>>2],w[b+12>>2])},Qd:(a,b)=>{E.vertexAttribDivisor(a,b)},gb:Pc,fb:Qc,u:()=>0,sa:(a,b,c)=>Rc(a,{Je:u[c>>2],Ae:u[c+4>>2],lf:u[c+8>>2],gf:b,se:u[c+12>>2],Re:u[c+16>>2]}),P:(a,b)=>{a=U(a);return a?a.requestPointerLock?Lb()?cc(a):b?(Jb(cc,2,[a]),1):-2:-1:-4},Va:()=>{ma("OOM")},Sa:a=>{eval(a?z(r,a):"")},W:Sc,z:(a,b,c)=>"undefined"==typeof onbeforeunload?-1:1!==c?-5:Tc(a,b),I:(a,b,c,d)=>Uc(a,b,c,d,12,"blur"),k:Ub,s:(a,b,c)=>{a=U(a);if(!a)return-4;
a.style.width=b+"px";a.style.height=c+"px";return 0},J:(a,b,c,d)=>Uc(a,b,c,d,13,"focus"),B:(a,b,c,d)=>{if(!S.fullscreenEnabled())return-1;a=U(a);if(!a)return-4;Vc(a,b,c,d,"webkitfullscreenchange");return Vc(a,b,c,d,"fullscreenchange")},U:(a,b,c)=>Sc()?-1:Wc(a,b,c,26,"gamepadconnected"),T:(a,b,c)=>Sc()?-1:Wc(a,b,c,27,"gamepaddisconnected"),E:(a,b,c,d)=>Xc(a,b,c,d,2,"keydown"),C:(a,b,c,d)=>Xc(a,b,c,d,1,"keypress"),D:(a,b,c,d)=>Xc(a,b,c,d,3,"keyup"),Ra:(a,b,c)=>{a=V(a);Cb(a,b,c)},O:(a,b,c,d)=>Zc(a,b,
c,d,5,"mousedown"),M:(a,b,c,d)=>Zc(a,b,c,d,33,"mouseenter"),L:(a,b,c,d)=>Zc(a,b,c,d,34,"mouseleave"),x:(a,b,c,d)=>Zc(a,b,c,d,8,"mousemove"),N:(a,b,c,d)=>Zc(a,b,c,d,6,"mouseup"),F:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.re||document.body.ff||document.body.Ze))return-1;a=U(a);if(!a)return-4;$c(a,b,c,d,"mozpointerlockchange");$c(a,b,c,d,"webkitpointerlockchange");$c(a,b,c,d,"mspointerlockchange");return $c(a,b,c,d,"pointerlockchange")},y:(a,b,c,d)=>
ad(a,b,c,d),G:(a,b,c,d)=>bd(a,b,c,d,25,"touchcancel"),v:(a,b,c,d)=>bd(a,b,c,d,23,"touchend"),w:(a,b,c,d)=>bd(a,b,c,d,24,"touchmove"),H:(a,b,c,d)=>bd(a,b,c,d,22,"touchstart"),A:(a,b,c)=>cd(a,b,c),K:(a,b,c,d)=>(a=U(a))?"undefined"!=typeof a.onwheel?dd(a,b,c,d):-1:-4,ta:a=>document.title=a?z(r,a):"",t:()=>{throw"Please compile your program with async support in order to use asynchronous operations like emscripten_sleep";},Za:(a,b)=>{var c=0,d=0,e;for(e of pd()){var g=b+c;v[a+d>>2]=g;c+=O(e,g,Infinity)+
1;d+=4}return 0},_a:(a,b)=>{var c=pd();v[a>>2]=c.length;a=0;for(var d of c)a+=mb(d)+1;v[b>>2]=a;return 0},Y:()=>52,$a:()=>52,Xa:function(){return 70},Z:(a,b,c,d)=>{for(var e=0,g=0;g<c;g++){var f=v[b>>2],l=v[b+4>>2];b+=8;for(var n=0;n<l;n++){var t=a,B=r[f+n],L=qd[t];0===B||10===B?((1===t?da:m)(z(L)),L.length=0):L.push(B)}e+=l}v[d>>2]=e;return 0},p:ec,a:fc,Ua:gc,b:hc,Qb:ic,Ta:jc,q:kc,ca:lc,n:mc,ua:nc,aa:oc,R:qc,o:rc,i:sc,c:tc,l:vc,va:xc,Q:yc,f:Ec,ba:Hc,r:Jc,g:Kc,Ya:Mc,d:Nc,Ec:Oc,j:Pc,jc:Qc},Z;
(async function(){function a(c){Z=c.exports;fa=Z.Vd;c=fa.buffer;q=new Int8Array(c);ia=new Int16Array(c);r=new Uint8Array(c);ja=new Uint16Array(c);u=new Int32Array(c);v=new Uint32Array(c);w=new Float32Array(c);x=new Float64Array(c);ka=new BigInt64Array(c);new BigUint64Array(c);Yb=Z.Zd;y--;h.monitorRunDependencies?.(y);0==y&&la&&(c=la,la=null,c());return Z}y++;h.monitorRunDependencies?.(y);var b={a:xd};if(h.instantiateWasm)return new Promise(c=>{h.instantiateWasm(b,(d,e)=>{c(a(d,e))})});na??=h.locateFile?
h.locateFile("game.wasm",k):k+"game.wasm";return a((await qa(b)).instance)})();var P=a=>(P=Z.Xd)(a),yd=h._main=(a,b)=>(yd=h._main=Z.Yd)(a,b),Sb=a=>(Sb=Z._d)(a),Pb=a=>(Pb=Z.$d)(a),Rb=()=>(Rb=Z.ae)();function zd(a=[]){var b=yd;a.unshift(ba);var c=a.length,d=Pb(4*(c+1)),e=d;a.forEach(f=>{v[e>>2]=Qb(f);e+=4});v[e>>2]=0;try{var g=b(c,d);Ba(g)}catch(f){za(f)}}
function Ad(a=aa){function b(){h.calledRun=!0;if(!p){Z.Wd();h.onRuntimeInitialized?.();h.noInitialRun||zd(a);if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var c=h.postRun.shift();ta.push(c)}sa(ta)}}if(0<y)la=Ad;else{if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)va();sa(ua);0<y?la=Ad:h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),1);b()},1)):b()}}
if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.shift()();Ad();
