var h;h||=typeof Module != 'undefined' ? Module : {};var aa=[],ca="./this.program",da="undefined"!=typeof document?document.currentScript?.src:void 0,ea="",fa;try{ea=(new URL(".",da)).href}catch{}fa=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};var ha=console.log.bind(console),ia=console.error.bind(console),ja,la,ma=!1,na,k,m,p,oa,q,r,u,pa,w,qa=0,ra=null;function sa(){qa++;h.monitorRunDependencies?.(qa)}
function ta(){qa--;h.monitorRunDependencies?.(qa);if(0==qa&&ra){var a=ra;ra=null;a()}}function ua(a){h.onAbort?.(a);a="Aborted("+a+")";ia(a);ma=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var va;async function wa(a){if(!ja)try{var b=await fa(a);return new Uint8Array(b)}catch{}if(a==va&&ja)a=new Uint8Array(ja);else throw"both async and sync fetching of the wasm failed";return a}
async function xa(a,b){try{var c=await wa(a);return await WebAssembly.instantiate(c,b)}catch(d){ia(`failed to asynchronously prepare wasm: ${d}`),ua(d)}}async function ya(a){var b=va;if(!ja&&"function"==typeof WebAssembly.instantiateStreaming)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){ia(`wasm streaming compile failed: ${d}`),ia("falling back to ArrayBuffer instantiation")}return xa(b,a)}
class za{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var Aa=a=>{for(;0<a.length;)a.shift()(h)},Ba=[],Ca=[],Da=()=>{var a=h.preRun.shift();Ca.push(a)},Ea=!0;
function Ga(a,b){var c="float";c.endsWith("*")&&(c="*");switch(c){case "i1":k[a]=b;break;case "i8":k[a]=b;break;case "i16":p[a>>1]=b;break;case "i32":q[a>>2]=b;break;case "i64":pa[a>>3]=BigInt(b);break;case "float":u[a>>2]=b;break;case "double":w[a>>3]=b;break;case "*":r[a>>2]=b;break;default:ua(`invalid type for setValue: ${c}`)}}
var Ha="undefined"!=typeof TextDecoder?new TextDecoder:void 0,x=(a,b=0,c=NaN)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ha)return Ha.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var f=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|f:(e&7)<<18|g<<12|f<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
Ia=(a,b)=>a?x(m,a,b):"",Ja=a=>{if(!(a instanceof za||"unwind"==a))throw a;},Ka=a=>{na=a;Ea||(h.onExit?.(a),ma=!0);throw new za(a);},La=a=>{na=a;Ka(a)},Ma=()=>{if(!Ea)try{var a=na;na=a;Ka(a)}catch(b){Ja(b)}},Na=!1,Oa=!1,Pa=[];
function Qa(){function a(){var c=h.canvas;Oa=document.pointerLockElement===c||document.mozPointerLockElement===c||document.webkitPointerLockElement===c||document.msPointerLockElement===c}if(!Ra){Ra=!0;var b=h.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),b.exitPointerLock=
b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",c=>{!Oa&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}var Sa=!1,Ta=void 0,Ua=void 0;
function Va(){if(!Na)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var Wa=[];function Xa(){var a=h.canvas;Wa.forEach(b=>b(a.width,a.height))}
function Ya(a,b,c){b&&c?(a.zf=b,a.rf=c):(b=a.zf,c=a.rf);var d=b,e=c;0<h.forcedAspectRatio&&(d/e<h.forcedAspectRatio?d=Math.round(e*h.forcedAspectRatio):e=Math.round(d/h.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/d,screen.height/e);d=Math.round(d*g);e=Math.round(e*g)}Ua?(a.width!=d&&(a.width=
d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var Ra,y=12288,Za=!1,$a=0,ab=0,bb=0,z={alpha:!1,depth:!1,stencil:!1,antialias:!1},cb={},db,B,eb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,g)=>b.drawArraysInstancedANGLE(c,d,e,g),a.drawElementsInstanced=(c,d,e,g,f)=>b.drawElementsInstancedANGLE(c,d,e,g,f))},fb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),
a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},gb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},hb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},ib=1,jb=[],F=[],kb=[],lb=[],mb=[],H=[],nb=[],I=[],ob=[],pb={},qb=4,rb=0,sb=a=>{for(var b=ib++,c=a.length;c<b;c++)a[c]=null;return b},tb=(a,b,c,d)=>{for(var e=0;e<a;e++){var g=B[c](),f=g&&sb(d);g?(g.name=f,d[f]=g):J||=1282;q[b+4*e>>2]=f}},vb=(a,b)=>{a.le||(a.le=a.getContext,a.getContext=function(d,e){e=a.le(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?ub(c,b):0},ub=(a,b)=>{var c=
sb(I),d={handle:c,attributes:b,version:b.$e,qe:a};a.canvas&&(a.canvas.ue=d);I[c]=d;("undefined"==typeof b.mf||b.mf)&&wb(d);return c},yb=a=>{xb=I[a];h.ctx=B=xb?.qe},wb=a=>{a||=xb;if(!a.uf){a.uf=!0;var b=a.qe;b.Lf=b.getExtension("WEBGL_multi_draw");b.pf=b.getExtension("EXT_polygon_offset_clamp");b.nf=b.getExtension("EXT_clip_control");b.yf=b.getExtension("WEBGL_polygon_mode");eb(b);fb(b);gb(b);b.pe=b.getExtension("EXT_disjoint_timer_query");hb(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||
b.getExtension(c)})}},zb={},J,xb,Ab=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},K=(a,b,c)=>{var d=m;if(!(0<c))return 0;var e=b;c=b+c-1;for(var g=0;g<a.length;++g){var f=a.charCodeAt(g);if(55296<=f&&57343>=f){var l=a.charCodeAt(++g);f=65536+((f&1023)<<10)|l&1023}if(127>=f){if(b>=c)break;d[b++]=f}else{if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6}else{if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12}else{if(b+3>=c)break;d[b++]=
240|f>>18;d[b++]=128|f>>12&63}d[b++]=128|f>>6&63}d[b++]=128|f&63}}d[b]=0;return b-e},Bb=a=>{var b=Ab(a)+1,c=L(b);c&&K(a,c,b);return c},Tb=(a,b,c,d,e)=>{function g(){return f<Cb?(Ma(),!1):!0}Db=a;Eb=d;var f=Cb;Fb=!1;Gb=function(){if(!ma)if(0<Ib.length){var l=Ib.shift();l.Hf(l.Af);if(Jb){var n=Jb,v=0==n%1?n-1:Math.floor(n);Jb=l.Df?v:(8*n+(v+.5))/9}h.setStatus&&(l=h.statusMessage||"Please wait...",n=Jb??0,v=Kb.Gf??0,n?n<v?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(l):h.setStatus(""));
g()&&setTimeout(Gb,0)}else if(g())if(Lb=Lb+1|0,1==Mb&&1<Nb&&0!=Lb%Nb)Ob();else{0==Mb&&(Pb=performance.now());a:if(!ma){for(l of Qb)if(!1===l())break a;if(!ma)try{a(),Ma()}catch(E){Ja(E)}for(n of Rb)n()}g()&&Ob()}};e||(0<b?Sb(0,1E3/b):Sb(1,1),Ob());if(c)throw"unwind";},Fb=!1,Ob=null,Cb=0,Db=null,Eb=0,Mb=0,Nb=0,Lb=0,Ib=[],Qb=[],Rb=[],Ub=0;
function Vb(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Ub)Ub=b+1E3/60;else for(;b+2>=Ub;)Ub+=1E3/60;setTimeout(a,Math.max(Ub-b,0))}}
var Kb={},Gb,Jb,Pb,Wb,Sb=(a,b)=>{Mb=a;Nb=b;if(Db)if(Fb||=!0,0==a)Ob=function(){setTimeout(Gb,Math.max(0,Pb+b-performance.now())|0)};else if(1==a)Ob=function(){Vb(Gb)};else if(2==a){if("undefined"==typeof Wb)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Wb=d=>{c.push(d);postMessage("setimmediate","*")}}else Wb=setImmediate;Ob=function(){Wb(Gb)}}},Xb=[],Yb=(a,b)=>{Xb.length=
0;for(var c;c=m[a++];){var d=105!=c;d&=112!=c;b+=d&&b%8?4:0;Xb.push(112==c?r[b>>2]:106==c?pa[b>>3]:105==c?q[b>>2]:w[b>>3]);b+=d?8:4}return Xb};function Zb(a){var b=M.ke[a];b.target.removeEventListener(b.he,b.Ye,b.ie);M.ke.splice(a,1)}function $b(a,b,c){function d(g,f){if(g.length!=f.length)return!1;for(var l in g)if(g[l]!=f[l])return!1;return!0}for(var e of M.re)if(e.Qe==a&&d(e.We,c))return;M.re.push({Qe:a,bf:b,We:c});M.re.sort((g,f)=>g.bf<f.bf)}function ac(a){M.re=M.re.filter(b=>b.Qe!=a)}
function bc(){return navigator.userActivation?navigator.userActivation.isActive:M.Le&&M.ff.we}function cc(){if(bc()){var a=M.re;M.re=[];for(var b of a)b.Qe(...b.We)}}function N(a){if(!a.target)return-4;if(a.je)a.Ye=function(c){++M.Le;M.ff=a;cc();a.me(c);cc();--M.Le},a.target.addEventListener(a.he,a.Ye,a.ie),M.ke.push(a);else for(var b=0;b<M.ke.length;++b)M.ke[b].target==a.target&&M.ke[b].he==a.he&&Zb(b--);return 0}
function dc(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var M={Bf:0,Ke:0,Me:0,Fe:0,Ve:0,Se:0,Ie:0,Ff:0,Mf:0,Ef:0,Je:0,Oe:0,Ue:0,Re:0,Jf(a,b,c){k.set(k.subarray(b,b+c),a)},Nf(){for(;M.ke.length;)Zb(M.ke.length-1);M.re=[]},Le:0,re:[],ke:[],wf:(a,b)=>{for(var c=0;c<M.ke.length;++c)M.ke[c].target!=a||b&&b!=M.ke[c].he||Zb(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},ec=[0,document,window],O=a=>{a=2<a?a?x(m,a):"":a;return ec[a]||document.querySelector(a)},gc=a=>{var b=Ab(a)+1,c=fc(b);K(a,c,b);return c},jc=a=>
{var b=hc(),c=fc(8),d=c+4;a=gc(a.id);if(a=O(a))q[c>>2]=a.width,q[d>>2]=a.height;c=[q[c>>2],q[d>>2]];ic(b);return c},kc=(a,b,c)=>{a=O(a);if(!a)return-4;a.width=b;a.height=c;return 0},lc=(a,b,c)=>{if(a.Cf){var d=hc();a=gc(a.id);kc(a,b,c);ic(d)}else a.width=b,a.height=c},mc={},nc=[],oc,P=a=>{var b=nc[a];b||(nc[a]=b=oc.get(a));return b},pc=a=>{function b(){document.fullscreenElement||document.webkitFullscreenElement||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",
b),lc(a,d,e),a.style.width=g,a.style.height=f,a.style.backgroundColor=l,n||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=n,a.style.paddingLeft=v,a.style.paddingRight=E,a.style.paddingTop=C,a.style.paddingBottom=G,a.style.marginLeft=T,a.style.marginRight=ba,a.style.marginTop=U,a.style.marginBottom=Q,document.body.style.margin=X,document.documentElement.style.overflow=ka,document.body.scroll=t,a.style.se=V,a.ue&&a.ue.qe.viewport(0,0,d,e),mc.xe&&P(mc.xe)(37,0,mc.Xe))}
var c=jc(a),d=c[0],e=c[1],g=a.style.width,f=a.style.height,l=a.style.backgroundColor,n=document.body.style.backgroundColor,v=a.style.paddingLeft,E=a.style.paddingRight,C=a.style.paddingTop,G=a.style.paddingBottom,T=a.style.marginLeft,ba=a.style.marginRight,U=a.style.marginTop,Q=a.style.marginBottom,X=document.body.style.margin,ka=document.documentElement.style.overflow,t=document.body.scroll,V=a.style.se;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",
b)},qc=(a,b,c)=>{a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"},rc=a=>0>ec.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},sc=(a,b)=>{if(0!=b.Pe||0!=b.Ge){pc(a);var c=b.xf?innerWidth:screen.width,d=b.xf?innerHeight:screen.height,e=rc(a),g=e.width;e=e.height;var f=jc(a),l=f[0];f=f[1];3==b.Pe?(qc(a,(d-e)/2,(c-g)/2),c=g,d=e):2==b.Pe&&(c*f<l*d?(g=f*c/l,qc(a,(d-g)/2,0),d=g):(g=l*d/f,qc(a,0,(c-g)/2),c=g));var n;(n=a.style).backgroundColor||(n.backgroundColor=
"black");let v;(v=document.body.style).backgroundColor||(v.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.qf&&(a.style.se="optimizeSpeed",a.style.se="-moz-crisp-edges",a.style.se="-o-crisp-edges",a.style.se="-webkit-optimize-contrast",a.style.se="optimize-contrast",a.style.se="crisp-edges",a.style.se="pixelated");n=2==b.Ge?devicePixelRatio:1;0!=b.Ge&&(c=c*n|0,d=d*n|0,lc(a,c,d),a.ue&&a.ue.qe.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);
else return M.fullscreenEnabled()?-3:-1;mc=b;b.xe&&P(b.xe)(37,0,b.Xe);return 0},tc=a=>{if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?-3:-1;return 0},uc=(a,b)=>{w[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)w[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)w[a+8*c+528>>3]="object"==typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)k[a+c+1040]="object"==typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];
k[a+1104]=b.connected;q[a+1108>>2]=b.index;q[a+8>>2]=b.axes.length;q[a+12>>2]=b.buttons.length;K(b.id,a+1112,64);K(b.mapping,a+1176,64)},vc=(a,b)=>{B.attachShader(F[a],H[b])},wc=(a,b)=>{B.bindBuffer(a,jb[b])},xc=a=>B.blendEquation(a),yc=(a,b)=>B.blendFunc(a,b),zc=(a,b,c,d)=>{B.bufferData(a,c?m.subarray(c,c+b):b,d)},Ac=a=>B.clear(a),Bc=(a,b,c,d)=>B.clearColor(a,b,c,d),Cc=a=>{B.compileShader(H[a])},Dc=()=>{var a=sb(F),b=B.createProgram();b.name=a;b.Ee=b.Ce=b.De=0;b.Te=1;F[a]=b;return a},Ec=a=>{var b=
sb(H);H[b]=B.createShader(a);return b},Fc=a=>{B.depthMask(!!a)},Gc=a=>B.disable(a),Hc=[],Ic=(a,b,c,d)=>{B.drawElements(a,b,c,d)},Jc=a=>B.enable(a),Kc=a=>{B.enableVertexAttribArray(a)},Lc=(a,b)=>{tb(a,b,"createBuffer",jb)},Mc=(a,b,c,d,e,g,f,l)=>{b=F[b];if(a=B[a](b,c))d=l&&K(a.name,l,d),e&&(q[e>>2]=d),g&&(q[g>>2]=a.size),f&&(q[f>>2]=a.type)},Nc=(a,b)=>B.getAttribLocation(F[a],b?x(m,b):""),S=(a,b)=>{r[a>>2]=b;r[a+4>>2]=(b-r[a>>2])/4294967296},Oc=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;
break;case 36344:0!=c&&1!=c&&(J||=1280);return;case 36345:d=0;break;case 34466:var e=B.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=B.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":J||=1280;return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:J||=1280;return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof
Array){for(a=0;a<e.length;++a)switch(c){case 0:q[b+4*a>>2]=e[a];break;case 2:u[b+4*a>>2]=e[a];break;case 4:k[b+a]=e[a]?1:0}return}try{d=e.name|0}catch(g){J||=1280;ia(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${g})`);return}}break;default:J||=1280;ia(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${e} of type ${typeof e}!`);return}switch(c){case 1:S(b,d);break;case 0:q[b>>2]=d;break;case 2:u[b>>2]=d;break;case 4:k[b]=
d?1:0}}else J||=1281},Pc=(a,b,c)=>{if(c){a=B.pe.getQueryObjectEXT(ob[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;S(c,d)}else J||=1281},Qc=(a,b,c)=>{if(c){a=B.pe.getQueryObjectEXT(ob[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;q[c>>2]=d}else J||=1281},Rc=()=>{var a=hb(B);return a=a.concat(a.map(b=>"GL_"+b))},Sc=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Tc=a=>{var b=a.ve,c=a.df,d;if(!b){a.ve=b={};a.cf={};var e=B.getProgramParameter(a,35718);for(d=0;d<e;++d){var g=B.getActiveUniform(a,d);var f=g.name;
g=g.size;var l=Sc(f);l=0<l?f.slice(0,l):f;var n=a.Te;a.Te+=g;c[l]=[g,n];for(f=0;f<g;++f)b[n]=f,a.cf[n++]=l}}},Uc=(a,b)=>{b=b?x(m,b):"";if(a=F[a]){Tc(a);var c=a.ve,d=0,e=b,g=Sc(b);0<g&&(d=parseInt(b.slice(g+1))>>>0,e=b.slice(0,g));if((e=a.df[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||B.getUniformLocation(a,b)))return d}else J||=1281;return-1},W=a=>{var b=B.gf;if(b){var c=b.ve[a];"number"==typeof c&&(b.ve[a]=c=B.getUniformLocation(b,b.cf[a]+(0<c?`[${c}]`:"")));return c}J||=1282},Vc=(a,b,c,d)=>{if(c)if(a=F[a],
Tc(a),a=B.getUniform(a,W(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:q[c>>2]=a;break;case 2:u[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:q[c+4*b>>2]=a[b];break;case 2:u[c+4*b>>2]=a[b]}else J||=1281},Wc=(a,b,c,d)=>{if(c)if(a=B.getVertexAttrib(a,b),34975==b)q[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:q[c>>2]=a;break;case 2:u[c>>2]=a;break;case 5:q[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:q[c+4*b>>2]=a[b];break;
case 2:u[c+4*b>>2]=a[b];break;case 5:q[c+4*b>>2]=Math.fround(a[b])}else J||=1281},Xc=a=>{a=F[a];B.linkProgram(a);a.ve=0;a.df={}},Yc=(a,b,c,d,e)=>{a-=5120;a=1==a?m:4==a?q:6==a?u:5==a||28922==a?r:oa;b=d*((rb||c)*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+qb-1&-qb);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},Zc=(a,b,c,d)=>{for(var e="",g=0;g<b;++g)e+=Ia(r[c+4*g>>2],d?r[d+4*g>>2]:void 0);B.shaderSource(H[a],e)},$c=(a,b)=>{B.uniform1f(W(a),
b)},ad=[],bd=[],cd=(a,b,c,d)=>{B.uniform3f(W(a),b,c,d)},dd=(a,b,c,d)=>{if(18>=b){var e=ad[16*b],g=u;d>>=2;b*=16;for(var f=0;f<b;f+=16){var l=d+f;e[f]=g[l];e[f+1]=g[l+1];e[f+2]=g[l+2];e[f+3]=g[l+3];e[f+4]=g[l+4];e[f+5]=g[l+5];e[f+6]=g[l+6];e[f+7]=g[l+7];e[f+8]=g[l+8];e[f+9]=g[l+9];e[f+10]=g[l+10];e[f+11]=g[l+11];e[f+12]=g[l+12];e[f+13]=g[l+13];e[f+14]=g[l+14];e[f+15]=g[l+15]}}else e=u.subarray(d>>2,d+64*b>>2);B.uniformMatrix4fv(W(a),!!c,e)},ed=a=>{a=F[a];B.useProgram(a);B.gf=a},fd=(a,b,c,d,e,g)=>{B.vertexAttribPointer(a,
b,c,!!d,e,g)},gd=(a,b,c,d)=>B.viewport(a,b,c,d),hd=(a,b)=>{if(!M.fullscreenEnabled())return-1;a=O(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?bc()?sc(a,b):b.lf?($b(sc,1,[a,b]),1):-2:-3:-4},jd=()=>{try{if(navigator.getGamepads)return(M.Be=navigator.getGamepads())?0:-1}catch(a){navigator.getGamepads=null}return-1},kd=(a,b)=>{var c={target:O(2),he:"beforeunload",je:b,me:(d=event)=>{var e=P(b)(28,0,a);e&&=e?x(m,e):"";if(e)return d.preventDefault(),d.returnValue=e},ie:!0};return N(c)},ld=
(a,b,c,d,e,g)=>{M.Ie||(M.Ie=L(256));a={target:O(a),he:g,je:d,me:(f=event)=>{var l=f.target.id?f.target.id:"",n=M.Ie;K(dc(f.target),n+0,128);K(l,n+128,128);P(d)(e,n,b)&&f.preventDefault()},ie:c};return N(a)},md=(a,b,c,d,e)=>{M.Je||(M.Je=L(276));return N({target:a,he:e,je:d,me:(g=event)=>{var f=M.Je,l=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,n=!!l;k[f]=n;k[f+1]=M.fullscreenEnabled();var v=n?l:M.vf,E=v?.id||"";K(dc(v),f+
2,128);K(E,f+130,128);q[f+260>>2]=v?v.clientWidth:0;q[f+264>>2]=v?v.clientHeight:0;q[f+268>>2]=screen.width;q[f+272>>2]=screen.height;n&&(M.vf=l);P(d)(19,f,b)&&g.preventDefault()},ie:c})},nd=(a,b,c,d,e)=>{M.Ke||(M.Ke=L(1240));b={target:O(2),we:!0,he:e,je:c,me:(g=event)=>{var f=M.Ke;uc(f,g.gamepad);P(c)(d,f,a)&&g.preventDefault()},ie:b};return N(b)},od=(a,b,c,d,e,g)=>{M.Me||(M.Me=L(160));a={target:O(a),he:g,je:d,me:f=>{var l=M.Me;w[l>>3]=f.timeStamp;var n=l>>2;q[n+2]=f.location;k[l+12]=f.ctrlKey;k[l+
13]=f.shiftKey;k[l+14]=f.altKey;k[l+15]=f.metaKey;k[l+16]=f.repeat;q[n+5]=f.charCode;q[n+6]=f.keyCode;q[n+7]=f.which;K(f.key||"",l+32,32);K(f.code||"",l+64,32);K(f.char||"",l+96,32);K(f.locale||"",l+128,32);P(d)(e,l,b)&&f.preventDefault()},ie:c};return N(a)},pd=(a,b,c)=>{w[a>>3]=b.timeStamp;var d=a>>2;q[d+2]=b.screenX;q[d+3]=b.screenY;q[d+4]=b.clientX;q[d+5]=b.clientY;k[a+24]=b.ctrlKey;k[a+25]=b.shiftKey;k[a+26]=b.altKey;k[a+27]=b.metaKey;p[2*d+14]=b.button;p[2*d+15]=b.buttons;q[d+8]=b.movementX;
q[d+9]=b.movementY;a=rc(c);q[d+10]=b.clientX-(a.left|0);q[d+11]=b.clientY-(a.top|0)},qd=(a,b,c,d,e,g)=>{M.Fe||(M.Fe=L(64));a=O(a);return N({target:a,we:"mousemove"!=g&&"mouseenter"!=g&&"mouseleave"!=g,he:g,je:d,me:(f=event)=>{pd(M.Fe,f,a);P(d)(e,M.Fe,b)&&f.preventDefault()},ie:c})},rd=(a,b,c,d,e)=>{M.Oe||(M.Oe=L(257));return N({target:a,he:e,je:d,me:(g=event)=>{var f=M.Oe,l=document.pointerLockElement||document.le||document.sf||document.Ae;k[f]=!!l;var n=l?.id||"";K(dc(l),f+1,128);K(n,f+129,128);
P(d)(20,f,b)&&g.preventDefault()},ie:c})},sd=(a,b,c,d)=>{M.Se||(M.Se=L(36));a=O(a);return N({target:a,he:"resize",je:d,me:(e=event)=>{if(e.target==a){var g=document.body;if(g){var f=M.Se;q[f>>2]=0;q[f+4>>2]=g.clientWidth;q[f+8>>2]=g.clientHeight;q[f+12>>2]=innerWidth;q[f+16>>2]=innerHeight;q[f+20>>2]=outerWidth;q[f+24>>2]=outerHeight;q[f+28>>2]=pageXOffset|0;q[f+32>>2]=pageYOffset|0;P(d)(10,f,b)&&e.preventDefault()}}},ie:c})},td=(a,b,c,d,e,g)=>{M.Re||(M.Re=L(1552));a=O(a);return N({target:a,we:"touchstart"==
g||"touchend"==g,he:g,je:d,me:f=>{var l={},n=f.touches;for(var v of n)v.Ze=v.af=0,l[v.identifier]=v;for(var E of f.changedTouches)E.Ze=1,l[E.identifier]=E;for(var C of f.targetTouches)l[C.identifier].af=1;n=M.Re;w[n>>3]=f.timeStamp;k[n+12]=f.ctrlKey;k[n+13]=f.shiftKey;k[n+14]=f.altKey;k[n+15]=f.metaKey;v=n+16;E=rc(a);C=0;for(let G of Object.values(l))if(l=v>>2,q[l]=G.identifier,q[l+1]=G.screenX,q[l+2]=G.screenY,q[l+3]=G.clientX,q[l+4]=G.clientY,q[l+5]=G.pageX,q[l+6]=G.pageY,k[v+28]=G.Ze,k[v+29]=G.af,
q[l+8]=G.clientX-(E.left|0),q[l+9]=G.clientY-(E.top|0),v+=48,31<++C)break;q[n+8>>2]=C;P(d)(e,n,b)&&f.preventDefault()},ie:c})},ud=(a,b,c)=>{var d=ec[1];M.Ue||(M.Ue=L(8));return N({target:d,he:"visibilitychange",je:c,me:(e=event)=>{var g=M.Ue,f=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);k[g]=document.hidden;q[g+4>>2]=f;P(c)(21,g,a)&&e.preventDefault()},ie:b})},vd=(a,b,c,d)=>{M.Ve||(M.Ve=L(96));return N({target:a,we:!0,he:"wheel",je:d,me:(e=event)=>{var g=M.Ve;pd(g,
e,a);w[g+64>>3]=e.deltaX;w[g+72>>3]=e.deltaY;w[g+80>>3]=e.deltaZ;q[g+88>>2]=e.deltaMode;P(d)(9,g,b)&&e.preventDefault()},ie:c})};function wd(a){var b=Y,c=b.Ae.pop()||b.le.length;b.le[c]=a;return c}class xd{le=[void 0];Ae=[];get(a){return this.le[a]}has(a){return void 0!==this.le[a]}}var Y,yd;
function zd(a,b,c,d,e){function g(){var D=0,R=0;t.response&&X&&0===r[a+12>>2]&&(R=t.response.byteLength);0<R&&(D=L(R),m.set(new Uint8Array(t.response),D));r[a+12>>2]=D;S(a+16,R);S(a+24,0);(D=t.response?t.response.byteLength:0)&&S(a+32,D);p[a+40>>1]=t.readyState;p[a+42>>1]=t.status;t.statusText&&K(t.statusText,a+44,64)}var f=r[a+8>>2];if(f){var l=f?x(m,f):"",n=a+108,v=Ia(n+0);v||="GET";var E=r[n+56>>2],C=r[n+68>>2],G=r[n+72>>2];f=r[n+76>>2];var T=r[n+80>>2],ba=r[n+84>>2],U=r[n+88>>2],Q=r[n+52>>2],
X=!!(Q&1),ka=!!(Q&2);Q=!!(Q&64);C=C?C?x(m,C):"":void 0;G=G?G?x(m,G):"":void 0;var t=new XMLHttpRequest;t.withCredentials=!!m[n+60];t.open(v,l,!Q,C,G);Q||(t.timeout=E);t.le=l;t.responseType="arraybuffer";T&&(l=T?x(m,T):"",t.overrideMimeType(l));if(f)for(;;){n=r[f>>2];if(!n)break;l=r[f+4>>2];if(!l)break;f+=8;n=n?x(m,n):"";l=l?x(m,l):"";t.setRequestHeader(n,l)}var V=wd(t);r[a>>2]=V;f=ba&&U?m.slice(ba,ba+U):null;t.onload=D=>{Y.has(V)&&(g(),200<=t.status&&300>t.status?b?.(a,t,D):c?.(a,t,D))};t.onerror=
D=>{Y.has(V)&&(g(),c?.(a,t,D))};t.ontimeout=D=>{Y.has(V)&&c?.(a,t,D)};t.onprogress=D=>{if(Y.has(V)){var R=X&&ka&&t.response?t.response.byteLength:0,A=0;0<R&&X&&ka&&(A=L(R),m.set(new Uint8Array(t.response),A));r[a+12>>2]=A;S(a+16,R);S(a+24,D.loaded-R);S(a+32,D.total);p[a+40>>1]=t.readyState;3<=t.readyState&&0===t.status&&0<D.loaded&&(t.status=200);p[a+42>>1]=t.status;t.statusText&&K(t.statusText,a+44,64);d?.(a,t,D);A&&Ad(A)}};t.onreadystatechange=D=>{Y.has(V)&&(p[a+40>>1]=t.readyState,2<=t.readyState&&
(p[a+42>>1]=t.status),e?.(a,t,D))};try{t.send(f)}catch(D){c?.(a,t,D)}}else c(a,0,"no url specified!")}function Bd(a,b,c,d){var e=yd;if(e){var g=r[a+108+64>>2];g||=r[a+8>>2];var f=g?x(m,g):"";try{var l=e.transaction(["FILES"],"readwrite").objectStore("FILES").put(b,f);l.onsuccess=()=>{p[a+40>>1]=4;p[a+42>>1]=200;K("OK",a+44,64);c(a,0,f)};l.onerror=n=>{p[a+40>>1]=4;p[a+42>>1]=413;K("Payload Too Large",a+44,64);d(a,0,n)}}catch(n){d(a,0,n)}}else d(a,0,"IndexedDB not available!")}
function Cd(a,b,c){var d=yd;if(d){var e=r[a+108+64>>2];e||=r[a+8>>2];e=e?x(m,e):"";try{var g=d.transaction(["FILES"],"readonly").objectStore("FILES").get(e);g.onsuccess=f=>{if(f.target.result){f=f.target.result;var l=f.byteLength||f.length,n=L(l);m.set(new Uint8Array(f),n);r[a+12>>2]=n;S(a+16,l);S(a+24,0);S(a+32,l);p[a+40>>1]=4;p[a+42>>1]=200;K("OK",a+44,64);b(a,0,f)}else p[a+40>>1]=4,p[a+42>>1]=404,K("Not Found",a+44,64),c(a,0,"no data")};g.onerror=f=>{p[a+40>>1]=4;p[a+42>>1]=404;K("Not Found",a+
44,64);c(a,0,f)}}catch(f){c(a,0,f)}}else c(a,0,"IndexedDB not available!")}function Dd(a,b,c){var d=yd;if(d){var e=r[a+108+64>>2];e||=r[a+8>>2];e=e?x(m,e):"";try{var g=d.transaction(["FILES"],"readwrite").objectStore("FILES").delete(e);g.onsuccess=f=>{f=f.target.result;r[a+12>>2]=0;S(a+16,0);S(a+24,0);S(a+32,0);p[a+40>>1]=4;p[a+42>>1]=200;K("OK",a+44,64);b(a,0,f)};g.onerror=f=>{p[a+40>>1]=4;p[a+42>>1]=404;K("Not Found",a+44,64);c(a,0,f)}}catch(f){c(a,0,f)}}else c(a,0,"IndexedDB not available!")}
var Ed={},Gd=()=>{if(!Fd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in Ed)void 0===Ed[b]?delete a[b]:a[b]=Ed[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Fd=c}return Fd},Fd,Hd=[null,[],[]],Id=(a,b,c)=>{a.addEventListener(b,c,{once:!0})},Jd=a=>{var b;b||=[document,document.getElementById("canvas")];["keydown","mousedown",
"touchstart"].forEach(c=>{b.forEach(d=>{d&&Id(d,c,()=>{"suspended"===a.state&&a.resume()})})})},Kd=(a,b=[])=>{P(a)(...b)};
h.requestFullscreen=function(a,b){function c(){Na=!1;var g=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===g?(d.exitFullscreen=Va,Ta&&d.requestPointerLock(),Na=!0,Ua?("undefined"!=typeof SDL&&(q[SDL.screen>>2]=r[SDL.screen>>2]|8388608),Ya(h.canvas),Xa()):Ya(d)):(g.parentNode.insertBefore(d,g),g.parentNode.removeChild(g),Ua?("undefined"!=typeof SDL&&(q[SDL.screen>>2]=
r[SDL.screen>>2]&-8388609),Ya(h.canvas),Xa()):Ya(d));h.onFullScreen?.(Na);h.onFullscreen?.(Na)}Ta=a;Ua=b;"undefined"==typeof Ta&&(Ta=!0);"undefined"==typeof Ua&&(Ua=!1);var d=h.canvas;Sa||(Sa=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=
e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()};h.setCanvasSize=function(a,b,c){Ya(h.canvas,a,b);c||Xa()};h.getUserMedia=function(a){let b;(b=window).getUserMedia||(b.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)};
h.createContext=function(a,b,c,d){if(b&&h.ctx&&a==h.canvas)return h.ctx;var e;if(b){var g={antialias:!1,alpha:!1,$e:1};if(d)for(var f in d)g[f]=d[f];if("undefined"!=typeof zb&&(e=vb(a,g)))var l=I[e].qe}else l=a.getContext("2d");if(!l)return null;c&&(h.ctx=l,b&&yb(e),Pa.forEach(n=>n()),Qa());return l};h.requestAnimationFrame=Vb;h.pauseMainLoop=function(){Ob=null;Cb++};h.resumeMainLoop=function(){Cb++;var a=Mb,b=Nb,c=Db;Db=null;Tb(c,0,!1,Eb,!0);Sb(a,b);Ob()};h.preMainLoop&&Qb.push(h.preMainLoop);
h.postMainLoop&&Rb.push(h.postMainLoop);for(let a=0;32>a;++a)Hc.push(Array(a));for(var Ld=new Float32Array(288),Md=0;288>=Md;++Md)ad[Md]=Ld.subarray(0,Md);var Nd=new Int32Array(288);for(Md=0;288>=Md;++Md)bd[Md]=Nd.subarray(0,Md);Y=new xd;sa();
(function(a,b){try{var c=indexedDB.open("emscripten_filesystem",1)}catch(d){b(d);return}c.onupgradeneeded=d=>{d=d.target.result;d.objectStoreNames.contains("FILES")&&d.deleteObjectStore("FILES");d.createObjectStore("FILES")};c.onsuccess=d=>a(d.target.result);c.onerror=b})(a=>{yd=a;ta()},()=>{yd=!1;ta()});h.noExitRuntime&&(Ea=h.noExitRuntime);h.print&&(ha=h.print);h.printErr&&(ia=h.printErr);h.wasmBinary&&(ja=h.wasmBinary);h.arguments&&(aa=h.arguments);h.thisProgram&&(ca=h.thisProgram);
var Od={8004052:()=>{alert("The FishyHotel server is currently down for maintinance.")},8004121:()=>{1==confirm("Would you like to play Hypergolia?")&&window.open("https://silentrooms.itch.io/hypergolia").focus()},8004245:()=>{1==confirm("Would you like to play Fishtank Dungeons?")&&window.open("https://fishyhotel.com/fishtankdungeons").focus()},8004377:()=>{1==confirm("Would you like to play BloodGames Coin Pusher?")&&window.open("https://fishyhotel.com/blood").focus()},8004503:()=>{1==confirm("Would you like to play Fishtank Arena?")&&
window.open("https://fishtankdungeons.itch.io/arena").focus()},8004631:()=>"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?!0:!1,8004778:()=>"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?!0:!1,8005012:a=>{"undefined"===typeof h.SDL2&&(h.SDL2={});var b=h.SDL2;a?b.capture={}:b.audio={};b.ge||("undefined"!==typeof AudioContext?b.ge=new AudioContext:"undefined"!==typeof webkitAudioContext&&
(b.ge=new webkitAudioContext),b.ge&&"undefined"===typeof navigator.userActivation&&Jd(b.ge));return void 0===b.ge?-1:0},8005564:()=>h.SDL2.ge.sampleRate,8005632:(a,b,c,d)=>{function e(){}function g(l){void 0!==f.capture.oe&&(clearInterval(f.capture.oe),f.capture.oe=void 0,f.capture.te=void 0);f.capture.Ne=f.ge.createMediaStreamSource(l);f.capture.ne=f.ge.createScriptProcessor(b,a,1);f.capture.ne.onaudioprocess=function(n){void 0!==f&&void 0!==f.capture&&(n.outputBuffer.getChannelData(0).fill(0),f.capture.He=
n.inputBuffer,Kd(c,[d]))};f.capture.Ne.connect(f.capture.ne);f.capture.ne.connect(f.ge.destination);f.capture.stream=l}var f=h.SDL2;f.capture.te=f.ge.createBuffer(a,b,f.ge.sampleRate);f.capture.te.getChannelData(0).fill(0);f.capture.oe=setInterval(function(){f.capture.He=f.capture.te;Kd(c,[d])},b/f.ge.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(g).catch(e):void 0!==navigator.webkitGetUserMedia&&
navigator.webkitGetUserMedia({audio:!0,video:!1},g,e)},8007325:(a,b,c,d)=>{var e=h.SDL2;e.audio.ne=e.ge.createScriptProcessor(b,0,a);e.audio.ne.onaudioprocess=function(g){void 0!==e&&void 0!==e.audio&&(void 0!==e.audio.oe&&(clearInterval(e.audio.oe),e.audio.oe=void 0,e.audio.te=void 0),e.audio.ze=g.outputBuffer,Kd(c,[d]))};e.audio.ne.connect(e.ge.destination);"suspended"===e.ge.state&&(e.audio.te=e.ge.createBuffer(a,b,e.ge.sampleRate),e.audio.te.getChannelData(0).fill(0),e.audio.oe=setInterval(function(){"undefined"!==
typeof navigator.userActivation&&navigator.userActivation.hasBeenActive&&e.ge.resume();e.audio.ze=e.audio.te;Kd(c,[d]);e.audio.ze=void 0},b/e.ge.sampleRate*1E3))},8008500:(a,b)=>{for(var c=h.SDL2,d=c.capture.He.numberOfChannels,e=0;e<d;++e){var g=c.capture.He.getChannelData(e);if(g.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+g.length+" samples vs expected "+b+" samples!";if(1==d)for(var f=0;f<b;++f)Ga(a+4*f,g[f]);else for(f=0;f<b;++f)Ga(a+4*(f*d+e),g[f])}},8009105:(a,
b)=>{var c=h.SDL2;a>>>=2;for(var d=c.audio.ze.numberOfChannels,e=0;e<d;++e){var g=c.audio.ze.getChannelData(e);if(g.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+g.length+" samples vs expected "+b+" samples!";for(var f=0;f<b;++f)g[f]=u[a+(f*d+e)]}},8009594:a=>{var b=h.SDL2;if(a){void 0!==b.capture.oe&&clearInterval(b.capture.oe);if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c])}void 0!==b.capture.ne&&
(b.capture.ne.onaudioprocess=function(){},b.capture.ne.disconnect());void 0!==b.capture.Ne&&b.capture.Ne.disconnect();b.capture=void 0}else void 0!=b.audio.ne&&b.audio.ne.disconnect(),void 0!==b.audio.oe&&clearInterval(b.audio.oe),b.audio=void 0;void 0!==b.ge&&void 0===b.audio&&void 0===b.capture&&(b.ge.close(),b.ge=void 0)},8010600:(a,b,c)=>{h.SDL2||(h.SDL2={});var d=h.SDL2;d.ef!==h.canvas&&(d.ye=h.createContext(h.canvas,!1,!0),d.ef=h.canvas);if(d.w!==a||d.h!==b||d.tf!==d.ye)d.image=d.ye.createImageData(a,
b),d.w=a,d.h=b,d.tf=d.ye;a=d.image.data;b=c/4;var e=0;if("undefined"!==typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var g=q[b];a[e]=g&255;a[e+1]=g>>8&255;a[e+2]=g>>16&255;a[e+3]=255;b++;e+=4}else if(d.jf!==a&&(d.hf=new Int32Array(a.buffer),d.kf=new Uint8Array(a.buffer),d.jf=a),a=d.hf,c=a.length,a.set(q.subarray(b,b+c)),a=d.kf,b=3,e=b+4*c,0==c%8)for(;b<e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=
b+4|0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=255,b=b+4|0;d.ye.putImageData(d.image,0,0)},8012068:(a,b,c,d,e)=>{var g=document.createElement("canvas");g.width=a;g.height=b;var f=g.getContext("2d");a=f.createImageData(a,b);b=a.data;e/=4;var l=0,n;if("undefined"!==typeof CanvasPixelArray&&b instanceof CanvasPixelArray)for(n=b.length;l<n;){var v=q[e];b[l]=v&255;b[l+1]=v>>8&255;b[l+2]=v>>16&255;b[l+3]=v>>24&255;e++;l+=4}else b=new Int32Array(b.buffer),n=b.length,b.set(q.subarray(e,e+n));f.putImageData(a,
0,0);c=0===c&&0===d?"url("+g.toDataURL()+"), auto":"url("+g.toDataURL()+") "+c+" "+d+", auto";d=L(c.length+1);K(c,d,c.length+1);return d},8013056:a=>{h.canvas&&(h.canvas.style.cursor=a?x(m,a):"")},8013139:()=>{h.canvas&&(h.canvas.style.cursor="none")},8013208:()=>window.innerWidth,8013238:()=>window.innerHeight},Pd={aa:function(){return 0},_a:function(){return 0},$a:function(){},Ua:()=>{},Ea:a=>{if(12448==a)return y=12288,1;y=12300;return 0},Ha:(a,b,c,d,e)=>{if(62E3!=a)y=12296,c=0;else{if(b)for(;;){a=
q[b>>2];if(12321==a)z.alpha=0<q[b+4>>2];else if(12325==a)z.depth=0<q[b+4>>2];else if(12326==a)z.stencil=0<q[b+4>>2];else if(12337==a)a=q[b+4>>2],z.antialias=0<a;else if(12338==a)a=q[b+4>>2],z.antialias=1==a;else if(12544==a)z.If=12547!=q[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(q[e>>2]=1),c&&0<d&&(r[c>>2]=62002),y=12288,c=1):(y=12300,c=0)}return c},va:(a,b,c,d)=>{if(62E3!=a)return y=12296,0;for(a=1;;){b=q[d>>2];if(12440==b)a=q[d+4>>2];else if(12344==b)break;else return y=12292,0;d+=8}if(2!=
a)return y=12293,0;z.$e=a-1;z.Kf=0;db=vb(h.canvas,z);if(0!=db)return y=12288,yb(db),Pa.forEach(e=>e()),yb(null),62004;y=12297;return 0},xa:(a,b)=>{if(62E3!=a)return y=12296,0;if(62002!=b)return y=12293,0;y=12288;return 62006},wa:(a,b)=>{if(62E3!=a)return y=12296,0;if(62004!=b)return y=12294,0;a=db;xb===I[a]&&(xb=null);"object"==typeof M&&M.wf(I[a].qe.canvas);I[a]?.qe.canvas&&(I[a].qe.canvas.ue=void 0);I[a]=null;y=12288;$a==b&&($a=0);return 1},ya:(a,b)=>{if(62E3!=a)return y=12296,0;if(62006!=b)return y=
12301,1;ab==b&&(ab=0);bb==b&&(bb=0);y=12288;return 1},Ja:(a,b,c,d)=>{if(62E3!=a)return y=12296,0;if(62002!=b)return y=12293,0;if(!d)return y=12300,0;y=12288;switch(c){case 12320:return q[d>>2]=z.alpha?32:24,1;case 12321:return q[d>>2]=z.alpha?8:0,1;case 12322:return q[d>>2]=8,1;case 12323:return q[d>>2]=8,1;case 12324:return q[d>>2]=8,1;case 12325:return q[d>>2]=z.depth?24:0,1;case 12326:return q[d>>2]=z.stencil?8:0,1;case 12327:return q[d>>2]=12344,1;case 12328:return q[d>>2]=62002,1;case 12329:return q[d>>
2]=0,1;case 12330:return q[d>>2]=4096,1;case 12331:return q[d>>2]=16777216,1;case 12332:return q[d>>2]=4096,1;case 12333:return q[d>>2]=0,1;case 12334:return q[d>>2]=0,1;case 12335:return q[d>>2]=12344,1;case 12337:return q[d>>2]=z.antialias?4:0,1;case 12338:return q[d>>2]=z.antialias?1:0,1;case 12339:return q[d>>2]=4,1;case 12340:return q[d>>2]=12344,1;case 12341:case 12342:case 12343:return q[d>>2]=-1,1;case 12345:case 12346:return q[d>>2]=0,1;case 12347:return q[d>>2]=0,1;case 12348:return q[d>>
2]=1;case 12349:case 12350:return q[d>>2]=0,1;case 12351:return q[d>>2]=12430,1;case 12352:return q[d>>2]=4,1;case 12354:return q[d>>2]=0,1;default:return y=12292,0}},S:a=>{y=12288;return 0!=a&&1!=a?0:62E3},ua:()=>y,Fa:(a,b,c)=>{if(62E3!=a)return y=12296,0;b&&(q[b>>2]=1);c&&(q[c>>2]=4);Za=!0;y=12288;return 1},za:(a,b,c,d)=>{if(62E3!=a)return y=12296,0;if(0!=d&&62004!=d)return y=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return y=12301,0;yb(d?db:null);$a=d;bb=b;ab=c;y=12288;return 1},ta:(a,b)=>{if(62E3!=
a)return y=12296,0;y=12288;if(cb[b])return cb[b];switch(b){case 12371:a=Bb("Emscripten");break;case 12372:a=Bb("1.4 Emscripten EGL");break;case 12373:a=Bb("");break;case 12429:a=Bb("OpenGL_ES");break;default:return y=12300,0}return cb[b]=a},Aa:()=>{if(Za)if(B)if(B.isContextLost())y=12302;else return y=12288,1;else y=12290;else y=12289;return 0},Ba:(a,b)=>{if(62E3!=a)return y=12296,0;0==b?Sb(0,0):Sb(1,b);y=12288;return 1},Ga:a=>{if(62E3!=a)return y=12296,0;bb=ab=$a=0;Za=!1;y=12288;return 1},Da:()=>
{y=12288;return 1},Ca:()=>{y=12288;return 1},j:(a,b,c)=>{b=Yb(b,c);return Od[a](...b)},e:(a,b,c)=>{b=Yb(b,c);return Od[a](...b)},La:(a,b,c)=>{b=Yb(b,c);return Od[a](...b)},ba:()=>Date.now(),oa:()=>{if(!M.fullscreenEnabled())return-1;ac(sc);var a=ec[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},ra:()=>{ac(tc);if(document.exitPointerLock)document.exitPointerLock();else return-1;
return 0},Ma:function(a){if(Y.has(a)){var b=Y.get(a),c=Y;c.le[a]=void 0;c.Ae.push(a);0<b.readyState&&4>b.readyState&&b.abort()}},l:()=>devicePixelRatio,f:(a,b,c)=>{a=O(a);if(!a)return-4;a=rc(a);w[b>>3]=a.width;w[c>>3]=a.height;return 0},V:(a,b)=>{if(0>a||a>=M.Be.length)return-5;if(!M.Be[a])return-7;uc(b,M.Be[a]);return 0},Z:()=>performance.now(),Ka:()=>M.Be.length,sa:(a,b)=>{q[a>>2]=screen.width;q[b>>2]=screen.height},Pd:a=>B.activeTexture(a),Nd:vc,ja:(a,b)=>{B.pe.beginQueryEXT(a,ob[b])},Md:(a,b,
c)=>{B.bindAttribLocation(F[a],b,c?x(m,c):"")},Ld:wc,Kd:(a,b)=>{B.bindFramebuffer(a,kb[b])},Jd:(a,b)=>{B.bindRenderbuffer(a,lb[b])},Id:(a,b)=>{B.bindTexture(a,mb[b])},Xd:a=>{B.bindVertexArray(nb[a])},Hd:(a,b,c,d)=>B.blendColor(a,b,c,d),Gd:xc,Fd:(a,b)=>B.blendEquationSeparate(a,b),Ed:yc,Dd:(a,b,c,d)=>B.blendFuncSeparate(a,b,c,d),Cd:zc,Bd:(a,b,c,d)=>{B.bufferSubData(a,b,m.subarray(d,d+c))},Ad:a=>B.checkFramebufferStatus(a),zd:Ac,yd:Bc,xd:a=>B.clearDepth(a),wd:a=>B.clearStencil(a),bb:(a,b)=>{B.nf.clipControlEXT(a,
b)},vd:(a,b,c,d)=>{B.colorMask(!!a,!!b,!!c,!!d)},ud:Cc,td:(a,b,c,d,e,g,f,l)=>{B.compressedTexImage2D(a,b,c,d,e,g,m.subarray(l,l+f))},sd:(a,b,c,d,e,g,f,l,n)=>{B.compressedTexSubImage2D(a,b,c,d,e,g,f,m.subarray(n,n+l))},rd:(a,b,c,d,e,g,f,l)=>B.copyTexImage2D(a,b,c,d,e,g,f,l),qd:(a,b,c,d,e,g,f,l)=>B.copyTexSubImage2D(a,b,c,d,e,g,f,l),pd:Dc,od:Ec,nd:a=>B.cullFace(a),md:(a,b)=>{for(var c=0;c<a;c++){var d=q[b+4*c>>2],e=jb[d];e&&(B.deleteBuffer(e),e.name=0,jb[d]=null)}},ld:(a,b)=>{for(var c=0;c<a;++c){var d=
q[b+4*c>>2],e=kb[d];e&&(B.deleteFramebuffer(e),e.name=0,kb[d]=null)}},kd:a=>{if(a){var b=F[a];b?(B.deleteProgram(b),b.name=0,F[a]=null):J||=1281}},la:(a,b)=>{for(var c=0;c<a;c++){var d=q[b+4*c>>2],e=ob[d];e&&(B.pe.deleteQueryEXT(e),ob[d]=null)}},id:(a,b)=>{for(var c=0;c<a;c++){var d=q[b+4*c>>2],e=lb[d];e&&(B.deleteRenderbuffer(e),e.name=0,lb[d]=null)}},hd:a=>{if(a){var b=H[a];b?(B.deleteShader(b),H[a]=null):J||=1281}},gd:(a,b)=>{for(var c=0;c<a;c++){var d=q[b+4*c>>2],e=mb[d];e&&(B.deleteTexture(e),
e.name=0,mb[d]=null)}},Wd:(a,b)=>{for(var c=0;c<a;c++){var d=q[b+4*c>>2];B.deleteVertexArray(nb[d]);nb[d]=null}},fd:a=>B.depthFunc(a),ed:Fc,dd:(a,b)=>B.depthRange(a,b),cd:(a,b)=>{B.detachShader(F[a],H[b])},bd:Gc,ad:a=>{B.disableVertexAttribArray(a)},$c:(a,b,c)=>{B.drawArrays(a,b,c)},Sd:(a,b,c,d)=>{B.drawArraysInstanced(a,b,c,d)},Td:(a,b)=>{for(var c=Hc[a],d=0;d<a;d++)c[d]=q[b+4*d>>2];B.drawBuffers(c)},Zc:Ic,Rd:(a,b,c,d,e)=>{B.drawElementsInstanced(a,b,c,d,e)},Yc:Jc,Xc:Kc,ia:a=>{B.pe.endQueryEXT(a)},
Wc:()=>B.finish(),Vc:()=>B.flush(),Uc:(a,b,c,d)=>{B.framebufferRenderbuffer(a,b,c,lb[d])},Tc:(a,b,c,d,e)=>{B.framebufferTexture2D(a,b,c,mb[d],e)},Sc:a=>B.frontFace(a),Rc:Lc,Pc:(a,b)=>{tb(a,b,"createFramebuffer",kb)},ma:(a,b)=>{for(var c=0;c<a;c++){var d=B.pe.createQueryEXT();if(!d){for(J||=1282;c<a;)q[b+4*c++>>2]=0;break}var e=sb(ob);d.name=e;ob[e]=d;q[b+4*c>>2]=e}},Oc:(a,b)=>{tb(a,b,"createRenderbuffer",lb)},Nc:(a,b)=>{tb(a,b,"createTexture",mb)},Vd:(a,b)=>{tb(a,b,"createVertexArray",nb)},Qc:a=>
B.generateMipmap(a),Mc:(a,b,c,d,e,g,f)=>Mc("getActiveAttrib",a,b,c,d,e,g,f),Lc:(a,b,c,d,e,g,f)=>Mc("getActiveUniform",a,b,c,d,e,g,f),Kc:(a,b,c,d)=>{a=B.getAttachedShaders(F[a]);var e=a.length;e>b&&(e=b);q[c>>2]=e;for(b=0;b<e;++b)q[d+4*b>>2]=H.indexOf(a[b])},Jc:Nc,Ic:(a,b)=>Oc(a,b,4),Hc:(a,b,c)=>{c?q[c>>2]=B.getBufferParameter(a,b):J||=1281},Gc:()=>{var a=B.getError()||J;J=0;return a},Fc:(a,b)=>Oc(a,b,2),Ec:(a,b,c,d)=>{a=B.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||
a instanceof WebGLTexture)a=a.name|0;q[d>>2]=a},Dc:(a,b)=>Oc(a,b,0),Bc:(a,b,c,d)=>{a=B.getProgramInfoLog(F[a]);null===a&&(a="(unknown error)");b=0<b&&d?K(a,d,b):0;c&&(q[c>>2]=b)},Cc:(a,b,c)=>{if(c)if(a>=ib)J||=1281;else if(a=F[a],35716==b)a=B.getProgramInfoLog(a),null===a&&(a="(unknown error)"),q[c>>2]=a.length+1;else if(35719==b){if(!a.Ee){var d=B.getProgramParameter(a,35718);for(b=0;b<d;++b)a.Ee=Math.max(a.Ee,B.getActiveUniform(a,b).name.length+1)}q[c>>2]=a.Ee}else if(35722==b){if(!a.Ce)for(d=B.getProgramParameter(a,
35721),b=0;b<d;++b)a.Ce=Math.max(a.Ce,B.getActiveAttrib(a,b).name.length+1);q[c>>2]=a.Ce}else if(35381==b){if(!a.De)for(d=B.getProgramParameter(a,35382),b=0;b<d;++b)a.De=Math.max(a.De,B.getActiveUniformBlockName(a,b).length+1);q[c>>2]=a.De}else q[c>>2]=B.getProgramParameter(a,b);else J||=1281},da:Pc,fa:Qc,Yd:Pc,ea:Qc,ga:(a,b,c)=>{c?q[c>>2]=B.pe.getQueryEXT(a,b):J||=1281},Ac:(a,b,c)=>{c?q[c>>2]=B.getRenderbufferParameter(a,b):J||=1281},yc:(a,b,c,d)=>{a=B.getShaderInfoLog(H[a]);null===a&&(a="(unknown error)");
b=0<b&&d?K(a,d,b):0;c&&(q[c>>2]=b)},xc:(a,b,c,d)=>{a=B.getShaderPrecisionFormat(a,b);q[c>>2]=a.rangeMin;q[c+4>>2]=a.rangeMax;q[d>>2]=a.precision},wc:(a,b,c,d)=>{if(a=B.getShaderSource(H[a]))b=0<b&&d?K(a,d,b):0,c&&(q[c>>2]=b)},zc:(a,b,c)=>{c?35716==b?(a=B.getShaderInfoLog(H[a]),null===a&&(a="(unknown error)"),q[c>>2]=a?a.length+1:0):35720==b?(a=B.getShaderSource(H[a]),q[c>>2]=a?a.length+1:0):q[c>>2]=B.getShaderParameter(H[a],b):J||=1281},vc:a=>{var b=pb[a];if(!b){switch(a){case 7939:b=Bb(Rc().join(" "));
break;case 7936:case 7937:case 37445:case 37446:(b=B.getParameter(a))||(J||=1280);b=b?Bb(b):0;break;case 7938:b=Bb(`OpenGL ES 2.0 (${B.getParameter(7938)})`);break;case 35724:b=B.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=Bb(b);break;default:J||=1280}pb[a]=b}return b},uc:(a,b,c)=>{c?u[c>>2]=B.getTexParameter(a,b):J||=1281},tc:(a,b,c)=>{c?q[c>>2]=B.getTexParameter(a,b):J||=1281},qc:Uc,
sc:(a,b,c)=>{Vc(a,b,c,2)},rc:(a,b,c)=>{Vc(a,b,c,0)},nc:(a,b,c)=>{c?q[c>>2]=B.getVertexAttribOffset(a,b):J||=1281},pc:(a,b,c)=>{Wc(a,b,c,2)},oc:(a,b,c)=>{Wc(a,b,c,5)},mc:(a,b)=>B.hint(a,b),kc:a=>(a=jb[a])?B.isBuffer(a):0,jc:a=>B.isEnabled(a),ic:a=>(a=kb[a])?B.isFramebuffer(a):0,hc:a=>(a=F[a])?B.isProgram(a):0,ka:a=>(a=ob[a])?B.pe.isQueryEXT(a):0,gc:a=>(a=lb[a])?B.isRenderbuffer(a):0,fc:a=>(a=H[a])?B.isShader(a):0,ec:a=>(a=mb[a])?B.isTexture(a):0,Ud:a=>(a=nb[a])?B.isVertexArray(a):0,dc:a=>B.lineWidth(a),
cc:Xc,bc:(a,b)=>{3317==a?qb=b:3314==a&&(rb=b);B.pixelStorei(a,b)},ab:(a,b)=>{B.yf.polygonModeWEBGL(a,b)},ac:(a,b)=>B.polygonOffset(a,b),cb:(a,b,c)=>{B.pf.polygonOffsetClampEXT(a,b,c)},ha:(a,b)=>{B.pe.queryCounterEXT(ob[a],b)},$b:(a,b,c,d,e,g,f)=>{(f=Yc(g,e,c,d,f))?B.readPixels(a,b,c,d,e,g,f):J||=1280},_b:()=>{},Zb:(a,b,c,d)=>B.renderbufferStorage(a,b,c,d),Yb:(a,b)=>{B.sampleCoverage(a,!!b)},Xb:(a,b,c,d)=>B.scissor(a,b,c,d),Wb:()=>{J||=1280},Vb:Zc,Ub:(a,b,c)=>B.stencilFunc(a,b,c),Tb:(a,b,c,d)=>B.stencilFuncSeparate(a,
b,c,d),Sb:a=>B.stencilMask(a),Rb:(a,b)=>B.stencilMaskSeparate(a,b),Qb:(a,b,c)=>B.stencilOp(a,b,c),Pb:(a,b,c,d)=>B.stencilOpSeparate(a,b,c,d),Ob:(a,b,c,d,e,g,f,l,n)=>{n=n?Yc(l,f,d,e,n):null;B.texImage2D(a,b,c,d,e,g,f,l,n)},Nb:(a,b,c)=>B.texParameterf(a,b,c),Mb:(a,b,c)=>{B.texParameterf(a,b,u[c>>2])},Lb:(a,b,c)=>B.texParameteri(a,b,c),Kb:(a,b,c)=>{B.texParameteri(a,b,q[c>>2])},Jb:(a,b,c,d,e,g,f,l,n)=>{n=n?Yc(l,f,e,g,n):null;B.texSubImage2D(a,b,c,d,e,g,f,l,n)},Ib:$c,Hb:(a,b,c)=>{if(288>=b)for(var d=
ad[b],e=0;e<b;++e)d[e]=u[c+4*e>>2];else d=u.subarray(c>>2,c+4*b>>2);B.uniform1fv(W(a),d)},Gb:(a,b)=>{B.uniform1i(W(a),b)},Fb:(a,b,c)=>{if(288>=b)for(var d=bd[b],e=0;e<b;++e)d[e]=q[c+4*e>>2];else d=q.subarray(c>>2,c+4*b>>2);B.uniform1iv(W(a),d)},Eb:(a,b,c)=>{B.uniform2f(W(a),b,c)},Db:(a,b,c)=>{if(144>=b){b*=2;for(var d=ad[b],e=0;e<b;e+=2)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2]}else d=u.subarray(c>>2,c+8*b>>2);B.uniform2fv(W(a),d)},Cb:(a,b,c)=>{B.uniform2i(W(a),b,c)},Bb:(a,b,c)=>{if(144>=b){b*=2;for(var d=
bd[b],e=0;e<b;e+=2)d[e]=q[c+4*e>>2],d[e+1]=q[c+(4*e+4)>>2]}else d=q.subarray(c>>2,c+8*b>>2);B.uniform2iv(W(a),d)},Ab:cd,zb:(a,b,c)=>{if(96>=b){b*=3;for(var d=ad[b],e=0;e<b;e+=3)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2]}else d=u.subarray(c>>2,c+12*b>>2);B.uniform3fv(W(a),d)},yb:(a,b,c,d)=>{B.uniform3i(W(a),b,c,d)},xb:(a,b,c)=>{if(96>=b){b*=3;for(var d=bd[b],e=0;e<b;e+=3)d[e]=q[c+4*e>>2],d[e+1]=q[c+(4*e+4)>>2],d[e+2]=q[c+(4*e+8)>>2]}else d=q.subarray(c>>2,c+12*b>>2);B.uniform3iv(W(a),
d)},wb:(a,b,c,d,e)=>{B.uniform4f(W(a),b,c,d,e)},vb:(a,b,c)=>{if(72>=b){var d=ad[4*b],e=u;c>>=2;b*=4;for(var g=0;g<b;g+=4){var f=c+g;d[g]=e[f];d[g+1]=e[f+1];d[g+2]=e[f+2];d[g+3]=e[f+3]}}else d=u.subarray(c>>2,c+16*b>>2);B.uniform4fv(W(a),d)},ub:(a,b,c,d,e)=>{B.uniform4i(W(a),b,c,d,e)},tb:(a,b,c)=>{if(72>=b){b*=4;for(var d=bd[b],e=0;e<b;e+=4)d[e]=q[c+4*e>>2],d[e+1]=q[c+(4*e+4)>>2],d[e+2]=q[c+(4*e+8)>>2],d[e+3]=q[c+(4*e+12)>>2]}else d=q.subarray(c>>2,c+16*b>>2);B.uniform4iv(W(a),d)},sb:(a,b,c,d)=>{if(72>=
b){b*=4;for(var e=ad[b],g=0;g<b;g+=4)e[g]=u[d+4*g>>2],e[g+1]=u[d+(4*g+4)>>2],e[g+2]=u[d+(4*g+8)>>2],e[g+3]=u[d+(4*g+12)>>2]}else e=u.subarray(d>>2,d+16*b>>2);B.uniformMatrix2fv(W(a),!!c,e)},rb:(a,b,c,d)=>{if(32>=b){b*=9;for(var e=ad[b],g=0;g<b;g+=9)e[g]=u[d+4*g>>2],e[g+1]=u[d+(4*g+4)>>2],e[g+2]=u[d+(4*g+8)>>2],e[g+3]=u[d+(4*g+12)>>2],e[g+4]=u[d+(4*g+16)>>2],e[g+5]=u[d+(4*g+20)>>2],e[g+6]=u[d+(4*g+24)>>2],e[g+7]=u[d+(4*g+28)>>2],e[g+8]=u[d+(4*g+32)>>2]}else e=u.subarray(d>>2,d+36*b>>2);B.uniformMatrix3fv(W(a),
!!c,e)},qb:dd,pb:ed,ob:a=>{B.validateProgram(F[a])},nb:(a,b)=>B.vertexAttrib1f(a,b),mb:(a,b)=>{B.vertexAttrib1f(a,u[b>>2])},lb:(a,b,c)=>B.vertexAttrib2f(a,b,c),kb:(a,b)=>{B.vertexAttrib2f(a,u[b>>2],u[b+4>>2])},jb:(a,b,c,d)=>B.vertexAttrib3f(a,b,c,d),ib:(a,b)=>{B.vertexAttrib3f(a,u[b>>2],u[b+4>>2],u[b+8>>2])},hb:(a,b,c,d,e)=>B.vertexAttrib4f(a,b,c,d,e),gb:(a,b)=>{B.vertexAttrib4f(a,u[b>>2],u[b+4>>2],u[b+8>>2],u[b+12>>2])},Qd:(a,b)=>{B.vertexAttribDivisor(a,b)},fb:fd,db:gd,q:()=>0,Oa:()=>!0,pa:(a,b,
c)=>hd(a,{Pe:q[c>>2],Ge:q[c+4>>2],qf:q[c+8>>2],lf:b,xe:q[c+12>>2],Xe:q[c+16>>2]}),Q:(a,b)=>{a=O(a);return a?a.requestPointerLock?bc()?tc(a):b?($b(tc,2,[a]),1):-2:-1:-4},Ta:()=>{ua("OOM")},X:a=>{eval(a?x(m,a):"")},W:jd,y:(a,b,c)=>"undefined"==typeof onbeforeunload?-1:1!==c?-5:kd(a,b),K:(a,b,c,d)=>ld(a,b,c,d,12,"blur"),k:kc,o:(a,b,c)=>{a=O(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},L:(a,b,c,d)=>ld(a,b,c,d,13,"focus"),A:(a,b,c,d)=>{if(!M.fullscreenEnabled())return-1;a=O(a);
if(!a)return-4;md(a,b,c,d,"webkitfullscreenchange");return md(a,b,c,d,"fullscreenchange")},U:(a,b,c)=>jd()?-1:nd(a,b,c,26,"gamepadconnected"),T:(a,b,c)=>jd()?-1:nd(a,b,c,27,"gamepaddisconnected"),D:(a,b,c,d)=>od(a,b,c,d,2,"keydown"),B:(a,b,c,d)=>od(a,b,c,d,1,"keypress"),C:(a,b,c,d)=>od(a,b,c,d,3,"keyup"),Pa:(a,b,c)=>{a=P(a);Tb(a,b,c)},t:(a,b,c,d)=>qd(a,b,c,d,5,"mousedown"),O:(a,b,c,d)=>qd(a,b,c,d,33,"mouseenter"),N:(a,b,c,d)=>qd(a,b,c,d,34,"mouseleave"),u:(a,b,c,d)=>qd(a,b,c,d,8,"mousemove"),s:(a,
b,c,d)=>qd(a,b,c,d,6,"mouseup"),E:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.le||document.body.sf||document.body.Ae))return-1;a=O(a);if(!a)return-4;rd(a,b,c,d,"mozpointerlockchange");rd(a,b,c,d,"webkitpointerlockchange");rd(a,b,c,d,"mspointerlockchange");return rd(a,b,c,d,"pointerlockchange")},v:(a,b,c,d)=>sd(a,b,c,d),G:(a,b,c,d)=>td(a,b,c,d,25,"touchcancel"),I:(a,b,c,d)=>td(a,b,c,d,23,"touchend"),H:(a,b,c,d)=>td(a,b,c,d,24,"touchmove"),J:(a,b,c,d)=>
td(a,b,c,d,22,"touchstart"),z:(a,b,c)=>ud(a,b,c),M:(a,b,c,d)=>(a=O(a))?"undefined"!=typeof a.onwheel?vd(a,b,c,d):-1:-4,qa:a=>document.title=a?x(m,a):"",p:()=>{throw"Please compile your program with async support in order to use asynchronous operations like emscripten_sleep";},Na:function(a,b,c,d,e){function g(A){if(G)A();else if(!ma)try{A(),Ma()}catch(Hb){Ja(Hb)}}var f=a+108,l=r[f+36>>2],n=r[f+40>>2],v=r[f+44>>2],E=r[f+48>>2],C=r[f+52>>2],G=!!(C&64),T=A=>{g(()=>{l?P(l)(A):b?.(A)})},ba=A=>{g(()=>{v?
P(v)(A):d?.(A)})},U=A=>{g(()=>{n?P(n)(A):c?.(A)})},Q=A=>{g(()=>{E?P(E)(A):e?.(A)})},X=A=>{zd(A,T,U,ba,Q)},ka=(A,Hb)=>{Bd(A,Hb.response,Fa=>{g(()=>{l?P(l)(Fa):b?.(Fa)})},Fa=>{g(()=>{l?P(l)(Fa):b?.(Fa)})})},t=A=>{zd(A,ka,U,ba,Q)},V=Ia(f+0),D=!!(C&16),R=!!(C&4);C=!!(C&32);if("EM_IDB_STORE"===V)X=r[f+84>>2],Bd(a,m.slice(X,X+r[f+88>>2]),T,U);else if("EM_IDB_DELETE"===V)Dd(a,T,U);else if(D){if(C)return 0;zd(a,R?ka:T,U,ba,Q)}else Cd(a,T,C?U:R?t:X);return a},Wa:(a,b)=>{var c=0,d=0,e;for(e of Gd()){var g=
b+c;r[a+d>>2]=g;c+=K(e,g,Infinity)+1;d+=4}return 0},Xa:(a,b)=>{var c=Gd();r[a>>2]=c.length;a=0;for(var d of c)a+=Ab(d)+1;r[b>>2]=a;return 0},_:()=>52,Za:()=>52,Va:function(){return 70},$:(a,b,c,d)=>{for(var e=0,g=0;g<c;g++){var f=r[b>>2],l=r[b+4>>2];b+=8;for(var n=0;n<l;n++){var v=a,E=m[f+n],C=Hd[v];0===E||10===E?((1===v?ha:ia)(x(C)),C.length=0):C.push(E)}e+=l}r[d>>2]=e;return 0},Qa:function(){var a=prompt("The default link below will have its SSL certificate expire on the 20th of November 2025, to continue using FishyHotel you will need to create your own server using the code at this URL:\n\nhttps://github.com/fishyhotel/FishyHotel/blob/main/server.php\n\nBy uploading it to a web host with SSL, and then providing a link to the URL where it is hosted into this input prompt.\n\nYou will still need to make some minor changes to that file to get it working, but it's nothing most people can't handle.",
"https://server.fishyhotel.com:1337/fishy.php"),b=Ab(a)+1,c=L(b);K(a,c,b);return c},ca:vc,a:wc,Sa:xc,Ya:yc,b:zc,lc:Ac,Ra:Bc,F:Cc,na:Dc,R:Ec,g:Fc,n:Gc,Ia:Ic,m:Jc,r:Kc,c:Lc,x:Nc,h:Uc,Od:Xc,P:Zc,i:$c,eb:cd,d:dd,jd:ed,w:fd,_c:gd,Y:function(){var a=new Uint32Array(1);crypto.getRandomValues(a);return a[0]}},Z;
(async function(){function a(c){Z=c.exports;la=Z.Zd;c=la.buffer;k=new Int8Array(c);p=new Int16Array(c);m=new Uint8Array(c);oa=new Uint16Array(c);q=new Int32Array(c);r=new Uint32Array(c);u=new Float32Array(c);w=new Float64Array(c);pa=new BigInt64Array(c);new BigUint64Array(c);oc=Z.ae;ta();return Z}sa();var b={a:Pd};if(h.instantiateWasm)return new Promise(c=>{h.instantiateWasm(b,(d,e)=>{c(a(d,e))})});va??=h.locateFile?h.locateFile("index.wasm",ea):ea+"index.wasm";return a((await ya(b)).instance)})();
var Qd=h._main=(a,b)=>(Qd=h._main=Z.$d)(a,b),L=a=>(L=Z.be)(a),Ad=a=>(Ad=Z.ce)(a),ic=a=>(ic=Z.de)(a),fc=a=>(fc=Z.ee)(a),hc=()=>(hc=Z.fe)();function Rd(a=[]){var b=Qd;a.unshift(ca);var c=a.length,d=fc(4*(c+1)),e=d;a.forEach(f=>{r[e>>2]=gc(f);e+=4});r[e>>2]=0;try{var g=b(c,d);La(g)}catch(f){Ja(f)}}
function Sd(a=aa){function b(){h.calledRun=!0;if(!ma){Z._d();h.onRuntimeInitialized?.();h.noInitialRun||Rd(a);if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var c=h.postRun.shift();Ba.push(c)}Aa(Ba)}}if(0<qa)ra=Sd;else{if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Da();Aa(Ca);0<qa?ra=Sd:h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),1);b()},1)):b()}}
if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.shift()();Sd();
