var h;h||=typeof Module != 'undefined' ? Module : {};var aa=Object.assign({},h),ba=[],ca="./this.program",k="",da;"undefined"!=typeof document&&document.currentScript&&(k=document.currentScript.src);k=k.startsWith("blob:")?"":k.slice(0,k.replace(/[?#].*/,"").lastIndexOf("/")+1);da=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};var ea=h.print||console.log.bind(console),l=h.printErr||console.error.bind(console);
Object.assign(h,aa);aa=null;h.arguments&&(ba=h.arguments);h.thisProgram&&(ca=h.thisProgram);var fa=h.wasmBinary,ha,p=!1,ia,q,r,ja,ka,u,v,w,la,x,y=0,ma=null;function na(a){h.onAbort?.(a);a="Aborted("+a+")";l(a);p=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var oa;async function pa(a){if(!fa)try{var b=await da(a);return new Uint8Array(b)}catch{}if(a==oa&&fa)a=new Uint8Array(fa);else throw"both async and sync fetching of the wasm failed";return a}
async function qa(a,b){try{var c=await pa(a);return await WebAssembly.instantiate(c,b)}catch(d){l(`failed to asynchronously prepare wasm: ${d}`),na(d)}}async function ra(a){var b=oa;if(!fa&&"function"==typeof WebAssembly.instantiateStreaming)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){l(`wasm streaming compile failed: ${d}`),l("falling back to ArrayBuffer instantiation")}return qa(b,a)}
var va={26746565:()=>"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?!0:!1,26746712:()=>"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?!0:!1,26746946:a=>{"undefined"===typeof h.SDL2&&(h.SDL2={});var b=h.SDL2;a?b.capture={}:b.audio={};b.ge||("undefined"!==typeof AudioContext?b.ge=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.ge=new webkitAudioContext),
b.ge&&"undefined"===typeof navigator.userActivation&&sa(b.ge));return void 0===b.ge?-1:0},26747498:()=>h.SDL2.ge.sampleRate,26747566:(a,b,c,d)=>{function e(){}function f(m){void 0!==g.capture.ne&&(clearInterval(g.capture.ne),g.capture.ne=void 0,g.capture.se=void 0);g.capture.Me=g.ge.createMediaStreamSource(m);g.capture.me=g.ge.createScriptProcessor(b,a,1);g.capture.me.onaudioprocess=function(n){void 0!==g&&void 0!==g.capture&&(n.outputBuffer.getChannelData(0).fill(0),g.capture.Ge=n.inputBuffer,ta(c,
[d]))};g.capture.Me.connect(g.capture.me);g.capture.me.connect(g.ge.destination);g.capture.stream=m}var g=h.SDL2;g.capture.se=g.ge.createBuffer(a,b,g.ge.sampleRate);g.capture.se.getChannelData(0).fill(0);g.capture.ne=setInterval(function(){g.capture.Ge=g.capture.se;ta(c,[d])},b/g.ge.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(f).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,
video:!1},f,e)},26749259:(a,b,c,d)=>{var e=h.SDL2;e.audio.me=e.ge.createScriptProcessor(b,0,a);e.audio.me.onaudioprocess=function(f){void 0!==e&&void 0!==e.audio&&(void 0!==e.audio.ne&&(clearInterval(e.audio.ne),e.audio.ne=void 0,e.audio.se=void 0),e.audio.ze=f.outputBuffer,ta(c,[d]))};e.audio.me.connect(e.ge.destination);"suspended"===e.ge.state&&(e.audio.se=e.ge.createBuffer(a,b,e.ge.sampleRate),e.audio.se.getChannelData(0).fill(0),e.audio.ne=setInterval(function(){"undefined"!==typeof navigator.userActivation&&
navigator.userActivation.hasBeenActive&&e.ge.resume();e.audio.ze=e.audio.se;ta(c,[d]);e.audio.ze=void 0},b/e.ge.sampleRate*1E3))},26750434:(a,b)=>{for(var c=h.SDL2,d=c.capture.Ge.numberOfChannels,e=0;e<d;++e){var f=c.capture.Ge.getChannelData(e);if(f.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";if(1==d)for(var g=0;g<b;++g)ua(a+4*g,f[g]);else for(g=0;g<b;++g)ua(a+4*(g*d+e),f[g])}},26751039:(a,b)=>{var c=h.SDL2;a>>>=2;for(var d=
c.audio.ze.numberOfChannels,e=0;e<d;++e){var f=c.audio.ze.getChannelData(e);if(f.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";for(var g=0;g<b;++g)f[g]=w[a+(g*d+e)]}},26751528:a=>{var b=h.SDL2;if(a){void 0!==b.capture.ne&&clearInterval(b.capture.ne);if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c])}void 0!==b.capture.me&&(b.capture.me.onaudioprocess=
function(){},b.capture.me.disconnect());void 0!==b.capture.Me&&b.capture.Me.disconnect();b.capture=void 0}else void 0!=b.audio.me&&b.audio.me.disconnect(),void 0!==b.audio.ne&&clearInterval(b.audio.ne),b.audio=void 0;void 0!==b.ge&&void 0===b.audio&&void 0===b.capture&&(b.ge.close(),b.ge=void 0)},26752534:(a,b,c)=>{h.SDL2||(h.SDL2={});var d=h.SDL2;d.ff!==h.canvas&&(d.ye=h.createContext(h.canvas,!1,!0),d.ff=h.canvas);if(d.w!==a||d.h!==b||d.tf!==d.ye)d.image=d.ye.createImageData(a,b),d.w=a,d.h=b,d.tf=
d.ye;a=d.image.data;b=c/4;var e=0;if("undefined"!==typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var f=u[b];a[e]=f&255;a[e+1]=f>>8&255;a[e+2]=f>>16&255;a[e+3]=255;b++;e+=4}else if(d.kf!==a&&(d.jf=new Int32Array(a.buffer),d.lf=new Uint8Array(a.buffer),d.kf=a),a=d.jf,c=a.length,a.set(u.subarray(b,b+c)),a=d.lf,b=3,e=b+4*c,0==c%8)for(;b<e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|
0;else for(;b<e;)a[b]=255,b=b+4|0;d.ye.putImageData(d.image,0,0)},26754002:(a,b,c,d,e)=>{var f=document.createElement("canvas");f.width=a;f.height=b;var g=f.getContext("2d");a=g.createImageData(a,b);b=a.data;e/=4;var m=0,n;if("undefined"!==typeof CanvasPixelArray&&b instanceof CanvasPixelArray)for(n=b.length;m<n;){var t=u[e];b[m]=t&255;b[m+1]=t>>8&255;b[m+2]=t>>16&255;b[m+3]=t>>24&255;e++;m+=4}else b=new Int32Array(b.buffer),n=b.length,b.set(u.subarray(e,e+n));g.putImageData(a,0,0);c=0===c&&0===d?
"url("+f.toDataURL()+"), auto":"url("+f.toDataURL()+") "+c+" "+d+", auto";d=z(c.length+1);A(c,d,c.length+1);return d},26754990:a=>{h.canvas&&(h.canvas.style.cursor=a?C(r,a):"")},26755073:()=>{h.canvas&&(h.canvas.style.cursor="none")},26755142:()=>window.innerWidth,26755172:()=>window.innerHeight};class wa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var xa=a=>{for(;0<a.length;)a.shift()(h)},ya=[],za=[],Aa=()=>{var a=h.preRun.shift();za.unshift(a)},Ba=h.noExitRuntime||!0;function ua(a,b){var c="float";c.endsWith("*")&&(c="*");switch(c){case "i1":q[a]=b;break;case "i8":q[a]=b;break;case "i16":ja[a>>1]=b;break;case "i32":u[a>>2]=b;break;case "i64":la[a>>3]=BigInt(b);break;case "float":w[a>>2]=b;break;case "double":x[a>>3]=b;break;case "*":v[a>>2]=b;break;default:na(`invalid type for setValue: ${c}`)}}
var Ca="undefined"!=typeof TextDecoder?new TextDecoder:void 0,C=(a,b=0,c=NaN)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ca)return Ca.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
Da=[0,31,60,91,121,152,182,213,244,274,305,335],Ea=[0,31,59,90,120,151,181,212,243,273,304,334],A=(a,b,c)=>{var d=r;if(!(0<c))return 0;var e=b;c=b+c-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var m=a.charCodeAt(++f);g=65536+((g&1023)<<10)|m&1023}if(127>=g){if(b>=c)break;d[b++]=g}else{if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6}else{if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63}d[b++]=128|g>>6&63}d[b++]=128|g&
63}}d[b]=0;return b-e},Fa=a=>{if(!(a instanceof wa||"unwind"==a))throw a;},Ga=a=>{ia=a;Ba||(h.onExit?.(a),p=!0);throw new wa(a);},Ha=a=>{ia=a;Ga(a)},Ia=()=>{if(!Ba)try{var a=ia;ia=a;Ga(a)}catch(b){Fa(b)}},Ja=!1,Ka=!1,La=[];
function Ma(){function a(){var c=h.canvas;Ka=document.pointerLockElement===c||document.mozPointerLockElement===c||document.webkitPointerLockElement===c||document.msPointerLockElement===c}if(!Na){Na=!0;var b=h.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),b.exitPointerLock=
b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",c=>{!Ka&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}var Oa=!1,Pa=void 0,D=void 0;
function Qa(){if(!Ja)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var Ra=[];function Sa(){var a=h.canvas;Ra.forEach(b=>b(a.width,a.height))}
function Ta(a,b,c){b&&c?(a.zf=b,a.sf=c):(b=a.zf,c=a.sf);var d=b,e=c;0<h.forcedAspectRatio&&(d/e<h.forcedAspectRatio?d=Math.round(e*h.forcedAspectRatio):e=Math.round(d/h.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*f)}D?(a.width!=d&&(a.width=
d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var Na,E=12288,Ua=!1,Va=0,Wa=0,Xa=0,F={alpha:!1,depth:!1,stencil:!1,antialias:!1},Ya={},Za,G,$a=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,f)=>b.drawArraysInstancedANGLE(c,d,e,f),a.drawElementsInstanced=(c,d,e,f,g)=>b.drawElementsInstancedANGLE(c,d,e,f,g))},ab=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),
a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},bb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},cb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},db=1,eb=[],H=[],fb=[],J=[],K=[],L=[],gb=[],M=[],N=[],hb={},ib=4,jb=0,kb=a=>{for(var b=db++,c=a.length;c<b;c++)a[c]=null;return b},lb=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=G[c](),g=f&&kb(d);f?(f.name=g,d[g]=f):O||=1282;u[b+4*e>>2]=g}},nb=(a,b)=>{a.ue||(a.ue=a.getContext,a.getContext=function(d,e){e=a.ue(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?mb(c,b):0},mb=(a,b)=>{var c=
kb(M),d={handle:c,attributes:b,version:b.af,pe:a};a.canvas&&(a.canvas.te=d);M[c]=d;("undefined"==typeof b.nf||b.nf)&&ob(d);return c},qb=a=>{pb=M[a];h.ctx=G=pb?.pe},ob=a=>{a||=pb;if(!a.uf){a.uf=!0;var b=a.pe;b.Lf=b.getExtension("WEBGL_multi_draw");b.qf=b.getExtension("EXT_polygon_offset_clamp");b.pf=b.getExtension("EXT_clip_control");b.yf=b.getExtension("WEBGL_polygon_mode");$a(b);ab(b);bb(b);b.oe=b.getExtension("EXT_disjoint_timer_query");cb(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||
b.getExtension(c)})}},rb={},O,pb,sb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},P=a=>{var b=sb(a)+1,c=z(b);c&&A(a,c,b);return c},Ib=(a,b,c,d,e)=>{function f(){return g<tb?(Ia(),!1):!0}ub=a;vb=d;var g=tb;wb=!1;xb=function(){if(!p)if(0<yb.length){var m=yb.shift();m.Hf(m.Af);if(zb){var n=zb,t=0==n%1?n-1:Math.floor(n);zb=m.Df?t:(8*n+(t+.5))/9}h.setStatus&&(m=h.statusMessage||"Please wait...",n=zb??0,t=Ab.Gf??0,n?n<t?h.setStatus("{message} ({expected - remaining}/{expected})"):
h.setStatus(m):h.setStatus(""));f()&&setTimeout(xb,0)}else if(f())if(Bb=Bb+1|0,1==Cb&&1<Db&&0!=Bb%Db)Q();else{0==Cb&&(Eb=performance.now());a:if(!p){for(m of Fb)if(!1===m())break a;if(!p)try{a(),Ia()}catch(B){Fa(B)}for(n of Gb)n()}f()&&Q()}};e||(0<b?Hb(0,1E3/b):Hb(1,1),Q());if(c)throw"unwind";},wb=!1,Q=null,tb=0,ub=null,vb=0,Cb=0,Db=0,Bb=0,yb=[],Fb=[],Gb=[],Jb=0;
function Kb(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Jb)Jb=b+1E3/60;else for(;b+2>=Jb;)Jb+=1E3/60;setTimeout(a,Math.max(Jb-b,0))}}
var Ab={},xb,zb,Eb,Lb,Hb=(a,b)=>{Cb=a;Db=b;if(ub)if(wb||=!0,0==a)Q=function(){setTimeout(xb,Math.max(0,Eb+b-performance.now())|0)};else if(1==a)Q=function(){Kb(xb)};else if(2==a){if("undefined"==typeof Lb)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Lb=d=>{c.push(d);postMessage("setimmediate","*")}}else Lb=setImmediate;Q=function(){Lb(xb)}}},Mb=[],Nb=(a,b)=>{Mb.length=0;
for(var c;c=r[a++];){var d=105!=c;d&=112!=c;b+=d&&b%8?4:0;Mb.push(112==c?v[b>>2]:106==c?la[b>>3]:105==c?u[b>>2]:x[b>>3]);b+=d?8:4}return Mb};function Ob(a){var b=R.ke[a];b.target.removeEventListener(b.he,b.Xe,b.ie);R.ke.splice(a,1)}function Pb(a,b,c){function d(f,g){if(f.length!=g.length)return!1;for(var m in f)if(f[m]!=g[m])return!1;return!0}for(var e of R.qe)if(e.Pe==a&&d(e.Ve,c))return;R.qe.push({Pe:a,cf:b,Ve:c});R.qe.sort((f,g)=>f.cf<g.cf)}function Qb(a){R.qe=R.qe.filter(b=>b.Pe!=a)}
function Rb(){return navigator.userActivation?navigator.userActivation.isActive:R.Ke&&R.gf.we}function Sb(){if(Rb()){var a=R.qe;R.qe=[];for(var b of a)b.Pe(...b.Ve)}}function S(a){if(!a.target)return-4;if(a.je)a.Xe=function(c){++R.Ke;R.gf=a;Sb();a.le(c);Sb();--R.Ke},a.target.addEventListener(a.he,a.Xe,a.ie),R.ke.push(a);else for(var b=0;b<R.ke.length;++b)R.ke[b].target==a.target&&R.ke[b].he==a.he&&Ob(b--);return 0}
function Tb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var R={Bf:0,Je:0,Le:0,Ee:0,Ue:0,Re:0,He:0,Ff:0,Mf:0,Ef:0,Ie:0,Ne:0,Te:0,Qe:0,Jf(a,b,c){q.set(q.subarray(b,b+c),a)},Nf(){for(;R.ke.length;)Ob(R.ke.length-1);R.qe=[]},Ke:0,qe:[],ke:[],wf:(a,b)=>{for(var c=0;c<R.ke.length;++c)R.ke[c].target!=a||b&&b!=R.ke[c].he||Ob(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},Ub={},Vb=[0,document,window],T=a=>{a=2<a?a?C(r,a):"":a;return Vb[a]||document.querySelector(a)},Xb=a=>{var b=sb(a)+1,c=Wb(b);A(a,c,b);return c},
$b=a=>{var b=Yb(),c=Wb(8),d=c+4;a=Xb(a.id);if(a=T(a))u[c>>2]=a.width,u[d>>2]=a.height;c=[u[c>>2],u[d>>2]];Zb(b);return c},ac=(a,b,c)=>{a=T(a);if(!a)return-4;a.width=b;a.height=c;return 0},bc=(a,b,c)=>{if(a.Cf){var d=Yb();a=Xb(a.id);ac(a,b,c);Zb(d)}else a.width=b,a.height=c},cc=[],dc,U=a=>{var b=cc[a];b||(a>=cc.length&&(cc.length=a+1),cc[a]=b=dc.get(a));return b},ec=a=>{function b(){document.fullscreenElement||document.webkitFullscreenElement||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",
b),bc(a,d,e),a.style.width=f,a.style.height=g,a.style.backgroundColor=m,n||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=n,a.style.paddingLeft=t,a.style.paddingRight=B,a.style.paddingTop=Z,a.style.paddingBottom=I,a.style.marginLeft=jd,a.style.marginRight=kd,a.style.marginTop=ld,a.style.marginBottom=md,document.body.style.margin=nd,document.documentElement.style.overflow=od,document.body.scroll=pd,a.style.re=qd,a.te&&a.te.pe.viewport(0,0,d,e),Ub.xe&&U(Ub.xe)(37,
0,Ub.We))}var c=$b(a),d=c[0],e=c[1],f=a.style.width,g=a.style.height,m=a.style.backgroundColor,n=document.body.style.backgroundColor,t=a.style.paddingLeft,B=a.style.paddingRight,Z=a.style.paddingTop,I=a.style.paddingBottom,jd=a.style.marginLeft,kd=a.style.marginRight,ld=a.style.marginTop,md=a.style.marginBottom,nd=document.body.style.margin,od=document.documentElement.style.overflow,pd=document.body.scroll,qd=a.style.re;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",
b)},fc=(a,b,c)=>{a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"},gc=a=>0>Vb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},hc=(a,b)=>{if(0!=b.Oe||0!=b.Fe){ec(a);var c=b.xf?innerWidth:screen.width,d=b.xf?innerHeight:screen.height,e=gc(a),f=e.width;e=e.height;var g=$b(a),m=g[0];g=g[1];3==b.Oe?(fc(a,(d-e)/2,(c-f)/2),c=f,d=e):2==b.Oe&&(c*g<m*d?(f=g*c/m,fc(a,(d-f)/2,0),d=f):(f=m*d/g,fc(a,0,(c-f)/2),c=f));var n;(n=a.style).backgroundColor||(n.backgroundColor=
"black");let t;(t=document.body.style).backgroundColor||(t.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.rf&&(a.style.re="optimizeSpeed",a.style.re="-moz-crisp-edges",a.style.re="-o-crisp-edges",a.style.re="-webkit-optimize-contrast",a.style.re="optimize-contrast",a.style.re="crisp-edges",a.style.re="pixelated");n=2==b.Fe?devicePixelRatio:1;0!=b.Fe&&(c=c*n|0,d=d*n|0,bc(a,c,d),a.te&&a.te.pe.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);
else return R.fullscreenEnabled()?-3:-1;Ub=b;b.xe&&U(b.xe)(37,0,b.We);return 0},ic=a=>{if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?-3:-1;return 0},jc=(a,b)=>{x[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)x[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)x[a+8*c+528>>3]="object"==typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)q[a+c+1040]="object"==typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];
q[a+1104]=b.connected;u[a+1108>>2]=b.index;u[a+8>>2]=b.axes.length;u[a+12>>2]=b.buttons.length;A(b.id,a+1112,64);A(b.mapping,a+1176,64)},kc=a=>{var b=document.pointerLockElement||document.ue||document.Ze||document.Ye;q[a]=!!b;var c=b?.id||"";A(Tb(b),a+1,128);A(c,a+129,128)},lc=(a,b)=>{G.attachShader(H[a],L[b])},mc=(a,b)=>{G.bindBuffer(a,eb[b])},nc=(a,b)=>G.blendFunc(a,b),oc=(a,b,c,d)=>{G.bufferData(a,c?r.subarray(c,c+b):b,d)},pc=a=>G.clear(a),qc=(a,b,c,d)=>G.clearColor(a,b,c,d),rc=a=>{G.compileShader(L[a])},
sc=()=>{var a=kb(H),b=G.createProgram();b.name=a;b.De=b.Be=b.Ce=0;b.Se=1;H[a]=b;return a},tc=a=>{var b=kb(L);L[b]=G.createShader(a);return b},uc=a=>{if(a){var b=H[a];b?(G.deleteProgram(b),b.name=0,H[a]=null):O||=1281}},vc=a=>G.disable(a),wc=[],xc=(a,b,c,d)=>{G.drawElements(a,b,c,d)},yc=a=>G.enable(a),zc=a=>{G.enableVertexAttribArray(a)},Ac=(a,b)=>{lb(a,b,"createBuffer",eb)},Bc=(a,b,c,d,e,f,g,m)=>{b=H[b];if(a=G[a](b,c))d=m&&A(a.name,m,d),e&&(u[e>>2]=d),f&&(u[f>>2]=a.size),g&&(u[g>>2]=a.type)},Cc=(a,
b)=>G.getAttribLocation(H[a],b?C(r,b):""),Dc=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&(O||=1280);return;case 36345:d=0;break;case 34466:var e=G.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=G.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":O||=1280;return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:O||=
1280;return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:u[b+4*a>>2]=e[a];break;case 2:w[b+4*a>>2]=e[a];break;case 4:q[b+a]=e[a]?1:0}return}try{d=e.name|0}catch(f){O||=1280;l(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${f})`);return}}break;default:O||=1280;l(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${e} of type ${typeof e}!`);
return}switch(c){case 1:c=d;v[b>>2]=c;v[b+4>>2]=(c-v[b>>2])/4294967296;break;case 0:u[b>>2]=d;break;case 2:w[b>>2]=d;break;case 4:q[b]=d?1:0}}else O||=1281},Ec=(a,b,c,d)=>{a=G.getProgramInfoLog(H[a]);null===a&&(a="(unknown error)");b=0<b&&d?A(a,d,b):0;c&&(u[c>>2]=b)},Fc=(a,b,c)=>{if(c)if(a>=db)O||=1281;else if(a=H[a],35716==b)a=G.getProgramInfoLog(a),null===a&&(a="(unknown error)"),u[c>>2]=a.length+1;else if(35719==b){if(!a.De){var d=G.getProgramParameter(a,35718);for(b=0;b<d;++b)a.De=Math.max(a.De,
G.getActiveUniform(a,b).name.length+1)}u[c>>2]=a.De}else if(35722==b){if(!a.Be)for(d=G.getProgramParameter(a,35721),b=0;b<d;++b)a.Be=Math.max(a.Be,G.getActiveAttrib(a,b).name.length+1);u[c>>2]=a.Be}else if(35381==b){if(!a.Ce)for(d=G.getProgramParameter(a,35382),b=0;b<d;++b)a.Ce=Math.max(a.Ce,G.getActiveUniformBlockName(a,b).length+1);u[c>>2]=a.Ce}else u[c>>2]=G.getProgramParameter(a,b);else O||=1281},Gc=(a,b,c)=>{if(c){a=G.oe.getQueryObjectEXT(N[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;v[c>>2]=
d;v[c+4>>2]=(d-v[c>>2])/4294967296}else O||=1281},Hc=(a,b,c)=>{if(c){a=G.oe.getQueryObjectEXT(N[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;u[c>>2]=d}else O||=1281},Ic=()=>{var a=cb(G);return a=a.concat(a.map(b=>"GL_"+b))},Jc=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Kc=a=>{var b=a.ve,c=a.ef,d;if(!b){a.ve=b={};a.df={};var e=G.getProgramParameter(a,35718);for(d=0;d<e;++d){var f=G.getActiveUniform(a,d);var g=f.name;f=f.size;var m=Jc(g);m=0<m?g.slice(0,m):g;var n=a.Se;a.Se+=f;c[m]=[f,n];for(g=0;g<f;++g)b[n]=
g,a.df[n++]=m}}},Lc=(a,b)=>{b=b?C(r,b):"";if(a=H[a]){Kc(a);var c=a.ve,d=0,e=b,f=Jc(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.ef[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||G.getUniformLocation(a,b)))return d}else O||=1281;return-1},V=a=>{var b=G.hf;if(b){var c=b.ve[a];"number"==typeof c&&(b.ve[a]=c=G.getUniformLocation(b,b.df[a]+(0<c?`[${c}]`:"")));return c}O||=1282},Mc=(a,b,c,d)=>{if(c)if(a=H[a],Kc(a),a=G.getUniform(a,V(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:u[c>>2]=
a;break;case 2:w[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:u[c+4*b>>2]=a[b];break;case 2:w[c+4*b>>2]=a[b]}else O||=1281},Nc=(a,b,c,d)=>{if(c)if(a=G.getVertexAttrib(a,b),34975==b)u[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:u[c>>2]=a;break;case 2:w[c>>2]=a;break;case 5:u[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:u[c+4*b>>2]=a[b];break;case 2:w[c+4*b>>2]=a[b];break;case 5:u[c+4*b>>2]=Math.fround(a[b])}else O||=1281},Oc=a=>{a=H[a];
G.linkProgram(a);a.ve=0;a.ef={}},Pc=(a,b,c,d,e)=>{a-=5120;a=1==a?r:4==a?u:6==a?w:5==a||28922==a?v:ka;b=d*((jb||c)*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+ib-1&-ib);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},Qc=(a,b,c,d)=>{for(var e="",f=0;f<b;++f){var g=(g=v[c+4*f>>2])?C(r,g,d?v[d+4*f>>2]:void 0):"";e+=g}G.shaderSource(L[a],e)},Rc=(a,b)=>{G.uniform1f(V(a),b)},W=[],Sc=[],Tc=(a,b,c,d)=>{if(18>=b){var e=W[16*b],f=w;d>>=2;
b*=16;for(var g=0;g<b;g+=16){var m=d+g;e[g]=f[m];e[g+1]=f[m+1];e[g+2]=f[m+2];e[g+3]=f[m+3];e[g+4]=f[m+4];e[g+5]=f[m+5];e[g+6]=f[m+6];e[g+7]=f[m+7];e[g+8]=f[m+8];e[g+9]=f[m+9];e[g+10]=f[m+10];e[g+11]=f[m+11];e[g+12]=f[m+12];e[g+13]=f[m+13];e[g+14]=f[m+14];e[g+15]=f[m+15]}}else e=w.subarray(d>>2,d+64*b>>2);G.uniformMatrix4fv(V(a),!!c,e)},Uc=a=>{a=H[a];G.useProgram(a);G.hf=a},Vc=(a,b,c,d,e,f)=>{G.vertexAttribPointer(a,b,c,!!d,e,f)},Wc=(a,b,c,d)=>G.viewport(a,b,c,d),Xc=(a,b)=>{if(!R.fullscreenEnabled())return-1;
a=T(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?Rb()?hc(a,b):b.mf?(Pb(hc,1,[a,b]),1):-2:-3:-4},Yc=()=>{try{if(navigator.getGamepads)return(R.Ae=navigator.getGamepads())?0:-1}catch(a){navigator.getGamepads=null}return-1},Zc=(a,b)=>{var c={target:T(2),he:"beforeunload",je:b,le:(d=event)=>{var e=U(b)(28,0,a);e&&=e?C(r,e):"";if(e)return d.preventDefault(),d.returnValue=e},ie:!0};return S(c)},$c=(a,b,c,d,e,f)=>{R.He||(R.He=z(256));a={target:T(a),he:f,je:d,le:(g=event)=>{var m=g.target.id?
g.target.id:"",n=R.He;A(Tb(g.target),n+0,128);A(m,n+128,128);U(d)(e,n,b)&&g.preventDefault()},ie:c};return S(a)},ad=(a,b,c,d,e)=>{R.Ie||(R.Ie=z(276));return S({target:a,he:e,je:d,le:(f=event)=>{var g=R.Ie,m=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,n=!!m;q[g]=n;q[g+1]=R.fullscreenEnabled();var t=n?m:R.vf,B=t?.id||"";A(Tb(t),g+2,128);A(B,g+130,128);u[g+260>>2]=t?t.clientWidth:0;u[g+264>>2]=t?t.clientHeight:0;u[g+268>>2]=
screen.width;u[g+272>>2]=screen.height;n&&(R.vf=m);U(d)(19,g,b)&&f.preventDefault()},ie:c})},bd=(a,b,c,d,e)=>{R.Je||(R.Je=z(1240));b={target:T(2),we:!0,he:e,je:c,le:(f=event)=>{var g=R.Je;jc(g,f.gamepad);U(c)(d,g,a)&&f.preventDefault()},ie:b};return S(b)},cd=(a,b,c,d,e,f)=>{R.Le||(R.Le=z(160));a={target:T(a),he:f,je:d,le:g=>{var m=R.Le;x[m>>3]=g.timeStamp;var n=m>>2;u[n+2]=g.location;q[m+12]=g.ctrlKey;q[m+13]=g.shiftKey;q[m+14]=g.altKey;q[m+15]=g.metaKey;q[m+16]=g.repeat;u[n+5]=g.charCode;u[n+6]=
g.keyCode;u[n+7]=g.which;A(g.key||"",m+32,32);A(g.code||"",m+64,32);A(g.char||"",m+96,32);A(g.locale||"",m+128,32);U(d)(e,m,b)&&g.preventDefault()},ie:c};return S(a)},dd=(a,b,c)=>{x[a>>3]=b.timeStamp;var d=a>>2;u[d+2]=b.screenX;u[d+3]=b.screenY;u[d+4]=b.clientX;u[d+5]=b.clientY;q[a+24]=b.ctrlKey;q[a+25]=b.shiftKey;q[a+26]=b.altKey;q[a+27]=b.metaKey;ja[2*d+14]=b.button;ja[2*d+15]=b.buttons;u[d+8]=b.movementX;u[d+9]=b.movementY;a=gc(c);u[d+10]=b.clientX-(a.left|0);u[d+11]=b.clientY-(a.top|0)},ed=(a,
b,c,d,e,f)=>{R.Ee||(R.Ee=z(64));a=T(a);return S({target:a,we:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,he:f,je:d,le:(g=event)=>{dd(R.Ee,g,a);U(d)(e,R.Ee,b)&&g.preventDefault()},ie:c})},fd=(a,b,c,d,e)=>{R.Ne||(R.Ne=z(257));return S({target:a,he:e,je:d,le:(f=event)=>{var g=R.Ne;kc(g);U(d)(20,g,b)&&f.preventDefault()},ie:c})},gd=(a,b,c,d)=>{R.Re||(R.Re=z(36));a=T(a);return S({target:a,he:"resize",je:d,le:(e=event)=>{if(e.target==a){var f=document.body;if(f){var g=R.Re;u[g>>2]=0;u[g+4>>2]=f.clientWidth;
u[g+8>>2]=f.clientHeight;u[g+12>>2]=innerWidth;u[g+16>>2]=innerHeight;u[g+20>>2]=outerWidth;u[g+24>>2]=outerHeight;u[g+28>>2]=pageXOffset|0;u[g+32>>2]=pageYOffset|0;U(d)(10,g,b)&&e.preventDefault()}}},ie:c})},hd=(a,b,c,d,e,f)=>{R.Qe||(R.Qe=z(1552));a=T(a);return S({target:a,we:"touchstart"==f||"touchend"==f,he:f,je:d,le:g=>{var m={},n=g.touches;for(var t of n)t.$e=t.bf=0,m[t.identifier]=t;for(var B of g.changedTouches)B.$e=1,m[B.identifier]=B;for(var Z of g.targetTouches)m[Z.identifier].bf=1;n=R.Qe;
x[n>>3]=g.timeStamp;q[n+12]=g.ctrlKey;q[n+13]=g.shiftKey;q[n+14]=g.altKey;q[n+15]=g.metaKey;t=n+16;B=gc(a);Z=0;for(let I of Object.values(m))if(m=t>>2,u[m]=I.identifier,u[m+1]=I.screenX,u[m+2]=I.screenY,u[m+3]=I.clientX,u[m+4]=I.clientY,u[m+5]=I.pageX,u[m+6]=I.pageY,q[t+28]=I.$e,q[t+29]=I.bf,u[m+8]=I.clientX-(B.left|0),u[m+9]=I.clientY-(B.top|0),t+=48,31<++Z)break;u[n+8>>2]=Z;U(d)(e,n,b)&&g.preventDefault()},ie:c})},rd=(a,b,c)=>{var d=Vb[1];R.Te||(R.Te=z(8));return S({target:d,he:"visibilitychange",
je:c,le:(e=event)=>{var f=R.Te,g=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);q[f]=document.hidden;u[f+4>>2]=g;U(c)(21,f,a)&&e.preventDefault()},ie:b})},sd=(a,b,c,d)=>{R.Ue||(R.Ue=z(96));return S({target:a,we:!0,he:"wheel",je:d,le:(e=event)=>{var f=R.Ue;dd(f,e,a);x[f+64>>3]=e.deltaX;x[f+72>>3]=e.deltaY;x[f+80>>3]=e.deltaZ;u[f+88>>2]=e.deltaMode;U(d)(9,f,b)&&e.preventDefault()},ie:c})},td={},vd=()=>{if(!ud){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",
HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in td)void 0===td[b]?delete a[b]:a[b]=td[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);ud=c}return ud},ud,wd=[null,[],[]],xd=(a,b,c)=>{a.addEventListener(b,c,{once:!0})},sa=a=>{var b;b||=[document,document.getElementById("canvas")];["keydown","mousedown","touchstart"].forEach(c=>{b.forEach(d=>{d&&xd(d,c,()=>{"suspended"===a.state&&a.resume()})})})},
ta=(a,b=[])=>{U(a)(...b)};
h.requestFullscreen=function(a,b){function c(){Ja=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=Qa,Pa&&d.requestPointerLock(),Ja=!0,D?("undefined"!=typeof SDL&&(u[SDL.screen>>2]=v[SDL.screen>>2]|8388608),Ta(h.canvas),Sa()):Ta(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),D?("undefined"!=typeof SDL&&(u[SDL.screen>>2]=v[SDL.screen>>
2]&-8388609),Ta(h.canvas),Sa()):Ta(d));h.onFullScreen?.(Ja);h.onFullscreen?.(Ja)}Pa=a;D=b;"undefined"==typeof Pa&&(Pa=!0);"undefined"==typeof D&&(D=!1);var d=h.canvas;Oa||(Oa=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=e.requestFullscreen||
e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()};h.setCanvasSize=function(a,b,c){Ta(h.canvas,a,b);c||Sa()};h.getUserMedia=function(a){let b;(b=window).getUserMedia||(b.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)};
h.createContext=function(a,b,c,d){if(b&&h.ctx&&a==h.canvas)return h.ctx;var e;if(b){var f={antialias:!1,alpha:!1,af:1};if(d)for(var g in d)f[g]=d[g];if("undefined"!=typeof rb&&(e=nb(a,f)))var m=M[e].pe}else m=a.getContext("2d");if(!m)return null;c&&(h.ctx=m,b&&qb(e),La.forEach(n=>n()),Ma());return m};h.requestAnimationFrame=Kb;h.pauseMainLoop=function(){Q=null;tb++};h.resumeMainLoop=function(){tb++;var a=Cb,b=Db,c=ub;ub=null;Ib(c,0,!1,vb,!0);Hb(a,b);Q()};h.preMainLoop&&Fb.push(h.preMainLoop);
h.postMainLoop&&Gb.push(h.postMainLoop);for(var X=0;32>X;++X)wc.push(Array(X));var yd=new Float32Array(288);for(X=0;288>=X;++X)W[X]=yd.subarray(0,X);var zd=new Int32Array(288);for(X=0;288>=X;++X)Sc[X]=zd.subarray(0,X);
var Ad={_:function(){return 0},bb:()=>{},db:function(){return 0},Za:()=>{},$a:()=>{},eb:function(){},ab:()=>{},Ua:function(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);u[b>>2]=a.getSeconds();u[b+4>>2]=a.getMinutes();u[b+8>>2]=a.getHours();u[b+12>>2]=a.getDate();u[b+16>>2]=a.getMonth();u[b+20>>2]=a.getFullYear()-1900;u[b+24>>2]=a.getDay();var c=a.getFullYear();u[b+28>>2]=(0!==c%4||0===c%100&&0!==c%400?Ea:Da)[a.getMonth()]+a.getDate()-1|0;u[b+36>>2]=-(60*a.getTimezoneOffset());
c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();u[b+32>>2]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0},Va:(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();v[a>>2]=60*Math.max(f,e);u[b>>2]=Number(f!=e);b=g=>{var m=Math.abs(g);return`UTC${0<=g?"-":"+"}${String(Math.floor(m/60)).padStart(2,"0")}${String(m%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(A(a,c,17),A(b,
d,17)):(A(a,d,17),A(b,c,17))},Ja:a=>{if(12448==a)return E=12288,1;E=12300;return 0},Ma:(a,b,c,d,e)=>{if(62E3!=a)E=12296,c=0;else{if(b)for(;;){a=u[b>>2];if(12321==a)F.alpha=0<u[b+4>>2];else if(12325==a)F.depth=0<u[b+4>>2];else if(12326==a)F.stencil=0<u[b+4>>2];else if(12337==a)a=u[b+4>>2],F.antialias=0<a;else if(12338==a)a=u[b+4>>2],F.antialias=1==a;else if(12544==a)F.If=12547!=u[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(u[e>>2]=1),c&&0<d&&(v[c>>2]=62002),E=12288,c=1):(E=12300,c=0)}return c},
Aa:(a,b,c,d)=>{if(62E3!=a)return E=12296,0;for(a=1;;){b=u[d>>2];if(12440==b)a=u[d+4>>2];else if(12344==b)break;else return E=12292,0;d+=8}if(2!=a)return E=12293,0;F.af=a-1;F.Kf=0;Za=nb(h.canvas,F);if(0!=Za)return E=12288,qb(Za),La.forEach(e=>e()),qb(null),62004;E=12297;return 0},Ca:(a,b)=>{if(62E3!=a)return E=12296,0;if(62002!=b)return E=12293,0;E=12288;return 62006},Ba:(a,b)=>{if(62E3!=a)return E=12296,0;if(62004!=b)return E=12294,0;a=Za;pb===M[a]&&(pb=null);"object"==typeof R&&R.wf(M[a].pe.canvas);
M[a]?.pe.canvas&&(M[a].pe.canvas.te=void 0);M[a]=null;E=12288;Va==b&&(Va=0);return 1},Da:(a,b)=>{if(62E3!=a)return E=12296,0;if(62006!=b)return E=12301,1;Wa==b&&(Wa=0);Xa==b&&(Xa=0);E=12288;return 1},Na:(a,b,c,d)=>{if(62E3!=a)return E=12296,0;if(62002!=b)return E=12293,0;if(!d)return E=12300,0;E=12288;switch(c){case 12320:return u[d>>2]=F.alpha?32:24,1;case 12321:return u[d>>2]=F.alpha?8:0,1;case 12322:return u[d>>2]=8,1;case 12323:return u[d>>2]=8,1;case 12324:return u[d>>2]=8,1;case 12325:return u[d>>
2]=F.depth?24:0,1;case 12326:return u[d>>2]=F.stencil?8:0,1;case 12327:return u[d>>2]=12344,1;case 12328:return u[d>>2]=62002,1;case 12329:return u[d>>2]=0,1;case 12330:return u[d>>2]=4096,1;case 12331:return u[d>>2]=16777216,1;case 12332:return u[d>>2]=4096,1;case 12333:return u[d>>2]=0,1;case 12334:return u[d>>2]=0,1;case 12335:return u[d>>2]=12344,1;case 12337:return u[d>>2]=F.antialias?4:0,1;case 12338:return u[d>>2]=F.antialias?1:0,1;case 12339:return u[d>>2]=4,1;case 12340:return u[d>>2]=12344,
1;case 12341:case 12342:case 12343:return u[d>>2]=-1,1;case 12345:case 12346:return u[d>>2]=0,1;case 12347:return u[d>>2]=0,1;case 12348:return u[d>>2]=1;case 12349:case 12350:return u[d>>2]=0,1;case 12351:return u[d>>2]=12430,1;case 12352:return u[d>>2]=4,1;case 12354:return u[d>>2]=0,1;default:return E=12292,0}},S:a=>{E=12288;return 0!=a&&1!=a?0:62E3},za:()=>E,Ka:(a,b,c)=>{if(62E3!=a)return E=12296,0;b&&(u[b>>2]=1);c&&(u[c>>2]=4);Ua=!0;E=12288;return 1},Ea:(a,b,c,d)=>{if(62E3!=a)return E=12296,
0;if(0!=d&&62004!=d)return E=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return E=12301,0;qb(d?Za:null);Va=d;Xa=b;Wa=c;E=12288;return 1},ya:(a,b)=>{if(62E3!=a)return E=12296,0;E=12288;if(Ya[b])return Ya[b];switch(b){case 12371:a=P("Emscripten");break;case 12372:a=P("1.4 Emscripten EGL");break;case 12373:a=P("");break;case 12429:a=P("OpenGL_ES");break;default:return E=12300,0}return Ya[b]=a},Fa:()=>{if(Ua)if(G)if(G.isContextLost())E=12302;else return E=12288,1;else E=12290;else E=12289;return 0},Ga:(a,
b)=>{if(62E3!=a)return E=12296,0;0==b?Hb(0,0):Hb(1,b);E=12288;return 1},La:a=>{if(62E3!=a)return E=12296,0;Xa=Wa=Va=0;Ua=!1;E=12288;return 1},Ia:()=>{E=12288;return 1},Ha:()=>{E=12288;return 1},Pa:(a,b,c)=>{b=Nb(b,c);return va[a](...b)},e:(a,b,c)=>{b=Nb(b,c);return va[a](...b)},Qa:(a,b,c)=>{b=Nb(b,c);return va[a](...b)},$:()=>Date.now(),ra:()=>{if(!R.fullscreenEnabled())return-1;Qb(hc);var a=Vb[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&
a.webkitExitFullscreen();else return-1;return 0},wa:()=>{Qb(ic);if(document.exitPointerLock)document.exitPointerLock();else return-1;return 0},m:()=>devicePixelRatio,g:(a,b,c)=>{a=T(a);if(!a)return-4;a=gc(a);x[b>>3]=a.width;x[c>>3]=a.height;return 0},V:(a,b)=>{if(0>a||a>=R.Ae.length)return-5;if(!R.Ae[a])return-7;jc(b,R.Ae[a]);return 0},X:()=>performance.now(),Oa:()=>R.Ae.length,Jb:a=>{a&&kc(a);return document.body&&(document.body.requestPointerLock||document.body.ue||document.body.Ze||document.body.Ye)?
0:-1},xa:(a,b)=>{u[a>>2]=screen.width;u[b>>2]=screen.height},Ud:a=>G.activeTexture(a),Td:lc,na:(a,b)=>{G.oe.beginQueryEXT(a,N[b])},Sd:(a,b,c)=>{G.bindAttribLocation(H[a],b,c?C(r,c):"")},Rd:mc,Qd:(a,b)=>{G.bindFramebuffer(a,fb[b])},Pd:(a,b)=>{G.bindRenderbuffer(a,J[b])},Od:(a,b)=>{G.bindTexture(a,K[b])},fa:a=>{G.bindVertexArray(gb[a])},Nd:(a,b,c,d)=>G.blendColor(a,b,c,d),Md:a=>G.blendEquation(a),Ld:(a,b)=>G.blendEquationSeparate(a,b),Kd:nc,Jd:(a,b,c,d)=>G.blendFuncSeparate(a,b,c,d),Id:oc,Hd:(a,b,c,
d)=>{G.bufferSubData(a,b,r.subarray(d,d+c))},Gd:a=>G.checkFramebufferStatus(a),Ed:pc,Dd:qc,Cd:a=>G.clearDepth(a),Bd:a=>G.clearStencil(a),gb:(a,b)=>{G.pf.clipControlEXT(a,b)},Ad:(a,b,c,d)=>{G.colorMask(!!a,!!b,!!c,!!d)},zd:rc,yd:(a,b,c,d,e,f,g,m)=>{G.compressedTexImage2D(a,b,c,d,e,f,r.subarray(m,m+g))},xd:(a,b,c,d,e,f,g,m,n)=>{G.compressedTexSubImage2D(a,b,c,d,e,f,g,r.subarray(n,n+m))},wd:(a,b,c,d,e,f,g,m)=>G.copyTexImage2D(a,b,c,d,e,f,g,m),vd:(a,b,c,d,e,f,g,m)=>G.copyTexSubImage2D(a,b,c,d,e,f,g,m),
ud:sc,td:tc,sd:a=>G.cullFace(a),rd:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=eb[d];e&&(G.deleteBuffer(e),e.name=0,eb[d]=null)}},qd:(a,b)=>{for(var c=0;c<a;++c){var d=u[b+4*c>>2],e=fb[d];e&&(G.deleteFramebuffer(e),e.name=0,fb[d]=null)}},pd:uc,pa:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=N[d];e&&(G.oe.deleteQueryEXT(e),N[d]=null)}},od:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=J[d];e&&(G.deleteRenderbuffer(e),e.name=0,J[d]=null)}},nd:a=>{if(a){var b=L[a];b?(G.deleteShader(b),L[a]=
null):O||=1281}},md:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=K[d];e&&(G.deleteTexture(e),e.name=0,K[d]=null)}},ea:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2];G.deleteVertexArray(gb[d]);gb[d]=null}},ld:a=>G.depthFunc(a),jd:a=>{G.depthMask(!!a)},id:(a,b)=>G.depthRange(a,b),hd:(a,b)=>{G.detachShader(H[a],L[b])},gd:vc,fd:a=>{G.disableVertexAttribArray(a)},ed:(a,b,c)=>{G.drawArrays(a,b,c)},Xd:(a,b,c,d)=>{G.drawArraysInstanced(a,b,c,d)},Yd:(a,b)=>{for(var c=wc[a],d=0;d<a;d++)c[d]=u[b+4*d>>2];
G.drawBuffers(c)},dd:xc,Wd:(a,b,c,d,e)=>{G.drawElementsInstanced(a,b,c,d,e)},cd:yc,bd:zc,ma:a=>{G.oe.endQueryEXT(a)},ad:()=>G.finish(),$c:()=>G.flush(),_c:(a,b,c,d)=>{G.framebufferRenderbuffer(a,b,c,J[d])},Zc:(a,b,c,d,e)=>{G.framebufferTexture2D(a,b,c,K[d],e)},Yc:a=>G.frontFace(a),Xc:Ac,Vc:(a,b)=>{lb(a,b,"createFramebuffer",fb)},qa:(a,b)=>{for(var c=0;c<a;c++){var d=G.oe.createQueryEXT();if(!d){for(O||=1282;c<a;)u[b+4*c++>>2]=0;break}var e=kb(N);d.name=e;N[e]=d;u[b+4*c>>2]=e}},Uc:(a,b)=>{lb(a,b,"createRenderbuffer",
J)},Tc:(a,b)=>{lb(a,b,"createTexture",K)},da:(a,b)=>{lb(a,b,"createVertexArray",gb)},Wc:a=>G.generateMipmap(a),Sc:(a,b,c,d,e,f,g)=>Bc("getActiveAttrib",a,b,c,d,e,f,g),Rc:(a,b,c,d,e,f,g)=>Bc("getActiveUniform",a,b,c,d,e,f,g),Qc:(a,b,c,d)=>{a=G.getAttachedShaders(H[a]);var e=a.length;e>b&&(e=b);u[c>>2]=e;for(b=0;b<e;++b)u[d+4*b>>2]=L.indexOf(a[b])},Pc:Cc,Oc:(a,b)=>Dc(a,b,4),Nc:(a,b,c)=>{c?u[c>>2]=G.getBufferParameter(a,b):O||=1281},Mc:()=>{var a=G.getError()||O;O=0;return a},Lc:(a,b)=>Dc(a,b,2),Kc:(a,
b,c,d)=>{a=G.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;u[d>>2]=a},Jc:(a,b)=>Dc(a,b,0),Gc:Ec,Ic:Fc,ha:Gc,ja:Hc,ga:Gc,ia:Hc,ka:(a,b,c)=>{c?u[c>>2]=G.oe.getQueryEXT(a,b):O||=1281},Fc:(a,b,c)=>{c?u[c>>2]=G.getRenderbufferParameter(a,b):O||=1281},Dc:(a,b,c,d)=>{a=G.getShaderInfoLog(L[a]);null===a&&(a="(unknown error)");b=0<b&&d?A(a,d,b):0;c&&(u[c>>2]=b)},Cc:(a,b,c,d)=>{a=G.getShaderPrecisionFormat(a,b);u[c>>2]=a.rangeMin;u[c+4>>2]=
a.rangeMax;u[d>>2]=a.precision},Bc:(a,b,c,d)=>{if(a=G.getShaderSource(L[a]))b=0<b&&d?A(a,d,b):0,c&&(u[c>>2]=b)},Ec:(a,b,c)=>{c?35716==b?(a=G.getShaderInfoLog(L[a]),null===a&&(a="(unknown error)"),u[c>>2]=a?a.length+1:0):35720==b?(a=G.getShaderSource(L[a]),u[c>>2]=a?a.length+1:0):u[c>>2]=G.getShaderParameter(L[a],b):O||=1281},Ac:a=>{var b=hb[a];if(!b){switch(a){case 7939:b=P(Ic().join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=G.getParameter(a))||(O||=1280);b=b?P(b):0;break;case 7938:b=
P(`OpenGL ES 2.0 (${G.getParameter(7938)})`);break;case 35724:b=G.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=P(b);break;default:O||=1280}hb[a]=b}return b},zc:(a,b,c)=>{c?w[c>>2]=G.getTexParameter(a,b):O||=1281},yc:(a,b,c)=>{c?u[c>>2]=G.getTexParameter(a,b):O||=1281},vc:Lc,xc:(a,b,c)=>{Mc(a,b,c,2)},wc:(a,b,c)=>{Mc(a,b,c,0)},sc:(a,b,c)=>{c?u[c>>2]=G.getVertexAttribOffset(a,b):O||=1281},
uc:(a,b,c)=>{Nc(a,b,c,2)},tc:(a,b,c)=>{Nc(a,b,c,5)},rc:(a,b)=>G.hint(a,b),qc:a=>(a=eb[a])?G.isBuffer(a):0,pc:a=>G.isEnabled(a),oc:a=>(a=fb[a])?G.isFramebuffer(a):0,nc:a=>(a=H[a])?G.isProgram(a):0,oa:a=>(a=N[a])?G.oe.isQueryEXT(a):0,mc:a=>(a=J[a])?G.isRenderbuffer(a):0,lc:a=>(a=L[a])?G.isShader(a):0,kc:a=>(a=K[a])?G.isTexture(a):0,Zd:a=>(a=gb[a])?G.isVertexArray(a):0,jc:a=>G.lineWidth(a),ic:Oc,hc:(a,b)=>{3317==a?ib=b:3314==a&&(jb=b);G.pixelStorei(a,b)},fb:(a,b)=>{G.yf.polygonModeWEBGL(a,b)},gc:(a,
b)=>G.polygonOffset(a,b),hb:(a,b,c)=>{G.qf.polygonOffsetClampEXT(a,b,c)},la:(a,b)=>{G.oe.queryCounterEXT(N[a],b)},fc:(a,b,c,d,e,f,g)=>{(g=Pc(f,e,c,d,g))?G.readPixels(a,b,c,d,e,f,g):O||=1280},ec:()=>{},dc:(a,b,c,d)=>G.renderbufferStorage(a,b,c,d),bc:(a,b)=>{G.sampleCoverage(a,!!b)},ac:(a,b,c,d)=>G.scissor(a,b,c,d),$b:()=>{O||=1280},_b:Qc,Zb:(a,b,c)=>G.stencilFunc(a,b,c),Yb:(a,b,c,d)=>G.stencilFuncSeparate(a,b,c,d),Xb:a=>G.stencilMask(a),Wb:(a,b)=>G.stencilMaskSeparate(a,b),Vb:(a,b,c)=>G.stencilOp(a,
b,c),Ub:(a,b,c,d)=>G.stencilOpSeparate(a,b,c,d),Tb:(a,b,c,d,e,f,g,m,n)=>{n=n?Pc(m,g,d,e,n):null;G.texImage2D(a,b,c,d,e,f,g,m,n)},Sb:(a,b,c)=>G.texParameterf(a,b,c),Rb:(a,b,c)=>{G.texParameterf(a,b,w[c>>2])},Qb:(a,b,c)=>G.texParameteri(a,b,c),Pb:(a,b,c)=>{G.texParameteri(a,b,u[c>>2])},Ob:(a,b,c,d,e,f,g,m,n)=>{n=n?Pc(m,g,e,f,n):null;G.texSubImage2D(a,b,c,d,e,f,g,m,n)},Nb:Rc,Mb:(a,b,c)=>{if(288>=b)for(var d=W[b],e=0;e<b;++e)d[e]=w[c+4*e>>2];else d=w.subarray(c>>2,c+4*b>>2);G.uniform1fv(V(a),d)},Lb:(a,
b)=>{G.uniform1i(V(a),b)},Kb:(a,b,c)=>{if(288>=b)for(var d=Sc[b],e=0;e<b;++e)d[e]=u[c+4*e>>2];else d=u.subarray(c>>2,c+4*b>>2);G.uniform1iv(V(a),d)},Ib:(a,b,c)=>{G.uniform2f(V(a),b,c)},Hb:(a,b,c)=>{if(144>=b){b*=2;for(var d=W[b],e=0;e<b;e+=2)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2]}else d=w.subarray(c>>2,c+8*b>>2);G.uniform2fv(V(a),d)},Gb:(a,b,c)=>{G.uniform2i(V(a),b,c)},Fb:(a,b,c)=>{if(144>=b){b*=2;for(var d=Sc[b],e=0;e<b;e+=2)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2]}else d=u.subarray(c>>2,c+8*b>>
2);G.uniform2iv(V(a),d)},Eb:(a,b,c,d)=>{G.uniform3f(V(a),b,c,d)},Db:(a,b,c)=>{if(96>=b){b*=3;for(var d=W[b],e=0;e<b;e+=3)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2]}else d=w.subarray(c>>2,c+12*b>>2);G.uniform3fv(V(a),d)},Cb:(a,b,c,d)=>{G.uniform3i(V(a),b,c,d)},Bb:(a,b,c)=>{if(96>=b){b*=3;for(var d=Sc[b],e=0;e<b;e+=3)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2]}else d=u.subarray(c>>2,c+12*b>>2);G.uniform3iv(V(a),d)},Ab:(a,b,c,d,e)=>{G.uniform4f(V(a),b,c,d,e)},zb:(a,
b,c)=>{if(72>=b){var d=W[4*b],e=w;c>>=2;b*=4;for(var f=0;f<b;f+=4){var g=c+f;d[f]=e[g];d[f+1]=e[g+1];d[f+2]=e[g+2];d[f+3]=e[g+3]}}else d=w.subarray(c>>2,c+16*b>>2);G.uniform4fv(V(a),d)},yb:(a,b,c,d,e)=>{G.uniform4i(V(a),b,c,d,e)},xb:(a,b,c)=>{if(72>=b){b*=4;for(var d=Sc[b],e=0;e<b;e+=4)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2],d[e+3]=u[c+(4*e+12)>>2]}else d=u.subarray(c>>2,c+16*b>>2);G.uniform4iv(V(a),d)},wb:(a,b,c,d)=>{if(72>=b){b*=4;for(var e=W[b],f=0;f<b;f+=4)e[f]=w[d+4*f>>
2],e[f+1]=w[d+(4*f+4)>>2],e[f+2]=w[d+(4*f+8)>>2],e[f+3]=w[d+(4*f+12)>>2]}else e=w.subarray(d>>2,d+16*b>>2);G.uniformMatrix2fv(V(a),!!c,e)},vb:(a,b,c,d)=>{if(32>=b){b*=9;for(var e=W[b],f=0;f<b;f+=9)e[f]=w[d+4*f>>2],e[f+1]=w[d+(4*f+4)>>2],e[f+2]=w[d+(4*f+8)>>2],e[f+3]=w[d+(4*f+12)>>2],e[f+4]=w[d+(4*f+16)>>2],e[f+5]=w[d+(4*f+20)>>2],e[f+6]=w[d+(4*f+24)>>2],e[f+7]=w[d+(4*f+28)>>2],e[f+8]=w[d+(4*f+32)>>2]}else e=w.subarray(d>>2,d+36*b>>2);G.uniformMatrix3fv(V(a),!!c,e)},ub:Tc,tb:Uc,sb:a=>{G.validateProgram(H[a])},
rb:(a,b)=>G.vertexAttrib1f(a,b),qb:(a,b)=>{G.vertexAttrib1f(a,w[b>>2])},pb:(a,b,c)=>G.vertexAttrib2f(a,b,c),ob:(a,b)=>{G.vertexAttrib2f(a,w[b>>2],w[b+4>>2])},nb:(a,b,c,d)=>G.vertexAttrib3f(a,b,c,d),mb:(a,b)=>{G.vertexAttrib3f(a,w[b>>2],w[b+4>>2],w[b+8>>2])},lb:(a,b,c,d,e)=>G.vertexAttrib4f(a,b,c,d,e),kb:(a,b)=>{G.vertexAttrib4f(a,w[b>>2],w[b+4>>2],w[b+8>>2],w[b+12>>2])},Vd:(a,b)=>{G.vertexAttribDivisor(a,b)},jb:Vc,ib:Wc,r:()=>0,sa:(a,b,c)=>Xc(a,{Oe:u[c>>2],Fe:u[c+4>>2],rf:u[c+8>>2],mf:b,xe:u[c+12>>
2],We:u[c+16>>2]}),Q:(a,b)=>{a=T(a);return a?a.requestPointerLock?Rb()?ic(a):b?(Pb(ic,2,[a]),1):-2:-1:-4},Ta:()=>{na("OOM")},d:a=>{eval(a?C(r,a):"")},W:Yc,x:(a,b,c)=>"undefined"==typeof onbeforeunload?-1:1!==c?-5:Zc(a,b),I:(a,b,c,d)=>$c(a,b,c,d,12,"blur"),k:ac,o:(a,b,c)=>{a=T(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},J:(a,b,c,d)=>$c(a,b,c,d,13,"focus"),z:(a,b,c,d)=>{if(!R.fullscreenEnabled())return-1;a=T(a);if(!a)return-4;ad(a,b,c,d,"webkitfullscreenchange");return ad(a,
b,c,d,"fullscreenchange")},U:(a,b,c)=>Yc()?-1:bd(a,b,c,26,"gamepadconnected"),T:(a,b,c)=>Yc()?-1:bd(a,b,c,27,"gamepaddisconnected"),C:(a,b,c,d)=>cd(a,b,c,d,2,"keydown"),A:(a,b,c,d)=>cd(a,b,c,d,1,"keypress"),B:(a,b,c,d)=>cd(a,b,c,d,3,"keyup"),Ra:(a,b,c)=>{a=U(a);Ib(a,b,c)},O:(a,b,c,d)=>ed(a,b,c,d,5,"mousedown"),M:(a,b,c,d)=>ed(a,b,c,d,33,"mouseenter"),L:(a,b,c,d)=>ed(a,b,c,d,34,"mouseleave"),P:(a,b,c,d)=>ed(a,b,c,d,8,"mousemove"),N:(a,b,c,d)=>ed(a,b,c,d,6,"mouseup"),D:(a,b,c,d)=>{if(!document||!document.body||
!(document.body.requestPointerLock||document.body.ue||document.body.Ze||document.body.Ye))return-1;a=T(a);if(!a)return-4;fd(a,b,c,d,"mozpointerlockchange");fd(a,b,c,d,"webkitpointerlockchange");fd(a,b,c,d,"mspointerlockchange");return fd(a,b,c,d,"pointerlockchange")},s:(a,b,c,d)=>gd(a,b,c,d),E:(a,b,c,d)=>hd(a,b,c,d,25,"touchcancel"),G:(a,b,c,d)=>hd(a,b,c,d,23,"touchend"),F:(a,b,c,d)=>hd(a,b,c,d,24,"touchmove"),H:(a,b,c,d)=>hd(a,b,c,d,22,"touchstart"),y:(a,b,c)=>rd(a,b,c),K:(a,b,c,d)=>(a=T(a))?"undefined"!=
typeof a.onwheel?sd(a,b,c,d):-1:-4,ta:a=>document.title=a?C(r,a):"",q:()=>{throw"Please compile your program with async support in order to use asynchronous operations like emscripten_sleep";},Xa:(a,b)=>{var c=0;vd().forEach((d,e)=>{var f=b+c;e=v[a+4*e>>2]=f;for(f=0;f<d.length;++f)q[e++]=d.charCodeAt(f);q[e]=0;c+=d.length+1});return 0},Ya:(a,b)=>{var c=vd();v[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);v[b>>2]=d;return 0},Y:()=>52,cb:()=>52,Wa:function(){return 70},Z:(a,b,c,d)=>{for(var e=
0,f=0;f<c;f++){var g=v[b>>2],m=v[b+4>>2];b+=8;for(var n=0;n<m;n++){var t=r[g+n],B=wd[a];0===t||10===t?((1===a?ea:l)(C(B)),B.length=0):B.push(t)}e+=m}v[d>>2]=e;return 0},aa:lc,a:mc,Sa:nc,b:oc,u:pc,n:qc,ba:rc,Fd:sc,w:tc,ua:uc,_a:vc,p:xc,t:yc,i:zc,c:Ac,v:Cc,va:Ec,R:Fc,l:Lc,kd:Oc,ca:Qc,f:Rc,h:Tc,Hc:Uc,j:Vc,cc:Wc},Y;
(async function(){function a(c){Y=c.exports;ha=Y._d;c=ha.buffer;h.HEAP8=q=new Int8Array(c);h.HEAP16=ja=new Int16Array(c);h.HEAPU8=r=new Uint8Array(c);h.HEAPU16=ka=new Uint16Array(c);h.HEAP32=u=new Int32Array(c);h.HEAPU32=v=new Uint32Array(c);h.HEAPF32=w=new Float32Array(c);h.HEAPF64=x=new Float64Array(c);h.HEAP64=la=new BigInt64Array(c);h.HEAPU64=new BigUint64Array(c);dc=Y.ce;y--;h.monitorRunDependencies?.(y);0==y&&ma&&(c=ma,ma=null,c());return Y}y++;h.monitorRunDependencies?.(y);var b={a:Ad};if(h.instantiateWasm)return new Promise(c=>
{h.instantiateWasm(b,(d,e)=>{a(d,e);c(d.exports)})});oa??=h.locateFile?h.locateFile("index.wasm",k):k+"index.wasm";return a((await ra(b)).instance)})();var z=a=>(z=Y.ae)(a),Bd=h._main=(a,b)=>(Bd=h._main=Y.be)(a,b),Zb=a=>(Zb=Y.de)(a),Wb=a=>(Wb=Y.ee)(a),Yb=()=>(Yb=Y.fe)();function Cd(a=[]){var b=Bd;a.unshift(ca);var c=a.length,d=Wb(4*(c+1)),e=d;a.forEach(g=>{v[e>>2]=Xb(g);e+=4});v[e>>2]=0;try{var f=b(c,d);Ha(f)}catch(g){Fa(g)}}
function Dd(a=ba){function b(){h.calledRun=!0;if(!p){Y.$d();h.onRuntimeInitialized?.();h.noInitialRun||Cd(a);if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var c=h.postRun.shift();ya.unshift(c)}xa(ya)}}if(0<y)ma=Dd;else{if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Aa();xa(za);0<y?ma=Dd:h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),1);b()},1)):b()}}
if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();Dd();
