var h;h||=typeof Module != 'undefined' ? Module : {};var aa=[],ba="./this.program",k="",ca;"undefined"!=typeof document&&document.currentScript&&(k=document.currentScript.src);k=k.startsWith("blob:")?"":k.slice(0,k.replace(/[?#].*/,"").lastIndexOf("/")+1);ca=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};
var da=console.log.bind(console),m=console.error.bind(console),ea,fa,p=!1,ha,q,r,ia,ja,u,v,w,ka,x,y=0,la=null;function ma(a){h.onAbort?.(a);a="Aborted("+a+")";m(a);p=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var na;async function oa(a){if(!ea)try{var b=await ca(a);return new Uint8Array(b)}catch{}if(a==na&&ea)a=new Uint8Array(ea);else throw"both async and sync fetching of the wasm failed";return a}
async function pa(a,b){try{var c=await oa(a);return await WebAssembly.instantiate(c,b)}catch(d){m(`failed to asynchronously prepare wasm: ${d}`),ma(d)}}async function qa(a){var b=na;if(!ea&&"function"==typeof WebAssembly.instantiateStreaming)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){m(`wasm streaming compile failed: ${d}`),m("falling back to ArrayBuffer instantiation")}return pa(b,a)}
class ra{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var sa=a=>{for(;0<a.length;)a.shift()(h)},ta=[],ua=[],va=()=>{var a=h.preRun.shift();ua.push(a)},wa=!0;
function xa(a,b){var c="float";c.endsWith("*")&&(c="*");switch(c){case "i1":q[a]=b;break;case "i8":q[a]=b;break;case "i16":ia[a>>1]=b;break;case "i32":u[a>>2]=b;break;case "i64":ka[a>>3]=BigInt(b);break;case "float":w[a>>2]=b;break;case "double":x[a>>3]=b;break;case "*":v[a>>2]=b;break;default:ma(`invalid type for setValue: ${c}`)}}
var ya="undefined"!=typeof TextDecoder?new TextDecoder:void 0,z=(a,b=0,c=NaN)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&ya)return ya.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
za=[0,31,60,91,121,152,182,213,244,274,305,335],Aa=[0,31,59,90,120,151,181,212,243,273,304,334],A=(a,b,c)=>{var d=r;if(!(0<c))return 0;var e=b;c=b+c-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var l=a.charCodeAt(++f);g=65536+((g&1023)<<10)|l&1023}if(127>=g){if(b>=c)break;d[b++]=g}else{if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6}else{if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63}d[b++]=128|g>>6&63}d[b++]=128|g&
63}}d[b]=0;return b-e},Ba=a=>{if(!(a instanceof ra||"unwind"==a))throw a;},Ca=a=>{ha=a;wa||(h.onExit?.(a),p=!0);throw new ra(a);},Da=a=>{ha=a;Ca(a)},Ea=()=>{if(!wa)try{var a=ha;ha=a;Ca(a)}catch(b){Ba(b)}},Fa=!1,Ga=!1,Ha=[];
function Ia(){function a(){var c=h.canvas;Ga=document.pointerLockElement===c||document.mozPointerLockElement===c||document.webkitPointerLockElement===c||document.msPointerLockElement===c}if(!Ja){Ja=!0;var b=h.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),b.exitPointerLock=
b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",c=>{!Ga&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}var Ka=!1,La=void 0,C=void 0;
function Ma(){if(!Fa)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var Na=[];function Oa(){var a=h.canvas;Na.forEach(b=>b(a.width,a.height))}
function Pa(a,b,c){b&&c?(a.wf=b,a.pf=c):(b=a.wf,c=a.pf);var d=b,e=c;0<h.forcedAspectRatio&&(d/e<h.forcedAspectRatio?d=Math.round(e*h.forcedAspectRatio):e=Math.round(d/h.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*f)}C?(a.width!=d&&(a.width=
d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var Ja,D=12288,Qa=!1,Ra=0,Sa=0,Ta=0,E={alpha:!1,depth:!1,stencil:!1,antialias:!1},Ua={},Va,F,Wa=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,f)=>b.drawArraysInstancedANGLE(c,d,e,f),a.drawElementsInstanced=(c,d,e,f,g)=>b.drawElementsInstancedANGLE(c,d,e,f,g))},Xa=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),
a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},Ya=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},Za=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},$a=1,ab=[],G=[],bb=[],H=[],J=[],K=[],cb=[],M=[],N=[],db={},eb=4,fb=0,gb=a=>{for(var b=$a++,c=a.length;c<b;c++)a[c]=null;return b},hb=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=F[c](),g=f&&gb(d);f?(f.name=g,d[g]=f):O||=1282;u[b+4*e>>2]=g}},jb=(a,b)=>{a.re||(a.re=a.getContext,a.getContext=function(d,e){e=a.re(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?ib(c,b):0},ib=(a,b)=>{var c=
gb(M),d={handle:c,attributes:b,version:b.Ye,me:a};a.canvas&&(a.canvas.qe=d);M[c]=d;("undefined"==typeof b.kf||b.kf)&&kb(d);return c},mb=a=>{lb=M[a];h.ctx=F=lb?.me},kb=a=>{a||=lb;if(!a.rf){a.rf=!0;var b=a.me;b.If=b.getExtension("WEBGL_multi_draw");b.mf=b.getExtension("EXT_polygon_offset_clamp");b.lf=b.getExtension("EXT_clip_control");b.vf=b.getExtension("WEBGL_polygon_mode");Wa(b);Xa(b);Ya(b);b.le=b.getExtension("EXT_disjoint_timer_query");Za(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||
b.getExtension(c)})}},nb={},O,lb,ob=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Q=a=>{var b=ob(a)+1,c=P(b);c&&A(a,c,b);return c},Eb=(a,b,c,d,e)=>{function f(){return g<pb?(Ea(),!1):!0}qb=a;rb=d;var g=pb;sb=!1;tb=function(){if(!p)if(0<ub.length){var l=ub.shift();l.Ef(l.xf);if(vb){var n=vb,t=0==n%1?n-1:Math.floor(n);vb=l.Af?t:(8*n+(t+.5))/9}h.setStatus&&(l=h.statusMessage||"Please wait...",n=vb??0,t=wb.Df??0,n?n<t?h.setStatus("{message} ({expected - remaining}/{expected})"):
h.setStatus(l):h.setStatus(""));f()&&setTimeout(tb,0)}else if(f())if(xb=xb+1|0,1==yb&&1<zb&&0!=xb%zb)R();else{0==yb&&(Ab=performance.now());a:if(!p){for(l of Bb)if(!1===l())break a;if(!p)try{a(),Ea()}catch(B){Ba(B)}for(n of Cb)n()}f()&&R()}};e||(0<b?Db(0,1E3/b):Db(1,1),R());if(c)throw"unwind";},sb=!1,R=null,pb=0,qb=null,rb=0,yb=0,zb=0,xb=0,ub=[],Bb=[],Cb=[],Fb=0;
function Gb(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Fb)Fb=b+1E3/60;else for(;b+2>=Fb;)Fb+=1E3/60;setTimeout(a,Math.max(Fb-b,0))}}
var wb={},tb,vb,Ab,Hb,Db=(a,b)=>{yb=a;zb=b;if(qb)if(sb||=!0,0==a)R=function(){setTimeout(tb,Math.max(0,Ab+b-performance.now())|0)};else if(1==a)R=function(){Gb(tb)};else if(2==a){if("undefined"==typeof Hb)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Hb=d=>{c.push(d);postMessage("setimmediate","*")}}else Hb=setImmediate;R=function(){Hb(tb)}}},Ib=[],Jb=(a,b)=>{Ib.length=0;
for(var c;c=r[a++];){var d=105!=c;d&=112!=c;b+=d&&b%8?4:0;Ib.push(112==c?v[b>>2]:106==c?ka[b>>3]:105==c?u[b>>2]:x[b>>3]);b+=d?8:4}return Ib};function Kb(a){var b=S.he[a];b.target.removeEventListener(b.ee,b.Ve,b.fe);S.he.splice(a,1)}function Lb(a,b,c){function d(f,g){if(f.length!=g.length)return!1;for(var l in f)if(f[l]!=g[l])return!1;return!0}for(var e of S.ne)if(e.Me==a&&d(e.Se,c))return;S.ne.push({Me:a,$e:b,Se:c});S.ne.sort((f,g)=>f.$e<g.$e)}function Mb(a){S.ne=S.ne.filter(b=>b.Me!=a)}
function Nb(){return navigator.userActivation?navigator.userActivation.isActive:S.He&&S.df.te}function Ob(){if(Nb()){var a=S.ne;S.ne=[];for(var b of a)b.Me(...b.Se)}}function T(a){if(!a.target)return-4;if(a.ge)a.Ve=function(c){++S.He;S.df=a;Ob();a.ie(c);Ob();--S.He},a.target.addEventListener(a.ee,a.Ve,a.fe),S.he.push(a);else for(var b=0;b<S.he.length;++b)S.he[b].target==a.target&&S.he[b].ee==a.ee&&Kb(b--);return 0}
function Pb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var S={yf:0,Ge:0,Ie:0,Be:0,Re:0,Oe:0,Ee:0,Cf:0,Jf:0,Bf:0,Fe:0,Ke:0,Qe:0,Ne:0,Gf(a,b,c){q.set(q.subarray(b,b+c),a)},Kf(){for(;S.he.length;)Kb(S.he.length-1);S.ne=[]},He:0,ne:[],he:[],tf:(a,b)=>{for(var c=0;c<S.he.length;++c)S.he[c].target!=a||b&&b!=S.he[c].ee||Kb(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},Qb=[0,document,window],U=a=>{a=2<a?a?z(r,a):"":a;return Qb[a]||document.querySelector(a)},Sb=a=>{var b=ob(a)+1,c=Rb(b);A(a,c,b);return c},Vb=a=>
{var b=Tb(),c=Rb(8),d=c+4;a=Sb(a.id);if(a=U(a))u[c>>2]=a.width,u[d>>2]=a.height;c=[u[c>>2],u[d>>2]];Ub(b);return c},Wb=(a,b,c)=>{a=U(a);if(!a)return-4;a.width=b;a.height=c;return 0},Xb=(a,b,c)=>{if(a.zf){var d=Tb();a=Sb(a.id);Wb(a,b,c);Ub(d)}else a.width=b,a.height=c},Yb={},Zb=[],$b,V=a=>{var b=Zb[a];b||(Zb[a]=b=$b.get(a));return b},ac=a=>{function b(){document.fullscreenElement||document.webkitFullscreenElement||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",
b),Xb(a,d,e),a.style.width=f,a.style.height=g,a.style.backgroundColor=l,n||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=n,a.style.paddingLeft=t,a.style.paddingRight=B,a.style.paddingTop=L,a.style.paddingBottom=I,a.style.marginLeft=gd,a.style.marginRight=hd,a.style.marginTop=jd,a.style.marginBottom=kd,document.body.style.margin=ld,document.documentElement.style.overflow=md,document.body.scroll=nd,a.style.oe=od,a.qe&&a.qe.me.viewport(0,0,d,e),Yb.ue&&V(Yb.ue)(37,
0,Yb.Te))}var c=Vb(a),d=c[0],e=c[1],f=a.style.width,g=a.style.height,l=a.style.backgroundColor,n=document.body.style.backgroundColor,t=a.style.paddingLeft,B=a.style.paddingRight,L=a.style.paddingTop,I=a.style.paddingBottom,gd=a.style.marginLeft,hd=a.style.marginRight,jd=a.style.marginTop,kd=a.style.marginBottom,ld=document.body.style.margin,md=document.documentElement.style.overflow,nd=document.body.scroll,od=a.style.oe;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",
b)},bc=(a,b,c)=>{a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"},cc=a=>0>Qb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},dc=(a,b)=>{if(0!=b.Le||0!=b.Ce){ac(a);var c=b.uf?innerWidth:screen.width,d=b.uf?innerHeight:screen.height,e=cc(a),f=e.width;e=e.height;var g=Vb(a),l=g[0];g=g[1];3==b.Le?(bc(a,(d-e)/2,(c-f)/2),c=f,d=e):2==b.Le&&(c*g<l*d?(f=g*c/l,bc(a,(d-f)/2,0),d=f):(f=l*d/g,bc(a,0,(c-f)/2),c=f));var n;(n=a.style).backgroundColor||(n.backgroundColor=
"black");let t;(t=document.body.style).backgroundColor||(t.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.nf&&(a.style.oe="optimizeSpeed",a.style.oe="-moz-crisp-edges",a.style.oe="-o-crisp-edges",a.style.oe="-webkit-optimize-contrast",a.style.oe="optimize-contrast",a.style.oe="crisp-edges",a.style.oe="pixelated");n=2==b.Ce?devicePixelRatio:1;0!=b.Ce&&(c=c*n|0,d=d*n|0,Xb(a,c,d),a.qe&&a.qe.me.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);
else return S.fullscreenEnabled()?-3:-1;Yb=b;b.ue&&V(b.ue)(37,0,b.Te);return 0},ec=a=>{if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?-3:-1;return 0},fc=(a,b)=>{x[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)x[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)x[a+8*c+528>>3]="object"==typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)q[a+c+1040]="object"==typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];
q[a+1104]=b.connected;u[a+1108>>2]=b.index;u[a+8>>2]=b.axes.length;u[a+12>>2]=b.buttons.length;A(b.id,a+1112,64);A(b.mapping,a+1176,64)},gc=a=>{var b=document.pointerLockElement||document.re||document.We||document.Ue;q[a]=!!b;var c=b?.id||"";A(Pb(b),a+1,128);A(c,a+129,128)},hc=(a,b)=>{F.attachShader(G[a],K[b])},ic=(a,b)=>{F.bindBuffer(a,ab[b])},jc=(a,b)=>F.blendFunc(a,b),kc=(a,b,c,d)=>{F.bufferData(a,c?r.subarray(c,c+b):b,d)},lc=a=>F.clear(a),mc=(a,b,c,d)=>F.clearColor(a,b,c,d),nc=a=>{F.compileShader(K[a])},
oc=()=>{var a=gb(G),b=F.createProgram();b.name=a;b.Ae=b.ye=b.ze=0;b.Pe=1;G[a]=b;return a},pc=a=>{var b=gb(K);K[b]=F.createShader(a);return b},qc=a=>{if(a){var b=G[a];b?(F.deleteProgram(b),b.name=0,G[a]=null):O||=1281}},rc=a=>F.disable(a),sc=[],tc=(a,b,c,d)=>{F.drawElements(a,b,c,d)},uc=a=>F.enable(a),vc=a=>{F.enableVertexAttribArray(a)},wc=(a,b)=>{hb(a,b,"createBuffer",ab)},xc=(a,b,c,d,e,f,g,l)=>{b=G[b];if(a=F[a](b,c))d=l&&A(a.name,l,d),e&&(u[e>>2]=d),f&&(u[f>>2]=a.size),g&&(u[g>>2]=a.type)},yc=(a,
b)=>F.getAttribLocation(G[a],b?z(r,b):""),zc=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&(O||=1280);return;case 36345:d=0;break;case 34466:var e=F.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=F.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":O||=1280;return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:O||=
1280;return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:u[b+4*a>>2]=e[a];break;case 2:w[b+4*a>>2]=e[a];break;case 4:q[b+a]=e[a]?1:0}return}try{d=e.name|0}catch(f){O||=1280;m(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${f})`);return}}break;default:O||=1280;m(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${e} of type ${typeof e}!`);
return}switch(c){case 1:c=d;v[b>>2]=c;v[b+4>>2]=(c-v[b>>2])/4294967296;break;case 0:u[b>>2]=d;break;case 2:w[b>>2]=d;break;case 4:q[b]=d?1:0}}else O||=1281},Ac=(a,b,c,d)=>{a=F.getProgramInfoLog(G[a]);null===a&&(a="(unknown error)");b=0<b&&d?A(a,d,b):0;c&&(u[c>>2]=b)},Bc=(a,b,c)=>{if(c)if(a>=$a)O||=1281;else if(a=G[a],35716==b)a=F.getProgramInfoLog(a),null===a&&(a="(unknown error)"),u[c>>2]=a.length+1;else if(35719==b){if(!a.Ae){var d=F.getProgramParameter(a,35718);for(b=0;b<d;++b)a.Ae=Math.max(a.Ae,
F.getActiveUniform(a,b).name.length+1)}u[c>>2]=a.Ae}else if(35722==b){if(!a.ye)for(d=F.getProgramParameter(a,35721),b=0;b<d;++b)a.ye=Math.max(a.ye,F.getActiveAttrib(a,b).name.length+1);u[c>>2]=a.ye}else if(35381==b){if(!a.ze)for(d=F.getProgramParameter(a,35382),b=0;b<d;++b)a.ze=Math.max(a.ze,F.getActiveUniformBlockName(a,b).length+1);u[c>>2]=a.ze}else u[c>>2]=F.getProgramParameter(a,b);else O||=1281},Cc=(a,b,c)=>{if(c){a=F.le.getQueryObjectEXT(N[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;v[c>>2]=
d;v[c+4>>2]=(d-v[c>>2])/4294967296}else O||=1281},Dc=(a,b,c)=>{if(c){a=F.le.getQueryObjectEXT(N[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;u[c>>2]=d}else O||=1281},Ec=()=>{var a=Za(F);return a=a.concat(a.map(b=>"GL_"+b))},Fc=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Gc=a=>{var b=a.se,c=a.bf,d;if(!b){a.se=b={};a.af={};var e=F.getProgramParameter(a,35718);for(d=0;d<e;++d){var f=F.getActiveUniform(a,d);var g=f.name;f=f.size;var l=Fc(g);l=0<l?g.slice(0,l):g;var n=a.Pe;a.Pe+=f;c[l]=[f,n];for(g=0;g<f;++g)b[n]=
g,a.af[n++]=l}}},Hc=(a,b)=>{b=b?z(r,b):"";if(a=G[a]){Gc(a);var c=a.se,d=0,e=b,f=Fc(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.bf[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||F.getUniformLocation(a,b)))return d}else O||=1281;return-1},W=a=>{var b=F.ef;if(b){var c=b.se[a];"number"==typeof c&&(b.se[a]=c=F.getUniformLocation(b,b.af[a]+(0<c?`[${c}]`:"")));return c}O||=1282},Ic=(a,b,c,d)=>{if(c)if(a=G[a],Gc(a),a=F.getUniform(a,W(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:u[c>>2]=
a;break;case 2:w[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:u[c+4*b>>2]=a[b];break;case 2:w[c+4*b>>2]=a[b]}else O||=1281},Jc=(a,b,c,d)=>{if(c)if(a=F.getVertexAttrib(a,b),34975==b)u[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:u[c>>2]=a;break;case 2:w[c>>2]=a;break;case 5:u[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:u[c+4*b>>2]=a[b];break;case 2:w[c+4*b>>2]=a[b];break;case 5:u[c+4*b>>2]=Math.fround(a[b])}else O||=1281},Kc=a=>{a=G[a];
F.linkProgram(a);a.se=0;a.bf={}},Lc=(a,b,c,d,e)=>{a-=5120;a=1==a?r:4==a?u:6==a?w:5==a||28922==a?v:ja;b=d*((fb||c)*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+eb-1&-eb);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},Mc=(a,b,c,d)=>{for(var e="",f=0;f<b;++f){var g=(g=v[c+4*f>>2])?z(r,g,d?v[d+4*f>>2]:void 0):"";e+=g}F.shaderSource(K[a],e)},Nc=(a,b)=>{F.uniform1f(W(a),b)},X=[],Oc=[],Pc=(a,b,c,d)=>{if(18>=b){var e=X[16*b],f=w;d>>=2;
b*=16;for(var g=0;g<b;g+=16){var l=d+g;e[g]=f[l];e[g+1]=f[l+1];e[g+2]=f[l+2];e[g+3]=f[l+3];e[g+4]=f[l+4];e[g+5]=f[l+5];e[g+6]=f[l+6];e[g+7]=f[l+7];e[g+8]=f[l+8];e[g+9]=f[l+9];e[g+10]=f[l+10];e[g+11]=f[l+11];e[g+12]=f[l+12];e[g+13]=f[l+13];e[g+14]=f[l+14];e[g+15]=f[l+15]}}else e=w.subarray(d>>2,d+64*b>>2);F.uniformMatrix4fv(W(a),!!c,e)},Qc=a=>{a=G[a];F.useProgram(a);F.ef=a},Rc=(a,b,c,d,e,f)=>{F.vertexAttribPointer(a,b,c,!!d,e,f)},Sc=(a,b,c,d)=>F.viewport(a,b,c,d),Tc=(a,b)=>{if(!S.fullscreenEnabled())return-1;
a=U(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?Nb()?dc(a,b):b.jf?(Lb(dc,1,[a,b]),1):-2:-3:-4},Uc=()=>{try{if(navigator.getGamepads)return(S.xe=navigator.getGamepads())?0:-1}catch(a){navigator.getGamepads=null}return-1},Vc=(a,b)=>{var c={target:U(2),ee:"beforeunload",ge:b,ie:(d=event)=>{var e=V(b)(28,0,a);e&&=e?z(r,e):"";if(e)return d.preventDefault(),d.returnValue=e},fe:!0};return T(c)},Wc=(a,b,c,d,e,f)=>{S.Ee||(S.Ee=P(256));a={target:U(a),ee:f,ge:d,ie:(g=event)=>{var l=g.target.id?
g.target.id:"",n=S.Ee;A(Pb(g.target),n+0,128);A(l,n+128,128);V(d)(e,n,b)&&g.preventDefault()},fe:c};return T(a)},Xc=(a,b,c,d,e)=>{S.Fe||(S.Fe=P(276));return T({target:a,ee:e,ge:d,ie:(f=event)=>{var g=S.Fe,l=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,n=!!l;q[g]=n;q[g+1]=S.fullscreenEnabled();var t=n?l:S.sf,B=t?.id||"";A(Pb(t),g+2,128);A(B,g+130,128);u[g+260>>2]=t?t.clientWidth:0;u[g+264>>2]=t?t.clientHeight:0;u[g+268>>2]=
screen.width;u[g+272>>2]=screen.height;n&&(S.sf=l);V(d)(19,g,b)&&f.preventDefault()},fe:c})},Yc=(a,b,c,d,e)=>{S.Ge||(S.Ge=P(1240));b={target:U(2),te:!0,ee:e,ge:c,ie:(f=event)=>{var g=S.Ge;fc(g,f.gamepad);V(c)(d,g,a)&&f.preventDefault()},fe:b};return T(b)},Zc=(a,b,c,d,e,f)=>{S.Ie||(S.Ie=P(160));a={target:U(a),ee:f,ge:d,ie:g=>{var l=S.Ie;x[l>>3]=g.timeStamp;var n=l>>2;u[n+2]=g.location;q[l+12]=g.ctrlKey;q[l+13]=g.shiftKey;q[l+14]=g.altKey;q[l+15]=g.metaKey;q[l+16]=g.repeat;u[n+5]=g.charCode;u[n+6]=
g.keyCode;u[n+7]=g.which;A(g.key||"",l+32,32);A(g.code||"",l+64,32);A(g.char||"",l+96,32);A(g.locale||"",l+128,32);V(d)(e,l,b)&&g.preventDefault()},fe:c};return T(a)},$c=(a,b,c)=>{x[a>>3]=b.timeStamp;var d=a>>2;u[d+2]=b.screenX;u[d+3]=b.screenY;u[d+4]=b.clientX;u[d+5]=b.clientY;q[a+24]=b.ctrlKey;q[a+25]=b.shiftKey;q[a+26]=b.altKey;q[a+27]=b.metaKey;ia[2*d+14]=b.button;ia[2*d+15]=b.buttons;u[d+8]=b.movementX;u[d+9]=b.movementY;a=cc(c);u[d+10]=b.clientX-(a.left|0);u[d+11]=b.clientY-(a.top|0)},ad=(a,
b,c,d,e,f)=>{S.Be||(S.Be=P(64));a=U(a);return T({target:a,te:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,ee:f,ge:d,ie:(g=event)=>{$c(S.Be,g,a);V(d)(e,S.Be,b)&&g.preventDefault()},fe:c})},bd=(a,b,c,d,e)=>{S.Ke||(S.Ke=P(257));return T({target:a,ee:e,ge:d,ie:(f=event)=>{var g=S.Ke;gc(g);V(d)(20,g,b)&&f.preventDefault()},fe:c})},cd=(a,b,c,d)=>{S.Oe||(S.Oe=P(36));a=U(a);return T({target:a,ee:"resize",ge:d,ie:(e=event)=>{if(e.target==a){var f=document.body;if(f){var g=S.Oe;u[g>>2]=0;u[g+4>>2]=f.clientWidth;
u[g+8>>2]=f.clientHeight;u[g+12>>2]=innerWidth;u[g+16>>2]=innerHeight;u[g+20>>2]=outerWidth;u[g+24>>2]=outerHeight;u[g+28>>2]=pageXOffset|0;u[g+32>>2]=pageYOffset|0;V(d)(10,g,b)&&e.preventDefault()}}},fe:c})},dd=(a,b,c,d,e,f)=>{S.Ne||(S.Ne=P(1552));a=U(a);return T({target:a,te:"touchstart"==f||"touchend"==f,ee:f,ge:d,ie:g=>{var l={},n=g.touches;for(var t of n)t.Xe=t.Ze=0,l[t.identifier]=t;for(var B of g.changedTouches)B.Xe=1,l[B.identifier]=B;for(var L of g.targetTouches)l[L.identifier].Ze=1;n=S.Ne;
x[n>>3]=g.timeStamp;q[n+12]=g.ctrlKey;q[n+13]=g.shiftKey;q[n+14]=g.altKey;q[n+15]=g.metaKey;t=n+16;B=cc(a);L=0;for(let I of Object.values(l))if(l=t>>2,u[l]=I.identifier,u[l+1]=I.screenX,u[l+2]=I.screenY,u[l+3]=I.clientX,u[l+4]=I.clientY,u[l+5]=I.pageX,u[l+6]=I.pageY,q[t+28]=I.Xe,q[t+29]=I.Ze,u[l+8]=I.clientX-(B.left|0),u[l+9]=I.clientY-(B.top|0),t+=48,31<++L)break;u[n+8>>2]=L;V(d)(e,n,b)&&g.preventDefault()},fe:c})},ed=(a,b,c)=>{var d=Qb[1];S.Qe||(S.Qe=P(8));return T({target:d,ee:"visibilitychange",
ge:c,ie:(e=event)=>{var f=S.Qe,g=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);q[f]=document.hidden;u[f+4>>2]=g;V(c)(21,f,a)&&e.preventDefault()},fe:b})},fd=(a,b,c,d)=>{S.Re||(S.Re=P(96));return T({target:a,te:!0,ee:"wheel",ge:d,ie:(e=event)=>{var f=S.Re;$c(f,e,a);x[f+64>>3]=e.deltaX;x[f+72>>3]=e.deltaY;x[f+80>>3]=e.deltaZ;u[f+88>>2]=e.deltaMode;V(d)(9,f,b)&&e.preventDefault()},fe:c})},pd={},rd=()=>{if(!qd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",
HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ba||"./this.program"},b;for(b in pd)void 0===pd[b]?delete a[b]:a[b]=pd[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);qd=c}return qd},qd,sd=[null,[],[]],td=(a,b,c)=>{a.addEventListener(b,c,{once:!0})},ud=a=>{var b;b||=[document,document.getElementById("canvas")];["keydown","mousedown","touchstart"].forEach(c=>{b.forEach(d=>{d&&td(d,c,()=>{"suspended"===a.state&&a.resume()})})})},
vd=(a,b=[])=>{V(a)(...b)};
h.requestFullscreen=function(a,b){function c(){Fa=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=Ma,La&&d.requestPointerLock(),Fa=!0,C?("undefined"!=typeof SDL&&(u[SDL.screen>>2]=v[SDL.screen>>2]|8388608),Pa(h.canvas),Oa()):Pa(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),C?("undefined"!=typeof SDL&&(u[SDL.screen>>2]=v[SDL.screen>>
2]&-8388609),Pa(h.canvas),Oa()):Pa(d));h.onFullScreen?.(Fa);h.onFullscreen?.(Fa)}La=a;C=b;"undefined"==typeof La&&(La=!0);"undefined"==typeof C&&(C=!1);var d=h.canvas;Ka||(Ka=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=e.requestFullscreen||
e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()};h.setCanvasSize=function(a,b,c){Pa(h.canvas,a,b);c||Oa()};h.getUserMedia=function(a){let b;(b=window).getUserMedia||(b.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)};
h.createContext=function(a,b,c,d){if(b&&h.ctx&&a==h.canvas)return h.ctx;var e;if(b){var f={antialias:!1,alpha:!1,Ye:1};if(d)for(var g in d)f[g]=d[g];if("undefined"!=typeof nb&&(e=jb(a,f)))var l=M[e].me}else l=a.getContext("2d");if(!l)return null;c&&(h.ctx=l,b&&mb(e),Ha.forEach(n=>n()),Ia());return l};h.requestAnimationFrame=Gb;h.pauseMainLoop=function(){R=null;pb++};h.resumeMainLoop=function(){pb++;var a=yb,b=zb,c=qb;qb=null;Eb(c,0,!1,rb,!0);Db(a,b);R()};h.preMainLoop&&Bb.push(h.preMainLoop);
h.postMainLoop&&Cb.push(h.postMainLoop);for(let a=0;32>a;++a)sc.push(Array(a));for(var wd=new Float32Array(288),Y=0;288>=Y;++Y)X[Y]=wd.subarray(0,Y);var xd=new Int32Array(288);for(Y=0;288>=Y;++Y)Oc[Y]=xd.subarray(0,Y);h.noExitRuntime&&(wa=h.noExitRuntime);h.print&&(da=h.print);h.printErr&&(m=h.printErr);h.wasmBinary&&(ea=h.wasmBinary);h.arguments&&(aa=h.arguments);h.thisProgram&&(ba=h.thisProgram);
var yd={20592061:()=>"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?!0:!1,20592208:()=>"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?!0:!1,20592442:a=>{"undefined"===typeof h.SDL2&&(h.SDL2={});var b=h.SDL2;a?b.capture={}:b.audio={};b.de||("undefined"!==typeof AudioContext?b.de=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.de=new webkitAudioContext),
b.de&&"undefined"===typeof navigator.userActivation&&ud(b.de));return void 0===b.de?-1:0},20592994:()=>h.SDL2.de.sampleRate,20593062:(a,b,c,d)=>{function e(){}function f(l){void 0!==g.capture.ke&&(clearInterval(g.capture.ke),g.capture.ke=void 0,g.capture.pe=void 0);g.capture.Je=g.de.createMediaStreamSource(l);g.capture.je=g.de.createScriptProcessor(b,a,1);g.capture.je.onaudioprocess=function(n){void 0!==g&&void 0!==g.capture&&(n.outputBuffer.getChannelData(0).fill(0),g.capture.De=n.inputBuffer,vd(c,
[d]))};g.capture.Je.connect(g.capture.je);g.capture.je.connect(g.de.destination);g.capture.stream=l}var g=h.SDL2;g.capture.pe=g.de.createBuffer(a,b,g.de.sampleRate);g.capture.pe.getChannelData(0).fill(0);g.capture.ke=setInterval(function(){g.capture.De=g.capture.pe;vd(c,[d])},b/g.de.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(f).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,
video:!1},f,e)},20594755:(a,b,c,d)=>{var e=h.SDL2;e.audio.je=e.de.createScriptProcessor(b,0,a);e.audio.je.onaudioprocess=function(f){void 0!==e&&void 0!==e.audio&&(void 0!==e.audio.ke&&(clearInterval(e.audio.ke),e.audio.ke=void 0,e.audio.pe=void 0),e.audio.we=f.outputBuffer,vd(c,[d]))};e.audio.je.connect(e.de.destination);"suspended"===e.de.state&&(e.audio.pe=e.de.createBuffer(a,b,e.de.sampleRate),e.audio.pe.getChannelData(0).fill(0),e.audio.ke=setInterval(function(){"undefined"!==typeof navigator.userActivation&&
navigator.userActivation.hasBeenActive&&e.de.resume();e.audio.we=e.audio.pe;vd(c,[d]);e.audio.we=void 0},b/e.de.sampleRate*1E3))},20595930:(a,b)=>{for(var c=h.SDL2,d=c.capture.De.numberOfChannels,e=0;e<d;++e){var f=c.capture.De.getChannelData(e);if(f.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";if(1==d)for(var g=0;g<b;++g)xa(a+4*g,f[g]);else for(g=0;g<b;++g)xa(a+4*(g*d+e),f[g])}},20596535:(a,b)=>{var c=h.SDL2;a>>>=2;for(var d=
c.audio.we.numberOfChannels,e=0;e<d;++e){var f=c.audio.we.getChannelData(e);if(f.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";for(var g=0;g<b;++g)f[g]=w[a+(g*d+e)]}},20597024:a=>{var b=h.SDL2;if(a){void 0!==b.capture.ke&&clearInterval(b.capture.ke);if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c])}void 0!==b.capture.je&&(b.capture.je.onaudioprocess=
function(){},b.capture.je.disconnect());void 0!==b.capture.Je&&b.capture.Je.disconnect();b.capture=void 0}else void 0!=b.audio.je&&b.audio.je.disconnect(),void 0!==b.audio.ke&&clearInterval(b.audio.ke),b.audio=void 0;void 0!==b.de&&void 0===b.audio&&void 0===b.capture&&(b.de.close(),b.de=void 0)},20598030:(a,b,c)=>{h.SDL2||(h.SDL2={});var d=h.SDL2;d.cf!==h.canvas&&(d.ve=h.createContext(h.canvas,!1,!0),d.cf=h.canvas);if(d.w!==a||d.h!==b||d.qf!==d.ve)d.image=d.ve.createImageData(a,b),d.w=a,d.h=b,d.qf=
d.ve;a=d.image.data;b=c/4;var e=0;if("undefined"!==typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var f=u[b];a[e]=f&255;a[e+1]=f>>8&255;a[e+2]=f>>16&255;a[e+3]=255;b++;e+=4}else if(d.gf!==a&&(d.ff=new Int32Array(a.buffer),d.hf=new Uint8Array(a.buffer),d.gf=a),a=d.ff,c=a.length,a.set(u.subarray(b,b+c)),a=d.hf,b=3,e=b+4*c,0==c%8)for(;b<e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|
0;else for(;b<e;)a[b]=255,b=b+4|0;d.ve.putImageData(d.image,0,0)},20599498:(a,b,c,d,e)=>{var f=document.createElement("canvas");f.width=a;f.height=b;var g=f.getContext("2d");a=g.createImageData(a,b);b=a.data;e/=4;var l=0,n;if("undefined"!==typeof CanvasPixelArray&&b instanceof CanvasPixelArray)for(n=b.length;l<n;){var t=u[e];b[l]=t&255;b[l+1]=t>>8&255;b[l+2]=t>>16&255;b[l+3]=t>>24&255;e++;l+=4}else b=new Int32Array(b.buffer),n=b.length,b.set(u.subarray(e,e+n));g.putImageData(a,0,0);c=0===c&&0===d?
"url("+f.toDataURL()+"), auto":"url("+f.toDataURL()+") "+c+" "+d+", auto";d=P(c.length+1);A(c,d,c.length+1);return d},20600486:a=>{h.canvas&&(h.canvas.style.cursor=a?z(r,a):"")},20600569:()=>{h.canvas&&(h.canvas.style.cursor="none")},20600638:()=>window.innerWidth,20600668:()=>window.innerHeight},zd={_:function(){return 0},ab:function(){return 0},bb:function(){},Ua:()=>{},Va:function(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);u[b>>2]=a.getSeconds();u[b+4>>2]=a.getMinutes();
u[b+8>>2]=a.getHours();u[b+12>>2]=a.getDate();u[b+16>>2]=a.getMonth();u[b+20>>2]=a.getFullYear()-1900;u[b+24>>2]=a.getDay();var c=a.getFullYear();u[b+28>>2]=(0!==c%4||0===c%100&&0!==c%400?Aa:za)[a.getMonth()]+a.getDate()-1|0;u[b+36>>2]=-(60*a.getTimezoneOffset());c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();u[b+32>>2]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0},Wa:(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();
e=(new Date(e,6,1)).getTimezoneOffset();v[a>>2]=60*Math.max(f,e);u[b>>2]=Number(f!=e);b=g=>{var l=Math.abs(g);return`UTC${0<=g?"-":"+"}${String(Math.floor(l/60)).padStart(2,"0")}${String(l%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(A(a,c,17),A(b,d,17)):(A(a,d,17),A(b,c,17))},Ja:a=>{if(12448==a)return D=12288,1;D=12300;return 0},Ma:(a,b,c,d,e)=>{if(62E3!=a)D=12296,c=0;else{if(b)for(;;){a=u[b>>2];if(12321==a)E.alpha=0<u[b+4>>2];else if(12325==a)E.depth=0<u[b+4>>2];else if(12326==a)E.stencil=0<u[b+4>>
2];else if(12337==a)a=u[b+4>>2],E.antialias=0<a;else if(12338==a)a=u[b+4>>2],E.antialias=1==a;else if(12544==a)E.Ff=12547!=u[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(u[e>>2]=1),c&&0<d&&(v[c>>2]=62002),D=12288,c=1):(D=12300,c=0)}return c},Aa:(a,b,c,d)=>{if(62E3!=a)return D=12296,0;for(a=1;;){b=u[d>>2];if(12440==b)a=u[d+4>>2];else if(12344==b)break;else return D=12292,0;d+=8}if(2!=a)return D=12293,0;E.Ye=a-1;E.Hf=0;Va=jb(h.canvas,E);if(0!=Va)return D=12288,mb(Va),Ha.forEach(e=>e()),mb(null),
62004;D=12297;return 0},Ca:(a,b)=>{if(62E3!=a)return D=12296,0;if(62002!=b)return D=12293,0;D=12288;return 62006},Ba:(a,b)=>{if(62E3!=a)return D=12296,0;if(62004!=b)return D=12294,0;a=Va;lb===M[a]&&(lb=null);"object"==typeof S&&S.tf(M[a].me.canvas);M[a]?.me.canvas&&(M[a].me.canvas.qe=void 0);M[a]=null;D=12288;Ra==b&&(Ra=0);return 1},Da:(a,b)=>{if(62E3!=a)return D=12296,0;if(62006!=b)return D=12301,1;Sa==b&&(Sa=0);Ta==b&&(Ta=0);D=12288;return 1},Na:(a,b,c,d)=>{if(62E3!=a)return D=12296,0;if(62002!=
b)return D=12293,0;if(!d)return D=12300,0;D=12288;switch(c){case 12320:return u[d>>2]=E.alpha?32:24,1;case 12321:return u[d>>2]=E.alpha?8:0,1;case 12322:return u[d>>2]=8,1;case 12323:return u[d>>2]=8,1;case 12324:return u[d>>2]=8,1;case 12325:return u[d>>2]=E.depth?24:0,1;case 12326:return u[d>>2]=E.stencil?8:0,1;case 12327:return u[d>>2]=12344,1;case 12328:return u[d>>2]=62002,1;case 12329:return u[d>>2]=0,1;case 12330:return u[d>>2]=4096,1;case 12331:return u[d>>2]=16777216,1;case 12332:return u[d>>
2]=4096,1;case 12333:return u[d>>2]=0,1;case 12334:return u[d>>2]=0,1;case 12335:return u[d>>2]=12344,1;case 12337:return u[d>>2]=E.antialias?4:0,1;case 12338:return u[d>>2]=E.antialias?1:0,1;case 12339:return u[d>>2]=4,1;case 12340:return u[d>>2]=12344,1;case 12341:case 12342:case 12343:return u[d>>2]=-1,1;case 12345:case 12346:return u[d>>2]=0,1;case 12347:return u[d>>2]=0,1;case 12348:return u[d>>2]=1;case 12349:case 12350:return u[d>>2]=0,1;case 12351:return u[d>>2]=12430,1;case 12352:return u[d>>
2]=4,1;case 12354:return u[d>>2]=0,1;default:return D=12292,0}},S:a=>{D=12288;return 0!=a&&1!=a?0:62E3},za:()=>D,Ka:(a,b,c)=>{if(62E3!=a)return D=12296,0;b&&(u[b>>2]=1);c&&(u[c>>2]=4);Qa=!0;D=12288;return 1},Ea:(a,b,c,d)=>{if(62E3!=a)return D=12296,0;if(0!=d&&62004!=d)return D=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return D=12301,0;mb(d?Va:null);Ra=d;Ta=b;Sa=c;D=12288;return 1},ya:(a,b)=>{if(62E3!=a)return D=12296,0;D=12288;if(Ua[b])return Ua[b];switch(b){case 12371:a=Q("Emscripten");break;case 12372:a=
Q("1.4 Emscripten EGL");break;case 12373:a=Q("");break;case 12429:a=Q("OpenGL_ES");break;default:return D=12300,0}return Ua[b]=a},Fa:()=>{if(Qa)if(F)if(F.isContextLost())D=12302;else return D=12288,1;else D=12290;else D=12289;return 0},Ga:(a,b)=>{if(62E3!=a)return D=12296,0;0==b?Db(0,0):Db(1,b);D=12288;return 1},La:a=>{if(62E3!=a)return D=12296,0;Ta=Sa=Ra=0;Qa=!1;D=12288;return 1},Ia:()=>{D=12288;return 1},Ha:()=>{D=12288;return 1},Pa:(a,b,c)=>{b=Jb(b,c);return yd[a](...b)},e:(a,b,c)=>{b=Jb(b,c);
return yd[a](...b)},Qa:(a,b,c)=>{b=Jb(b,c);return yd[a](...b)},$:()=>Date.now(),ra:()=>{if(!S.fullscreenEnabled())return-1;Mb(dc);var a=Qb[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},wa:()=>{Mb(ec);if(document.exitPointerLock)document.exitPointerLock();else return-1;return 0},m:()=>devicePixelRatio,g:(a,b,c)=>{a=U(a);if(!a)return-4;a=cc(a);x[b>>3]=a.width;x[c>>3]=a.height;
return 0},V:(a,b)=>{if(0>a||a>=S.xe.length)return-5;if(!S.xe[a])return-7;fc(b,S.xe[a]);return 0},X:()=>performance.now(),Oa:()=>S.xe.length,Gb:a=>{a&&gc(a);return document.body&&(document.body.requestPointerLock||document.body.re||document.body.We||document.body.Ue)?0:-1},xa:(a,b)=>{u[a>>2]=screen.width;u[b>>2]=screen.height},Rd:a=>F.activeTexture(a),Qd:hc,na:(a,b)=>{F.le.beginQueryEXT(a,N[b])},Pd:(a,b,c)=>{F.bindAttribLocation(G[a],b,c?z(r,c):"")},Od:ic,Nd:(a,b)=>{F.bindFramebuffer(a,bb[b])},Md:(a,
b)=>{F.bindRenderbuffer(a,H[b])},Ld:(a,b)=>{F.bindTexture(a,J[b])},fa:a=>{F.bindVertexArray(cb[a])},Kd:(a,b,c,d)=>F.blendColor(a,b,c,d),Jd:a=>F.blendEquation(a),Id:(a,b)=>F.blendEquationSeparate(a,b),Hd:jc,Gd:(a,b,c,d)=>F.blendFuncSeparate(a,b,c,d),Fd:kc,Ed:(a,b,c,d)=>{F.bufferSubData(a,b,r.subarray(d,d+c))},Dd:a=>F.checkFramebufferStatus(a),Bd:lc,Ad:mc,zd:a=>F.clearDepth(a),yd:a=>F.clearStencil(a),db:(a,b)=>{F.lf.clipControlEXT(a,b)},xd:(a,b,c,d)=>{F.colorMask(!!a,!!b,!!c,!!d)},wd:nc,vd:(a,b,c,d,
e,f,g,l)=>{F.compressedTexImage2D(a,b,c,d,e,f,r.subarray(l,l+g))},ud:(a,b,c,d,e,f,g,l,n)=>{F.compressedTexSubImage2D(a,b,c,d,e,f,g,r.subarray(n,n+l))},td:(a,b,c,d,e,f,g,l)=>F.copyTexImage2D(a,b,c,d,e,f,g,l),sd:(a,b,c,d,e,f,g,l)=>F.copyTexSubImage2D(a,b,c,d,e,f,g,l),rd:oc,qd:pc,pd:a=>F.cullFace(a),od:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=ab[d];e&&(F.deleteBuffer(e),e.name=0,ab[d]=null)}},nd:(a,b)=>{for(var c=0;c<a;++c){var d=u[b+4*c>>2],e=bb[d];e&&(F.deleteFramebuffer(e),e.name=0,bb[d]=
null)}},md:qc,pa:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=N[d];e&&(F.le.deleteQueryEXT(e),N[d]=null)}},ld:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=H[d];e&&(F.deleteRenderbuffer(e),e.name=0,H[d]=null)}},kd:a=>{if(a){var b=K[a];b?(F.deleteShader(b),K[a]=null):O||=1281}},jd:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=J[d];e&&(F.deleteTexture(e),e.name=0,J[d]=null)}},ea:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2];F.deleteVertexArray(cb[d]);cb[d]=null}},id:a=>F.depthFunc(a),gd:a=>
{F.depthMask(!!a)},fd:(a,b)=>F.depthRange(a,b),ed:(a,b)=>{F.detachShader(G[a],K[b])},dd:rc,cd:a=>{F.disableVertexAttribArray(a)},bd:(a,b,c)=>{F.drawArrays(a,b,c)},Ud:(a,b,c,d)=>{F.drawArraysInstanced(a,b,c,d)},Vd:(a,b)=>{for(var c=sc[a],d=0;d<a;d++)c[d]=u[b+4*d>>2];F.drawBuffers(c)},ad:tc,Td:(a,b,c,d,e)=>{F.drawElementsInstanced(a,b,c,d,e)},$c:uc,_c:vc,ma:a=>{F.le.endQueryEXT(a)},Zc:()=>F.finish(),Yc:()=>F.flush(),Xc:(a,b,c,d)=>{F.framebufferRenderbuffer(a,b,c,H[d])},Wc:(a,b,c,d,e)=>{F.framebufferTexture2D(a,
b,c,J[d],e)},Vc:a=>F.frontFace(a),Uc:wc,Sc:(a,b)=>{hb(a,b,"createFramebuffer",bb)},qa:(a,b)=>{for(var c=0;c<a;c++){var d=F.le.createQueryEXT();if(!d){for(O||=1282;c<a;)u[b+4*c++>>2]=0;break}var e=gb(N);d.name=e;N[e]=d;u[b+4*c>>2]=e}},Rc:(a,b)=>{hb(a,b,"createRenderbuffer",H)},Qc:(a,b)=>{hb(a,b,"createTexture",J)},da:(a,b)=>{hb(a,b,"createVertexArray",cb)},Tc:a=>F.generateMipmap(a),Pc:(a,b,c,d,e,f,g)=>xc("getActiveAttrib",a,b,c,d,e,f,g),Oc:(a,b,c,d,e,f,g)=>xc("getActiveUniform",a,b,c,d,e,f,g),Nc:(a,
b,c,d)=>{a=F.getAttachedShaders(G[a]);var e=a.length;e>b&&(e=b);u[c>>2]=e;for(b=0;b<e;++b)u[d+4*b>>2]=K.indexOf(a[b])},Mc:yc,Lc:(a,b)=>zc(a,b,4),Kc:(a,b,c)=>{c?u[c>>2]=F.getBufferParameter(a,b):O||=1281},Jc:()=>{var a=F.getError()||O;O=0;return a},Ic:(a,b)=>zc(a,b,2),Hc:(a,b,c,d)=>{a=F.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;u[d>>2]=a},Gc:(a,b)=>zc(a,b,0),Dc:Ac,Fc:Bc,ha:Cc,ja:Dc,ga:Cc,ia:Dc,ka:(a,b,c)=>{c?u[c>>2]=F.le.getQueryEXT(a,
b):O||=1281},Cc:(a,b,c)=>{c?u[c>>2]=F.getRenderbufferParameter(a,b):O||=1281},Ac:(a,b,c,d)=>{a=F.getShaderInfoLog(K[a]);null===a&&(a="(unknown error)");b=0<b&&d?A(a,d,b):0;c&&(u[c>>2]=b)},zc:(a,b,c,d)=>{a=F.getShaderPrecisionFormat(a,b);u[c>>2]=a.rangeMin;u[c+4>>2]=a.rangeMax;u[d>>2]=a.precision},yc:(a,b,c,d)=>{if(a=F.getShaderSource(K[a]))b=0<b&&d?A(a,d,b):0,c&&(u[c>>2]=b)},Bc:(a,b,c)=>{c?35716==b?(a=F.getShaderInfoLog(K[a]),null===a&&(a="(unknown error)"),u[c>>2]=a?a.length+1:0):35720==b?(a=F.getShaderSource(K[a]),
u[c>>2]=a?a.length+1:0):u[c>>2]=F.getShaderParameter(K[a],b):O||=1281},xc:a=>{var b=db[a];if(!b){switch(a){case 7939:b=Q(Ec().join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=F.getParameter(a))||(O||=1280);b=b?Q(b):0;break;case 7938:b=Q(`OpenGL ES 2.0 (${F.getParameter(7938)})`);break;case 35724:b=F.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=Q(b);break;default:O||=1280}db[a]=
b}return b},wc:(a,b,c)=>{c?w[c>>2]=F.getTexParameter(a,b):O||=1281},vc:(a,b,c)=>{c?u[c>>2]=F.getTexParameter(a,b):O||=1281},sc:Hc,uc:(a,b,c)=>{Ic(a,b,c,2)},tc:(a,b,c)=>{Ic(a,b,c,0)},pc:(a,b,c)=>{c?u[c>>2]=F.getVertexAttribOffset(a,b):O||=1281},rc:(a,b,c)=>{Jc(a,b,c,2)},qc:(a,b,c)=>{Jc(a,b,c,5)},oc:(a,b)=>F.hint(a,b),nc:a=>(a=ab[a])?F.isBuffer(a):0,mc:a=>F.isEnabled(a),lc:a=>(a=bb[a])?F.isFramebuffer(a):0,kc:a=>(a=G[a])?F.isProgram(a):0,oa:a=>(a=N[a])?F.le.isQueryEXT(a):0,jc:a=>(a=H[a])?F.isRenderbuffer(a):
0,ic:a=>(a=K[a])?F.isShader(a):0,hc:a=>(a=J[a])?F.isTexture(a):0,Wd:a=>(a=cb[a])?F.isVertexArray(a):0,gc:a=>F.lineWidth(a),fc:Kc,ec:(a,b)=>{3317==a?eb=b:3314==a&&(fb=b);F.pixelStorei(a,b)},cb:(a,b)=>{F.vf.polygonModeWEBGL(a,b)},dc:(a,b)=>F.polygonOffset(a,b),eb:(a,b,c)=>{F.mf.polygonOffsetClampEXT(a,b,c)},la:(a,b)=>{F.le.queryCounterEXT(N[a],b)},cc:(a,b,c,d,e,f,g)=>{(g=Lc(f,e,c,d,g))?F.readPixels(a,b,c,d,e,f,g):O||=1280},bc:()=>{},ac:(a,b,c,d)=>F.renderbufferStorage(a,b,c,d),_b:(a,b)=>{F.sampleCoverage(a,
!!b)},Zb:(a,b,c,d)=>F.scissor(a,b,c,d),Yb:()=>{O||=1280},Xb:Mc,Wb:(a,b,c)=>F.stencilFunc(a,b,c),Vb:(a,b,c,d)=>F.stencilFuncSeparate(a,b,c,d),Ub:a=>F.stencilMask(a),Tb:(a,b)=>F.stencilMaskSeparate(a,b),Sb:(a,b,c)=>F.stencilOp(a,b,c),Rb:(a,b,c,d)=>F.stencilOpSeparate(a,b,c,d),Qb:(a,b,c,d,e,f,g,l,n)=>{n=n?Lc(l,g,d,e,n):null;F.texImage2D(a,b,c,d,e,f,g,l,n)},Pb:(a,b,c)=>F.texParameterf(a,b,c),Ob:(a,b,c)=>{F.texParameterf(a,b,w[c>>2])},Nb:(a,b,c)=>F.texParameteri(a,b,c),Mb:(a,b,c)=>{F.texParameteri(a,b,
u[c>>2])},Lb:(a,b,c,d,e,f,g,l,n)=>{n=n?Lc(l,g,e,f,n):null;F.texSubImage2D(a,b,c,d,e,f,g,l,n)},Kb:Nc,Jb:(a,b,c)=>{if(288>=b)for(var d=X[b],e=0;e<b;++e)d[e]=w[c+4*e>>2];else d=w.subarray(c>>2,c+4*b>>2);F.uniform1fv(W(a),d)},Ib:(a,b)=>{F.uniform1i(W(a),b)},Hb:(a,b,c)=>{if(288>=b)for(var d=Oc[b],e=0;e<b;++e)d[e]=u[c+4*e>>2];else d=u.subarray(c>>2,c+4*b>>2);F.uniform1iv(W(a),d)},Fb:(a,b,c)=>{F.uniform2f(W(a),b,c)},Eb:(a,b,c)=>{if(144>=b){b*=2;for(var d=X[b],e=0;e<b;e+=2)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*
e+4)>>2]}else d=w.subarray(c>>2,c+8*b>>2);F.uniform2fv(W(a),d)},Db:(a,b,c)=>{F.uniform2i(W(a),b,c)},Cb:(a,b,c)=>{if(144>=b){b*=2;for(var d=Oc[b],e=0;e<b;e+=2)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2]}else d=u.subarray(c>>2,c+8*b>>2);F.uniform2iv(W(a),d)},Bb:(a,b,c,d)=>{F.uniform3f(W(a),b,c,d)},Ab:(a,b,c)=>{if(96>=b){b*=3;for(var d=X[b],e=0;e<b;e+=3)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2]}else d=w.subarray(c>>2,c+12*b>>2);F.uniform3fv(W(a),d)},zb:(a,b,c,d)=>{F.uniform3i(W(a),b,
c,d)},yb:(a,b,c)=>{if(96>=b){b*=3;for(var d=Oc[b],e=0;e<b;e+=3)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2]}else d=u.subarray(c>>2,c+12*b>>2);F.uniform3iv(W(a),d)},xb:(a,b,c,d,e)=>{F.uniform4f(W(a),b,c,d,e)},wb:(a,b,c)=>{if(72>=b){var d=X[4*b],e=w;c>>=2;b*=4;for(var f=0;f<b;f+=4){var g=c+f;d[f]=e[g];d[f+1]=e[g+1];d[f+2]=e[g+2];d[f+3]=e[g+3]}}else d=w.subarray(c>>2,c+16*b>>2);F.uniform4fv(W(a),d)},vb:(a,b,c,d,e)=>{F.uniform4i(W(a),b,c,d,e)},ub:(a,b,c)=>{if(72>=b){b*=4;for(var d=Oc[b],
e=0;e<b;e+=4)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2],d[e+3]=u[c+(4*e+12)>>2]}else d=u.subarray(c>>2,c+16*b>>2);F.uniform4iv(W(a),d)},tb:(a,b,c,d)=>{if(72>=b){b*=4;for(var e=X[b],f=0;f<b;f+=4)e[f]=w[d+4*f>>2],e[f+1]=w[d+(4*f+4)>>2],e[f+2]=w[d+(4*f+8)>>2],e[f+3]=w[d+(4*f+12)>>2]}else e=w.subarray(d>>2,d+16*b>>2);F.uniformMatrix2fv(W(a),!!c,e)},sb:(a,b,c,d)=>{if(32>=b){b*=9;for(var e=X[b],f=0;f<b;f+=9)e[f]=w[d+4*f>>2],e[f+1]=w[d+(4*f+4)>>2],e[f+2]=w[d+(4*f+8)>>2],e[f+3]=w[d+(4*
f+12)>>2],e[f+4]=w[d+(4*f+16)>>2],e[f+5]=w[d+(4*f+20)>>2],e[f+6]=w[d+(4*f+24)>>2],e[f+7]=w[d+(4*f+28)>>2],e[f+8]=w[d+(4*f+32)>>2]}else e=w.subarray(d>>2,d+36*b>>2);F.uniformMatrix3fv(W(a),!!c,e)},rb:Pc,qb:Qc,pb:a=>{F.validateProgram(G[a])},ob:(a,b)=>F.vertexAttrib1f(a,b),nb:(a,b)=>{F.vertexAttrib1f(a,w[b>>2])},mb:(a,b,c)=>F.vertexAttrib2f(a,b,c),lb:(a,b)=>{F.vertexAttrib2f(a,w[b>>2],w[b+4>>2])},kb:(a,b,c,d)=>F.vertexAttrib3f(a,b,c,d),jb:(a,b)=>{F.vertexAttrib3f(a,w[b>>2],w[b+4>>2],w[b+8>>2])},ib:(a,
b,c,d,e)=>F.vertexAttrib4f(a,b,c,d,e),hb:(a,b)=>{F.vertexAttrib4f(a,w[b>>2],w[b+4>>2],w[b+8>>2],w[b+12>>2])},Sd:(a,b)=>{F.vertexAttribDivisor(a,b)},gb:Rc,fb:Sc,r:()=>0,sa:(a,b,c)=>Tc(a,{Le:u[c>>2],Ce:u[c+4>>2],nf:u[c+8>>2],jf:b,ue:u[c+12>>2],Te:u[c+16>>2]}),Q:(a,b)=>{a=U(a);return a?a.requestPointerLock?Nb()?ec(a):b?(Lb(ec,2,[a]),1):-2:-1:-4},Ta:()=>{ma("OOM")},d:a=>{eval(a?z(r,a):"")},W:Uc,x:(a,b,c)=>"undefined"==typeof onbeforeunload?-1:1!==c?-5:Vc(a,b),I:(a,b,c,d)=>Wc(a,b,c,d,12,"blur"),k:Wb,o:(a,
b,c)=>{a=U(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},J:(a,b,c,d)=>Wc(a,b,c,d,13,"focus"),z:(a,b,c,d)=>{if(!S.fullscreenEnabled())return-1;a=U(a);if(!a)return-4;Xc(a,b,c,d,"webkitfullscreenchange");return Xc(a,b,c,d,"fullscreenchange")},U:(a,b,c)=>Uc()?-1:Yc(a,b,c,26,"gamepadconnected"),T:(a,b,c)=>Uc()?-1:Yc(a,b,c,27,"gamepaddisconnected"),C:(a,b,c,d)=>Zc(a,b,c,d,2,"keydown"),A:(a,b,c,d)=>Zc(a,b,c,d,1,"keypress"),B:(a,b,c,d)=>Zc(a,b,c,d,3,"keyup"),Ra:(a,b,c)=>{a=V(a);Eb(a,
b,c)},O:(a,b,c,d)=>ad(a,b,c,d,5,"mousedown"),M:(a,b,c,d)=>ad(a,b,c,d,33,"mouseenter"),L:(a,b,c,d)=>ad(a,b,c,d,34,"mouseleave"),P:(a,b,c,d)=>ad(a,b,c,d,8,"mousemove"),N:(a,b,c,d)=>ad(a,b,c,d,6,"mouseup"),D:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.re||document.body.We||document.body.Ue))return-1;a=U(a);if(!a)return-4;bd(a,b,c,d,"mozpointerlockchange");bd(a,b,c,d,"webkitpointerlockchange");bd(a,b,c,d,"mspointerlockchange");return bd(a,b,c,d,"pointerlockchange")},
s:(a,b,c,d)=>cd(a,b,c,d),E:(a,b,c,d)=>dd(a,b,c,d,25,"touchcancel"),G:(a,b,c,d)=>dd(a,b,c,d,23,"touchend"),F:(a,b,c,d)=>dd(a,b,c,d,24,"touchmove"),H:(a,b,c,d)=>dd(a,b,c,d,22,"touchstart"),y:(a,b,c)=>ed(a,b,c),K:(a,b,c,d)=>(a=U(a))?"undefined"!=typeof a.onwheel?fd(a,b,c,d):-1:-4,ta:a=>document.title=a?z(r,a):"",q:()=>{throw"Please compile your program with async support in order to use asynchronous operations like emscripten_sleep";},Za:(a,b)=>{var c=0,d=0,e;for(e of rd()){var f=b+c;v[a+d>>2]=f;c+=
A(e,f,Infinity)+1;d+=4}return 0},_a:(a,b)=>{var c=rd();v[a>>2]=c.length;a=0;for(var d of c)a+=ob(d)+1;v[b>>2]=a;return 0},Y:()=>52,$a:()=>52,Xa:function(){return 70},Z:(a,b,c,d)=>{for(var e=0,f=0;f<c;f++){var g=v[b>>2],l=v[b+4>>2];b+=8;for(var n=0;n<l;n++){var t=a,B=r[g+n],L=sd[t];0===B||10===B?((1===t?da:m)(z(L)),L.length=0):L.push(B)}e+=l}v[d>>2]=e;return 0},aa:hc,a:ic,Sa:jc,b:kc,u:lc,n:mc,ba:nc,Cd:oc,w:pc,ua:qc,Ya:rc,p:tc,t:uc,i:vc,c:wc,v:yc,va:Ac,R:Bc,l:Hc,hd:Kc,ca:Mc,f:Nc,h:Pc,Ec:Qc,j:Rc,$b:Sc},
Z;
(async function(){function a(c){Z=c.exports;fa=Z.Xd;c=fa.buffer;q=new Int8Array(c);ia=new Int16Array(c);r=new Uint8Array(c);ja=new Uint16Array(c);u=new Int32Array(c);v=new Uint32Array(c);w=new Float32Array(c);x=new Float64Array(c);ka=new BigInt64Array(c);new BigUint64Array(c);$b=Z.$d;y--;h.monitorRunDependencies?.(y);0==y&&la&&(c=la,la=null,c());return Z}y++;h.monitorRunDependencies?.(y);var b={a:zd};if(h.instantiateWasm)return new Promise(c=>{h.instantiateWasm(b,(d,e)=>{c(a(d,e))})});na??=h.locateFile?h.locateFile("index.wasm",
k):k+"index.wasm";return a((await qa(b)).instance)})();var P=a=>(P=Z.Zd)(a),Ad=h._main=(a,b)=>(Ad=h._main=Z._d)(a,b),Ub=a=>(Ub=Z.ae)(a),Rb=a=>(Rb=Z.be)(a),Tb=()=>(Tb=Z.ce)();function Bd(a=[]){var b=Ad;a.unshift(ba);var c=a.length,d=Rb(4*(c+1)),e=d;a.forEach(g=>{v[e>>2]=Sb(g);e+=4});v[e>>2]=0;try{var f=b(c,d);Da(f)}catch(g){Ba(g)}}
function Cd(a=aa){function b(){h.calledRun=!0;if(!p){Z.Yd();h.onRuntimeInitialized?.();h.noInitialRun||Bd(a);if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var c=h.postRun.shift();ta.push(c)}sa(ta)}}if(0<y)la=Cd;else{if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)va();sa(ua);0<y?la=Cd:h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),1);b()},1)):b()}}
if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.shift()();Cd();
