var h;h||=typeof Module != 'undefined' ? Module : {};var aa=Object.assign({},h),ba=[],ca="./this.program",k="",da;"undefined"!=typeof document&&document.currentScript&&(k=document.currentScript.src);k=k.startsWith("blob:")?"":k.slice(0,k.replace(/[?#].*/,"").lastIndexOf("/")+1);da=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};var ea=h.print||console.log.bind(console),m=h.printErr||console.error.bind(console);
Object.assign(h,aa);aa=null;h.arguments&&(ba=h.arguments);h.thisProgram&&(ca=h.thisProgram);var fa=h.wasmBinary,ha,p=!1,ia,q,r,ja,ka,u,v,w,la,x,y=0,ma=null;function na(a){h.onAbort?.(a);a="Aborted("+a+")";m(a);p=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var oa;async function pa(a){if(!fa)try{var b=await da(a);return new Uint8Array(b)}catch{}if(a==oa&&fa)a=new Uint8Array(fa);else throw"both async and sync fetching of the wasm failed";return a}
async function qa(a,b){try{var c=await pa(a);return await WebAssembly.instantiate(c,b)}catch(d){m(`failed to asynchronously prepare wasm: ${d}`),na(d)}}async function ra(a){var b=oa;if(!fa&&"function"==typeof WebAssembly.instantiateStreaming)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){m(`wasm streaming compile failed: ${d}`),m("falling back to ArrayBuffer instantiation")}return qa(b,a)}
var va={5136181:()=>"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?!0:!1,5136328:()=>"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?!0:!1,5136562:a=>{"undefined"===typeof h.SDL2&&(h.SDL2={});var b=h.SDL2;a?b.capture={}:b.audio={};b.ce||("undefined"!==typeof AudioContext?b.ce=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.ce=new webkitAudioContext),b.ce&&
"undefined"===typeof navigator.userActivation&&sa(b.ce));return void 0===b.ce?-1:0},5137114:()=>h.SDL2.ce.sampleRate,5137182:(a,b,c,d)=>{function e(){}function f(l){void 0!==g.capture.je&&(clearInterval(g.capture.je),g.capture.je=void 0,g.capture.oe=void 0);g.capture.Ie=g.ce.createMediaStreamSource(l);g.capture.ie=g.ce.createScriptProcessor(b,a,1);g.capture.ie.onaudioprocess=function(n){void 0!==g&&void 0!==g.capture&&(n.outputBuffer.getChannelData(0).fill(0),g.capture.Ce=n.inputBuffer,ta(c,[d]))};
g.capture.Ie.connect(g.capture.ie);g.capture.ie.connect(g.ce.destination);g.capture.stream=l}var g=h.SDL2;g.capture.oe=g.ce.createBuffer(a,b,g.ce.sampleRate);g.capture.oe.getChannelData(0).fill(0);g.capture.je=setInterval(function(){g.capture.Ce=g.capture.oe;ta(c,[d])},b/g.ce.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(f).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,
video:!1},f,e)},5138875:(a,b,c,d)=>{var e=h.SDL2;e.audio.ie=e.ce.createScriptProcessor(b,0,a);e.audio.ie.onaudioprocess=function(f){void 0!==e&&void 0!==e.audio&&(void 0!==e.audio.je&&(clearInterval(e.audio.je),e.audio.je=void 0,e.audio.oe=void 0),e.audio.ve=f.outputBuffer,ta(c,[d]))};e.audio.ie.connect(e.ce.destination);"suspended"===e.ce.state&&(e.audio.oe=e.ce.createBuffer(a,b,e.ce.sampleRate),e.audio.oe.getChannelData(0).fill(0),e.audio.je=setInterval(function(){"undefined"!==typeof navigator.userActivation&&
navigator.userActivation.hasBeenActive&&e.ce.resume();e.audio.ve=e.audio.oe;ta(c,[d]);e.audio.ve=void 0},b/e.ce.sampleRate*1E3))},5140050:(a,b)=>{for(var c=h.SDL2,d=c.capture.Ce.numberOfChannels,e=0;e<d;++e){var f=c.capture.Ce.getChannelData(e);if(f.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";if(1==d)for(var g=0;g<b;++g)ua(a+4*g,f[g]);else for(g=0;g<b;++g)ua(a+4*(g*d+e),f[g])}},5140655:(a,b)=>{var c=h.SDL2;a>>>=2;for(var d=
c.audio.ve.numberOfChannels,e=0;e<d;++e){var f=c.audio.ve.getChannelData(e);if(f.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";for(var g=0;g<b;++g)f[g]=w[a+(g*d+e)]}},5141144:a=>{var b=h.SDL2;if(a){void 0!==b.capture.je&&clearInterval(b.capture.je);if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c])}void 0!==b.capture.ie&&(b.capture.ie.onaudioprocess=
function(){},b.capture.ie.disconnect());void 0!==b.capture.Ie&&b.capture.Ie.disconnect();b.capture=void 0}else void 0!=b.audio.ie&&b.audio.ie.disconnect(),void 0!==b.audio.je&&clearInterval(b.audio.je),b.audio=void 0;void 0!==b.ce&&void 0===b.audio&&void 0===b.capture&&(b.ce.close(),b.ce=void 0)},5142150:(a,b,c)=>{h.SDL2||(h.SDL2={});var d=h.SDL2;d.$e!==h.canvas&&(d.ue=h.createContext(h.canvas,!1,!0),d.$e=h.canvas);if(d.w!==a||d.h!==b||d.pf!==d.ue)d.image=d.ue.createImageData(a,b),d.w=a,d.h=b,d.pf=
d.ue;a=d.image.data;b=c/4;var e=0;if("undefined"!==typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var f=u[b];a[e]=f&255;a[e+1]=f>>8&255;a[e+2]=f>>16&255;a[e+3]=255;b++;e+=4}else if(d.df!==a&&(d.cf=new Int32Array(a.buffer),d.ef=new Uint8Array(a.buffer),d.df=a),a=d.cf,c=a.length,a.set(u.subarray(b,b+c)),a=d.ef,b=3,e=b+4*c,0==c%8)for(;b<e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|
0;else for(;b<e;)a[b]=255,b=b+4|0;d.ue.putImageData(d.image,0,0)},5143618:(a,b,c,d,e)=>{var f=document.createElement("canvas");f.width=a;f.height=b;var g=f.getContext("2d");a=g.createImageData(a,b);b=a.data;e/=4;var l=0,n;if("undefined"!==typeof CanvasPixelArray&&b instanceof CanvasPixelArray)for(n=b.length;l<n;){var t=u[e];b[l]=t&255;b[l+1]=t>>8&255;b[l+2]=t>>16&255;b[l+3]=t>>24&255;e++;l+=4}else b=new Int32Array(b.buffer),n=b.length,b.set(u.subarray(e,e+n));g.putImageData(a,0,0);c=0===c&&0===d?
"url("+f.toDataURL()+"), auto":"url("+f.toDataURL()+") "+c+" "+d+", auto";d=z(c.length+1);A(c,d,c.length+1);return d},5144606:a=>{h.canvas&&(h.canvas.style.cursor=a?C(r,a):"")},5144689:()=>{h.canvas&&(h.canvas.style.cursor="none")},5144758:()=>window.innerWidth,5144788:()=>window.innerHeight};class wa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var xa=a=>{for(;0<a.length;)a.shift()(h)},ya=[],za=[],Aa=()=>{var a=h.preRun.shift();za.unshift(a)},Ba=h.noExitRuntime||!0;function ua(a,b){var c="float";c.endsWith("*")&&(c="*");switch(c){case "i1":q[a]=b;break;case "i8":q[a]=b;break;case "i16":ja[a>>1]=b;break;case "i32":u[a>>2]=b;break;case "i64":la[a>>3]=BigInt(b);break;case "float":w[a>>2]=b;break;case "double":x[a>>3]=b;break;case "*":v[a>>2]=b;break;default:na(`invalid type for setValue: ${c}`)}}
var Ca="undefined"!=typeof TextDecoder?new TextDecoder:void 0,C=(a,b=0,c=NaN)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ca)return Ca.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
Da=a=>{if(!(a instanceof wa||"unwind"==a))throw a;},Ea=a=>{ia=a;Ba||(h.onExit?.(a),p=!0);throw new wa(a);},Fa=a=>{ia=a;Ea(a)},Ga=()=>{if(!Ba)try{var a=ia;ia=a;Ea(a)}catch(b){Da(b)}},Ha=!1,Ia=!1,Ja=[];
function Ka(){function a(){var c=h.canvas;Ia=document.pointerLockElement===c||document.mozPointerLockElement===c||document.webkitPointerLockElement===c||document.msPointerLockElement===c}if(!La){La=!0;var b=h.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),b.exitPointerLock=
b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",c=>{!Ia&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}var Ma=!1,Na=void 0,D=void 0;
function Oa(){if(!Ha)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var Pa=[];function Qa(){var a=h.canvas;Pa.forEach(b=>b(a.width,a.height))}
function Ra(a,b,c){b&&c?(a.vf=b,a.nf=c):(b=a.vf,c=a.nf);var d=b,e=c;0<h.forcedAspectRatio&&(d/e<h.forcedAspectRatio?d=Math.round(e*h.forcedAspectRatio):e=Math.round(d/h.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*f)}D?(a.width!=d&&(a.width=
d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var La,E=12288,Sa=!1,Ta=0,Ua=0,Va=0,F={alpha:!1,depth:!1,stencil:!1,antialias:!1},Wa={},Xa,G,Ya=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,f)=>b.drawArraysInstancedANGLE(c,d,e,f),a.drawElementsInstanced=(c,d,e,f,g)=>b.drawElementsInstancedANGLE(c,d,e,f,g))},Za=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),
a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},$a=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},ab=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},bb=1,cb=[],H=[],db=[],J=[],K=[],L=[],eb=[],M=[],N=[],fb={},gb=4,hb=0,ib=a=>{for(var b=bb++,c=a.length;c<b;c++)a[c]=null;return b},jb=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=G[c](),g=f&&ib(d);f?(f.name=g,d[g]=f):O||=1282;u[b+4*e>>2]=g}},lb=(a,b)=>{a.te||(a.te=a.getContext,a.getContext=function(d,e){e=a.te(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?kb(c,b):0},kb=(a,b)=>{var c=
ib(M),d={handle:c,attributes:b,version:b.Ve,le:a};a.canvas&&(a.canvas.pe=d);M[c]=d;("undefined"==typeof b.jf||b.jf)&&mb(d);return c},ob=a=>{nb=M[a];h.ctx=G=nb?.le},mb=a=>{a||=nb;if(!a.qf){a.qf=!0;var b=a.le;b.Hf=b.getExtension("WEBGL_multi_draw");b.lf=b.getExtension("EXT_polygon_offset_clamp");b.kf=b.getExtension("EXT_clip_control");b.uf=b.getExtension("WEBGL_polygon_mode");Ya(b);Za(b);$a(b);b.ke=b.getExtension("EXT_disjoint_timer_query");ab(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||
b.getExtension(c)})}},pb={},O,nb,qb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},A=(a,b,c)=>{var d=r;if(!(0<c))return 0;var e=b;c=b+c-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var l=a.charCodeAt(++f);g=65536+((g&1023)<<10)|l&1023}if(127>=g){if(b>=c)break;d[b++]=g}else{if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6}else{if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12}else{if(b+3>=c)break;d[b++]=
240|g>>18;d[b++]=128|g>>12&63}d[b++]=128|g>>6&63}d[b++]=128|g&63}}d[b]=0;return b-e},P=a=>{var b=qb(a)+1,c=z(b);c&&A(a,c,b);return c},Gb=(a,b,c,d,e)=>{function f(){return g<rb?(Ga(),!1):!0}sb=a;tb=d;var g=rb;ub=!1;vb=function(){if(!p)if(0<wb.length){var l=wb.shift();l.Df(l.wf);if(xb){var n=xb,t=0==n%1?n-1:Math.floor(n);xb=l.zf?t:(8*n+(t+.5))/9}h.setStatus&&(l=h.statusMessage||"Please wait...",n=xb??0,t=yb.Cf??0,n?n<t?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(l):h.setStatus(""));
f()&&setTimeout(vb,0)}else if(f())if(zb=zb+1|0,1==Ab&&1<Bb&&0!=zb%Bb)Q();else{0==Ab&&(Cb=performance.now());a:if(!p){for(l of Db)if(!1===l())break a;if(!p)try{a(),Ga()}catch(B){Da(B)}for(n of Eb)n()}f()&&Q()}};e||(0<b?Fb(0,1E3/b):Fb(1,1),Q());if(c)throw"unwind";},ub=!1,Q=null,rb=0,sb=null,tb=0,Ab=0,Bb=0,zb=0,wb=[],Db=[],Eb=[],Hb=0;
function Ib(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Hb)Hb=b+1E3/60;else for(;b+2>=Hb;)Hb+=1E3/60;setTimeout(a,Math.max(Hb-b,0))}}
var yb={},vb,xb,Cb,Jb,Fb=(a,b)=>{Ab=a;Bb=b;if(sb)if(ub||=!0,0==a)Q=function(){setTimeout(vb,Math.max(0,Cb+b-performance.now())|0)};else if(1==a)Q=function(){Ib(vb)};else if(2==a){if("undefined"==typeof Jb)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Jb=d=>{c.push(d);postMessage("setimmediate","*")}}else Jb=setImmediate;Q=function(){Jb(vb)}}},Kb=[],Lb=(a,b)=>{Kb.length=0;
for(var c;c=r[a++];){var d=105!=c;d&=112!=c;b+=d&&b%8?4:0;Kb.push(112==c?v[b>>2]:106==c?la[b>>3]:105==c?u[b>>2]:x[b>>3]);b+=d?8:4}return Kb};function Mb(a){var b=R.ge[a];b.target.removeEventListener(b.de,b.Te,b.ee);R.ge.splice(a,1)}function Nb(a,b,c){function d(f,g){if(f.length!=g.length)return!1;for(var l in f)if(f[l]!=g[l])return!1;return!0}for(var e of R.me)if(e.Le==a&&d(e.Re,c))return;R.me.push({Le:a,Xe:b,Re:c});R.me.sort((f,g)=>f.Xe<g.Xe)}function Ob(a){R.me=R.me.filter(b=>b.Le!=a)}
function Pb(){return navigator.userActivation?navigator.userActivation.isActive:R.Ge&&R.af.re}function Qb(){if(Pb()){var a=R.me;R.me=[];for(var b of a)b.Le(...b.Re)}}function S(a){if(!a.target)return-4;if(a.fe)a.Te=function(c){++R.Ge;R.af=a;Qb();a.he(c);Qb();--R.Ge},a.target.addEventListener(a.de,a.Te,a.ee),R.ge.push(a);else for(var b=0;b<R.ge.length;++b)R.ge[b].target==a.target&&R.ge[b].de==a.de&&Mb(b--);return 0}
function Rb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var R={xf:0,Fe:0,He:0,Ae:0,Qe:0,Ne:0,De:0,Bf:0,If:0,Af:0,Ee:0,Je:0,Pe:0,Me:0,Ff(a,b,c){q.set(q.subarray(b,b+c),a)},Jf(){for(;R.ge.length;)Mb(R.ge.length-1);R.me=[]},Ge:0,me:[],ge:[],sf:(a,b)=>{for(var c=0;c<R.ge.length;++c)R.ge[c].target!=a||b&&b!=R.ge[c].de||Mb(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},Sb={},Tb=[0,document,window],T=a=>{a=2<a?a?C(r,a):"":a;return Tb[a]||document.querySelector(a)},Vb=a=>{var b=qb(a)+1,c=Ub(b);A(a,c,b);return c},
Yb=a=>{var b=Wb(),c=Ub(8),d=c+4;a=Vb(a.id);if(a=T(a))u[c>>2]=a.width,u[d>>2]=a.height;c=[u[c>>2],u[d>>2]];Xb(b);return c},Zb=(a,b,c)=>{a=T(a);if(!a)return-4;a.width=b;a.height=c;return 0},$b=(a,b,c)=>{if(a.yf){var d=Wb();a=Vb(a.id);Zb(a,b,c);Xb(d)}else a.width=b,a.height=c},ac=[],bc,U=a=>{var b=ac[a];b||(a>=ac.length&&(ac.length=a+1),ac[a]=b=bc.get(a));return b},cc=a=>{function b(){document.fullscreenElement||document.webkitFullscreenElement||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",
b),$b(a,d,e),a.style.width=f,a.style.height=g,a.style.backgroundColor=l,n||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=n,a.style.paddingLeft=t,a.style.paddingRight=B,a.style.paddingTop=Z,a.style.paddingBottom=I,a.style.marginLeft=ed,a.style.marginRight=fd,a.style.marginTop=gd,a.style.marginBottom=hd,document.body.style.margin=jd,document.documentElement.style.overflow=kd,document.body.scroll=ld,a.style.ne=md,a.pe&&a.pe.le.viewport(0,0,d,e),Sb.se&&U(Sb.se)(37,
0,Sb.Se))}var c=Yb(a),d=c[0],e=c[1],f=a.style.width,g=a.style.height,l=a.style.backgroundColor,n=document.body.style.backgroundColor,t=a.style.paddingLeft,B=a.style.paddingRight,Z=a.style.paddingTop,I=a.style.paddingBottom,ed=a.style.marginLeft,fd=a.style.marginRight,gd=a.style.marginTop,hd=a.style.marginBottom,jd=document.body.style.margin,kd=document.documentElement.style.overflow,ld=document.body.scroll,md=a.style.ne;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",
b)},dc=(a,b,c)=>{a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"},ec=a=>0>Tb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},fc=(a,b)=>{if(0!=b.Ke||0!=b.Be){cc(a);var c=b.tf?innerWidth:screen.width,d=b.tf?innerHeight:screen.height,e=ec(a),f=e.width;e=e.height;var g=Yb(a),l=g[0];g=g[1];3==b.Ke?(dc(a,(d-e)/2,(c-f)/2),c=f,d=e):2==b.Ke&&(c*g<l*d?(f=g*c/l,dc(a,(d-f)/2,0),d=f):(f=l*d/g,dc(a,0,(c-f)/2),c=f));var n;(n=a.style).backgroundColor||(n.backgroundColor=
"black");let t;(t=document.body.style).backgroundColor||(t.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.mf&&(a.style.ne="optimizeSpeed",a.style.ne="-moz-crisp-edges",a.style.ne="-o-crisp-edges",a.style.ne="-webkit-optimize-contrast",a.style.ne="optimize-contrast",a.style.ne="crisp-edges",a.style.ne="pixelated");n=2==b.Be?devicePixelRatio:1;0!=b.Be&&(c=c*n|0,d=d*n|0,$b(a,c,d),a.pe&&a.pe.le.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);
else return R.fullscreenEnabled()?-3:-1;Sb=b;b.se&&U(b.se)(37,0,b.Se);return 0},gc=a=>{if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?-3:-1;return 0},hc=(a,b)=>{x[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)x[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)x[a+8*c+528>>3]="object"==typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)q[a+c+1040]="object"==typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];
q[a+1104]=b.connected;u[a+1108>>2]=b.index;u[a+8>>2]=b.axes.length;u[a+12>>2]=b.buttons.length;A(b.id,a+1112,64);A(b.mapping,a+1176,64)},ic=(a,b)=>{G.attachShader(H[a],L[b])},jc=(a,b)=>{G.bindBuffer(a,cb[b])},kc=(a,b,c,d)=>{G.bufferData(a,c?r.subarray(c,c+b):b,d)},lc=a=>G.clear(a),mc=(a,b,c,d)=>G.clearColor(a,b,c,d),nc=a=>{G.compileShader(L[a])},oc=()=>{var a=ib(H),b=G.createProgram();b.name=a;b.ze=b.xe=b.ye=0;b.Oe=1;H[a]=b;return a},pc=a=>{var b=ib(L);L[b]=G.createShader(a);return b},qc=a=>{if(a){var b=
H[a];b?(G.deleteProgram(b),b.name=0,H[a]=null):O||=1281}},rc=[],sc=(a,b,c,d)=>{G.drawElements(a,b,c,d)},tc=a=>G.enable(a),uc=a=>{G.enableVertexAttribArray(a)},vc=(a,b)=>{jb(a,b,"createBuffer",cb)},wc=(a,b,c,d,e,f,g,l)=>{b=H[b];if(a=G[a](b,c))d=l&&A(a.name,l,d),e&&(u[e>>2]=d),f&&(u[f>>2]=a.size),g&&(u[g>>2]=a.type)},xc=(a,b)=>G.getAttribLocation(H[a],b?C(r,b):""),yc=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&(O||=1280);return;case 36345:d=0;break;case 34466:var e=
G.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=G.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":O||=1280;return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:O||=1280;return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:u[b+4*a>>2]=e[a];break;case 2:w[b+
4*a>>2]=e[a];break;case 4:q[b+a]=e[a]?1:0}return}try{d=e.name|0}catch(f){O||=1280;m(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${f})`);return}}break;default:O||=1280;m(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${e} of type ${typeof e}!`);return}switch(c){case 1:c=d;v[b>>2]=c;v[b+4>>2]=(c-v[b>>2])/4294967296;break;case 0:u[b>>2]=d;break;case 2:w[b>>2]=d;break;case 4:q[b]=d?1:0}}else O||=1281},zc=(a,b,c,d)=>
{a=G.getProgramInfoLog(H[a]);null===a&&(a="(unknown error)");b=0<b&&d?A(a,d,b):0;c&&(u[c>>2]=b)},Ac=(a,b,c)=>{if(c)if(a>=bb)O||=1281;else if(a=H[a],35716==b)a=G.getProgramInfoLog(a),null===a&&(a="(unknown error)"),u[c>>2]=a.length+1;else if(35719==b){if(!a.ze){var d=G.getProgramParameter(a,35718);for(b=0;b<d;++b)a.ze=Math.max(a.ze,G.getActiveUniform(a,b).name.length+1)}u[c>>2]=a.ze}else if(35722==b){if(!a.xe)for(d=G.getProgramParameter(a,35721),b=0;b<d;++b)a.xe=Math.max(a.xe,G.getActiveAttrib(a,b).name.length+
1);u[c>>2]=a.xe}else if(35381==b){if(!a.ye)for(d=G.getProgramParameter(a,35382),b=0;b<d;++b)a.ye=Math.max(a.ye,G.getActiveUniformBlockName(a,b).length+1);u[c>>2]=a.ye}else u[c>>2]=G.getProgramParameter(a,b);else O||=1281},Bc=(a,b,c)=>{if(c){a=G.ke.getQueryObjectEXT(N[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;v[c>>2]=d;v[c+4>>2]=(d-v[c>>2])/4294967296}else O||=1281},Cc=(a,b,c)=>{if(c){a=G.ke.getQueryObjectEXT(N[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;u[c>>2]=d}else O||=1281},Dc=()=>{var a=ab(G);
return a=a.concat(a.map(b=>"GL_"+b))},Ec=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Fc=a=>{var b=a.qe,c=a.Ze,d;if(!b){a.qe=b={};a.Ye={};var e=G.getProgramParameter(a,35718);for(d=0;d<e;++d){var f=G.getActiveUniform(a,d);var g=f.name;f=f.size;var l=Ec(g);l=0<l?g.slice(0,l):g;var n=a.Oe;a.Oe+=f;c[l]=[f,n];for(g=0;g<f;++g)b[n]=g,a.Ye[n++]=l}}},Gc=(a,b)=>{b=b?C(r,b):"";if(a=H[a]){Fc(a);var c=a.qe,d=0,e=b,f=Ec(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.Ze[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||
G.getUniformLocation(a,b)))return d}else O||=1281;return-1},V=a=>{var b=G.bf;if(b){var c=b.qe[a];"number"==typeof c&&(b.qe[a]=c=G.getUniformLocation(b,b.Ye[a]+(0<c?`[${c}]`:"")));return c}O||=1282},Hc=(a,b,c,d)=>{if(c)if(a=H[a],Fc(a),a=G.getUniform(a,V(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:u[c>>2]=a;break;case 2:w[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:u[c+4*b>>2]=a[b];break;case 2:w[c+4*b>>2]=a[b]}else O||=1281},Ic=(a,b,c,d)=>{if(c)if(a=G.getVertexAttrib(a,b),
34975==b)u[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:u[c>>2]=a;break;case 2:w[c>>2]=a;break;case 5:u[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:u[c+4*b>>2]=a[b];break;case 2:w[c+4*b>>2]=a[b];break;case 5:u[c+4*b>>2]=Math.fround(a[b])}else O||=1281},Jc=a=>{a=H[a];G.linkProgram(a);a.qe=0;a.Ze={}},Kc=(a,b,c,d,e)=>{a-=5120;a=1==a?r:4==a?u:6==a?w:5==a||28922==a?v:ka;b=d*((hb||c)*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+
gb-1&-gb);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},Lc=(a,b,c,d)=>{for(var e="",f=0;f<b;++f){var g=(g=v[c+4*f>>2])?C(r,g,d?v[d+4*f>>2]:void 0):"";e+=g}G.shaderSource(L[a],e)},Mc=(a,b)=>{G.uniform1f(V(a),b)},W=[],Nc=[],Oc=(a,b,c,d)=>{G.uniform3f(V(a),b,c,d)},Pc=(a,b,c,d)=>{if(18>=b){var e=W[16*b],f=w;d>>=2;b*=16;for(var g=0;g<b;g+=16){var l=d+g;e[g]=f[l];e[g+1]=f[l+1];e[g+2]=f[l+2];e[g+3]=f[l+3];e[g+4]=f[l+4];e[g+5]=f[l+5];e[g+6]=f[l+6];e[g+
7]=f[l+7];e[g+8]=f[l+8];e[g+9]=f[l+9];e[g+10]=f[l+10];e[g+11]=f[l+11];e[g+12]=f[l+12];e[g+13]=f[l+13];e[g+14]=f[l+14];e[g+15]=f[l+15]}}else e=w.subarray(d>>2,d+64*b>>2);G.uniformMatrix4fv(V(a),!!c,e)},Qc=a=>{a=H[a];G.useProgram(a);G.bf=a},Rc=(a,b,c,d,e,f)=>{G.vertexAttribPointer(a,b,c,!!d,e,f)},Sc=(a,b,c,d)=>G.viewport(a,b,c,d),Tc=(a,b)=>{if(!R.fullscreenEnabled())return-1;a=T(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?Pb()?fc(a,b):b.gf?(Nb(fc,1,[a,b]),1):-2:-3:-4},Uc=()=>{try{if(navigator.getGamepads)return(R.we=
navigator.getGamepads())?0:-1}catch(a){navigator.getGamepads=null}return-1},Vc=(a,b)=>{var c={target:T(2),de:"beforeunload",fe:b,he:(d=event)=>{var e=U(b)(28,0,a);e&&=e?C(r,e):"";if(e)return d.preventDefault(),d.returnValue=e},ee:!0};return S(c)},Wc=(a,b,c,d,e,f)=>{R.De||(R.De=z(256));a={target:T(a),de:f,fe:d,he:(g=event)=>{var l=g.target.id?g.target.id:"",n=R.De;A(Rb(g.target),n+0,128);A(l,n+128,128);U(d)(e,n,b)&&g.preventDefault()},ee:c};return S(a)},Xc=(a,b,c,d,e)=>{R.Ee||(R.Ee=z(276));return S({target:a,
de:e,fe:d,he:(f=event)=>{var g=R.Ee,l=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,n=!!l;q[g]=n;q[g+1]=R.fullscreenEnabled();var t=n?l:R.rf,B=t?.id||"";A(Rb(t),g+2,128);A(B,g+130,128);u[g+260>>2]=t?t.clientWidth:0;u[g+264>>2]=t?t.clientHeight:0;u[g+268>>2]=screen.width;u[g+272>>2]=screen.height;n&&(R.rf=l);U(d)(19,g,b)&&f.preventDefault()},ee:c})},Yc=(a,b,c,d,e)=>{R.Fe||(R.Fe=z(1240));b={target:T(2),re:!0,de:e,fe:c,he:(f=
event)=>{var g=R.Fe;hc(g,f.gamepad);U(c)(d,g,a)&&f.preventDefault()},ee:b};return S(b)},Zc=(a,b,c,d,e,f)=>{R.He||(R.He=z(160));a={target:T(a),de:f,fe:d,he:g=>{var l=R.He;x[l>>3]=g.timeStamp;var n=l>>2;u[n+2]=g.location;q[l+12]=g.ctrlKey;q[l+13]=g.shiftKey;q[l+14]=g.altKey;q[l+15]=g.metaKey;q[l+16]=g.repeat;u[n+5]=g.charCode;u[n+6]=g.keyCode;u[n+7]=g.which;A(g.key||"",l+32,32);A(g.code||"",l+64,32);A(g.char||"",l+96,32);A(g.locale||"",l+128,32);U(d)(e,l,b)&&g.preventDefault()},ee:c};return S(a)},$c=
(a,b,c)=>{x[a>>3]=b.timeStamp;var d=a>>2;u[d+2]=b.screenX;u[d+3]=b.screenY;u[d+4]=b.clientX;u[d+5]=b.clientY;q[a+24]=b.ctrlKey;q[a+25]=b.shiftKey;q[a+26]=b.altKey;q[a+27]=b.metaKey;ja[2*d+14]=b.button;ja[2*d+15]=b.buttons;u[d+8]=b.movementX;u[d+9]=b.movementY;a=ec(c);u[d+10]=b.clientX-(a.left|0);u[d+11]=b.clientY-(a.top|0)},ad=(a,b,c,d,e,f)=>{R.Ae||(R.Ae=z(64));a=T(a);return S({target:a,re:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,de:f,fe:d,he:(g=event)=>{$c(R.Ae,g,a);U(d)(e,R.Ae,b)&&g.preventDefault()},
ee:c})},bd=(a,b,c,d,e)=>{R.Je||(R.Je=z(257));return S({target:a,de:e,fe:d,he:(f=event)=>{var g=R.Je,l=document.pointerLockElement||document.te||document.hf||document.ff;q[g]=!!l;var n=l?.id||"";A(Rb(l),g+1,128);A(n,g+129,128);U(d)(20,g,b)&&f.preventDefault()},ee:c})},cd=(a,b,c,d)=>{R.Ne||(R.Ne=z(36));a=T(a);return S({target:a,de:"resize",fe:d,he:(e=event)=>{if(e.target==a){var f=document.body;if(f){var g=R.Ne;u[g>>2]=0;u[g+4>>2]=f.clientWidth;u[g+8>>2]=f.clientHeight;u[g+12>>2]=innerWidth;u[g+16>>
2]=innerHeight;u[g+20>>2]=outerWidth;u[g+24>>2]=outerHeight;u[g+28>>2]=pageXOffset|0;u[g+32>>2]=pageYOffset|0;U(d)(10,g,b)&&e.preventDefault()}}},ee:c})},dd=(a,b,c,d,e,f)=>{R.Me||(R.Me=z(1552));a=T(a);return S({target:a,re:"touchstart"==f||"touchend"==f,de:f,fe:d,he:g=>{var l={},n=g.touches;for(var t of n)t.Ue=t.We=0,l[t.identifier]=t;for(var B of g.changedTouches)B.Ue=1,l[B.identifier]=B;for(var Z of g.targetTouches)l[Z.identifier].We=1;n=R.Me;x[n>>3]=g.timeStamp;q[n+12]=g.ctrlKey;q[n+13]=g.shiftKey;
q[n+14]=g.altKey;q[n+15]=g.metaKey;t=n+16;B=ec(a);Z=0;for(let I of Object.values(l))if(l=t>>2,u[l]=I.identifier,u[l+1]=I.screenX,u[l+2]=I.screenY,u[l+3]=I.clientX,u[l+4]=I.clientY,u[l+5]=I.pageX,u[l+6]=I.pageY,q[t+28]=I.Ue,q[t+29]=I.We,u[l+8]=I.clientX-(B.left|0),u[l+9]=I.clientY-(B.top|0),t+=48,31<++Z)break;u[n+8>>2]=Z;U(d)(e,n,b)&&g.preventDefault()},ee:c})},nd=(a,b,c)=>{var d=Tb[1];R.Pe||(R.Pe=z(8));return S({target:d,de:"visibilitychange",fe:c,he:(e=event)=>{var f=R.Pe,g=["hidden","visible","prerender",
"unloaded"].indexOf(document.visibilityState);q[f]=document.hidden;u[f+4>>2]=g;U(c)(21,f,a)&&e.preventDefault()},ee:b})},od=(a,b,c,d)=>{R.Qe||(R.Qe=z(96));return S({target:a,re:!0,de:"wheel",fe:d,he:(e=event)=>{var f=R.Qe;$c(f,e,a);x[f+64>>3]=e.deltaX;x[f+72>>3]=e.deltaY;x[f+80>>3]=e.deltaZ;u[f+88>>2]=e.deltaMode;U(d)(9,f,b)&&e.preventDefault()},ee:c})},pd={},rd=()=>{if(!qd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&
navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in pd)void 0===pd[b]?delete a[b]:a[b]=pd[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);qd=c}return qd},qd,sd=[null,[],[]],td=(a,b,c)=>{a.addEventListener(b,c,{once:!0})},sa=a=>{var b;b||=[document,document.getElementById("canvas")];["keydown","mousedown","touchstart"].forEach(c=>{b.forEach(d=>{d&&td(d,c,()=>{"suspended"===a.state&&a.resume()})})})},ta=(a,b=[])=>{U(a)(...b)};
h.requestFullscreen=function(a,b){function c(){Ha=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=Oa,Na&&d.requestPointerLock(),Ha=!0,D?("undefined"!=typeof SDL&&(u[SDL.screen>>2]=v[SDL.screen>>2]|8388608),Ra(h.canvas),Qa()):Ra(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),D?("undefined"!=typeof SDL&&(u[SDL.screen>>2]=v[SDL.screen>>
2]&-8388609),Ra(h.canvas),Qa()):Ra(d));h.onFullScreen?.(Ha);h.onFullscreen?.(Ha)}Na=a;D=b;"undefined"==typeof Na&&(Na=!0);"undefined"==typeof D&&(D=!1);var d=h.canvas;Ma||(Ma=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=e.requestFullscreen||
e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()};h.setCanvasSize=function(a,b,c){Ra(h.canvas,a,b);c||Qa()};h.getUserMedia=function(a){let b;(b=window).getUserMedia||(b.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)};
h.createContext=function(a,b,c,d){if(b&&h.ctx&&a==h.canvas)return h.ctx;var e;if(b){var f={antialias:!1,alpha:!1,Ve:1};if(d)for(var g in d)f[g]=d[g];if("undefined"!=typeof pb&&(e=lb(a,f)))var l=M[e].le}else l=a.getContext("2d");if(!l)return null;c&&(h.ctx=l,b&&ob(e),Ja.forEach(n=>n()),Ka());return l};h.requestAnimationFrame=Ib;h.pauseMainLoop=function(){Q=null;rb++};h.resumeMainLoop=function(){rb++;var a=Ab,b=Bb,c=sb;sb=null;Gb(c,0,!1,tb,!0);Fb(a,b);Q()};h.preMainLoop&&Db.push(h.preMainLoop);
h.postMainLoop&&Eb.push(h.postMainLoop);for(var X=0;32>X;++X)rc.push(Array(X));var ud=new Float32Array(288);for(X=0;288>=X;++X)W[X]=ud.subarray(0,X);var vd=new Int32Array(288);for(X=0;288>=X;++X)Nc[X]=vd.subarray(0,X);
var wd={X:function(){return 0},Za:()=>{},$a:function(){return 0},Wa:()=>{},Xa:()=>{},bb:function(){},Ya:()=>{},Ja:a=>{if(12448==a)return E=12288,1;E=12300;return 0},Ma:(a,b,c,d,e)=>{if(62E3!=a)E=12296,c=0;else{if(b)for(;;){a=u[b>>2];if(12321==a)F.alpha=0<u[b+4>>2];else if(12325==a)F.depth=0<u[b+4>>2];else if(12326==a)F.stencil=0<u[b+4>>2];else if(12337==a)a=u[b+4>>2],F.antialias=0<a;else if(12338==a)a=u[b+4>>2],F.antialias=1==a;else if(12544==a)F.Ef=12547!=u[b+4>>2];else if(12344==a)break;b+=8}c&&
d||e?(e&&(u[e>>2]=1),c&&0<d&&(v[c>>2]=62002),E=12288,c=1):(E=12300,c=0)}return c},za:(a,b,c,d)=>{if(62E3!=a)return E=12296,0;for(a=1;;){b=u[d>>2];if(12440==b)a=u[d+4>>2];else if(12344==b)break;else return E=12292,0;d+=8}if(2!=a)return E=12293,0;F.Ve=a-1;F.Gf=0;Xa=lb(h.canvas,F);if(0!=Xa)return E=12288,ob(Xa),Ja.forEach(e=>e()),ob(null),62004;E=12297;return 0},Ba:(a,b)=>{if(62E3!=a)return E=12296,0;if(62002!=b)return E=12293,0;E=12288;return 62006},Aa:(a,b)=>{if(62E3!=a)return E=12296,0;if(62004!=
b)return E=12294,0;a=Xa;nb===M[a]&&(nb=null);"object"==typeof R&&R.sf(M[a].le.canvas);M[a]?.le.canvas&&(M[a].le.canvas.pe=void 0);M[a]=null;E=12288;Ta==b&&(Ta=0);return 1},Ca:(a,b)=>{if(62E3!=a)return E=12296,0;if(62006!=b)return E=12301,1;Ua==b&&(Ua=0);Va==b&&(Va=0);E=12288;return 1},Na:(a,b,c,d)=>{if(62E3!=a)return E=12296,0;if(62002!=b)return E=12293,0;if(!d)return E=12300,0;E=12288;switch(c){case 12320:return u[d>>2]=F.alpha?32:24,1;case 12321:return u[d>>2]=F.alpha?8:0,1;case 12322:return u[d>>
2]=8,1;case 12323:return u[d>>2]=8,1;case 12324:return u[d>>2]=8,1;case 12325:return u[d>>2]=F.depth?24:0,1;case 12326:return u[d>>2]=F.stencil?8:0,1;case 12327:return u[d>>2]=12344,1;case 12328:return u[d>>2]=62002,1;case 12329:return u[d>>2]=0,1;case 12330:return u[d>>2]=4096,1;case 12331:return u[d>>2]=16777216,1;case 12332:return u[d>>2]=4096,1;case 12333:return u[d>>2]=0,1;case 12334:return u[d>>2]=0,1;case 12335:return u[d>>2]=12344,1;case 12337:return u[d>>2]=F.antialias?4:0,1;case 12338:return u[d>>
2]=F.antialias?1:0,1;case 12339:return u[d>>2]=4,1;case 12340:return u[d>>2]=12344,1;case 12341:case 12342:case 12343:return u[d>>2]=-1,1;case 12345:case 12346:return u[d>>2]=0,1;case 12347:return u[d>>2]=0,1;case 12348:return u[d>>2]=1;case 12349:case 12350:return u[d>>2]=0,1;case 12351:return u[d>>2]=12430,1;case 12352:return u[d>>2]=4,1;case 12354:return u[d>>2]=0,1;default:return E=12292,0}},O:a=>{E=12288;return 0!=a&&1!=a?0:62E3},ya:()=>E,Ka:(a,b,c)=>{if(62E3!=a)return E=12296,0;b&&(u[b>>2]=
1);c&&(u[c>>2]=4);Sa=!0;E=12288;return 1},Da:(a,b,c,d)=>{if(62E3!=a)return E=12296,0;if(0!=d&&62004!=d)return E=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return E=12301,0;ob(d?Xa:null);Ta=d;Va=b;Ua=c;E=12288;return 1},xa:(a,b)=>{if(62E3!=a)return E=12296,0;E=12288;if(Wa[b])return Wa[b];switch(b){case 12371:a=P("Emscripten");break;case 12372:a=P("1.4 Emscripten EGL");break;case 12373:a=P("");break;case 12429:a=P("OpenGL_ES");break;default:return E=12300,0}return Wa[b]=a},Ea:()=>{if(Sa)if(G)if(G.isContextLost())E=
12302;else return E=12288,1;else E=12290;else E=12289;return 0},Ga:(a,b)=>{if(62E3!=a)return E=12296,0;0==b?Fb(0,0):Fb(1,b);E=12288;return 1},La:a=>{if(62E3!=a)return E=12296,0;Va=Ua=Ta=0;Sa=!1;E=12288;return 1},Ia:()=>{E=12288;return 1},Ha:()=>{E=12288;return 1},Pa:(a,b,c)=>{b=Lb(b,c);return va[a](...b)},a:(a,b,c)=>{b=Lb(b,c);return va[a](...b)},Qa:(a,b,c)=>{b=Lb(b,c);return va[a](...b)},cb:()=>Date.now(),qa:()=>{if(!R.fullscreenEnabled())return-1;Ob(fc);var a=Tb[1];if(a.exitFullscreen)a.fullscreenElement&&
a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},va:()=>{Ob(gc);if(document.exitPointerLock)document.exitPointerLock();else return-1;return 0},f:()=>devicePixelRatio,c:(a,b,c)=>{a=T(a);if(!a)return-4;a=ec(a);x[b>>3]=a.width;x[c>>3]=a.height;return 0},R:(a,b)=>{if(0>a||a>=R.we.length)return-5;if(!R.we[a])return-7;hc(b,R.we[a]);return 0},T:()=>performance.now(),Oa:()=>R.we.length,wa:(a,b)=>{u[a>>2]=screen.width;u[b>>2]=screen.height},
Sd:a=>G.activeTexture(a),Rd:ic,ma:(a,b)=>{G.ke.beginQueryEXT(a,N[b])},Qd:(a,b,c)=>{G.bindAttribLocation(H[a],b,c?C(r,c):"")},Pd:jc,Od:(a,b)=>{G.bindFramebuffer(a,db[b])},Nd:(a,b)=>{G.bindRenderbuffer(a,J[b])},Md:(a,b)=>{G.bindTexture(a,K[b])},ea:a=>{G.bindVertexArray(eb[a])},Ld:(a,b,c,d)=>G.blendColor(a,b,c,d),Kd:a=>G.blendEquation(a),Jd:(a,b)=>G.blendEquationSeparate(a,b),Id:(a,b)=>G.blendFunc(a,b),Hd:(a,b,c,d)=>G.blendFuncSeparate(a,b,c,d),Gd:kc,Fd:(a,b,c,d)=>{G.bufferSubData(a,b,r.subarray(d,d+
c))},Ed:a=>G.checkFramebufferStatus(a),Dd:lc,Cd:mc,Ad:a=>G.clearDepth(a),zd:a=>G.clearStencil(a),eb:(a,b)=>{G.kf.clipControlEXT(a,b)},yd:(a,b,c,d)=>{G.colorMask(!!a,!!b,!!c,!!d)},xd:nc,wd:(a,b,c,d,e,f,g,l)=>{G.compressedTexImage2D(a,b,c,d,e,f,r.subarray(l,l+g))},vd:(a,b,c,d,e,f,g,l,n)=>{G.compressedTexSubImage2D(a,b,c,d,e,f,g,r.subarray(n,n+l))},ud:(a,b,c,d,e,f,g,l)=>G.copyTexImage2D(a,b,c,d,e,f,g,l),td:(a,b,c,d,e,f,g,l)=>G.copyTexSubImage2D(a,b,c,d,e,f,g,l),sd:oc,rd:pc,qd:a=>G.cullFace(a),pd:(a,
b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=cb[d];e&&(G.deleteBuffer(e),e.name=0,cb[d]=null)}},od:(a,b)=>{for(var c=0;c<a;++c){var d=u[b+4*c>>2],e=db[d];e&&(G.deleteFramebuffer(e),e.name=0,db[d]=null)}},nd:qc,oa:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=N[d];e&&(G.ke.deleteQueryEXT(e),N[d]=null)}},md:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=J[d];e&&(G.deleteRenderbuffer(e),e.name=0,J[d]=null)}},ld:a=>{if(a){var b=L[a];b?(G.deleteShader(b),L[a]=null):O||=1281}},kd:(a,b)=>{for(var c=
0;c<a;c++){var d=u[b+4*c>>2],e=K[d];e&&(G.deleteTexture(e),e.name=0,K[d]=null)}},da:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2];G.deleteVertexArray(eb[d]);eb[d]=null}},jd:a=>G.depthFunc(a),id:a=>{G.depthMask(!!a)},hd:(a,b)=>G.depthRange(a,b),fd:(a,b)=>{G.detachShader(H[a],L[b])},ed:a=>G.disable(a),dd:a=>{G.disableVertexAttribArray(a)},cd:(a,b,c)=>{G.drawArrays(a,b,c)},Vd:(a,b,c,d)=>{G.drawArraysInstanced(a,b,c,d)},aa:(a,b)=>{for(var c=rc[a],d=0;d<a;d++)c[d]=u[b+4*d>>2];G.drawBuffers(c)},bd:sc,
Ud:(a,b,c,d,e)=>{G.drawElementsInstanced(a,b,c,d,e)},ad:tc,$c:uc,la:a=>{G.ke.endQueryEXT(a)},_c:()=>G.finish(),Zc:()=>G.flush(),Yc:(a,b,c,d)=>{G.framebufferRenderbuffer(a,b,c,J[d])},Xc:(a,b,c,d,e)=>{G.framebufferTexture2D(a,b,c,K[d],e)},Wc:a=>G.frontFace(a),Vc:vc,Tc:(a,b)=>{jb(a,b,"createFramebuffer",db)},pa:(a,b)=>{for(var c=0;c<a;c++){var d=G.ke.createQueryEXT();if(!d){for(O||=1282;c<a;)u[b+4*c++>>2]=0;break}var e=ib(N);d.name=e;N[e]=d;u[b+4*c>>2]=e}},Sc:(a,b)=>{jb(a,b,"createRenderbuffer",J)},
Rc:(a,b)=>{jb(a,b,"createTexture",K)},ca:(a,b)=>{jb(a,b,"createVertexArray",eb)},Uc:a=>G.generateMipmap(a),Qc:(a,b,c,d,e,f,g)=>wc("getActiveAttrib",a,b,c,d,e,f,g),Pc:(a,b,c,d,e,f,g)=>wc("getActiveUniform",a,b,c,d,e,f,g),Oc:(a,b,c,d)=>{a=G.getAttachedShaders(H[a]);var e=a.length;e>b&&(e=b);u[c>>2]=e;for(b=0;b<e;++b)u[d+4*b>>2]=L.indexOf(a[b])},Nc:xc,Mc:(a,b)=>yc(a,b,4),Lc:(a,b,c)=>{c?u[c>>2]=G.getBufferParameter(a,b):O||=1281},Kc:()=>{var a=G.getError()||O;O=0;return a},Jc:(a,b)=>yc(a,b,2),Ic:(a,b,
c,d)=>{a=G.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;u[d>>2]=a},Hc:(a,b)=>yc(a,b,0),Fc:zc,Gc:Ac,ga:Bc,ia:Cc,fa:Bc,ha:Cc,ja:(a,b,c)=>{c?u[c>>2]=G.ke.getQueryEXT(a,b):O||=1281},Ec:(a,b,c)=>{c?u[c>>2]=G.getRenderbufferParameter(a,b):O||=1281},Bc:(a,b,c,d)=>{a=G.getShaderInfoLog(L[a]);null===a&&(a="(unknown error)");b=0<b&&d?A(a,d,b):0;c&&(u[c>>2]=b)},Ac:(a,b,c,d)=>{a=G.getShaderPrecisionFormat(a,b);u[c>>2]=a.rangeMin;u[c+4>>2]=a.rangeMax;
u[d>>2]=a.precision},zc:(a,b,c,d)=>{if(a=G.getShaderSource(L[a]))b=0<b&&d?A(a,d,b):0,c&&(u[c>>2]=b)},Cc:(a,b,c)=>{c?35716==b?(a=G.getShaderInfoLog(L[a]),null===a&&(a="(unknown error)"),u[c>>2]=a?a.length+1:0):35720==b?(a=G.getShaderSource(L[a]),u[c>>2]=a?a.length+1:0):u[c>>2]=G.getShaderParameter(L[a],b):O||=1281},yc:a=>{var b=fb[a];if(!b){switch(a){case 7939:b=P(Dc().join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=G.getParameter(a))||(O||=1280);b=b?P(b):0;break;case 7938:b=P(`OpenGL ES 2.0 (${G.getParameter(7938)})`);
break;case 35724:b=G.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=P(b);break;default:O||=1280}fb[a]=b}return b},xc:(a,b,c)=>{c?w[c>>2]=G.getTexParameter(a,b):O||=1281},wc:(a,b,c)=>{c?u[c>>2]=G.getTexParameter(a,b):O||=1281},tc:Gc,vc:(a,b,c)=>{Hc(a,b,c,2)},uc:(a,b,c)=>{Hc(a,b,c,0)},pc:(a,b,c)=>{c?u[c>>2]=G.getVertexAttribOffset(a,b):O||=1281},rc:(a,b,c)=>{Ic(a,b,c,2)},qc:(a,b,c)=>{Ic(a,
b,c,5)},oc:(a,b)=>G.hint(a,b),nc:a=>(a=cb[a])?G.isBuffer(a):0,mc:a=>G.isEnabled(a),lc:a=>(a=db[a])?G.isFramebuffer(a):0,kc:a=>(a=H[a])?G.isProgram(a):0,na:a=>(a=N[a])?G.ke.isQueryEXT(a):0,jc:a=>(a=J[a])?G.isRenderbuffer(a):0,ic:a=>(a=L[a])?G.isShader(a):0,hc:a=>(a=K[a])?G.isTexture(a):0,ba:a=>(a=eb[a])?G.isVertexArray(a):0,gc:a=>G.lineWidth(a),fc:Jc,ec:(a,b)=>{3317==a?gb=b:3314==a&&(hb=b);G.pixelStorei(a,b)},db:(a,b)=>{G.uf.polygonModeWEBGL(a,b)},dc:(a,b)=>G.polygonOffset(a,b),fb:(a,b,c)=>{G.lf.polygonOffsetClampEXT(a,
b,c)},ka:(a,b)=>{G.ke.queryCounterEXT(N[a],b)},cc:(a,b,c,d,e,f,g)=>{(g=Kc(f,e,c,d,g))?G.readPixels(a,b,c,d,e,f,g):O||=1280},bc:()=>{},ac:(a,b,c,d)=>G.renderbufferStorage(a,b,c,d),$b:(a,b)=>{G.sampleCoverage(a,!!b)},_b:(a,b,c,d)=>G.scissor(a,b,c,d),Zb:()=>{O||=1280},Yb:Lc,Xb:(a,b,c)=>G.stencilFunc(a,b,c),Wb:(a,b,c,d)=>G.stencilFuncSeparate(a,b,c,d),Vb:a=>G.stencilMask(a),Ub:(a,b)=>G.stencilMaskSeparate(a,b),Tb:(a,b,c)=>G.stencilOp(a,b,c),Sb:(a,b,c,d)=>G.stencilOpSeparate(a,b,c,d),Rb:(a,b,c,d,e,f,g,
l,n)=>{n=n?Kc(l,g,d,e,n):null;G.texImage2D(a,b,c,d,e,f,g,l,n)},Qb:(a,b,c)=>G.texParameterf(a,b,c),Pb:(a,b,c)=>{G.texParameterf(a,b,w[c>>2])},Ob:(a,b,c)=>G.texParameteri(a,b,c),Nb:(a,b,c)=>{G.texParameteri(a,b,u[c>>2])},Mb:(a,b,c,d,e,f,g,l,n)=>{n=n?Kc(l,g,e,f,n):null;G.texSubImage2D(a,b,c,d,e,f,g,l,n)},Lb:Mc,Kb:(a,b,c)=>{if(288>=b)for(var d=W[b],e=0;e<b;++e)d[e]=w[c+4*e>>2];else d=w.subarray(c>>2,c+4*b>>2);G.uniform1fv(V(a),d)},Jb:(a,b)=>{G.uniform1i(V(a),b)},Ib:(a,b,c)=>{if(288>=b)for(var d=Nc[b],
e=0;e<b;++e)d[e]=u[c+4*e>>2];else d=u.subarray(c>>2,c+4*b>>2);G.uniform1iv(V(a),d)},Hb:(a,b,c)=>{G.uniform2f(V(a),b,c)},Gb:(a,b,c)=>{if(144>=b){b*=2;for(var d=W[b],e=0;e<b;e+=2)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2]}else d=w.subarray(c>>2,c+8*b>>2);G.uniform2fv(V(a),d)},Eb:(a,b,c)=>{G.uniform2i(V(a),b,c)},Db:(a,b,c)=>{if(144>=b){b*=2;for(var d=Nc[b],e=0;e<b;e+=2)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2]}else d=u.subarray(c>>2,c+8*b>>2);G.uniform2iv(V(a),d)},Cb:Oc,Bb:(a,b,c)=>{if(96>=b){b*=3;for(var d=
W[b],e=0;e<b;e+=3)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2]}else d=w.subarray(c>>2,c+12*b>>2);G.uniform3fv(V(a),d)},Ab:(a,b,c,d)=>{G.uniform3i(V(a),b,c,d)},zb:(a,b,c)=>{if(96>=b){b*=3;for(var d=Nc[b],e=0;e<b;e+=3)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2]}else d=u.subarray(c>>2,c+12*b>>2);G.uniform3iv(V(a),d)},yb:(a,b,c,d,e)=>{G.uniform4f(V(a),b,c,d,e)},xb:(a,b,c)=>{if(72>=b){var d=W[4*b],e=w;c>>=2;b*=4;for(var f=0;f<b;f+=4){var g=c+f;d[f]=e[g];d[f+1]=e[g+
1];d[f+2]=e[g+2];d[f+3]=e[g+3]}}else d=w.subarray(c>>2,c+16*b>>2);G.uniform4fv(V(a),d)},wb:(a,b,c,d,e)=>{G.uniform4i(V(a),b,c,d,e)},vb:(a,b,c)=>{if(72>=b){b*=4;for(var d=Nc[b],e=0;e<b;e+=4)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2],d[e+3]=u[c+(4*e+12)>>2]}else d=u.subarray(c>>2,c+16*b>>2);G.uniform4iv(V(a),d)},ub:(a,b,c,d)=>{if(72>=b){b*=4;for(var e=W[b],f=0;f<b;f+=4)e[f]=w[d+4*f>>2],e[f+1]=w[d+(4*f+4)>>2],e[f+2]=w[d+(4*f+8)>>2],e[f+3]=w[d+(4*f+12)>>2]}else e=w.subarray(d>>2,d+
16*b>>2);G.uniformMatrix2fv(V(a),!!c,e)},tb:(a,b,c,d)=>{if(32>=b){b*=9;for(var e=W[b],f=0;f<b;f+=9)e[f]=w[d+4*f>>2],e[f+1]=w[d+(4*f+4)>>2],e[f+2]=w[d+(4*f+8)>>2],e[f+3]=w[d+(4*f+12)>>2],e[f+4]=w[d+(4*f+16)>>2],e[f+5]=w[d+(4*f+20)>>2],e[f+6]=w[d+(4*f+24)>>2],e[f+7]=w[d+(4*f+28)>>2],e[f+8]=w[d+(4*f+32)>>2]}else e=w.subarray(d>>2,d+36*b>>2);G.uniformMatrix3fv(V(a),!!c,e)},sb:Pc,rb:Qc,qb:a=>{G.validateProgram(H[a])},pb:(a,b)=>G.vertexAttrib1f(a,b),ob:(a,b)=>{G.vertexAttrib1f(a,w[b>>2])},nb:(a,b,c)=>G.vertexAttrib2f(a,
b,c),mb:(a,b)=>{G.vertexAttrib2f(a,w[b>>2],w[b+4>>2])},lb:(a,b,c,d)=>G.vertexAttrib3f(a,b,c,d),kb:(a,b)=>{G.vertexAttrib3f(a,w[b>>2],w[b+4>>2],w[b+8>>2])},jb:(a,b,c,d,e)=>G.vertexAttrib4f(a,b,c,d,e),ib:(a,b)=>{G.vertexAttrib4f(a,w[b>>2],w[b+4>>2],w[b+8>>2],w[b+12>>2])},Td:(a,b)=>{G.vertexAttribDivisor(a,b)},hb:Rc,gb:Sc,m:()=>0,ra:(a,b,c)=>Tc(a,{Ke:u[c>>2],Be:u[c+4>>2],mf:u[c+8>>2],gf:b,se:u[c+12>>2],Se:u[c+16>>2]}),N:(a,b)=>{a=T(a);return a?a.requestPointerLock?Pb()?gc(a):b?(Nb(gc,2,[a]),1):-2:-1:
-4},Sa:()=>{na("OOM")},r:a=>{eval(a?C(r,a):"")},S:Uc,u:(a,b,c)=>"undefined"==typeof onbeforeunload?-1:1!==c?-5:Vc(a,b),F:(a,b,c,d)=>Wc(a,b,c,d,12,"blur"),e:Zb,j:(a,b,c)=>{a=T(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},G:(a,b,c,d)=>Wc(a,b,c,d,13,"focus"),w:(a,b,c,d)=>{if(!R.fullscreenEnabled())return-1;a=T(a);if(!a)return-4;Xc(a,b,c,d,"webkitfullscreenchange");return Xc(a,b,c,d,"fullscreenchange")},Q:(a,b,c)=>Uc()?-1:Yc(a,b,c,26,"gamepadconnected"),P:(a,b,c)=>Uc()?-1:Yc(a,
b,c,27,"gamepaddisconnected"),z:(a,b,c,d)=>Zc(a,b,c,d,2,"keydown"),x:(a,b,c,d)=>Zc(a,b,c,d,1,"keypress"),y:(a,b,c,d)=>Zc(a,b,c,d,3,"keyup"),Ra:(a,b,c)=>{a=U(a);Gb(a,b,c)},L:(a,b,c,d)=>ad(a,b,c,d,5,"mousedown"),J:(a,b,c,d)=>ad(a,b,c,d,33,"mouseenter"),I:(a,b,c,d)=>ad(a,b,c,d,34,"mouseleave"),o:(a,b,c,d)=>ad(a,b,c,d,8,"mousemove"),K:(a,b,c,d)=>ad(a,b,c,d,6,"mouseup"),A:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.te||document.body.hf||document.body.ff))return-1;
a=T(a);if(!a)return-4;bd(a,b,c,d,"mozpointerlockchange");bd(a,b,c,d,"webkitpointerlockchange");bd(a,b,c,d,"mspointerlockchange");return bd(a,b,c,d,"pointerlockchange")},p:(a,b,c,d)=>cd(a,b,c,d),B:(a,b,c,d)=>dd(a,b,c,d,25,"touchcancel"),D:(a,b,c,d)=>dd(a,b,c,d,23,"touchend"),C:(a,b,c,d)=>dd(a,b,c,d,24,"touchmove"),E:(a,b,c,d)=>dd(a,b,c,d,22,"touchstart"),v:(a,b,c)=>nd(a,b,c),H:(a,b,c,d)=>(a=T(a))?"undefined"!=typeof a.onwheel?od(a,b,c,d):-1:-4,sa:a=>document.title=a?C(r,a):"",k:()=>{throw"Please compile your program with async support in order to use asynchronous operations like emscripten_sleep";
},Ua:(a,b)=>{var c=0;rd().forEach((d,e)=>{var f=b+c;e=v[a+4*e>>2]=f;for(f=0;f<d.length;++f)q[e++]=d.charCodeAt(f);q[e]=0;c+=d.length+1});return 0},Va:(a,b)=>{var c=rd();v[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);v[b>>2]=d;return 0},V:()=>52,_a:()=>52,Ta:function(){return 70},W:(a,b,c,d)=>{for(var e=0,f=0;f<c;f++){var g=v[b>>2],l=v[b+4>>2];b+=8;for(var n=0;n<l;n++){var t=r[g+n],B=sd[a];0===t||10===t?((1===a?ea:m)(C(B)),B.length=0):B.push(t)}e+=l}v[d>>2]=e;return 0},Z:ic,d:jc,h:kc,Fb:lc,ab:mc,
_:nc,Bd:oc,t:pc,ta:qc,Fa:sc,U:tc,l:uc,i:vc,s:xc,ua:zc,M:Ac,b:Gc,gd:Jc,$:Lc,g:Mc,q:Oc,Y:Pc,Dc:Qc,n:Rc,sc:Sc},Y;
(async function(){function a(c){Y=c.exports;ha=Y.Wd;c=ha.buffer;h.HEAP8=q=new Int8Array(c);h.HEAP16=ja=new Int16Array(c);h.HEAPU8=r=new Uint8Array(c);h.HEAPU16=ka=new Uint16Array(c);h.HEAP32=u=new Int32Array(c);h.HEAPU32=v=new Uint32Array(c);h.HEAPF32=w=new Float32Array(c);h.HEAPF64=x=new Float64Array(c);h.HEAP64=la=new BigInt64Array(c);h.HEAPU64=new BigUint64Array(c);bc=Y._d;y--;h.monitorRunDependencies?.(y);0==y&&ma&&(c=ma,ma=null,c());return Y}y++;h.monitorRunDependencies?.(y);var b={a:wd};if(h.instantiateWasm)return new Promise(c=>
{h.instantiateWasm(b,(d,e)=>{a(d,e);c(d.exports)})});oa??=h.locateFile?h.locateFile("index.wasm",k):k+"index.wasm";return a((await ra(b)).instance)})();var z=a=>(z=Y.Yd)(a),xd=h._main=(a,b)=>(xd=h._main=Y.Zd)(a,b),Xb=a=>(Xb=Y.$d)(a),Ub=a=>(Ub=Y.ae)(a),Wb=()=>(Wb=Y.be)();function yd(a=[]){var b=xd;a.unshift(ca);var c=a.length,d=Ub(4*(c+1)),e=d;a.forEach(g=>{v[e>>2]=Vb(g);e+=4});v[e>>2]=0;try{var f=b(c,d);Fa(f)}catch(g){Da(g)}}
function zd(a=ba){function b(){h.calledRun=!0;if(!p){Y.Xd();h.onRuntimeInitialized?.();h.noInitialRun||yd(a);if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var c=h.postRun.shift();ya.unshift(c)}xa(ya)}}if(0<y)ma=zd;else{if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Aa();xa(za);0<y?ma=zd:h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),1);b()},1)):b()}}
if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();zd();
